const data = {
  a: ["z", "b"],
  abase: ["abate"],
  abasement: ["abatement"],
  abate: ["abase"],
  abatement: ["abasement"],
  acme: ["acne"],
  acne: ["acme"],
  acorn: ["adorn"],
  adorn: ["acorn"],
  aerate: ["berate"],
  afar: ["agar"],
  agar: ["afar"],
  aid: ["bid"],
  aide: ["bide"],
  ail: ["aim"],
  aim: ["ail"],
  alack: ["black"],
  alight: ["blight"],
  aloha: ["alpha"],
  along: ["among"],
  alp: ["amp"],
  alpha: ["aloha"],
  also: ["alto"],
  alto: ["also"],
  am: ["an"],
  among: ["along"],
  amp: ["alp"],
  an: ["am"],
  appointed: ["appointee"],
  appointee: ["appointed"],
  aright: ["bright"],
  ark: ["ask"],
  as: ["at"],
  ask: ["ark"],
  assess: ["assets"],
  assets: ["assess"],
  at: ["as"],
  aunt: ["bunt"],
  aw: ["ax"],
  award: ["aware"],
  aware: ["award"],
  awe: ["axe"],
  ax: ["aw"],
  axe: ["awe", "aye"],
  aye: ["bye", "axe"],
  b: ["a", "c"],
  bad: ["cad"],
  badge: ["cadge"],
  badger: ["cadger"],
  bag: ["bah"],
  bagpiper: ["bagpipes"],
  bagpipes: ["bagpiper"],
  bah: ["bag"],
  bake: ["cake", "bale"],
  baker: ["baler"],
  bald: ["bale"],
  bale: ["bake", "bald"],
  baler: ["baker"],
  balk: ["calk", "ball"],
  ball: ["call", "balk", "balm"],
  balm: ["calm", "ball"],
  ban: ["can"],
  banal: ["canal"],
  band: ["bane"],
  bandy: ["candy"],
  bane: ["cane", "band"],
  banister: ["canister"],
  banker: ["canker"],
  banter: ["canter"],
  bar: ["car"],
  bard: ["card", "bare"],
  bare: ["care", "base", "bard", "barf"],
  barely: ["basely", "barfly"],
  bareness: ["baseness"],
  barf: ["bare"],
  barfly: ["barely"],
  barhop: ["carhop"],
  bark: ["bask"],
  barrel: ["carrel"],
  barrier: ["carrier"],
  barter: ["carter", "baster"],
  base: ["case", "bare", "bate"],
  basely: ["barely"],
  basement: ["casement"],
  baseness: ["bareness"],
  bash: ["cash", "bath"],
  bask: ["cask", "bark"],
  basket: ["casket"],
  bass: ["bats", "bast"],
  bast: ["cast", "bass"],
  baste: ["caste"],
  baster: ["caster", "barter", "batter"],
  bat: ["cat"],
  batch: ["catch"],
  bate: ["base"],
  bath: ["bash"],
  bats: ["bass"],
  batter: ["baster"],
  battle: ["cattle"],
  batty: ["catty"],
  bay: ["cay"],
  beam: ["bean"],
  bean: ["beam"],
  beat: ["beau"],
  beau: ["beat"],
  bed: ["bee"],
  bee: ["bed"],
  bell: ["cell"],
  bent: ["cent"],
  berate: ["aerate"],
  beret: ["beset"],
  beset: ["beret"],
  beside: ["betide"],
  betide: ["beside"],
  bid: ["aid"],
  bide: ["aide"],
  bike: ["bile"],
  bile: ["bike"],
  bilk: ["bill"],
  bill: ["bilk"],
  bin: ["bio"],
  binder: ["cinder"],
  bio: ["bin"],
  bite: ["cite"],
  black: ["alack", "clack"],
  blank: ["clank"],
  blare: ["blase"],
  blase: ["blare"],
  blear: ["clear"],
  bleat: ["cleat"],
  blench: ["clench"],
  blew: ["clew"],
  blight: ["alight"],
  blink: ["clink"],
  blinker: ["clinker"],
  blip: ["clip"],
  blob: ["bloc"],
  bloc: ["blob"],
  block: ["clock"],
  blond: ["blood"],
  blood: ["blond"],
  blot: ["clot"],
  blown: ["clown"],
  blue: ["clue"],
  blues: ["bluet"],
  bluet: ["blues"],
  bluster: ["cluster"],
  boa: ["bob"],
  boast: ["coast"],
  boaster: ["coaster"],
  boat: ["coat"],
  boating: ["coating"],
  bob: ["cob", "boa"],
  bobble: ["cobble"],
  bock: ["cock"],
  bod: ["cod"],
  bode: ["code"],
  bog: ["cog"],
  boil: ["coil"],
  bola: ["cola"],
  bold: ["cold", "bole"],
  boldly: ["coldly"],
  boldness: ["coldness"],
  bole: ["bold"],
  bolt: ["colt"],
  bomb: ["comb"],
  bomber: ["comber"],
  bond: ["bone"],
  bone: ["cone", "bond"],
  bony: ["cony"],
  boo: ["coo", "bop"],
  book: ["cook"],
  bookie: ["cookie"],
  booking: ["cooking"],
  boom: ["boon"],
  boon: ["coon", "boom"],
  boot: ["coot"],
  bootie: ["cootie"],
  bop: ["cop", "boo"],
  bore: ["core"],
  borer: ["corer"],
  born: ["corn"],
  bosh: ["both"],
  both: ["bosh"],
  bough: ["cough"],
  bouncer: ["bounder"],
  bounder: ["bouncer"],
  bounty: ["county"],
  bow: ["cow", "box"],
  bower: ["cower", "boxer"],
  bowl: ["cowl"],
  bowling: ["cowling"],
  bowman: ["cowman"],
  box: ["bow", "boy"],
  boxer: ["bower"],
  boy: ["coy", "box"],
  bracer: ["braces"],
  braces: ["bracer"],
  brad: ["brae"],
  brae: ["brad"],
  brag: ["crag"],
  brash: ["crash"],
  brass: ["crass"],
  brave: ["crave"],
  brawl: ["crawl"],
  brawler: ["crawler"],
  braze: ["craze"],
  break: ["creak"],
  bream: ["cream"],
  breed: ["creed"],
  brew: ["crew"],
  brick: ["crick"],
  brier: ["crier"],
  bright: ["aright"],
  bristle: ["brittle"],
  brittle: ["bristle"],
  brook: ["crook"],
  brow: ["crow"],
  brown: ["crown"],
  bruise: ["cruise"],
  bruiser: ["cruiser"],
  brunch: ["crunch"],
  brush: ["crush"],
  bub: ["cub"],
  bud: ["cud"],
  buff: ["cuff"],
  bulk: ["bull"],
  bulkhead: ["bullhead"],
  bulky: ["bully"],
  bull: ["cull", "bulk"],
  bullhead: ["bulkhead"],
  bully: ["bulky"],
  bum: ["cum", "bun"],
  bun: ["bum"],
  buns: ["bunt"],
  bunt: ["aunt", "cunt", "buns"],
  bur: ["cur", "bus"],
  burl: ["curl"],
  burliness: ["curliness"],
  burly: ["curly"],
  bury: ["busy"],
  bus: ["bur", "but"],
  bushy: ["cushy"],
  buss: ["cuss", "bust"],
  bust: ["butt", "buss"],
  buster: ["butter"],
  busy: ["bury"],
  but: ["cut", "bus"],
  butler: ["cutler"],
  butt: ["bust"],
  butter: ["cutter", "buster"],
  bye: ["aye"],
  c: ["b", "d"],
  cab: ["dab"],
  cad: ["bad", "dad"],
  caddy: ["daddy"],
  cadge: ["badge"],
  cadger: ["badger"],
  cafe: ["cage"],
  cage: ["cafe"],
  cake: ["bake"],
  calk: ["balk", "call"],
  call: ["ball", "calk", "calm"],
  calm: ["balm", "call"],
  cam: ["dam", "can"],
  came: ["dame", "cane"],
  camp: ["damp"],
  camper: ["damper"],
  can: ["ban", "cam"],
  canal: ["banal"],
  cancer: ["dancer"],
  candle: ["dandle"],
  candy: ["bandy", "dandy"],
  cane: ["bane", "came"],
  canister: ["banister"],
  canker: ["banker"],
  canter: ["banter"],
  car: ["bar"],
  card: ["bard", "care"],
  carder: ["career"],
  care: ["bare", "dare", "case", "card"],
  career: ["carder"],
  carhop: ["barhop"],
  caring: ["daring", "casing"],
  carol: ["carom"],
  carom: ["carol"],
  carrel: ["barrel"],
  carrier: ["barrier"],
  cart: ["dart", "cast"],
  carter: ["barter", "darter", "caster"],
  case: ["base", "care"],
  casement: ["basement"],
  cash: ["bash", "dash"],
  casing: ["caring"],
  cask: ["bask"],
  casket: ["basket"],
  cast: ["bast", "cart"],
  caste: ["baste"],
  caster: ["baster", "carter"],
  castle: ["cattle"],
  cat: ["bat"],
  catch: ["batch"],
  cater: ["dater"],
  cattle: ["battle", "castle"],
  catty: ["batty"],
  cay: ["bay", "day"],
  cecal: ["decal"],
  cell: ["bell", "dell"],
  censer: ["center"],
  cent: ["bent", "dent"],
  center: ["censer"],
  cerium: ["cesium"],
  cesium: ["cerium"],
  chafe: ["chaff"],
  chaff: ["chafe"],
  chaos: ["chaps"],
  chaps: ["chaos"],
  charm: ["chasm"],
  chasm: ["charm"],
  cheeriness: ["cheesiness"],
  cheery: ["cheesy"],
  cheesiness: ["cheeriness"],
  cheesy: ["cheery"],
  chert: ["chest"],
  chess: ["chest"],
  chest: ["chert", "chess"],
  chic: ["chid"],
  chid: ["chic"],
  child: ["chile"],
  chile: ["chime", "child"],
  chime: ["chile", "chine"],
  chimer: ["chimes"],
  chimes: ["chimer"],
  chine: ["chime"],
  choker: ["choler"],
  choler: ["choker"],
  chord: ["chore"],
  chore: ["chose", "chord"],
  chose: ["chore"],
  chow: ["dhow"],
  cinder: ["binder"],
  cite: ["bite"],
  clack: ["black"],
  clam: ["clan"],
  clan: ["clam"],
  clank: ["blank"],
  clear: ["blear"],
  cleat: ["bleat"],
  clench: ["blench"],
  clew: ["blew"],
  clink: ["blink"],
  clinker: ["blinker"],
  clip: ["blip"],
  clock: ["block"],
  closure: ["cloture"],
  clot: ["blot"],
  cloture: ["closure"],
  clown: ["blown"],
  clue: ["blue"],
  cluster: ["bluster", "clutter"],
  clutter: ["cluster"],
  coast: ["boast"],
  coaster: ["boaster"],
  coat: ["boat"],
  coating: ["boating"],
  cob: ["bob"],
  cobble: ["bobble"],
  coca: ["coda"],
  cock: ["bock", "dock"],
  cod: ["bod"],
  coda: ["coca"],
  code: ["bode"],
  codger: ["dodger"],
  cog: ["bog", "dog"],
  coil: ["boil"],
  cola: ["bola", "coma"],
  cold: ["bold"],
  coldly: ["boldly"],
  coldness: ["boldness"],
  colic: ["comic"],
  collar: ["dollar"],
  color: ["dolor"],
  colt: ["bolt", "dolt"],
  coltish: ["doltish"],
  coma: ["cola", "comb"],
  comb: ["bomb", "coma"],
  comber: ["bomber"],
  come: ["dome", "cone"],
  comic: ["colic", "conic"],
  comical: ["conical"],
  comically: ["conically"],
  committed: ["committee"],
  committee: ["committed"],
  comport: ["compost"],
  compose: ["compote"],
  compost: ["comport"],
  compote: ["compose"],
  con: ["don", "coo"],
  cone: ["bone", "done", "come"],
  confer: ["conger"],
  confuse: ["confute"],
  confute: ["confuse"],
  conger: ["confer"],
  conic: ["comic"],
  conical: ["comical"],
  conically: ["comically"],
  conk: ["cook"],
  consent: ["content"],
  consort: ["contort"],
  content: ["consent"],
  contort: ["consort"],
  convex: ["convey"],
  convey: ["convex"],
  cony: ["bony"],
  coo: ["boo", "con", "cop"],
  cook: ["book", "conk", "cool"],
  cooker: ["cooler"],
  cookie: ["bookie", "coolie"],
  cooking: ["booking"],
  cool: ["cook"],
  cooler: ["cooker"],
  coolie: ["cookie"],
  coon: ["boon"],
  cooper: ["copper"],
  coot: ["boot"],
  cootie: ["bootie"],
  cop: ["bop", "coo"],
  cope: ["dope"],
  coping: ["doping"],
  copper: ["cooper"],
  copy: ["dopy"],
  cord: ["core"],
  core: ["bore", "cord"],
  corer: ["borer"],
  cork: ["dork"],
  corm: ["dorm", "corn"],
  corn: ["born", "corm"],
  corset: ["cosset"],
  cosset: ["corset"],
  cost: ["dost"],
  cot: ["dot"],
  cote: ["dote"],
  cough: ["bough", "dough"],
  county: ["bounty"],
  cove: ["dove"],
  cover: ["cower"],
  covers: ["covert"],
  covert: ["covers"],
  cow: ["bow"],
  cower: ["bower", "dower", "cover"],
  cowl: ["bowl"],
  cowling: ["bowling"],
  cowman: ["bowman"],
  coy: ["boy"],
  cozen: ["dozen"],
  crab: ["drab"],
  craft: ["draft"],
  craftily: ["draftily"],
  craftiness: ["draftiness"],
  craftsman: ["draftsman"],
  craftsmanship: ["draftsmanship"],
  craftswoman: ["draftswoman"],
  crafty: ["drafty"],
  crag: ["brag", "drag"],
  craggy: ["draggy"],
  cram: ["dram"],
  crank: ["drank"],
  crape: ["drape"],
  crash: ["brash"],
  crass: ["brass"],
  crave: ["brave"],
  craw: ["draw"],
  crawl: ["brawl", "drawl"],
  crawler: ["brawler"],
  craze: ["braze"],
  creak: ["break"],
  cream: ["bream", "dream"],
  creamer: ["dreamer"],
  creamily: ["dreamily"],
  creaminess: ["dreaminess"],
  creamy: ["dreamy"],
  crease: ["create"],
  create: ["crease"],
  creed: ["breed"],
  creek: ["creel"],
  creel: ["creek"],
  cress: ["dress", "crest"],
  crest: ["cress"],
  crew: ["brew", "drew"],
  crick: ["brick"],
  cried: ["dried"],
  crier: ["brier", "drier", "cries"],
  cries: ["crier"],
  crone: ["drone"],
  crook: ["brook"],
  crop: ["drop"],
  cropper: ["dropper"],
  cross: ["dross"],
  crotch: ["crouch"],
  crouch: ["crotch"],
  crow: ["brow"],
  crown: ["brown", "drown"],
  crowning: ["drowning"],
  cruise: ["bruise"],
  cruiser: ["bruiser"],
  crunch: ["brunch"],
  crush: ["brush"],
  cry: ["dry"],
  cub: ["bub", "dub"],
  cud: ["bud", "dud", "cue"],
  cue: ["due", "cud"],
  cuff: ["buff", "duff"],
  cull: ["bull", "dull"],
  cum: ["bum"],
  cunt: ["bunt"],
  cur: ["bur"],
  curability: ["durability"],
  curable: ["durable"],
  curd: ["cure"],
  cure: ["curd"],
  curl: ["burl"],
  curliness: ["burliness"],
  curly: ["burly"],
  cushy: ["bushy"],
  cuss: ["buss"],
  cut: ["but"],
  cutler: ["butler"],
  cutter: ["butter"],
  d: ["c", "e"],
  dab: ["cab"],
  dad: ["cad"],
  daddy: ["caddy"],
  dairy: ["daisy"],
  daisy: ["dairy"],
  dale: ["dame"],
  dam: ["cam"],
  dame: ["came", "dale"],
  damp: ["camp"],
  damper: ["camper"],
  dancer: ["cancer", "dander"],
  dander: ["dancer"],
  dandle: ["candle"],
  dandy: ["candy"],
  dare: ["care"],
  daring: ["caring"],
  darn: ["earn"],
  darner: ["earner"],
  dart: ["cart"],
  darter: ["carter"],
  dash: ["cash"],
  dater: ["cater", "eater"],
  day: ["cay"],
  debase: ["debate"],
  debate: ["debase"],
  debauched: ["debauchee"],
  debauchee: ["debauched"],
  decal: ["cecal"],
  dell: ["cell"],
  demote: ["denote"],
  denote: ["demote"],
  dent: ["cent"],
  deprecation: ["depredation"],
  depredation: ["deprecation"],
  despise: ["despite"],
  despite: ["despise"],
  devoted: ["devotee"],
  devotee: ["devoted"],
  dhow: ["chow"],
  diatomic: ["diatonic"],
  diatonic: ["diatomic"],
  did: ["die"],
  die: ["did"],
  dilly: ["dimly"],
  dim: ["din"],
  dime: ["dine"],
  dimly: ["dilly"],
  din: ["dim"],
  dine: ["dime"],
  dirk: ["disk"],
  disk: ["dirk"],
  dissension: ["distension"],
  distension: ["dissension", "distention"],
  distention: ["distension"],
  dither: ["either"],
  ditsy: ["ditty"],
  ditty: ["ditsy"],
  divers: ["divert"],
  divert: ["divest", "divers"],
  divest: ["divert"],
  divorced: ["divorcee"],
  divorcee: ["divorced"],
  dock: ["cock"],
  dodger: ["codger"],
  doer: ["does"],
  does: ["doer"],
  dog: ["cog"],
  dole: ["dome"],
  dollar: ["collar"],
  dolor: ["color"],
  dolt: ["colt"],
  doltish: ["coltish"],
  dome: ["come", "dole", "done"],
  don: ["con", "eon"],
  done: ["cone", "dome"],
  dope: ["cope"],
  doping: ["coping"],
  dopy: ["copy"],
  dork: ["cork"],
  dorm: ["corm"],
  dosage: ["dotage"],
  dose: ["dote"],
  dost: ["cost"],
  dot: ["cot"],
  dotage: ["dosage"],
  dote: ["cote", "dose"],
  doubles: ["doublet"],
  doublet: ["doubles"],
  dough: ["cough"],
  dove: ["cove"],
  dower: ["cower"],
  doyen: ["dozen"],
  dozen: ["cozen", "doyen"],
  drab: ["crab"],
  draft: ["craft"],
  draftily: ["craftily"],
  draftiness: ["craftiness"],
  draftsman: ["craftsman"],
  draftsmanship: ["craftsmanship"],
  draftswoman: ["craftswoman"],
  drafty: ["crafty"],
  drag: ["crag"],
  draggy: ["craggy"],
  dram: ["cram"],
  drank: ["crank"],
  drape: ["crape"],
  draper: ["drapes"],
  drapes: ["draper"],
  draw: ["craw"],
  drawl: ["crawl"],
  dream: ["cream"],
  dreamer: ["creamer"],
  dreamily: ["creamily"],
  dreaminess: ["creaminess"],
  dreamy: ["creamy"],
  dress: ["cress"],
  drew: ["crew"],
  dried: ["cried"],
  drier: ["crier"],
  drone: ["crone"],
  drop: ["crop"],
  dropper: ["cropper"],
  dross: ["cross"],
  drover: ["droves"],
  droves: ["drover"],
  drown: ["crown"],
  drowning: ["crowning"],
  dry: ["cry"],
  dub: ["cub"],
  dud: ["cud", "due"],
  duds: ["dues"],
  due: ["cue", "dud"],
  dues: ["duds", "duet"],
  duet: ["dues"],
  duff: ["cuff"],
  dug: ["duh"],
  duh: ["dug"],
  dull: ["cull"],
  dun: ["duo"],
  duo: ["dun"],
  durability: ["curability"],
  durable: ["curable"],
  dye: ["eye"],
  e: ["d", "f"],
  ear: ["far"],
  earn: ["darn"],
  earner: ["darner"],
  east: ["fast"],
  eat: ["fat"],
  eater: ["dater"],
  eek: ["eel"],
  eel: ["eek"],
  eight: ["fight"],
  either: ["dither"],
  elan: ["flan"],
  elk: ["ell"],
  ell: ["elk", "elm"],
  elm: ["ell"],
  elver: ["elves"],
  elves: ["elver"],
  em: ["en"],
  en: ["em"],
  enlisted: ["enlistee"],
  enlistee: ["enlisted"],
  eon: ["don"],
  escaped: ["escapee"],
  escapee: ["escaped"],
  ethological: ["etiological"],
  ethology: ["etiology"],
  etiological: ["ethological"],
  etiology: ["ethology"],
  eve: ["ewe"],
  ever: ["ewer"],
  ewe: ["eve"],
  ewer: ["ever"],
  excise: ["excite"],
  excite: ["excise"],
  exerciser: ["exercises"],
  exercises: ["exerciser"],
  eye: ["dye"],
  f: ["e", "g"],
  fable: ["gable"],
  fabled: ["gabled"],
  face: ["fade"],
  fad: ["gad"],
  fade: ["face"],
  fag: ["gag"],
  fain: ["gain"],
  fall: ["gall"],
  fame: ["game"],
  famine: ["gamine"],
  fang: ["gang"],
  far: ["ear", "gar"],
  fart: ["fast"],
  fast: ["east", "fart"],
  fasten: ["fatten"],
  fastening: ["fattening"],
  fat: ["eat"],
  fate: ["gate"],
  father: ["gather"],
  fatten: ["fasten"],
  fattening: ["fastening"],
  fax: ["fay"],
  fay: ["gay", "fax"],
  faze: ["gaze"],
  fear: ["gear"],
  fed: ["fee"],
  fee: ["gee", "fed"],
  fencer: ["fender"],
  fender: ["gender", "fencer"],
  fester: ["fetter"],
  fetter: ["fester"],
  fey: ["fez"],
  fez: ["fey"],
  fibber: ["gibber"],
  fig: ["gig"],
  fight: ["eight"],
  fill: ["gill", "film"],
  filly: ["filmy"],
  film: ["fill"],
  filmy: ["filly"],
  fin: ["gin"],
  find: ["fine"],
  fine: ["find"],
  finger: ["ginger"],
  fiord: ["fjord"],
  firth: ["girth"],
  fist: ["gist"],
  five: ["give"],
  fjord: ["fiord"],
  flan: ["elan"],
  flare: ["glare"],
  flaw: ["flax"],
  flax: ["flaw", "flay"],
  flay: ["flax"],
  fled: ["flee"],
  flee: ["glee", "fled"],
  flew: ["flex"],
  flex: ["flew"],
  flier: ["flies"],
  flies: ["flier"],
  flint: ["glint"],
  float: ["gloat"],
  flop: ["glop"],
  floppy: ["gloppy"],
  floss: ["gloss"],
  flossy: ["glossy"],
  flow: ["glow"],
  flower: ["glower"],
  flowing: ["glowing"],
  flue: ["glue"],
  fluster: ["flutter"],
  flutter: ["fluster"],
  foal: ["goal", "foam"],
  foam: ["foal"],
  fob: ["gob"],
  fold: ["gold"],
  folly: ["golly"],
  fond: ["food"],
  font: ["foot"],
  food: ["good", "fond"],
  foodie: ["goodie"],
  foot: ["font"],
  ford: ["fore"],
  fore: ["gore", "ford"],
  forge: ["gorge"],
  fray: ["gray"],
  frill: ["grill"],
  frizzly: ["grizzly"],
  frog: ["grog"],
  frosh: ["froth"],
  froth: ["frosh"],
  frown: ["grown"],
  frump: ["grump"],
  frumpy: ["grumpy"],
  full: ["gull"],
  fully: ["gully"],
  fun: ["gun"],
  funk: ["gunk"],
  funky: ["gunky"],
  funny: ["gunny"],
  fussiness: ["fustiness"],
  fussy: ["gussy", "fusty"],
  fustiness: ["fussiness"],
  fusty: ["gusty", "fussy"],
  g: ["f", "h"],
  gable: ["fable"],
  gabled: ["fabled"],
  gad: ["fad", "had"],
  gag: ["fag", "hag"],
  gaggle: ["haggle"],
  gain: ["fain"],
  gale: ["hale", "game"],
  gall: ["fall", "hall"],
  game: ["fame", "gale"],
  gamine: ["famine"],
  gang: ["fang", "hang"],
  gap: ["hap"],
  gar: ["far", "gas"],
  garden: ["harden"],
  gardener: ["hardener"],
  gas: ["has", "gar"],
  gash: ["hash"],
  gasp: ["hasp"],
  gate: ["fate", "hate"],
  gather: ["father"],
  gaunt: ["haunt"],
  gave: ["have"],
  gawk: ["hawk"],
  gay: ["fay", "hay"],
  gaze: ["faze", "haze"],
  gazer: ["hazer"],
  gear: ["fear", "hear"],
  gee: ["fee"],
  gel: ["gem"],
  geld: ["held"],
  gem: ["hem", "gel"],
  gender: ["fender"],
  geodesic: ["geodetic"],
  geodetic: ["geodesic"],
  gibber: ["fibber"],
  gig: ["fig"],
  gill: ["fill", "hill"],
  gilt: ["hilt"],
  gin: ["fin"],
  ginger: ["finger"],
  girt: ["gist"],
  girth: ["firth"],
  gist: ["fist", "hist", "girt"],
  give: ["five", "hive"],
  glace: ["glade"],
  glade: ["glace"],
  glare: ["flare"],
  gleam: ["glean"],
  glean: ["gleam"],
  glee: ["flee"],
  glint: ["flint"],
  glister: ["glitter"],
  glitter: ["glister"],
  gloat: ["float"],
  glop: ["flop"],
  gloppy: ["floppy"],
  gloss: ["floss"],
  glossy: ["flossy"],
  glow: ["flow"],
  glower: ["flower"],
  glowing: ["flowing"],
  glue: ["flue"],
  gnat: ["goat"],
  go: ["ho"],
  goal: ["foal"],
  goat: ["gnat"],
  gob: ["fob", "hob"],
  gobble: ["hobble"],
  gobbler: ["hobbler"],
  god: ["hod"],
  goer: ["hoer", "goes"],
  goes: ["goer"],
  gold: ["fold", "hold"],
  golly: ["folly", "holly"],
  gone: ["hone"],
  goner: ["honer"],
  good: ["food", "hood"],
  goodie: ["foodie"],
  goody: ["gooey"],
  gooey: ["hooey", "goody", "goofy"],
  goof: ["hoof"],
  goofy: ["gooey"],
  gook: ["hook"],
  goop: ["hoop"],
  gore: ["fore"],
  gorge: ["forge"],
  gorse: ["horse"],
  got: ["hot"],
  grace: ["grade"],
  grade: ["grace"],
  gray: ["fray"],
  grill: ["frill"],
  grim: ["grin"],
  grin: ["grim"],
  griper: ["gripes"],
  gripes: ["griper"],
  grizzly: ["frizzly"],
  grog: ["frog"],
  grown: ["frown"],
  grump: ["frump"],
  grumpy: ["frumpy"],
  guess: ["guest"],
  guest: ["guess"],
  guff: ["huff"],
  guild: ["guile"],
  guile: ["guild"],
  gull: ["full", "hull"],
  gully: ["fully"],
  gum: ["hum", "gun"],
  gun: ["fun", "gum"],
  gunk: ["funk", "hunk"],
  gunky: ["funky", "hunky"],
  gunny: ["funny"],
  gush: ["hush"],
  gussy: ["fussy", "hussy", "gutsy", "gusty"],
  gusty: ["fusty", "gutty", "gussy"],
  gut: ["hut"],
  gutsy: ["gussy", "gutty"],
  gutty: ["gusty", "gutsy"],
  h: ["g", "i"],
  had: ["gad"],
  hag: ["gag", "hah"],
  haggle: ["gaggle"],
  hah: ["hag"],
  hake: ["hale"],
  hale: ["gale", "hake", "half"],
  half: ["hale"],
  hall: ["gall"],
  hang: ["gang"],
  hap: ["gap"],
  hard: ["hare"],
  harden: ["garden"],
  hardener: ["gardener"],
  hare: ["hard"],
  harp: ["hasp"],
  hart: ["hast"],
  has: ["gas", "hat"],
  hash: ["gash", "hath"],
  hasp: ["gasp", "harp"],
  hast: ["hart"],
  hat: ["has"],
  hate: ["gate"],
  hath: ["hash"],
  haunt: ["gaunt"],
  have: ["gave"],
  hawk: ["gawk"],
  hay: ["gay"],
  haze: ["gaze"],
  hazer: ["gazer"],
  hear: ["gear"],
  heaver: ["heaves"],
  heaves: ["heaver"],
  held: ["geld"],
  hell: ["helm"],
  helm: ["hell"],
  help: ["hemp"],
  hem: ["gem", "hen"],
  hemp: ["help"],
  hen: ["hem"],
  herd: ["here"],
  here: ["herd"],
  hew: ["hex"],
  hex: ["hew", "hey"],
  hey: ["hex"],
  hid: ["hie"],
  hideous: ["hideout"],
  hideout: ["hideous"],
  hie: ["hid"],
  hill: ["gill"],
  hilt: ["gilt"],
  his: ["hit"],
  hiss: ["hist"],
  hist: ["gist", "hiss"],
  hit: ["his"],
  hive: ["give"],
  "h'm": ["i'm"],
  ho: ["go"],
  hob: ["gob"],
  hobble: ["gobble"],
  hobbler: ["gobbler"],
  hod: ["god", "hoe"],
  hoe: ["hod"],
  hoer: ["goer"],
  hoke: ["hole"],
  hokey: ["holey"],
  hold: ["gold", "hole"],
  hole: ["hoke", "home", "hold"],
  holey: ["hokey", "homey"],
  holiness: ["hominess"],
  holly: ["golly"],
  holograph: ["homograph"],
  home: ["hole", "hone"],
  homer: ["honer"],
  homey: ["holey", "honey"],
  hominess: ["holiness"],
  homograph: ["holograph"],
  hon: ["ion"],
  hone: ["gone", "home"],
  honer: ["goner", "homer"],
  honey: ["homey", "hooey"],
  honk: ["hook"],
  honker: ["hooker"],
  honky: ["hooky"],
  hood: ["good"],
  hooey: ["gooey", "honey"],
  hoof: ["goof"],
  hook: ["gook", "honk"],
  hooker: ["honker"],
  hooky: ["honky"],
  hoop: ["goop"],
  horse: ["gorse"],
  hot: ["got"],
  houseboat: ["housecoat"],
  housecoat: ["houseboat"],
  huff: ["guff"],
  hug: ["huh"],
  huh: ["hug"],
  hulk: ["hull"],
  hull: ["gull", "hulk"],
  hum: ["gum"],
  hunk: ["gunk"],
  hunky: ["gunky"],
  hurtle: ["hustle"],
  hush: ["gush"],
  hussy: ["gussy"],
  hustle: ["hurtle"],
  hut: ["gut"],
  i: ["h", "j"],
  iamb: ["jamb"],
  ilk: ["ill"],
  ill: ["ilk"],
  "i'm": ["h'm"],
  impatiens: ["impatient"],
  impatient: ["inpatient", "impatiens"],
  import: ["impost"],
  importer: ["imposter"],
  impost: ["import"],
  imposter: ["importer"],
  incise: ["incite"],
  incite: ["indite", "incise"],
  indite: ["incite"],
  infest: ["ingest"],
  ingest: ["infest"],
  inmate: ["innate"],
  inn: ["ion"],
  innate: ["inmate"],
  inpatient: ["impatient"],
  insider: ["insides"],
  insides: ["insider"],
  invert: ["invest"],
  invest: ["invert"],
  ion: ["hon", "inn"],
  is: ["it"],
  it: ["is"],
  j: ["i", "k"],
  jamb: ["iamb"],
  jeep: ["keep"],
  jilt: ["kilt"],
  jingly: ["kingly"],
  john: ["join"],
  join: ["john"],
  josher: ["kosher"],
  k: ["j", "l"],
  keep: ["jeep"],
  keg: ["leg"],
  kick: ["lick"],
  kid: ["lid"],
  kiln: ["kilo"],
  kilo: ["kiln"],
  kilt: ["jilt", "lilt"],
  kind: ["kine"],
  kine: ["line", "kind"],
  kingly: ["jingly"],
  kink: ["link"],
  kit: ["lit"],
  kite: ["lite"],
  kook: ["look"],
  kosher: ["josher"],
  l: ["k", "m"],
  la: ["ma"],
  lab: ["lac"],
  lac: ["lab", "lad"],
  lace: ["mace", "lade"],
  lacerate: ["macerate"],
  laceration: ["maceration"],
  lacy: ["lady"],
  lad: ["mad", "lac"],
  ladder: ["madder"],
  lade: ["made", "lace"],
  lady: ["lacy"],
  lag: ["mag"],
  laid: ["maid"],
  lain: ["main"],
  lake: ["make"],
  lama: ["mama", "lamb"],
  lamb: ["lama"],
  lame: ["lane"],
  land: ["lane"],
  lane: ["mane", "lame", "land"],
  lap: ["map"],
  larch: ["march"],
  lark: ["mark"],
  laser: ["maser", "later"],
  lash: ["mash", "lath"],
  lass: ["mass", "last"],
  last: ["mast", "lass"],
  latch: ["match"],
  late: ["mate"],
  later: ["laser"],
  lath: ["math", "lash"],
  latte: ["matte"],
  latter: ["matter"],
  launder: ["maunder"],
  law: ["maw", "lax"],
  lax: ["max", "law", "lay"],
  lay: ["may", "lax"],
  laze: ["maze"],
  lead: ["mead"],
  lean: ["mean"],
  leaning: ["meaning"],
  leanness: ["meanness"],
  leaver: ["leaves"],
  leaves: ["leaver"],
  led: ["lee"],
  lee: ["led"],
  leek: ["meek"],
  leer: ["lees"],
  lees: ["leer"],
  leg: ["keg"],
  lend: ["mend"],
  lender: ["mender"],
  lens: ["lent"],
  lent: ["lens"],
  less: ["mess", "lest"],
  lest: ["less"],
  let: ["met"],
  lice: ["mice"],
  licensed: ["licensee"],
  licensee: ["licensed"],
  lick: ["kick"],
  lid: ["kid", "mid", "lie"],
  lie: ["lid"],
  lien: ["mien"],
  light: ["might"],
  like: ["mike"],
  lilt: ["kilt", "milt"],
  lily: ["limy"],
  lime: ["mime", "line"],
  limn: ["limo"],
  limo: ["limn", "limp"],
  limp: ["limo"],
  limy: ["lily"],
  line: ["kine", "mine", "lime"],
  liner: ["miner", "lines"],
  lines: ["liner"],
  lining: ["mining"],
  link: ["kink", "mink"],
  lint: ["mint"],
  linty: ["minty"],
  lire: ["mire"],
  list: ["mist"],
  lit: ["kit"],
  lite: ["kite", "mite"],
  liter: ["miter"],
  litigate: ["mitigate"],
  litigation: ["mitigation"],
  liver: ["lives"],
  lives: ["liver"],
  loam: ["loan"],
  loan: ["moan", "loam"],
  loaner: ["moaner"],
  lob: ["mob"],
  lobster: ["mobster"],
  lock: ["mock"],
  locker: ["mocker"],
  lode: ["mode"],
  loll: ["moll"],
  look: ["kook"],
  loom: ["loon"],
  loon: ["moon", "loom"],
  loose: ["moose"],
  loot: ["moot"],
  lop: ["mop"],
  lope: ["mope"],
  lord: ["lore"],
  lore: ["more", "lose", "lord"],
  lorn: ["morn"],
  lose: ["lore"],
  loss: ["moss", "lots", "lost"],
  lost: ["most", "loss"],
  lot: ["mot"],
  loth: ["moth"],
  lotion: ["motion"],
  lots: ["loss"],
  lotto: ["motto"],
  louse: ["mouse"],
  lousiness: ["mousiness"],
  lousy: ["mousy"],
  lovable: ["movable"],
  love: ["move"],
  loveable: ["moveable"],
  lover: ["mover", "lower"],
  loving: ["moving"],
  lovingly: ["movingly"],
  low: ["mow", "lox"],
  lower: ["mower", "lover"],
  lox: ["low"],
  luck: ["muck"],
  lucky: ["mucky"],
  luff: ["muff"],
  lug: ["mug"],
  lull: ["mull"],
  lunch: ["munch"],
  lurk: ["murk"],
  lush: ["mush"],
  lust: ["must"],
  luster: ["muster"],
  lustily: ["mustily"],
  lustiness: ["mustiness"],
  lusty: ["musty"],
  lute: ["mute"],
  m: ["l", "n"],
  ma: ["la"],
  mace: ["lace", "made"],
  macerate: ["lacerate"],
  maceration: ["laceration"],
  macho: ["nacho"],
  mad: ["lad"],
  madder: ["ladder"],
  made: ["lade", "mace"],
  mag: ["lag", "nag"],
  maid: ["laid"],
  mail: ["nail", "maim"],
  maim: ["mail", "main"],
  main: ["lain", "maim"],
  make: ["lake", "male"],
  male: ["make"],
  mama: ["lama"],
  mane: ["lane"],
  map: ["lap", "nap"],
  mapper: ["napper"],
  march: ["larch"],
  mark: ["lark", "nark", "mask", "marl"],
  marked: ["masked"],
  marker: ["masker"],
  marl: ["mark"],
  marque: ["masque"],
  marrow: ["narrow"],
  mart: ["mast"],
  maser: ["laser"],
  mash: ["lash", "math"],
  mask: ["mark"],
  masked: ["marked"],
  masker: ["marker"],
  masque: ["marque"],
  mass: ["lass", "mast"],
  mast: ["last", "mart", "matt", "mass"],
  masted: ["matted"],
  master: ["matter"],
  match: ["latch", "natch"],
  mate: ["late"],
  math: ["lath", "mash"],
  matt: ["mast"],
  matte: ["latte"],
  matted: ["masted"],
  matter: ["latter", "natter", "master"],
  mature: ["nature"],
  maunder: ["launder"],
  maw: ["law", "max"],
  max: ["lax", "maw", "may"],
  may: ["lay", "nay", "max"],
  maze: ["laze"],
  mead: ["lead"],
  mean: ["lean"],
  meaning: ["leaning"],
  meanness: ["leanness"],
  means: ["meant"],
  meant: ["means"],
  meat: ["neat"],
  meed: ["need"],
  meek: ["leek"],
  mend: ["lend"],
  mender: ["lender"],
  mess: ["less"],
  met: ["let", "net"],
  mettle: ["nettle"],
  mettlesome: ["nettlesome"],
  mew: ["new"],
  mews: ["news"],
  mice: ["lice", "nice"],
  mid: ["lid"],
  mien: ["lien"],
  might: ["light", "night"],
  mike: ["like", "mile"],
  mil: ["nil"],
  mild: ["mile"],
  mile: ["mike", "mime", "mild"],
  milk: ["mill"],
  milker: ["miller"],
  mill: ["milk"],
  miller: ["milker"],
  milt: ["lilt"],
  mime: ["lime", "mile", "mine"],
  mind: ["mine"],
  mine: ["line", "nine", "mime", "mind"],
  miner: ["liner"],
  mining: ["lining"],
  mink: ["link"],
  mint: ["lint"],
  minty: ["linty"],
  mire: ["lire"],
  miser: ["miter"],
  miss: ["mist"],
  mist: ["list", "mitt", "miss"],
  mite: ["lite", "nite"],
  miter: ["liter", "niter", "miser"],
  mitigate: ["litigate"],
  mitigation: ["litigation"],
  mitt: ["mist"],
  mix: ["nix"],
  moan: ["loan"],
  moaner: ["loaner"],
  mob: ["lob"],
  mobility: ["nobility"],
  mobster: ["lobster"],
  mock: ["lock"],
  mocker: ["locker"],
  mod: ["nod"],
  modal: ["nodal"],
  mode: ["lode", "node"],
  model: ["modem"],
  modem: ["model"],
  modular: ["nodular"],
  module: ["nodule"],
  mold: ["mole"],
  mole: ["mold"],
  moll: ["loll"],
  moo: ["mop"],
  moon: ["loon", "noon"],
  moose: ["loose", "noose"],
  moot: ["loot"],
  mop: ["lop", "moo"],
  mope: ["lope", "nope"],
  more: ["lore"],
  morn: ["lorn"],
  mosey: ["nosey"],
  mosh: ["nosh", "moth"],
  moss: ["loss", "most"],
  most: ["lost", "moss"],
  mot: ["lot", "not"],
  mote: ["note", "moue"],
  moth: ["loth", "mosh"],
  motion: ["lotion", "notion"],
  motto: ["lotto"],
  moue: ["mote", "move"],
  mouse: ["louse"],
  mousiness: ["lousiness"],
  mousy: ["lousy"],
  movable: ["lovable"],
  move: ["love", "moue"],
  moveable: ["loveable"],
  mover: ["lover", "mower"],
  moving: ["loving"],
  movingly: ["lovingly"],
  mow: ["low", "now"],
  mower: ["lower", "mover"],
  mu: ["nu"],
  muck: ["luck"],
  mucky: ["lucky"],
  muff: ["luff"],
  mug: ["lug"],
  mull: ["lull", "null"],
  munch: ["lunch"],
  murk: ["lurk", "musk"],
  murkiness: ["muskiness"],
  murky: ["musky"],
  muse: ["mute"],
  mush: ["lush"],
  musk: ["murk"],
  muskiness: ["murkiness"],
  musky: ["murky"],
  muss: ["must"],
  mussy: ["musty"],
  must: ["lust", "mutt", "muss"],
  muster: ["luster", "mutter"],
  mustily: ["lustily"],
  mustiness: ["lustiness"],
  musty: ["lusty", "mussy"],
  mute: ["lute", "muse"],
  mutt: ["must"],
  mutter: ["muster"],
  muzzle: ["nuzzle"],
  n: ["m", "o"],
  nacho: ["macho"],
  nag: ["mag"],
  nail: ["mail"],
  nap: ["map"],
  napper: ["mapper"],
  nark: ["mark"],
  narrow: ["marrow"],
  nasal: ["natal"],
  nastily: ["nattily"],
  nastiness: ["nattiness"],
  nasty: ["natty"],
  natal: ["nasal"],
  natch: ["match"],
  natter: ["matter"],
  nattily: ["nastily"],
  nattiness: ["nastiness"],
  natty: ["nasty"],
  nature: ["mature"],
  nay: ["may"],
  neat: ["meat"],
  need: ["meed"],
  nestle: ["nettle"],
  net: ["met"],
  nettle: ["mettle", "nestle"],
  nettlesome: ["mettlesome"],
  new: ["mew"],
  news: ["mews", "newt"],
  newt: ["next", "news"],
  next: ["newt"],
  nice: ["mice"],
  night: ["might"],
  nil: ["mil", "oil"],
  nine: ["mine"],
  nite: ["mite"],
  niter: ["miter"],
  nix: ["mix"],
  nobility: ["mobility"],
  nod: ["mod"],
  nodal: ["modal"],
  node: ["mode"],
  nodular: ["modular"],
  nodule: ["module"],
  noon: ["moon"],
  noose: ["moose"],
  nope: ["mope"],
  nose: ["note"],
  nosed: ["noted"],
  nosey: ["mosey"],
  nosh: ["mosh"],
  not: ["mot"],
  note: ["mote", "nose"],
  noted: ["nosed"],
  notion: ["motion"],
  now: ["mow"],
  nu: ["mu"],
  null: ["mull"],
  nut: ["out"],
  nuzzle: ["muzzle"],
  o: ["n", "p"],
  oar: ["par"],
  oat: ["pat"],
  oath: ["path"],
  odd: ["ode"],
  ode: ["odd"],
  oenology: ["penology"],
  officer: ["offices"],
  offices: ["officer"],
  oil: ["nil"],
  oiled: ["piled"],
  oink: ["pink"],
  old: ["ole"],
  ole: ["old"],
  om: ["on"],
  on: ["om"],
  oops: ["pops"],
  orate: ["prate"],
  otter: ["outer"],
  out: ["nut", "put"],
  outer: ["otter"],
  outrider: ["outsider"],
  outsider: ["outrider"],
  overbook: ["overcook"],
  overcook: ["overbook"],
  ow: ["ox"],
  ox: ["ow"],
  p: ["o", "q"],
  pains: ["paint"],
  paint: ["pains"],
  pall: ["palm"],
  palm: ["pall"],
  par: ["oar"],
  parse: ["passe"],
  part: ["past"],
  party: ["pasty"],
  pass: ["past"],
  passe: ["parse", "paste"],
  passel: ["pastel"],
  past: ["part", "pass"],
  paste: ["passe"],
  pastel: ["passel"],
  pastern: ["pattern"],
  pasty: ["party", "patty"],
  pat: ["oat"],
  path: ["oath"],
  patsy: ["patty"],
  pattern: ["pastern"],
  patty: ["pasty", "patsy"],
  peak: ["peal"],
  peal: ["peak"],
  peek: ["peel"],
  peel: ["peek"],
  penny: ["peony"],
  penology: ["oenology"],
  peony: ["penny"],
  perkily: ["peskily"],
  perkiness: ["peskiness"],
  perky: ["pesky"],
  pert: ["pest"],
  peskily: ["perkily"],
  peskiness: ["perkiness"],
  pesky: ["perky"],
  pest: ["pert"],
  phalanger: ["phalanges"],
  phalanges: ["phalanger"],
  phenol: ["phenom"],
  phenom: ["phenol"],
  phoney: ["phooey"],
  phooey: ["phoney"],
  pike: ["pile"],
  pile: ["pike"],
  piled: ["oiled"],
  pink: ["oink"],
  piper: ["pipes"],
  pipes: ["piper"],
  pis: ["pit"],
  pit: ["pis"],
  plains: ["plaint"],
  plaint: ["plains"],
  plaster: ["platter"],
  platter: ["plaster"],
  pleased: ["pleated"],
  pleated: ["pleased"],
  poke: ["pole"],
  pole: ["poke"],
  pompom: ["pompon"],
  pompon: ["pompom"],
  pond: ["pone"],
  pone: ["pond"],
  pops: ["oops"],
  pore: ["pose"],
  port: ["post"],
  portage: ["postage"],
  portal: ["postal"],
  porter: ["poster"],
  pose: ["pore"],
  post: ["port"],
  postage: ["portage", "pottage"],
  postal: ["portal"],
  poster: ["porter", "potter"],
  postnasal: ["postnatal"],
  postnatal: ["postnasal"],
  pottage: ["postage"],
  potter: ["poster", "pouter"],
  pouter: ["potter"],
  prate: ["orate"],
  preserver: ["preserves"],
  preserves: ["preserver"],
  price: ["pride"],
  pride: ["price"],
  promoter: ["prompter"],
  prompter: ["promoter"],
  puke: ["pule"],
  pule: ["puke"],
  pulp: ["pump"],
  pump: ["pulp"],
  pus: ["put"],
  put: ["out", "pus"],
  q: ["p", "r"],
  quash: ["quasi"],
  quasi: ["quash"],
  r: ["q", "s"],
  racer: ["races"],
  races: ["racer"],
  racial: ["radial"],
  racially: ["radially"],
  rack: ["sack"],
  rad: ["sad"],
  radial: ["racial"],
  radially: ["racially"],
  rag: ["sag", "rah"],
  raga: ["saga"],
  rage: ["sage"],
  rah: ["rag"],
  raid: ["said"],
  rail: ["sail"],
  railing: ["sailing"],
  rake: ["sake"],
  rally: ["sally"],
  ram: ["ran"],
  ran: ["ram"],
  randy: ["sandy"],
  rang: ["sang"],
  rank: ["sank"],
  rap: ["sap"],
  rash: ["sash"],
  rasher: ["rather"],
  rat: ["sat"],
  rate: ["sate"],
  rather: ["rasher"],
  ravage: ["savage"],
  ravager: ["ravages"],
  ravages: ["ravager"],
  rave: ["save"],
  raving: ["saving"],
  ravings: ["savings"],
  raw: ["saw"],
  ray: ["say"],
  real: ["seal", "ream"],
  ream: ["seam", "real"],
  rear: ["sear"],
  reason: ["season"],
  reasonable: ["seasonable"],
  reasonably: ["seasonably"],
  reasoned: ["seasoned"],
  reasoning: ["seasoning"],
  reboil: ["recoil"],
  rebus: ["rebut"],
  rebut: ["rebus"],
  rec: ["sec", "red"],
  recant: ["secant"],
  recede: ["secede"],
  recession: ["secession"],
  reclusive: ["seclusive"],
  recoil: ["reboil"],
  rector: ["sector"],
  red: ["rec"],
  reduce: ["seduce"],
  reducer: ["seducer"],
  reduction: ["seduction"],
  reductive: ["seductive"],
  reed: ["seed"],
  reediness: ["seediness"],
  reedy: ["seedy"],
  reek: ["seek", "reel"],
  reel: ["reek"],
  reelect: ["reflect"],
  reelection: ["reflection"],
  reflect: ["reelect"],
  reflection: ["reelection"],
  refuse: ["refute"],
  refute: ["refuse"],
  regress: ["regrets"],
  regrets: ["regress"],
  relax: ["relay"],
  relay: ["relax"],
  rend: ["send"],
  render: ["sender"],
  rent: ["sent"],
  reparable: ["separable"],
  reparation: ["separation"],
  resell: ["retell"],
  resold: ["retold", "resole"],
  resole: ["resold"],
  resort: ["retort"],
  retell: ["resell"],
  retired: ["retiree"],
  retiree: ["retired"],
  retold: ["resold"],
  retook: ["retool"],
  retool: ["retook"],
  retort: ["resort"],
  revere: ["severe"],
  revers: ["revert"],
  reversible: ["revertible"],
  revert: ["revers"],
  revertible: ["reversible"],
  rice: ["ride"],
  ricer: ["rider"],
  rick: ["sick"],
  ride: ["side", "rice"],
  rider: ["ricer"],
  riding: ["siding"],
  rife: ["riff"],
  riff: ["rife"],
  rift: ["sift"],
  right: ["sight"],
  rightly: ["sightly"],
  rile: ["rime"],
  rill: ["sill"],
  rime: ["rile"],
  ring: ["sing"],
  ringer: ["singer"],
  ringing: ["singing"],
  rink: ["sink"],
  rip: ["sip"],
  ripper: ["sipper"],
  rise: ["rite"],
  rite: ["site", "rise"],
  roam: ["roan"],
  roan: ["roam"],
  roar: ["soar"],
  roaring: ["soaring"],
  rob: ["sob"],
  rock: ["sock"],
  rocket: ["socket"],
  rod: ["sod", "roe"],
  roe: ["rod"],
  roil: ["soil"],
  role: ["sole"],
  root: ["soot"],
  roper: ["ropes"],
  ropes: ["roper"],
  rosary: ["rotary"],
  rose: ["rote"],
  rot: ["sot"],
  rotary: ["rosary"],
  rote: ["rose", "roue"],
  roue: ["rote", "rove"],
  rough: ["sough"],
  round: ["sound"],
  roundly: ["soundly"],
  roundness: ["soundness"],
  rouse: ["souse", "route"],
  route: ["rouse"],
  rove: ["roue"],
  rover: ["rower"],
  roving: ["rowing"],
  row: ["sow"],
  rower: ["sower", "rover"],
  rowing: ["roving"],
  rub: ["sub"],
  rue: ["sue"],
  rum: ["sum", "run"],
  rump: ["sump"],
  run: ["sun", "rum"],
  rundown: ["sundown"],
  rung: ["sung"],
  runny: ["sunny"],
  runs: ["runt"],
  runt: ["runs"],
  rusty: ["rutty"],
  rutty: ["rusty"],
  s: ["r", "t"],
  sable: ["table"],
  sabra: ["sacra"],
  sac: ["sad"],
  sack: ["rack", "tack"],
  sacker: ["tacker"],
  sacra: ["sabra"],
  sad: ["rad", "tad", "sac"],
  safe: ["sage"],
  safely: ["sagely"],
  sag: ["rag", "tag"],
  saga: ["raga"],
  sage: ["rage", "safe"],
  sagely: ["safely"],
  said: ["raid"],
  sail: ["rail", "tail"],
  sailing: ["railing"],
  sailor: ["tailor"],
  saint: ["taint"],
  sainted: ["tainted"],
  sake: ["rake", "take", "sale"],
  sale: ["tale", "sake", "same"],
  sallow: ["tallow"],
  sally: ["rally", "tally"],
  salon: ["talon"],
  same: ["tame", "sale", "sane"],
  sameness: ["tameness", "saneness"],
  sand: ["sane"],
  sandy: ["randy"],
  sane: ["same", "sand"],
  saneness: ["sameness"],
  sang: ["rang", "tang"],
  sank: ["rank", "tank"],
  sap: ["rap", "tap"],
  sash: ["rash"],
  sat: ["rat", "tat"],
  sate: ["rate"],
  saunter: ["taunter"],
  savage: ["ravage"],
  save: ["rave"],
  saving: ["raving"],
  savings: ["ravings"],
  saw: ["raw", "sax"],
  sax: ["tax", "saw", "say"],
  say: ["ray", "sax"],
  scald: ["scale"],
  scale: ["scald"],
  scalp: ["scamp"],
  scalper: ["scamper"],
  scam: ["scan"],
  scamp: ["scalp"],
  scamper: ["scalper"],
  scan: ["scam"],
  scare: ["scarf"],
  scarf: ["scare"],
  scribbler: ["scribbles"],
  scribbles: ["scribbler"],
  sea: ["tea"],
  seal: ["real", "teal", "seam"],
  seam: ["ream", "team", "seal"],
  sear: ["rear", "tear"],
  season: ["reason"],
  seasonable: ["reasonable"],
  seasonably: ["reasonably"],
  seasoned: ["reasoned"],
  seasoning: ["reasoning"],
  seat: ["teat"],
  sec: ["rec"],
  secant: ["recant"],
  secede: ["recede"],
  secession: ["recession"],
  seclusive: ["reclusive"],
  sector: ["rector"],
  seduce: ["reduce"],
  seducer: ["reducer"],
  seduction: ["reduction"],
  seductive: ["reductive"],
  see: ["tee"],
  seed: ["reed"],
  seediness: ["reediness"],
  seedy: ["reedy"],
  seek: ["reek"],
  seem: ["teem", "seen"],
  seeming: ["teeming"],
  seen: ["teen", "seem"],
  seethe: ["teethe"],
  seething: ["teething"],
  sell: ["tell"],
  seller: ["teller"],
  send: ["rend", "tend"],
  sender: ["render", "tender"],
  senor: ["tenor"],
  sense: ["tense"],
  sent: ["rent", "tent"],
  separable: ["reparable"],
  separation: ["reparation"],
  sere: ["serf"],
  serf: ["sere"],
  sever: ["sewer"],
  severe: ["revere"],
  sew: ["sex"],
  sewer: ["sever"],
  sex: ["sew"],
  shag: ["shah"],
  shah: ["shag"],
  shake: ["shale"],
  shale: ["shake", "shame"],
  shame: ["shale"],
  shank: ["thank"],
  shard: ["share"],
  share: ["shard"],
  shat: ["that"],
  she: ["the"],
  shew: ["thew"],
  shim: ["shin"],
  shin: ["thin", "shim"],
  shine: ["thine"],
  shod: ["shoe"],
  shoe: ["shod"],
  shoo: ["shop"],
  shop: ["shoo"],
  shorn: ["thorn"],
  shrew: ["threw"],
  shrift: ["thrift"],
  shrill: ["thrill"],
  shrive: ["thrive"],
  shriven: ["thriven"],
  shy: ["thy"],
  sic: ["tic"],
  sick: ["rick", "tick"],
  sickle: ["tickle"],
  side: ["ride", "tide"],
  sidebar: ["sidecar"],
  sidecar: ["sidebar"],
  sidewalk: ["sidewall"],
  sidewall: ["sidewalk"],
  siding: ["riding"],
  sift: ["rift"],
  sight: ["right", "tight"],
  sightly: ["rightly", "tightly"],
  silk: ["sill"],
  silkiness: ["silliness"],
  silky: ["silly"],
  sill: ["rill", "till", "silk"],
  silliness: ["silkiness"],
  silly: ["silky"],
  silt: ["tilt"],
  sin: ["tin"],
  sine: ["tine"],
  sing: ["ring", "ting"],
  singe: ["tinge"],
  singer: ["ringer"],
  singing: ["ringing"],
  single: ["tingle"],
  singly: ["tingly"],
  sink: ["rink"],
  sinker: ["tinker"],
  sip: ["rip", "tip"],
  sipper: ["ripper", "tipper"],
  sir: ["sis"],
  sire: ["tire"],
  sis: ["sir", "sit"],
  sister: ["sitter"],
  sit: ["tit", "sis"],
  site: ["rite"],
  sitter: ["titter", "sister"],
  skate: ["slate"],
  skeet: ["sleet"],
  skew: ["slew"],
  skid: ["slid"],
  skids: ["skies"],
  skier: ["slier", "skies"],
  skies: ["skids", "skier"],
  skim: ["slim", "skin"],
  skin: ["skim"],
  skip: ["slip"],
  skipper: ["slipper"],
  skit: ["slit"],
  skulk: ["skull"],
  skull: ["skulk"],
  skunk: ["slunk"],
  sky: ["sly"],
  slack: ["smack"],
  slacker: ["smacker"],
  slash: ["smash"],
  slasher: ["smasher", "slather"],
  slate: ["skate"],
  slather: ["slasher"],
  sleet: ["skeet"],
  slew: ["skew"],
  slice: ["slide"],
  slicer: ["slider"],
  slid: ["skid"],
  slide: ["slice"],
  slider: ["slicer"],
  slier: ["skier"],
  slim: ["skim"],
  slip: ["skip"],
  slipper: ["skipper"],
  slit: ["skit"],
  slog: ["smog"],
  slosh: ["sloth"],
  sloth: ["slosh"],
  sludge: ["smudge"],
  sludgy: ["smudgy"],
  slug: ["smug"],
  slunk: ["skunk"],
  slut: ["smut"],
  slutty: ["smutty"],
  sly: ["sky"],
  smack: ["slack", "snack"],
  smacker: ["slacker"],
  smash: ["slash"],
  smasher: ["slasher"],
  smog: ["slog"],
  smudge: ["sludge"],
  smudgy: ["sludgy"],
  smug: ["slug", "snug"],
  smuggle: ["snuggle"],
  smugly: ["snugly"],
  smugness: ["snugness"],
  smut: ["slut"],
  smutty: ["slutty"],
  snack: ["smack"],
  snap: ["soap"],
  snot: ["soot"],
  snuffle: ["souffle"],
  snug: ["smug"],
  snuggle: ["smuggle"],
  snugly: ["smugly"],
  snugness: ["smugness"],
  so: ["to"],
  soap: ["snap"],
  soar: ["roar", "spar"],
  soaring: ["roaring", "sparing"],
  sob: ["rob"],
  sock: ["rock"],
  socket: ["rocket"],
  sod: ["rod"],
  soil: ["roil", "toil"],
  sold: ["told", "sole"],
  sole: ["role", "tole", "some", "sold"],
  some: ["tome", "sole"],
  son: ["ton"],
  song: ["tong"],
  sonic: ["tonic"],
  soot: ["root", "toot", "snot", "spot"],
  sooth: ["tooth"],
  sop: ["top"],
  sopping: ["topping"],
  sore: ["tore"],
  sort: ["tort"],
  sot: ["rot", "tot"],
  souffle: ["snuffle"],
  sough: ["rough", "tough"],
  sound: ["round"],
  soundly: ["roundly"],
  soundness: ["roundness"],
  sour: ["tour", "spur"],
  souse: ["rouse"],
  sow: ["row", "tow", "sox"],
  sower: ["rower", "tower"],
  sown: ["town"],
  sox: ["sow", "soy"],
  soy: ["toy", "spy", "sox"],
  space: ["spade"],
  spade: ["space"],
  spar: ["soar"],
  sparing: ["soaring"],
  spec: ["sped"],
  sped: ["spec"],
  spoils: ["spoilt"],
  spoilt: ["spoils"],
  spook: ["spool"],
  spool: ["spook"],
  spot: ["soot"],
  spur: ["sour"],
  spy: ["soy"],
  squeak: ["squeal"],
  squeaker: ["squealer"],
  squeal: ["squeak"],
  squealer: ["squeaker"],
  stake: ["stale"],
  stale: ["stake"],
  stalk: ["stall"],
  stall: ["stalk"],
  stars: ["start"],
  start: ["stars"],
  stave: ["suave"],
  steak: ["steal"],
  steal: ["steak", "steam"],
  steam: ["steal"],
  stet: ["suet"],
  stoke: ["stole"],
  stole: ["stoke"],
  suave: ["stave"],
  sub: ["rub", "tub"],
  suck: ["tuck"],
  sucker: ["tucker"],
  sue: ["rue"],
  suet: ["stet"],
  sulky: ["sully"],
  sully: ["sulky"],
  sum: ["rum", "sun"],
  sumo: ["sump"],
  sump: ["rump", "sumo"],
  sun: ["run", "tun", "sum"],
  sundown: ["rundown"],
  sung: ["rung"],
  sunny: ["runny", "tunny"],
  supplier: ["supplies"],
  supplies: ["supplier"],
  sure: ["surf"],
  surf: ["turf", "sure"],
  swaddle: ["twaddle"],
  swain: ["twain"],
  swam: ["swan"],
  swan: ["swam"],
  swash: ["swath"],
  swath: ["swash"],
  sweet: ["tweet"],
  swig: ["twig"],
  swill: ["twill"],
  swine: ["twine"],
  swirl: ["twirl"],
  swirly: ["twirly"],
  switch: ["twitch"],
  sword: ["swore"],
  swore: ["sword"],
  t: ["s", "u"],
  table: ["sable"],
  tack: ["sack"],
  tacker: ["sacker"],
  tad: ["sad"],
  tag: ["sag"],
  tail: ["sail"],
  tailor: ["sailor"],
  taint: ["saint"],
  tainted: ["sainted"],
  take: ["sake", "tale"],
  tale: ["sale", "take", "tame"],
  talk: ["tall"],
  talky: ["tally"],
  tall: ["talk"],
  tallow: ["sallow"],
  tally: ["sally", "talky"],
  talon: ["salon"],
  tam: ["tan"],
  tame: ["same", "tale"],
  tameness: ["sameness"],
  tan: ["tam"],
  tang: ["sang"],
  tank: ["sank"],
  tap: ["sap"],
  tarn: ["taro"],
  taro: ["tarn", "tarp"],
  tarp: ["taro"],
  taster: ["tatter"],
  tasting: ["tatting"],
  tat: ["sat", "tau"],
  tatter: ["taster"],
  tatting: ["tasting"],
  tau: ["tat"],
  taunter: ["saunter"],
  tax: ["sax"],
  tea: ["sea"],
  teak: ["teal"],
  teal: ["seal", "teak", "team"],
  team: ["seam", "teal"],
  tear: ["sear"],
  teat: ["seat"],
  tee: ["see"],
  teem: ["seem", "teen"],
  teeming: ["seeming"],
  teen: ["seen", "teem"],
  teethe: ["seethe"],
  teething: ["seething"],
  tell: ["sell"],
  teller: ["seller"],
  tend: ["send"],
  tender: ["sender"],
  tenor: ["senor"],
  tense: ["sense"],
  tent: ["sent"],
  term: ["tern"],
  tern: ["term"],
  tester: ["testes"],
  testes: ["tester"],
  thank: ["shank"],
  that: ["shat"],
  the: ["she", "tie"],
  them: ["then"],
  then: ["them"],
  there: ["these"],
  these: ["there"],
  thew: ["shew"],
  thin: ["shin"],
  thine: ["shine"],
  thorn: ["shorn"],
  threw: ["shrew"],
  thrift: ["shrift"],
  thrill: ["shrill"],
  thrive: ["shrive"],
  thriven: ["shriven"],
  throughout: ["throughput"],
  throughput: ["throughout"],
  thy: ["shy"],
  tic: ["sic"],
  tick: ["sick"],
  tickle: ["sickle"],
  tide: ["side"],
  tie: ["the"],
  tight: ["sight"],
  tightly: ["sightly"],
  tike: ["tile"],
  tile: ["tike", "time"],
  tiler: ["timer"],
  tiling: ["timing"],
  till: ["sill"],
  tilt: ["silt"],
  time: ["tile", "tine"],
  timer: ["tiler", "times"],
  times: ["timer"],
  timing: ["tiling"],
  tin: ["sin"],
  tine: ["sine", "time"],
  ting: ["sing"],
  tinge: ["singe"],
  tingle: ["single"],
  tingly: ["singly"],
  tinker: ["sinker"],
  tip: ["sip"],
  tipper: ["sipper"],
  tire: ["sire"],
  tit: ["sit"],
  titter: ["sitter"],
  to: ["so"],
  toil: ["soil"],
  toke: ["tole"],
  told: ["sold", "tole"],
  tole: ["sole", "toke", "tome", "told"],
  tom: ["ton"],
  tome: ["some", "tole", "tone"],
  ton: ["son", "tom", "too"],
  tone: ["tome"],
  tong: ["song"],
  tonic: ["sonic"],
  too: ["ton", "top"],
  took: ["tool"],
  tool: ["took"],
  toot: ["soot"],
  tooth: ["sooth"],
  top: ["sop", "too"],
  topping: ["sopping"],
  tore: ["sore"],
  tort: ["sort"],
  tot: ["sot"],
  tough: ["sough"],
  tour: ["sour"],
  tow: ["sow"],
  tower: ["sower"],
  town: ["sown"],
  toy: ["soy"],
  trace: ["trade"],
  tracer: ["trader"],
  tracing: ["trading"],
  trade: ["trace"],
  trader: ["tracer"],
  trading: ["tracing"],
  trained: ["trainee"],
  trainee: ["trained"],
  treacle: ["treadle"],
  treadle: ["treacle"],
  tribe: ["trice"],
  trice: ["tribe"],
  trio: ["trip"],
  trip: ["trio"],
  truss: ["trust"],
  trust: ["truss"],
  tub: ["sub"],
  tuck: ["suck"],
  tucker: ["sucker"],
  tun: ["sun"],
  tunny: ["sunny"],
  turf: ["surf"],
  twaddle: ["swaddle"],
  twain: ["swain"],
  tweet: ["sweet"],
  twig: ["swig"],
  twill: ["swill"],
  twine: ["swine"],
  twirl: ["swirl"],
  twirly: ["swirly"],
  twister: ["twitter"],
  twitch: ["switch"],
  twitter: ["twister"],
  u: ["t", "v"],
  underline: ["undermine"],
  undermine: ["underline"],
  unlovable: ["unmovable"],
  unloved: ["unmoved"],
  unmovable: ["unlovable"],
  unmoved: ["unloved"],
  unreal: ["unseal"],
  unreasonable: ["unseasonable"],
  unreasonably: ["unseasonably"],
  unseal: ["unreal"],
  unseasonable: ["unreasonable"],
  unseasonably: ["unreasonably"],
  unsold: ["untold"],
  untold: ["unsold"],
  v: ["u", "w"],
  vain: ["wain"],
  vale: ["wale"],
  value: ["valve"],
  valued: ["valved"],
  valueless: ["valveless"],
  valuer: ["values"],
  values: ["valuer"],
  valve: ["value"],
  valved: ["valued"],
  valveless: ["valueless"],
  van: ["wan"],
  vane: ["wane"],
  vary: ["wary"],
  vast: ["wast"],
  veal: ["weal"],
  veep: ["weep"],
  veld: ["weld"],
  vend: ["wend"],
  vender: ["veneer"],
  veneer: ["vender"],
  vent: ["went"],
  vest: ["west"],
  vet: ["wet"],
  vibe: ["vice"],
  vice: ["vibe"],
  vile: ["wile"],
  vine: ["wine"],
  vino: ["wino"],
  viper: ["wiper"],
  visa: ["vita"],
  vise: ["wise"],
  vita: ["visa"],
  vow: ["wow"],
  w: ["v", "x"],
  wafer: ["wager"],
  wager: ["wafer", "wages"],
  wages: ["wager"],
  wain: ["vain"],
  wake: ["wale"],
  wale: ["vale", "wake"],
  walk: ["wall"],
  wall: ["walk"],
  wan: ["van"],
  wand: ["wane"],
  wane: ["vane", "wand"],
  war: ["was"],
  ward: ["ware"],
  ware: ["ward"],
  warm: ["warn"],
  warn: ["warm"],
  warp: ["wasp"],
  wart: ["wast"],
  wary: ["vary"],
  was: ["war"],
  wasp: ["warp"],
  wast: ["vast", "wart", "watt"],
  wastage: ["wattage"],
  waster: ["wastes"],
  wastes: ["waster"],
  watt: ["wast"],
  wattage: ["wastage"],
  wax: ["way"],
  way: ["wax"],
  weak: ["weal"],
  weal: ["veal", "weak"],
  wed: ["wee"],
  wee: ["wed"],
  weep: ["veep"],
  weld: ["veld"],
  wend: ["vend"],
  went: ["vent"],
  west: ["vest"],
  wet: ["vet"],
  whereas: ["whereat"],
  whereat: ["whereas"],
  whistle: ["whittle"],
  whistler: ["whittler"],
  whittle: ["whistle"],
  whittler: ["whistler"],
  whooper: ["whopper"],
  whopper: ["whooper"],
  whore: ["whose"],
  whose: ["whore"],
  wild: ["wile"],
  wilds: ["wiles"],
  wile: ["vile", "wild"],
  wiles: ["wilds"],
  wind: ["wine"],
  wine: ["vine", "wind"],
  wino: ["vino"],
  wiper: ["viper"],
  wire: ["wise"],
  wise: ["vise", "wire"],
  wish: ["with"],
  wisher: ["wither"],
  with: ["wish"],
  wither: ["wisher"],
  won: ["woo"],
  woo: ["won"],
  word: ["wore"],
  wore: ["word"],
  worm: ["worn"],
  worn: ["worm"],
  wow: ["vow"],
  x: ["w", "y"],
  "x-axes": ["y-axes"],
  "x-axis": ["y-axis"],
  y: ["x", "z"],
  yap: ["zap"],
  "y-axes": ["x-axes"],
  "y-axis": ["x-axis"],
  yes: ["yet"],
  yet: ["yes"],
  yip: ["zip"],
  z: ["y", "a"],
  zap: ["yap"],
  zip: ["yip"],
};

export default data;
