const data = {
  a: ["e", "v", "h", "o"],
  abeam: ["wedge", "hedge"],
  abed: ["page", "gage"],
  abide: ["agree"],
  abs: ["gee", "see", "ego"],
  abyss: ["serge"],
  ad: ["go"],
  adenoid: ["peonage"],
  adieu: ["neigh"],
  adios: ["snipe", "serge", "gorge", "sarge"],
  ado: ["ape", "age", "ego", "ago"],
  adobe: ["agape"],
  adore: ["adage"],
  advised: ["peerage"],
  aeon: ["node", "undo"],
  agape: ["adobe"],
  agar: ["doge", "dose", "josh", "dodo"],
  age: ["age", "ash", "ado", "ago", "ego"],
  aged: ["page", "gage", "gash", "peso"],
  agent: ["lodge"],
  ages: ["gage", "sage", "edge", "ease", "gash", "sash", "sago"],
  agile: ["elide"],
  aging: [
    "suede",
    "guide",
    "snide",
    "surge",
    "gorge",
    "gorse",
    "guise",
    "burgh",
  ],
  ago: ["ode", "age", "ash", "ado", "ego", "ago"],
  agog: [
    "bode",
    "bade",
    "doge",
    "gage",
    "sage",
    "dose",
    "base",
    "babe",
    "gosh",
    "bosh",
    "dash",
    "gash",
    "sash",
    "bash",
    "dodo",
    "dado",
    "sago",
  ],
  agony: ["rondo"],
  agree: ["badge"],
  ah: ["ye", "he", "me", "ah", "yo", "ho"],
  aha: ["eye", "hah", "oho"],
  ahem: ["heme"],
  ahoy: ["heme", "home", "tome", "tame", "homo"],
  aid: ["pee", "gee", "pie", "pro"],
  aide: ["epee"],
  ail: ["lee", "tee", "lie", "tie"],
  ailing: ["goitre", "sortie"],
  aim: ["wee", "hie"],
  air: ["die"],
  airs: ["gyro"],
  airy: ["tyro"],
  ajar: ["dole", "yore"],
  alas: ["sole", "solo"],
  alder: ["depth"],
  ale: ["ale", "ate"],
  alga: ["ogle"],
  alight: ["labile"],
  alit: ["tile", "lite"],
  alive: ["earth"], //kind of cool
  aliyah: ["motile", "hereto"],
  allay: ["hello"],
  alley: ["hello"],
  allot: ["latte", "lotto"],
  allow: ["matte", "motto"],
  alloy: ["hello"],
  aloe: [
    "dole",
    "bole",
    "dale",
    "bale",
    "dote",
    "ante",
    "date",
    "bate",
    "doth",
    "both",
    "bath",
  ],
  aloha: ["emote"],
  alone: ["booth"],
  along: ["sooth", "booth"],
  also: ["ogle"],
  altar: ["jello"],
  alter: ["jello"],
  alto: ["alto"],
  am: ["we", "he", "ho"],
  an: ["uh", "oh", "no"],
  anal: ["lone", "tone"],
  and: ["goo"],
  anew: ["mane"],
  angel: ["taboo"],
  aniline: ["aniline"],
  anon: ["none"],
  ant: ["toe", "too"],
  ante: ["blue", "aloe"],
  any: ["hue", "rue", "hoe", "toe", "roe", "woe", "huh", "too", "woo"],
  ape: ["ado"],
  aphid: ["grade"],
  apish: ["aside"],
  are: ["aye", "eye", "dye", "bye", "ado"],
  aria: ["hide"],
  arise: ["aside"],
  array: ["redye"],
  art: ["lye"],
  arts: ["stye"],
  as: ["eh", "sh", "go", "so"],
  ash: ["age", "ash", "ago"],
  ashlar: ["dotage"],
  ashy: ["thee", "whee", "rage", "wage", "hash", "rash", "wash"],
  aside: ["agree", "apish"],
  asinine: ["burnish"],
  ass: ["gee", "see", "ssh", "ego"],
  assay: ["these"],
  asset: ["lasso"],
  at: ["to", "lo"],
  ate: ["ate", "ale"],
  atom: ["hate", "hole", "wale", "hale", "hath", "halo"],
  atone: ["booth"],
  atop: ["dote", "date", "dole", "dale", "doth"],
  attar: ["jello"],
  attendee: ["baguette"],
  aunt: ["tune", "tone", "lone"],
  aver: ["yeah"], //state to be the case
  avow: ["yeah"],
  aw: ["me", "ye", "yo"],
  away: ["heme", "home", "tome", "homo"],
  awe: ["aye", "eye", "dye", "bye"],
  awed: ["game"],
  awl: ["lye"],
  ax: ["oh"],
  axe: ["axe", "doe", "boo"],
  axial: ["throe"],
  axle: ["aloe"],
  aye: ["ate", "are", "ere", "awe", "ewe", "bro"],
  b: ["q", "g", "e"],
  baa: ["veg", "hog", "eve", "hoe"],
  babe: ["agog"],
  bad: ["peg", "pee", "gee"],
  bade: ["agog", "epee"],
  bag: ["beg", "dog", "bog", "gee", "see", "bee", "she", "doe"],
  baguette: ["attendee"],
  bah: ["hog", "hoe"],
  bail: ["tree", "jive", "live"],
  bait: ["tree", "live"],
  bald: ["glee"],
  bale: ["aloe"],
  baler: ["delve"],
  balsa: ["helve"],
  ban: ["nee"],
  bane: ["dove"],
  bang: ["dove"],
  bar: ["jog", "dog", "doe"],
  barb: ["gyve"],
  bard: ["gyve"],
  base: ["agog"],
  bash: ["agog"],
  basis: ["sieve"],
  basset: ["lessee"],
  bat: ["leg", "tog", "log", "tee", "lee", "the", "toe"],
  bate: ["aloe"],
  bath: ["aloe"],
  bathe: ["bathe"],
  bathos: ["goatee"],
  baths: ["salve"],
  bats: ["slog", "glee", "sloe"],
  bawd: ["gyve"],
  bay: ["hog", "tog", "tee", "wee", "the", "hoe", "toe", "roe", "woe"],
  bayou: ["nerve"],
  be: ["be"],
  beam: ["whee"],
  bean: ["node"],
  beast: ["levee"],
  beat: ["thee", "lode", "lobe"],
  beau: ["node"],
  bed: ["gag", "peg", "pee", "gee"],
  bee: ["bag", "beg", "bee"],
  beer: ["jade"],
  beet: ["lade"],
  beg: ["gag", "sag", "bag", "beg", "gee", "see", "bee"],
  begone: ["bungee"],
  beige: ["agree", "aside", "abide"],
  being: ["suede", "guide", "snide"],
  belong: ["bootee", "goatee"],
  below: ["melee"],
  bent: ["lode", "tube", "lube", "lobe"],
  bet: ["tag", "lag", "leg", "tee", "lee"],
  bevy: ["wade"],
  bey: ["hag", "tag", "rag", "wag", "tee", "wee"],
  beyond: ["goatee"],
  bi: ["re"],
  bias: ["sere", "gore", "sore"],
  bib: ["erg", "gig", "ere", "gee"],
  bid: ["peg", "pig", "gig", "pee", "gee", "pie"],
  bide: ["epee"],
  bidet: ["tepee"],
  bier: ["dare"],
  big: ["beg", "dig", "gig", "big", "gee", "see", "bee", "die"],
  biggie: ["biggie"],
  bin: ["ore", "nee"],
  bind: ["pure", "pore", "gore"],
  binding: ["soignee"],
  binge: ["adore"],
  bingo: ["adore"],
  bio: ["erg", "ere", "ore", "are", "nee"],
  biped: ["padre"],
  bird: ["pyre"],
  bit: ["leg", "tee", "lee", "tie", "lie"],
  biting: ["goitre", "sortie"],
  blah: ["hole", "mole", "mete", "mote"],
  blahs: ["emote", "smote"],
  bled: ["pale", "gale", "pate", "gate"],
  bleed: ["gable"],
  blew: ["male", "mate", "mete"],
  blight: ["labile"],
  blind: ["guile"],
  bloat: ["thole"],
  blob: ["gale", "gate"],
  blot: ["tole", "tale", "tote", "late"],
  blouse: ["denote"],
  blow: ["mole", "male", "mete", "mote", "mate"],
  blower: ["demote"],
  blowsy: ["remote"],
  blue: ["ante"],
  bluster: ["detente"],
  boa: ["veg", "hog", "hag", "hoe", "one"],
  boar: ["dong", "done"],
  boast: ["levee"],
  boat: ["tong", "long", "thee", "tone", "lone"],
  bob: ["gag", "gee"],
  bod: ["peg", "gag", "pee", "gee"],
  bode: ["agog", "epee"],
  bog: ["beg", "dog", "bog", "gag", "sag", "bag", "gee", "see", "bee", "doe"],
  boil: ["ting", "tree", "line", "tine"],
  boiling: ["boiling", "suiting"],
  bold: ["glee"],
  bole: ["aloe"],
  bombed: ["peewee"],
  bond: ["gong", "pone", "gone"],
  bonding: ["soignee"],
  bone: ["dung", "bung", "dong", "bong", "dune", "done", "bone"],
  bong: [
    "dung",
    "sung",
    "bung",
    "dong",
    "gong",
    "song",
    "bong",
    "snag",
    "dune",
    "done",
    "gone",
    "bone",
  ],
  bony: ["hung", "rung", "tong", "tune", "rune", "hone", "tone"],
  boo: ["nag", "nee", "one"],
  boob: ["gong", "gang", "gene", "gone"],
  boogie: ["begone"],
  boom: ["hang", "hone", "wane"],
  boon: ["none"],
  boor: ["dong", "dang", "yang", "done"],
  boot: ["tong", "long", "tang", "tone", "lone", "lane"],
  bootee: ["belong"],
  booth: ["along", "atone", "alone"],
  bootie: ["belong"],
  bop: ["dog", "doe"],
  bored: ["payee"],
  bosh: ["agog"],
  boss: ["gene"],
  both: ["aloe"],
  bow: ["mag"],
  box: ["one"],
  boxy: ["tong", "hone", "tone"],
  boy: [
    "hog",
    "tog",
    "hag",
    "tag",
    "rag",
    "wag",
    "tee",
    "wee",
    "hoe",
    "toe",
    "roe",
    "woe",
  ],
  bra: ["ode", "eye"],
  brae: ["bode"],
  brag: ["bode"],
  braid: ["geode"],
  bran: ["node"],
  brass: ["geode"],
  brat: ["lode"],
  bray: ["rode"],
  brew: ["made"],
  brie: ["aide", "bide"],
  brig: ["side", "bide"],
  brim: ["wide", "hide"],
  bring: ["suede", "guide", "snide"],
  briny: ["horde"],
  bro: ["ode", "eye", "aye"],
  broad: ["geode"],
  broil: ["trade"],
  brood: ["geode"],
  brow: ["mode", "made"],
  brr: ["dye"],
  building: ["gurgling"],
  bun: ["one"],
  bung: [
    "dung",
    "sung",
    "bung",
    "dong",
    "gong",
    "song",
    "bong",
    "dune",
    "done",
    "gone",
    "bone",
  ],
  bungee: ["begone"],
  buns: ["sung", "gong", "song", "gone"],
  bunt: ["lung", "tong", "long", "tune", "tone", "lone"],
  buoy: ["tong", "hang", "tang", "rang", "hone", "tone", "wane"],
  busing: ["soigne"],
  buss: ["gene"],
  by: ["he", "re", "we"],
  bye: ["erg", "ate", "are", "ere", "awe", "ewe"],
  d: ["p", "g"],
  dad: ["pep", "pop", "peg"],
  dado: ["agog", "dope", "doge"],
  dais: ["seep", "grog"],
  dale: ["atop", "dale", "date"],
  dam: ["hep", "hop", "hog"],
  dang: ["goop"],
  dare: ["dado"],
  darn: ["dude", "dodo"],
  dash: ["agog", "dash"],
  data: ["dote", "dole", "doth"],
  date: ["atop", "date", "dale"],
  dative: ["dearth"], //dative is indirect object
  dawn: ["dome", "dunno"],
  day: ["hep", "rep", "hop", "top", "hog", "tog"],
  days: ["step", "shop", "stop", "swop", "grog"],
  daze: ["daze"],
  dead: ["peep"],
  deal: ["leap", "jeep"],
  dean: ["neap", "dove"],
  dear: ["jeep", "deep"],
  death: ["dated"],
  deb: ["gap", "gag", "deb"],
  debt: ["leap"],
  deed: ["peep"],
  deem: ["heap", "weep"],
  deep: ["deep"],
  deer: ["jeep", "deep"],
  deign: ["dogie"],
  deism: ["dweeb"],
  delegate: ["delegate"],
  delete: ["delete"],
  delta: ["delta"],
  den: ["nap", "nag", "due", "doe", "dud", "dub"],
  dengue: ["dengue"],
  deny: ["drub"],
  detonate: ["detonate"],
  dew: ["map", "yap", "yep", "mag", "dye"],
  dhoti: ["delay"],
  diagnose: ["deanship"],
  dial: ["jeep"],
  diary: ["dryer"],
  dibs: ["seep", "deer"],
  did: ["pep", "pip", "peg", "pig", "gig"],
  dido: ["dope", "doge"],
  die: ["dip", "erg", "beg", "dig", "big"],
  diet: ["tarp"],
  dig: ["dip", "sip", "beg", "dig", "gig", "big"],
  dilate: ["delete"],
  dim: ["hep", "hip", "wig"],
  din: ["nip", "due", "doe"],
  dine: ["burp", "burg"],
  ding: ["burp", "gorp", "snip", "burg"],
  dingus: ["dengue"],
  dip: ["dip", "dig"],
  dis: ["sip", "erg", "gig"],
  dish: ["dyer"],
  dishes: ["debase"],
  dismay: ["drowse"],
  diva: ["harp", "dear"],
  dive: ["dear"],
  do: ["do"],
  dodo: ["agog", "dope", "doge", "dopa"],
  doe: ["bop", "beg", "dog", "bog", "bag", "den"],
  doer: ["jeep", "deep", "dang", "yang"],
  does: ["seep", "gang", "sang", "dean"],
  dog: ["sop", "bop", "gap", "sap", "beg", "dog", "bog", "gag", "sag", "bag"],
  doge: ["agog", "dado"],
  dogged: ["gasbag"],
  dogie: ["bebop", "deign"],
  dogma: ["dowse"],
  doing: ["doing", "going"],
  dole: ["atop", "dale", "date", "data"],
  dollar: ["dollop"],
  dollop: ["dollop"],
  dome: ["dawn"],
  don: ["nap", "nag", "due", "doe", "duo", "dun", "don"],
  dona: ["hoop", "hung", "done", "dona"],
  done: ["dung", "bung", "dong", "bong"],
  dong: [
    "goop",
    "snap",
    "soap",
    "dung",
    "sung",
    "bung",
    "dong",
    "gong",
    "song",
    "bong",
    "snag",
  ],
  donor: ["young"],
  doom: ["weep", "hoop", "heap", "hang"],
  door: ["jeep", "deep", "dong", "dang", "yang"],
  dopa: ["dodo"],
  dope: ["dado"],
  dose: ["deep", "beep", "agog"],
  dost: ["leap"],
  dot: ["top", "lop", "tap", "lap", "leg", "tog", "log", "tag", "lag"],
  dote: ["atop", "date", "dale", "data"],
  doth: ["atop", "date", "dale", "data"],
  doting: ["burlap"],
  dotted: ["gallop"],
  dove: ["dang", "bang", "dean"],
  down: ["dome", "dunno"],
  doze: ["daze"],
  drab: ["deed"],
  drawn: ["domed"],
  drown: ["domed"],
  drub: ["deny"],
  dry: ["dry"],
  dual: ["long", "tong"],
  dub: ["den"],
  due: ["den"],
  duel: ["tang"],
  dues: ["gang", "sang", "dean"],
  duet: ["tang"],
  dun: ["dun", "don"],
  dune: ["dung", "bung", "dong", "bong"],
  dung: ["dung", "sung", "bung", "dong", "gong", "song", "bong"],
  duo: ["den", "don"],
  dye: ["erg", "dew"],
  dyer: ["dyer"],
  e: ["a", "e", "d", "b"],
  eager: ["jaded"],
  ear: ["yea", "doe", "deb", "job"],
  eared: ["payee"],
  ease: ["deed", "aged"],
  easy: ["heed", "reed", "weed"],
  eat: ["tea", "lea", "tee", "lee", "the", "toe", "led", "lob"],
  eater: ["delve", "dated"],
  eats: ["glee", "sloe", "sled", "glob", "slob"],
  eave: ["eave"],
  ebb: ["gee"],
  ed: ["pa"],
  edge: ["edge"],
  eel: ["lea", "tea", "lee", "tee", "lad", "tad", "led", "jab", "lab", "tab"],
  eerie: ["dryad"],
  egad: ["pose"],
  ego: ["ode", "age", "odd", "add", "ebb"],
  egret: ["ledge"],
  eh: ["ya", "ha", "ma", "ye", "he", "me", "ad"],
  eight: ["labia"],
  either: ["dahlia"],
  elan: ["note"],
  elide: ["agile"],
  elite: ["elite"],
  else: ["beta"],
  em: ["ha", "we", "he"],
  emit: ["lewd"],
  emote: ["aloha"],
  end: ["pod", "god", "pub", "gob"],
  ending: ["soigne"],
  enemy: ["thane"],
  ensue: ["ensue"],
  envy: ["wane", "hand", "wand"],
  eon: ["nee", "one", "nod", "nab"],
  epee: ["bade"],
  epilog: ["betide"], //betide = happen
  era: ["ode", "eye", "odd"],
  ere: ["aye", "eye", "dye", "bye", "add"],
  erg: ["dye", "bye"],
  err: ["dye"],
  esprit: ["lidded"],
  essay: ["these"],
  esteem: ["heated"],
  ester: ["dated"],
  eta: ["eta", "ole", "old"],
  eve: ["baa", "dad", "bad", "dab"],
  ever: ["dead"],
  evil: ["lead"],
  ewe: ["aye", "eye", "dye", "bye"],
  ewer: ["dame", "jamb"],
  exam: ["whoa", "wood", "hood"],
  exit: ["trod"],
  eye: ["aha", "eta", "era", "bra", "ate", "are", "ere", "awe", "ewe"],
  eyed: ["pate", "gate", "pare", "garb"],
  eyelid: ["petard"],
  g: ["d", "g", "s", "b"],
  gab: ["god", "gob"],
  gable: ["bleed"],
  gad: ["pod", "god", "peg", "gob"],
  gadder: ["jagged"],
  gadget: ["legged"],
  gag: [
    "bed",
    "god",
    "sod",
    "bod",
    "beg",
    "dog",
    "bog",
    "deb",
    "gob",
    "sob",
    "bob",
  ],
  gage: ["aged", "abed", "agog", "ages"],
  gain: ["need"],
  gait: ["lied", "trod", "lees"],
  gal: ["led", "leg", "jog", "log", "tog", "job", "lob"],
  galaxy: ["rooted"],
  gale: ["bled", "blob"],
  galena: ["oodles"],
  galley: ["walled"],
  gallop: ["dotted"],
  galosh: ["heated"],
  game: ["awed"],
  gamey: ["rewed"],
  gang: ["good", "dues", "does", "goes", "snob", "boob"],
  gannet: ["tanned"],
  gap: ["dog", "deb"],
  gar: ["jog", "dog", "yes", "deb", "job"],
  garb: ["eyed"],
  garnet: ["landed"],
  garote: ["bladed"], //bladed garote is dark but could be a thing
  gas: ["god", "sod", "gob", "sob"],
  gasbag: ["dogged"],
  gash: ["heed", "meed", "aged", "agog", "ages"],
  gasp: ["deed"],
  gate: ["bled", "blob"],
  gator: ["dated"],
  gay: ["red", "wed", "hod", "rod", "hog", "tog", "web", "hob", "rob"],
  gazer: ["dazed"],
  gear: ["dead", "deed", "does"],
  gee: ["dad", "bad", "bed", "add", "bag", "beg", "abs", "dab", "deb", "ebb"],
  gel: ["lad", "tad", "led", "jag", "lag", "tag", "leg", "jab", "lab", "tab"],
  geld: ["glad", "pled"],
  gelid: ["piled", "piles"],
  gem: ["wad", "had", "wed", "wag", "hag", "was", "has", "web"],
  gene: ["dues", "does", "duds"],
  genial: ["throes"],
  genie: ["broad", "bends"],
  gent: ["toad", "load", "toed"],
  get: ["tad", "lad", "led", "tag", "lag", "leg", "tab", "lab"],
  gibber: ["jagged"],
  gibbet: ["legged"],
  gibe: ["aged", "deed", "berg", "ages"],
  gig: [
    "bed",
    "did",
    "bid",
    "beg",
    "dig",
    "gig",
    "big",
    "dis",
    "sis",
    "deb",
    "bib",
  ],
  gild: ["pled", "glib"],
  gin: ["orb", "nib"],
  gingham: ["homburg"],
  gist: ["lees"],
  give: ["bard", "dais", "barb"],
  giver: ["years"],
  glad: ["geld", "gold"],
  glamor: ["jewels"],
  glassy: ["resold"],
  gleam: ["heels"],
  glee: ["bald", "eats", "bats"],
  glen: ["oats"],
  glib: ["geld", "gild"],
  glob: ["geld", "gold", "eats"],
  gloom: ["heels"],
  gloomy: ["wheels"],
  glossy: ["resold"],
  glow: ["meld", "mold"],
  gnat: [
    "thud",
    "loud",
    "tend",
    "lend",
    "thug",
    "tong",
    "long",
    "thus",
    "lens",
  ],
  gnaw: ["mend", "mood"],
  gnu: ["nod", "nub"],
  go: ["ed", "ad", "as"],
  goad: ["good", "pend", "pond", "goad", "gong", "goes"],
  goal: [
    "toed",
    "lend",
    "tend",
    "lead",
    "load",
    "toad",
    "long",
    "tong",
    "lees",
    "lens",
  ],
  goalie: ["belong"],
  goat: [
    "toed",
    "tend",
    "lend",
    "lead",
    "toad",
    "load",
    "tong",
    "long",
    "lees",
    "lens",
  ],
  goatee: ["belong", "bathos"], //bathos is an effect of anticlimax
  gob: ["god", "end", "gad", "gag", "gas", "gob", "gab"],
  gobbet: ["legged", "legend"],
  gobs: ["seed", "send", "egad"],
  god: ["pod", "god", "pad", "gad", "peg", "gag", "gas", "gob", "gab"],
  goer: ["deed", "dead", "dang", "yang"],
  goes: ["seed", "sand", "send", "gang", "sang", "sans"],
  going: ["bored", "doing", "going"],
  gold: ["pled", "plod", "glad", "glob"],
  gonad: ["pound", "gonad", "penes"],
  gone: [
    "bond",
    "dung",
    "bung",
    "dong",
    "bong",
    "dues",
    "does",
    "buns",
    "boob",
  ],
  gong: [
    "good",
    "bond",
    "goad",
    "dung",
    "sung",
    "bung",
    "dong",
    "gong",
    "song",
    "bong",
    "snag",
    "dues",
    "does",
    "goes",
    "buns",
    "snob",
    "boob",
  ],
  gonna: ["hound"],
  goo: ["nod", "end", "and", "nag", "nab"],
  good: ["good", "pend", "pond", "goad", "gong", "pang", "gang", "goes"],
  goodie: ["depend"],
  goods: ["speed", "spend"],
  gooey: ["teens"],
  goon: ["need", "noes"],
  goop: ["deed", "dead", "dong", "dang", "does"],
  gore: ["eyed"],
  gosh: ["heed", "meed", "aged", "mend", "head", "mead", "agog", "ages"],
  got: [
    "led",
    "tad",
    "lad",
    "leg",
    "tog",
    "log",
    "tag",
    "lag",
    "lob",
    "tab",
    "lab",
  ],
  grain: ["needs"],
  grand: ["goods"],
  great: ["loads"],
  green: ["needs"],
  grey: ["ways"],
  groan: ["needs"],
  grog: ["days"],
  groin: ["needs"],
  groom: ["weeds", "woods", "hands", "heads"],
  guest: ["teens"],
  guide: ["aging"],
  guider: ["depend"],
  guile: ["blend", "blind"],
  guise: ["being", "aging"],
  guitar: ["doting"],
  gunny: ["hound", "round", "wound"],
  gush: ["mend"],
  gusset: ["legend"],
  gussy: ["teens"],
  gust: ["tend", "lend", "lens"],
  gyve: ["bard", "bawd", "eats", "bats", "barb"],
  h: ["y", "h", "a", "m"],
  ha: ["eh", "oh", "ha", "em", "om"],
  had: ["pea", "gem"],
  hag: ["bey", "shy", "soy", "boy", "shh", "sea", "boa", "gem"],
  hah: ["hey", "yea", "aha", "hem", "mom"],
  hail: ["trey", "levy", "troy", "teem"],
  hair: ["diva", "deem"],
  halal: ["totem"],
  hale: ["atom"],
  hallow: ["motley"],
  halo: ["atom"],
  ham: ["hey", "why", "hem"],
  hand: ["pooh", "poem"],
  hang: ["buoy", "doom", "boom"],
  has: ["shy", "soy", "shh", "sea", "gem"],
  hash: ["ashy"],
  hasp: ["deem"],
  hast: ["levy", "teem"],
  hat: ["thy", "toy", "tea", "lea", "tom"],
  hate: ["atom"],
  hath: ["atom"],
  haw: ["yea", "mom"],
  hay: ["hey", "thy", "why", "toy", "tea", "hem", "rem", "tom"],
  he: ["by", "ah", "eh", "am", "em"],
  head: ["poem"],
  headed: ["pagoda"],
  heal: ["they", "team", "loam", "teem", "them"],
  heap: ["deem"],
  hear: ["yeah", "deem"],
  heat: ["they", "team", "loam", "teem", "them"],
  heel: ["lady", "team", "teem"],
  heels: ["gleam", "steam"],
  heir: ["dray", "yeah", "dram", "deem"],
  held: ["play", "plea"],
  hello: ["allay", "alley"],
  helot: ["totem"],
  hem: ["way", "hay", "hey", "hah", "ham", "hem"],
  heme: ["away", "ahem"],
  hen: ["nay"],
  henna: ["honey", "hooey"],
  hep: ["day", "dam"],
  her: ["jay", "day", "yea", "jam", "dam", "yam"],
  herb: ["eddy"],
  herbal: ["logjam"],
  here: ["eddy"],
  hero: ["eddy"],
  hers: ["eddy"],
  hew: ["may", "yea", "yam"],
  hey: [
    "hay",
    "ray",
    "way",
    "hey",
    "hah",
    "rah",
    "tea",
    "ham",
    "tam",
    "ram",
    "hem",
    "rem",
  ],
  hi: ["eh", "em"],
  hid: ["pry", "pea", "gem"],
  hie: ["dry", "bey", "era", "bra", "arm", "aim", "dim"],
  him: ["wry", "hey", "hem", "him"],
  hind: ["gory", "poem"],
  hip: ["dry", "dim"],
  his: ["era", "sea", "gem"],
  hiss: ["eery", "sera", "germ", "seem"],
  hist: ["term", "teem"],
  hit: ["try", "tea", "lea"],
  hither: ["dahlia"],
  ho: ["eh", "oh", "ah", "em", "om", "am"],
  hoagie: ["beseem"],
  hoary: ["hyena"],
  hob: ["gay", "gem"],
  hobby: ["teeny", "weeny"],
  hod: ["pay", "gay", "pea", "gem"],
  hoe: ["bey", "boy", "any", "day", "bay", "bah", "boa", "baa", "dam"],
  hoer: ["deny", "yeah", "deem"],
  hog: [
    "bey",
    "soy",
    "boy",
    "day",
    "gay",
    "say",
    "bay",
    "bah",
    "sea",
    "boa",
    "baa",
    "gem",
    "dam",
  ],
  hogan: ["nosey"],
  hoist: ["teeny"],
  hold: ["ploy", "play", "plea"],
  holder: ["deploy"],
  hole: ["blah", "atom"],
  holey: ["relay", "rajah"],
  hollow: ["motley"],
  home: ["ahoy", "away", "ahem"],
  homey: ["tawny"],
  homo: ["ahoy", "away", "ahem"],
  hon: ["nay", "ooh"],
  hone: ["buoy", "bony", "dona", "doom", "boom"],
  honer: ["jenny"],
  honey: ["wanna", "henna"],
  honor: ["jenny"],
  hood: ["pony", "pooh", "poem"],
  hooey: ["teeny", "weeny", "wanna", "henna"],
  hoop: ["deny", "dona", "deem", "doom"],
  hooray: ["redeem"],
  hoot: ["tony", "teem", "loom", "team", "loam"],
  hop: ["day", "dam"],
  hornet: ["tandem"],
  horny: ["today"],
  hose: ["deny", "deem", "beam"],
  host: ["teem", "team"],
  hostel: ["jetsam"],
  hot: ["toy", "lay", "tea", "lea", "tom", "tam", "lam"],
  hotdog: ["deploy"],
  hots: ["stay", "slay", "stem", "slam"],
  hound: ["gunny", "gonna"],
  how: ["may", "yea", "mom", "yam"],
  hubby: ["teeny", "weeny"],
  hue: ["any"],
  huh: ["any"],
  humor: ["downy"],
  hung: ["bony", "dona"],
  hunt: ["tony", "tuna"],
  hussy: ["teeny", "weeny"],
  hyena: ["hoary"],
  hying: ["sorry", "sorta"],
  I: ["r", "e", "i"],
  i: ["r", "e", "i"],
  iamb: ["ewer"],
  ibis: ["seer"],
  id: ["pi"],
  idea: ["edge"],
  ideal: ["ledge", "lodge"],
  idem: ["wage"],
  ides: ["gape", "gage", "sage", "edge"],
  idiot: ["large"],
  idol: ["lope", "jape", "tape", "loge"],
  ilea: ["vale", "hale", "hate"],
  ill: ["ill"],
  in: ["or", "in"],
  indigo: ["indigo"],
  indoor: ["dengue"],
  ingest: ["league"],
  ingot: ["labor"],
  inhale: ["ethane"],
  inlay: ["rotor"],
  inn: ["our", "nor", "one", "inn", "ion"],
  into: ["aloe", "into"],
  iodine: ["burger"], //gross
  ion: ["nor", "oar", "nee", "one", "inn", "ion"],
  iota: ["iota"],
  ire: ["aye", "eye", "dye", "bye"],
  iris: ["side"],
  iron: ["node"],
  irons: ["suede"],
  irony: ["irony"],
  is: ["is"],
  isle: ["else", "idle"],
  islet: ["tater", "later"],
  ism: ["her", "wee"],
  isomer: ["yawner"],
  issue: ["anger"],
  issuer: ["danger"],
  it: ["ti", "it"],
  item: ["hate", "wale", "hale"],
  ivy: ["tar", "war"],
  j: ["l", "r"],
  jab: ["gel", "eel"],
  jabber: ["dagger"],
  jabot: ["lager"],
  jaded: ["paper", "pager"],
  jag: ["gel", "sol"],
  jagged: ["passel", "gadder", "passer"],
  jaguar: ["yonder"],
  jail: ["jeer", "leer", "tier"],
  jam: ["her"],
  jamb: ["ewer"],
  jaunt: ["tuner", "toner", "loner"],
  jawed: ["payer"],
  jay: ["her", "tor"],
  jean: ["oval", "noel", "near", "over"],
  jeans: ["sneer"],
  jeep: ["deal", "dear", "deer"],
  jeer: ["deal", "dear", "year", "jeer", "deer"],
  jeez: ["zeal"],
  jello: ["altar", "attar", "alter", "otter"],
  jennet: ["tanner"],
  jenny: ["tonal", "tuner", "honer", "toner", "wooer"],
  jersey: ["weeder"],
  jest: ["teal", "tear", "tsar", "leer"],
  jet: ["tar"],
  jetsam: ["hostel"],
  jew: ["mar"],
  jewel: ["tamer", "tanner", "layer"],
  jeweler: ["delayer"],
  jewels: ["slayer"],
  jib: ["gel", "eel", "err"],
  jibe: ["deer", "beer"],
  jig: ["gel", "brr", "sir"],
  jigger: ["dagger", "jabber", "dabber"],
  jihad: ["pearl"],
  jinn: ["noel"],
  jinni: ["inner"],
  jitney: ["ranter", "renter", "hauler"],
  jive: ["earl", "bail"],
  job: ["gel", "eel", "gal", "gar", "ear"],
  jobber: ["dagger"],
  jog: ["gel", "sol", "gal", "gar", "bar"],
  jogger: ["dagger", "jabber", "dabber"],
  jogging: ["snigger", "guesser"],
  join: ["oral", "near"],
  joiner: ["denial", "denier"],
  josh: ["heel", "heal", "meal", "year", "hear", "agar"],
  josher: ["damsel"],
  jot: ["tor", "tar"],
  joust: ["tenor"],
  joy: ["her", "tor", "tar", "war"],
  joyous: ["snorer"],
  l: ["j", "l", "t"],
  lab: ["gel", "eel", "get", "got"],
  labia: ["eight", "ergot"],
  labile: ["alight", "blight"],
  lad: ["gel", "pol", "pet", "get", "pot", "got"],
  lag: ["gel", "sol", "get", "set", "bet", "dot", "got", "sot"],
  lager: ["jabot"],
  laid: ["peel"],
  lair: ["diet"],
  lam: ["wet", "hot"],
  land: ["pool", "poet"],
  lane: ["duel", "duet", "boot"],
  lap: ["dot"],
  lash: ["heel", "meet"],
  lassie: ["diesel"],
  lasso: ["asset"],
  late: ["blot"],
  latte: ["allot"],
  law: ["met", "yet", "mot"],
  lay: ["wet", "hot", "tot", "rot"],
  layer: ["jewel"],
  lea: ["eel", "eat", "vat", "hat", "oat", "vet"],
  lead: ["peal", "goal", "peel", "peat", "phat", "goat", "poet"],
  lean: ["oval", "noel", "neat"],
  leap: ["deal", "debt"],
  lease: ["bevel"],
  least: ["level"],
  led: ["pal", "gal", "gel", "pat", "pet", "get"],
  lee: ["eel", "eat", "bat", "bet"],
  leer: ["deal", "debt"],
  lees: ["seal", "seat"],
  leeway: ["wombat"],
  leg: ["gal", "gel", "sat", "bat", "get", "set", "bet"],
  legal: ["legal"],
  legend: ["gobbet"],
  legged: ["passel", "gadget"],
  legit: ["tidal", "legal", "libel"],
  legroom: ["handset", "headset"],
  lei: ["eel", "rat", "eat"],
  lemon: ["newel"],
  lend: ["goal", "gnat", "goat", "poet"],
  lens: ["goal", "gnat", "goat", "suet"],
  lesion: ["unreal", "unreel"],
  less: ["seal", "seat"],
  lessee: ["basset"],
  lesson: ["unseal", "unseat"],
  lest: ["teal", "teat"],
  let: ["tat", "let"],
  lib: ["gel", "eel", "get"],
  libel: ["legit"],
  lid: ["gel", "pet", "get", "pit"],
  lie: ["eel", "ail", "art", "bet", "bit"],
  lied: ["peel", "pail", "part", "pert", "gait"],
  lieder: ["depart"],
  lien: ["nail", "obit"],
  lieu: ["nail"],
  light: ["label"],
  limbo: ["newel"],
  limy: ["whet", "twit", "whit"],
  line: ["burl", "duel", "boil", "duet"],
  lined: ["panel"],
  lingo: ["abort"],
  lint: ["toil", "tort"],
  lion: ["noel", "nail", "unit"],
  lira: ["edit"],
  lire: ["edit"],
  lisle: ["alert"],
  lists: ["steel", "sleet"],
  lit: ["let", "tit", "lit"],
  lite: ["alit"],
  live: ["earl", "bail", "dart", "bait"],
  livid: ["pearl"],
  lo: ["at"],
  load: [
    "peel",
    "pool",
    "peal",
    "goal",
    "poet",
    "pent",
    "gent",
    "peat",
    "phat",
    "goat",
  ],
  loads: ["spool", "spent"],
  loam: [
    "heel",
    "wool",
    "weal",
    "heal",
    "whet",
    "hoot",
    "went",
    "wont",
    "heat",
    "what",
  ],
  loamy: ["wheel", "wheal", "tweet", "wheat"],
  loan: ["noel", "oval", "neat"],
  lob: ["gel", "eel", "gal", "get", "got", "eat"],
  lobby: ["regal"],
  lobe: ["deal", "beet", "dent", "bent", "beat"],
  lodger: ["despot"],
  log: [
    "gel",
    "sol",
    "gal",
    "get",
    "set",
    "bet",
    "dot",
    "got",
    "sot",
    "sat",
    "bat",
  ],
  loge: ["abet"],
  loggia: ["vessel"],
  logjam: ["herbal"],
  logo: ["abet"],
  loin: ["oral", "neat"],
  loins: ["enrol"],
  lone: ["duel", "dual", "anal", "duet", "boot", "aunt", "bunt", "boat"],
  loner: ["jaunt", "daunt"],
  long: [
    "duel",
    "dual",
    "goal",
    "duet",
    "suet",
    "snot",
    "soot",
    "boot",
    "bunt",
    "gnat",
    "goat",
    "boat",
  ],
  longboat: ["longboat"],
  loom: [
    "heel",
    "wool",
    "weal",
    "heal",
    "hoot",
    "went",
    "wont",
    "want",
    "heat",
  ],
  loon: ["noel", "neat"],
  loony: ["tonal"],
  loop: ["deal", "dent"],
  loose: ["agent"],
  loot: ["tool", "teal", "toot", "loot", "tent", "lent", "teat"],
  lop: ["dot"],
  lose: ["deal", "beet", "dent", "bent", "beat"],
  losing: ["dorsal"],
  loss: ["seal", "gent", "sent", "seat"],
  lost: ["teal", "tent", "lent", "teat"],
  lot: ["let", "tot", "lot", "tat"],
  lots: ["stet", "slot", "stat", "slat"],
  lotto: ["allot"],
  loud: ["gnat"],
  lousy: ["renal", "tenet"],
  low: ["met", "yet", "mot", "mat"],
  lower: ["jennet"],
  lox: ["oat"],
  loyal: ["jewel", "towel", "total"],
  loyalist: ["teetotal"],
  lube: ["dent", "bent"],
  lung: ["bunt"],
  lust: ["tent", "lent"],
  lye: ["awl", "art"],
  m: ["w", "h"],
  ma: ["ow", "eh", "oh"],
  mad: ["pew"],
  mag: ["dew", "sew", "sow", "bow", "shh"],
  maid: ["grew", "prow", "grow"],
  mail: ["trow"],
  male: ["blew", "blow"],
  mallet: ["tallow"],
  mallow: ["mellow", "yellow", "mallow"],
  man: ["new", "now", "ooh"],
  mane: ["anew"],
  map: ["dew"],
  mar: ["jew", "dew", "yew", "yow"],
  mash: ["meow"],
  mat: ["tow", "low"],
  mate: ["blew", "blow"],
  matte: ["allow"],
  matter: ["yellow"],
  maw: ["mew", "yew", "mow", "yow"],
  max: ["ooh"],
  may: ["hew", "how", "tow", "row", "wow"],
  mayday: ["regrew", "regrow"],
  me: ["aw", "ah", "eh"],
  mead: ["phew"],
  meal: ["thaw", "thew"],
  meat: ["thaw", "thew"],
  men: ["new"],
  mend: ["gnaw"],
  meow: ["yeah"],
  mesh: ["yeah"],
  messy: ["resew"],
  met: ["law"],
  mete: ["blew", "blah"],
  mew: ["maw", "yaw", "mew", "yew"],
  mi: ["eh"],
  mid: ["pew"],
  mil: ["jew"],
  mile: ["blew"],
  mine: ["anew"],
  mite: ["blew"],
  moat: ["thew", "thaw"],
  mod: ["pew", "paw"],
  moil: ["trow"],
  mold: ["plow", "glow"],
  mole: ["blew", "blow", "blah"],
  molter: ["yellow"],
  mom: ["hew", "wow", "how", "haw", "hah"],
  money: ["renew"],
  mono: ["anew"],
  moo: ["new", "now", "ooh"],
  mood: ["gnaw", "pooh"],
  moor: ["yeah"],
  mop: ["dew"],
  mosey: ["resew", "resow"],
  mosh: ["meow", "yeah"],
  mossy: ["resew", "resow"],
  mot: ["tow", "low", "law"],
  mote: ["blew", "blow", "blah"],
  motley: ["hallow", "tallow", "wallow"],
  motto: ["allow"],
  moue: ["anew"],
  mousy: ["renew"],
  mow: ["mew", "yew", "mow", "yow", "maw", "yaw"],
  mynah: ["youth", "mouth", "month"],
  n: ["u", "n", "o"],
  nab: ["eon", "goo"],
  nag: ["den", "don", "son", "goo", "boo"],
  nail: ["lieu", "teen", "lien", "lion"],
  naive: ["baron"],
  nap: ["den", "don"],
  narrow: ["madden"],
  nay: [
    "hen",
    "ten",
    "wen",
    "hon",
    "ton",
    "won",
    "tho",
    "rho",
    "who",
    "too",
    "woo",
  ],
  neap: ["dean", "dodo"],
  near: ["jean", "dean", "dodo"],
  neat: ["lean", "than", "loan", "teen", "then"],
  nee: ["ban", "den", "ado"],
  need: ["peen"],
  neigh: ["adieu"],
  neon: ["undo"],
  nest: ["lean", "teen"],
  net: ["tau", "tan", "ten"],
  new: ["man", "men", "yen"],
  newsman: ["newsman"],
  newsroom: ["woodsman", "headsman"],
  next: ["loan"],
  nib: ["gin"],
  nibs: ["seen"],
  night: ["laden"],
  nil: ["ten", "tin"],
  nine: ["burn", "born", "euro"],
  nip: ["den", "din"],
  nisei: ["resin"],
  nit: ["ten", "tin"],
  no: ["nu", "en", "on", "an", "no"],
  nod: ["gnu", "pen", "pan", "goo"],
  noel: ["teen", "jean", "lean"],
  noes: ["seen"],
  nohow: ["yahoo"],
  noisy: ["heron", "reran"],
  none: ["anon", "boon"],
  noon: ["neon", "noon"],
  nor: ["you", "den", "yen", "don", "yon"],
  nose: ["beau", "been", "aeon", "dean", "bean"],
  nosed: ["paean", "pagan"],
  nosey: ["wagon"],
  nosh: ["menu", "aeon", "mean"],
  nosher: ["damson", "demean"],
  nosy: ["teen", "ween", "wean"],
  not: ["tau", "ten", "ton", "tan", "too"],
  note: ["elan"],
  notes: ["eaten", "salon"],
  now: ["you", "men", "yen", "yon", "man", "moo"],
  noway: ["women", "roman", "woman"],
  nu: ["nu", "no"],
  nub: ["gnu"],
  O: ["e", "o", "n", "a"],
  o: ["e", "o", "n", "a"],
  oar: ["doe", "den", "yen", "don", "yon", "yea"],
  oasis: ["sieve", "green"],
  oat: ["tee", "lee", "the", "toe", "tho", "too", "ten", "ton", "tea", "lea"],
  oaten: ["oaten"],
  oath: ["aloe"],
  oats: ["glee", "sloe", "glen"],
  obey: ["rage", "wage", "teen", "ween", "raga"],
  obi: ["ego"],
  obit: ["tree", "teen", "lien"],
  oblong: ["bootee", "goatee"],
  oboe: ["doge", "been"],
  ode: ["ape", "age", "ago", "ego"],
  odor: ["dope", "jape", "doge", "dopa", "yoga"],
  ogle: ["else", "also", "alga"],
  ogre: ["edge"],
  oh: ["ye", "he", "me", "yo", "ho", "an", "ya", "ha", "ma"],
  ohm: ["who", "wan"],
  oho: ["eye", "aye", "oho", "aha"],
  oil: ["lee", "tee", "lie", "tie", "ten", "tin", "lea", "tea"],
  oiled: ["patio"],
  oils: ["glee", "glen"],
  ole: ["ale", "ate", "eta"],
  oleo: ["able"],
  om: ["we", "he", "ho", "ha"],
  on: ["no", "on"],
  one: ["due", "doe", "duo", "boo", "dun", "bun", "eon", "don", "boa"],
  onion: ["union", "onion"],
  onto: ["aloe"],
  ooh: ["hoe", "moo", "yen", "hen", "men", "yon", "hon", "man", "yea"],
  opal: ["lode"],
  or: ["ye", "do", "yo", "ya"],
  oral: ["lode"],
  orb: ["eye"],
  ore: ["aye", "eye", "dye", "bye", "ado"],
  ornate: ["blonde"],
  osier: ["deign"],
  osprey: ["redden"],
  otter: ["jello", "delta"],
  ova: ["van"],
  oval: ["jean", "lean", "than", "loan"],
  over: ["jean", "dean"],
  ovoid: ["groan"],
  ow: ["me", "ye", "yo", "ma", "ya"],
  owe: ["aye", "eye", "dye", "bye"],
  owing: ["duenna"],
  owl: ["lye"],
  ox: ["on"],
  oxen: ["oboe", "neon"],
  oxide: ["apron"],
  oyster: ["delete"],
  ozone: ["booze"],
  p: ["d"],
  pa: ["ed"],
  pad: ["pod", "god"],
  padre: ["edged"],
  pagan: ["nosed"],
  page: ["aged", "abed"],
  pager: ["jaded"],
  paid: ["pied", "prod"],
  pail: ["lied", "trod"],
  pain: ["need"],
  pair: ["deed"],
  pal: ["led"],
  pale: ["bled"],
  paling: ["burled"],
  pallid: ["pitted"],
  pallor: ["dotted"],
  pan: ["nod"],
  pang: ["good"],
  panier: ["darned"],
  pant: ["toed"],
  pants: ["stood"],
  paper: ["jaded"],
  pare: ["eyed"],
  parent: ["loaded"],
  parer: ["jaded"],
  parole: ["bladed"],
  parolee: ["delayed"],
  pass: ["seed"],
  passel: ["jagged", "legged"],
  passer: ["jagged"],
  paste: ["bleed"],
  pat: ["led"],
  pate: ["bled"],
  pathos: ["sealed"],
  patio: ["oiled"],
  patois: ["sealed"],
  paw: ["mod"],
  pay: ["red", "wed", "hod", "rod"],
  payee: ["dated", "bated", "eared"],
  payer: ["dated", "jawed"],
  payola: ["elated"],
  pea: ["had", "odd"],
  peal: ["lead", "load", "toad", "toed"],
  pear: ["dead", "deed"],
  peat: ["lead", "toad", "load", "toed"],
  pee: ["dad", "bad", "bed", "add"],
  peel: ["lead"],
  peen: ["need"],
  peep: ["dead", "deed"],
  peer: ["dead", "deed"],
  peeress: ["seedbed"],
  peewee: ["daybed"],
  peg: ["dad", "gad", "sad", "bad", "bed"],
  pelves: ["sealed"],
  pelvis: ["sealed"],
  pen: ["odd"],
  pend: ["goad"],
  pent: ["toad", "load", "toed"],
  peon: ["need"],
  pep: ["dad"],
  per: ["dad"],
  persona: ["honeyed"],
  peso: ["egad", "need", "aged"],
  pest: ["lead"],
  pet: ["tad", "lad", "led"],
  peter: ["dated"],
  pew: ["mad"],
  peyote: ["elated"],
  phat: ["lead", "toad", "load"],
  phew: ["mead"],
  phi: ["rad"],
  photon: ["unload"],
  pi: ["ed", "id"],
  pie: ["bed", "aid", "did", "bid"],
  pied: ["paid"],
  pier: ["yard", "deed"],
  pig: ["bed", "did", "bid"],
  pilau: ["noted"],
  pile: ["bled"],
  piled: ["gelid"],
  piles: ["gelid"],
  piling: ["burled"],
  pillar: ["dotted"],
  pillow: ["malted", "matted"],
  pint: ["turd", "lord", "toed"],
  piny: ["turd", "word", "hued", "toed"],
  pip: ["did"],
  piper: ["jaded"],
  piping: ["sordid"],
  piss: ["seed"],
  pit: ["led", "lid"],
  pithy: ["hated"],
  piton: ["noted"],
  pitted: ["pallid"],
  pixy: ["word", "toed"],
  plat: ["told"],
  play: ["held", "weld", "hold", "told", "wold"],
  playboy: ["toehold"],
  playroom: ["handhold"],
  plea: ["veld", "held"],
  please: ["beheld"],
  pled: ["geld"],
  plod: ["geld", "gold"],
  plot: ["told"],
  plow: ["meld", "mold"],
  ploy: ["held", "weld", "hold", "told", "wold"],
  pod: ["pod", "god", "pad", "gad"],
  poem: ["weed", "heed", "wand", "hand", "wend", "head"],
  poet: ["land", "tend", "lend", "lead"],
  pogrom: ["wedded"],
  poi: ["red", "rod", "end", "rad"],
  pol: ["led", "lad", "tad"],
  pole: ["bled"],
  polio: ["oiled"],
  pond: ["good", "pond", "goad"],
  pone: ["bond"],
  pony: ["hued", "toed", "hood", "rood", "wood", "toad", "road"],
  pooh: ["heed", "meed", "hood", "mood", "mend", "hand", "head", "mead"],
  pool: ["toed", "lend", "tend", "land", "lead", "load", "toad"],
  poolroom: ["woodland", "headland"],
  poop: ["deed", "dead"],
  poor: ["deed", "dead"],
  pop: ["dad"],
  pore: ["eyed"],
  pose: ["deed", "aged", "bend", "dead", "bead", "egad"],
  posh: ["heed", "meed", "aged", "mend", "head", "mead"],
  posit: ["trend", "tread"],
  post: ["tend", "lend", "lead"],
  posy: ["heed", "reed", "weed", "tend", "rend", "wend", "head", "read"],
  pot: ["led", "tad", "lad"],
  pothole: ["bloated"],
  potion: ["united"],
  pound: ["gonad"],
  pro: ["odd", "add"],
  psi: ["red"],
  pub: ["end"],
  pus: ["end"],
  push: ["mend"],
  puss: ["send"],
  q: ["b"],
  r: ["j", "d", "y"],
  rabbet: ["legged"],
  rabbit: ["legged"],
  rabid: ["greed"],
  rad: ["pod", "god"],
  radar: ["dopey"],
  rag: ["bed", "god", "sod", "bod", "bey", "shy", "soy", "boy"],
  raga: ["obey"],
  ragbag: ["dogged"],
  rage: ["aged", "abed", "ashy"],
  rah: ["hod", "mod", "hey"],
  raid: ["pied", "prod", "prey", "grey"],
  rail: ["lied", "trod", "trey", "levy", "troy"],
  rain: ["need"],
  rajah: ["holey"],
  ram: ["wed", "hod", "hey", "why"],
  ran: ["nod"],
  rang: ["good", "buoy"],
  rani: ["rood", "envy"],
  rant: ["toed"],
  raper: ["jaded"],
  rare: ["eyed"],
  rash: ["heed", "meed", "aged", "ashy"],
  rasp: ["deed"],
  rat: ["led", "thy", "toy"],
  rate: ["bled"],
  rater: ["dated"],
  rating: ["burled"],
  ratio: ["oiled"],
  ration: ["united"],
  rations: ["gnarled"],
  rats: ["sled"],
  raw: ["mod"],
  ray: ["red", "wed", "hod", "rod", "hey", "thy", "why", "toy"],
  rayon: ["noted", "unwed", "nervy"],
  razor: ["dazed"],
  re: ["ad", "ed", "by"],
  read: ["goad"],
  real: ["lead", "load", "toad", "toed", "they"],
  ream: ["head", "weed", "heed", "whey"],
  reap: ["dead", "deed"],
  rear: ["dead", "deed"],
  rebid: ["greed"],
  reboil: ["tinged"],
  red: ["pad", "gad", "pay", "gay"],
  redden: ["napped"],
  redo: ["egad", "aged"],
  reel: ["lead", "lady"],
  reenter: ["deluded"],
  reeve: ["daddy"],
  regal: ["lobed", "today", "toddy", "lobby"],
  regather: ["deathbed"],
  regent: ["loaded"],
  reggae: ["dogged"],
  regress: ["seedbed"],
  regrew: ["mayday"],
  regrow: ["mayday"],
  rehang: ["doomed"],
  rein: ["need"],
  rejoin: ["nearby"],
  relay: ["relay", "holey"],
  release: ["beveled"],
  religion: ["unedited"],
  reline: ["burled"],
  relive: ["barley"],
  rem: ["wad", "had", "wed", "way", "hay", "hey"],
  remap: ["dowdy"],
  rend: ["goad"],
  renew: ["maned"],
  rennet: ["tanned"],
  rent: ["toad", "load", "toed"],
  rep: ["dad", "day"],
  repay: ["today", "toddy"],
  repeal: ["leaded", "loaded"],
  repeat: ["leaded", "loaded"],
  repel: ["jaded"],
  repent: ["loaded"],
  reside: ["agreed"],
  resin: ["needy"],
  resow: ["mosey"],
  rest: ["lead"],
  retie: ["delay", "belay"],
  retold: ["plated"],
  rev: ["add"],
  rewed: ["gamey"],
  rhea: ["head"],
  rhino: ["enemy"],
  rho: ["nay"],
  ribber: ["jagged"],
  rid: ["pry"],
  ridden: ["napped"],
  ride: ["aged"],
  ridge: ["edged"],
  rig: ["bed", "did", "bid", "dry", "bey"],
  rigger: ["jagged"],
  rigor: ["jaded"],
  rile: ["bled"],
  rim: ["wed", "hid", "wry", "hey"],
  rime: ["awed", "awry"],
  rind: ["gory"],
  ring: ["bury", "dory", "gory"],
  riot: ["lord", "lard", "toed", "laid"],
  rip: ["did", "dry"],
  rise: ["deed", "aged", "eery"],
  risotto: ["alleged"],
  rite: ["bled"],
  rival: ["teary"],
  rive: ["bard"],
  rivet: ["teary"],
  road: ["good", "pend", "pond", "goad", "pony"],
  roadie: ["depend"],
  roads: ["speed", "spend"],
  roam: ["weed", "heed", "wood", "hood", "wend", "head", "whey"],
  roan: ["need"],
  roar: ["deed", "dead", "deny"],
  roast: ["teeny"],
  rob: ["god", "end", "gad", "gay"],
  robber: ["jagged"],
  robe: ["aged", "deed", "bend", "egad", "dead", "bead", "deny"],
  robot: ["teeny"],
  rod: ["pod", "god", "pad", "gad", "pay", "gay"],
  rode: ["aged", "egad"],
  rodeo: ["edged"],
  roe: [
    "bed",
    "bod",
    "and",
    "end",
    "dad",
    "bad",
    "bey",
    "boy",
    "any",
    "day",
    "bay",
  ],
  roger: ["jaded"],
  roil: [
    "lied",
    "trod",
    "lend",
    "tend",
    "lead",
    "trey",
    "troy",
    "tiny",
    "tray",
  ],
  role: ["bled"],
  roman: ["noway"],
  rondo: ["agony"],
  rood: ["good", "pend", "pond", "goad", "pony"],
  room: ["weed", "heed", "wood", "hood", "wend", "wand", "hand", "head"],
  roomy: ["tweed"],
  roost: ["teeny"],
  root: ["toed", "tend", "lend", "land", "lead", "toad", "load", "tony"],
  roots: ["steed", "stood", "stand", "eland", "gland", "stead", "stony"],
  roper: ["jaded"],
  rose: ["deed", "aged", "bend", "dead", "bead", "egad", "deny"],
  rosette: ["alleged"],
  rosy: ["heed", "reed", "weed", "tend", "rend", "wend", "head", "read"],
  rot: ["led", "tad", "lad", "toy", "lay"],
  rote: ["bled"],
  rotor: ["dated", "delay"],
  round: ["gonad", "gunny"],
  rove: ["band"],
  row: ["mod", "mad", "may"],
  rowel: ["tanned"],
  rub: ["end"],
  rube: ["bend", "deny"],
  ruble: ["blend"],
  ruby: ["tend", "rend", "wend"],
  rue: ["and", "end", "any"],
  rumor: ["downy"],
  rune: ["bond", "bony"],
  rung: ["bond", "bony"],
  runny: ["hound", "round", "wound", "tunny", "runny"],
  runt: ["tony"],
  ruse: ["bend", "deny"],
  rush: ["mend"],
  russet: ["legend"],
  rust: ["tend", "lend"],
  rustle: ["attend"],
  rye: ["dry"],
  s: ["e", "g", "s"],
  sad: ["pee", "gee", "peg"],
  sadism: ["herpes"],
  sadist: ["teepee"],
  sag: ["gee", "see", "bee", "she", "doe", "beg", "dog", "bog"],
  saga: ["oboe"],
  sage: ["agog", "ages"],
  sago: ["oboe", "agog", "ages"],
  sahib: ["grave"],
  said: ["give", "grog", "pros"],
  sail: ["tree", "jive", "live", "lees"],
  sailor: ["dative"],
  saith: ["alive"],
  sale: ["aloe"],
  sales: ["salve", "sales"],
  salon: ["notes"],
  salsa: ["helve"],
  salve: ["bathe", "baths"],
  sand: ["goes"],
  sane: ["dove", "dues", "does"],
  sang: ["dove", "dues", "does", "goes"],
  sans: ["goes"],
  sap: ["doe", "dog"],
  sari: ["ides"],
  sash: ["agog", "ages"],
  sassy: ["reeve"],
  sat: ["tee", "lee", "the", "toe", "leg", "tog", "log"],
  sate: ["aloe"],
  save: ["eave"],
  saw: ["yes"],
  say: ["tee", "wee", "the", "hoe", "toe", "roe", "woe", "hog", "tog"],
  saying: ["soiree"],
  sea: ["ode", "hag", "veg", "has"],
  seal: ["thee", "lode", "lobe", "lees"],
  sealed: ["pelves"],
  seam: ["whee", "woes"],
  sear: ["does"],
  seaside: ["episode"],
  seat: ["thee", "lode", "lobe", "lees"],
  see: ["bee", "bag", "beg", "abs"],
  seem: ["wade"],
  seen: ["odds"],
  seer: ["jade"],
  seine: ["burbs"],
  senate: ["blonde"],
  send: ["goes", "gobs"],
  sense: ["bends"],
  sent: ["lode", "tube", "lube", "lobe"],
  sera: ["odds"],
  set: ["tee", "lee", "tag", "lag", "leg"],
  sew: ["mag", "yes"],
  sex: ["ode"],
  sexy: ["rode", "robe", "woes"],
  sh: ["ye", "he", "me", "as"],
  shag: ["dome", "some", "shag"],
  shah: ["heme", "home"],
  sham: ["heme", "home"],
  shat: ["tome"],
  shay: ["heme", "home", "tome"],
  she: ["aye", "eye", "dye", "bye", "bag"],
  shed: ["game"],
  shh: ["aye", "hag", "mag", "has"],
  shim: ["heme"],
  shiner: ["denims"],
  shiny: ["worms"],
  ship: ["dime", "drag"],
  shit: ["time", "lime"],
  shiv: ["arms"],
  shoal: ["theme"],
  shoat: ["theme"],
  shod: ["game"],
  shoe: ["dome", "dame", "days"],
  shoo: ["name"],
  shop: ["dome", "dame", "days"],
  shot: ["tome", "tame", "lame"],
  shy: ["rye", "the", "hag", "tag", "rag", "wag", "has", "was"],
  sibyl: ["there"],
  side: ["epee", "ages"],
  sigh: ["ages"],
  sign: ["ogre"],
  signaler: ["jalousie"],
  sin: ["ore", "nee"],
  sine: ["bore", "burg", "dues", "does"],
  sing: ["sure", "gore", "sore", "bore", "burg", "dues", "does", "goes"],
  singe: ["adore"],
  singing: ["soignee"],
  sinus: ["snore"],
  sip: ["die", "dig", "dis"],
  sir: ["die", "jig", "dig", "yes", "dis"],
  sis: ["ere", "gee", "see", "erg", "gig", "sis"],
  sisal: ["there"],
  sit: ["tee", "lee", "tie", "lie", "leg"],
  six: ["ore"],
  slag: ["dole", "sole", "bole", "dote"],
  slam: ["hole", "hots"],
  slap: ["dole", "dote"],
  slash: ["heels"],
  slat: ["tole", "tote", "lots"],
  slaw: ["mole", "mete", "mote"],
  slay: ["hole", "tole", "role", "tote", "rote", "hots"],
  slayer: ["jewels"],
  sled: ["pale", "gale", "pate", "gate"],
  sleet: ["ladle", "table"],
  sleeve: ["dabble", "babble"],
  slew: ["male", "mate", "mete"],
  slid: ["pile"],
  slide: ["agile"],
  slier: ["darts"],
  slight: ["labile"],
  slim: ["wile", "wits"],
  slimy: ["while", "white"],
  sling: ["guile", "suite"],
  slit: ["tile", "lite"],
  slob: ["gale", "gate", "eats"],
  sloe: [
    "dole",
    "bole",
    "dale",
    "bale",
    "dote",
    "ante",
    "date",
    "bate",
    "eats",
    "bats",
  ],
  slog: [
    "dole",
    "sole",
    "bole",
    "dale",
    "gale",
    "sale",
    "bale",
    "dote",
    "date",
    "gate",
    "sate",
    "bate",
    "bats",
  ],
  slogan: ["negate"],
  slop: ["dole", "dale", "dote", "date"],
  slosh: ["agate", "heels"],
  slot: ["tole", "tale", "tote", "late", "lots"],
  slow: ["mole", "male", "mete", "mote", "mate"],
  slue: ["ante"],
  smote: ["blahs"],
  snag: [
    "gene",
    "done",
    "gone",
    "bone",
    "shoe",
    "dong",
    "gong",
    "song",
    "bong",
  ],
  snail: ["teens"],
  snap: ["done", "dong"],
  sneer: ["debug", "jeans"],
  snide: ["aging"],
  snip: ["dine", "drug", "ding"],
  snipe: ["adios"],
  snit: ["true", "tine", "line", "ting", "lens"],
  snob: ["gene", "gone", "gong", "gang"],
  snood: ["genus"],
  snoot: ["teens"],
  snot: ["tone", "lone", "lane", "tong", "long", "tang", "lens"],
  snow: ["moue", "mane", "yang"],
  snug: ["snug"],
  so: ["as"],
  soap: ["done", "dong", "does"],
  soar: ["done", "dong", "does"],
  sob: ["gee", "gag", "gas"],
  sober: ["degas"],
  sod: ["pee", "gee", "peg", "gag", "gas"],
  soda: ["epee"],
  soigne: ["engine", "ending", "busing"],
  soil: ["tree", "line", "tine", "ting", "lees", "lens"],
  sol: ["lee", "tee", "toe", "leg", "jog", "log", "tog", "jag", "lag", "tag"],
  sold: ["glee"],
  sole: ["aloe", "alas"],
  solid: ["piles"],
  solids: ["epilog"],
  solo: ["aloe", "alas"],
  son: ["nee", "one", "nag"],
  sonar: ["young"],
  song: [
    "dune",
    "done",
    "gone",
    "bone",
    "dung",
    "sung",
    "bung",
    "dong",
    "gong",
    "song",
    "bong",
    "snag",
    "dues",
    "does",
    "goes",
    "buns",
  ],
  soon: ["none", "noes"],
  soot: ["tone", "lone", "lane", "tong", "long", "tang", "lees", "lens"],
  sooth: ["atone", "alone", "along"],
  sop: ["doe", "dog"],
  sot: ["tee", "lee", "toe", "leg", "tog", "log", "tag", "lag"],
  sow: ["mag", "yes"],
  sox: ["one"],
  soy: [
    "tee",
    "wee",
    "hoe",
    "toe",
    "roe",
    "woe",
    "hog",
    "tog",
    "hag",
    "tag",
    "rag",
    "wag",
    "has",
    "was",
  ],
  spa: ["ode"],
  span: ["node"],
  spasm: ["weeds"],
  spat: ["lode"],
  spay: ["rode"],
  spent: ["loads"],
  spew: ["made"],
  spiny: ["horde", "words"],
  spit: ["tide"],
  spite: ["elide"],
  split: ["tilde"],
  spoil: ["trade"],
  spoils: ["strode"],
  spool: ["loads"],
  spoon: ["needs"],
  spot: ["lode", "lade"],
  ssh: ["age", "yes", "ass"],
  stag: ["dote", "dole", "sole", "bole"], //bole is trunk of tree
  star: ["dote", "dole"],
  stash: ["heels"],
  stat: ["tote", "tole", "lots"],
  stats: ["stole"],
  stay: ["tote", "rote", "hole", "tole", "role", "hots"],
  steam: ["whale", "heels"],
  steamy: ["wheels"],
  steed: ["gable"],
  steel: ["ladle", "table"],
  stein: ["orate"],
  stem: ["hate", "wale", "hale"],
  steno: ["noble"],
  step: ["date", "dale"],
  sterna: ["huddle"],
  steroid: ["predate", "gradate"],
  stet: ["late", "tale"],
  stew: ["mate", "mete", "male"],
  stile: ["elite"],
  sting: ["suite", "guile"],
  stint: ["torte"],
  stoat: ["thole"],
  stogie: ["debate"],
  stole: ["elate"],
  stolen: ["oblate"], //spheroid flattened at the poles
  stolon: ["notate"],
  stony: ["roots"],
  stood: ["pants"],
  stop: ["dote", "date", "dole", "dale"],
  stow: ["mete", "mote", "mate", "mole", "male"],
  strain: ["needle"],
  strand: ["poodle"],
  strobe: ["beadle"],
  strong: ["doodle", "boodle", "bundle"], //boodle is money spent illegally
  strove: ["dandle"],
  strung: ["bundle"],
  stye: ["arts"],
  suet: ["lane", "tang", "lens"],
  suit: ["tine", "line", "ting", "lens"],
  suiting: ["suiting", "boiling"],
  suitor: ["doting"],
  sun: ["one"],
  sundae: ["begone"],
  sung: [
    "dune",
    "done",
    "gone",
    "bone",
    "dung",
    "sung",
    "bung",
    "dong",
    "gong",
    "song",
    "bong",
    "buns",
  ],
  swag: ["dome", "some"],
  swam: ["heme", "home"],
  swap: ["dome"],
  swat: ["tome"],
  sway: ["heme", "home", "tome"],
  sweat: ["theme"],
  swig: ["dime"],
  swim: ["heme"],
  swop: ["dome", "dame", "days"],
  synod: ["genre", "pants"],
  system: ["waters"],
  t: ["t", "l"],
  tab: ["get", "got", "gel", "eel"],
  tabloid: ["genteel"],
  taboo: ["angel"],
  tad: ["pet", "get", "pot", "got", "gel", "pol"],
  tag: ["get", "set", "bet", "dot", "got", "sot", "gel", "sol"],
  taiga: ["egret"],
  tail: ["trot"],
  tailed: ["petrel", "patrol"],
  tails: ["sleet", "steel"],
  tale: ["blot"],
  tallow: ["mallet"],
  tam: ["wet", "hot"],
  tamer: ["jewel"],
  tan: ["net", "not"],
  tang: ["duet", "suet", "snot", "soot", "boot", "duel"],
  tanned: ["gannet"],
  tanner: ["jennet"],
  tansy: ["tenet"],
  tap: ["dot"],
  tar: ["jet", "yet", "jot", "dot"],
  tassel: ["tassel"],
  tat: ["let", "tot", "lot"],
  tau: ["net", "not"],
  tawny: ["tunnel", "runnel"],
  taxi: ["root"],
  tea: ["eat", "vat", "hat", "oat", "vet", "eel"],
  teal: ["teat", "that", "teal"],
  team: ["heat", "what", "whet", "weal", "heal", "heel"],
  tear: ["debt", "deal"],
  tease: ["bevel"],
  teat: ["teat", "that", "teal"],
  tee: ["eat", "bat", "bet", "eel"],
  teem: ["heat", "weal", "heal", "heel"],
  teen: ["neat"],
  teeny: ["tubal"],
  ten: ["oat", "net"],
  tend: ["gnat", "goat", "poet", "goal"],
  tenet: ["tenet"],
  tenor: ["doubt"],
  tepid: ["pedal"],
  test: ["teat", "teal"],
  than: ["neat", "oval"],
  that: ["teat", "that", "teal"],
  thaw: ["meat", "moat", "meal"],
  the: ["eat", "bat"],
  thee: ["beat", "deal"],
  theism: ["herbal"],
  them: ["heat", "weal", "heal"],
  then: ["neat"],
  thew: ["meat", "meal"],
  they: ["heat", "teat", "heal", "teal", "real", "weal"],
  thin: ["neat", "oral"],
  thine: ["aural"],
  this: ["seat", "seal"],
  tho: ["eat", "oat"],
  thole: ["bleat", "bloat"],
  thou: ["neat"],
  threw: ["medal"],
  throes: ["sandal"],
  throw: ["medal", "modal"],
  thud: ["gnat"],
  thug: ["gnat"],
  thus: ["gnat"],
  thy: ["hat", "tat", "rat"],
  ti: ["it"],
  tibia: ["vigil"],
  tidal: ["legit"],
  tie: ["art", "bet", "bit", "eel", "ail"],
  tier: ["dart", "jail"],
  tiger: ["debit"],
  tight: ["label"],
  tile: ["alit"],
  timer: ["jewel"],
  timid: ["pewit"],
  tin: ["net", "nit", "nil", "oil"],
  tinder: ["deport"],
  tine: ["duet", "burl", "duel", "boil"],
  ting: [
    "sort",
    "duet",
    "suet",
    "suit",
    "snit",
    "burl",
    "duel",
    "soil",
    "boil",
  ],
  tinge: ["abort"],
  tint: ["tort", "toil"],
  tiny: ["hurt", "tort", "wort", "hurl", "toil", "roil"],
  tire: ["edit"],
  tit: ["let", "tit", "lit"],
  titled: ["pallet", "pellet"],
  to: ["at"],
  toad: [
    "poet",
    "pent",
    "gent",
    "peat",
    "phat",
    "goat",
    "peel",
    "pool",
    "peal",
    "goal",
  ],
  toast: ["level"],
  today: ["repel", "regal"],
  toe: ["bet", "dot", "ant", "eat", "bat", "eel"],
  toed: ["pant", "pent", "gent", "peat", "peel", "peal"],
  tog: [
    "get",
    "set",
    "bet",
    "dot",
    "got",
    "sot",
    "sat",
    "bat",
    "gel",
    "sol",
    "gal",
  ],
  toil: ["trot", "lent", "tent", "lint", "tint", "teat", "teal"],
  toilet: ["talent", "latent"],
  told: ["plot", "plat"],
  tole: ["blot"],
  tom: ["wet", "hot", "hat"],
  tomtit: ["lethal"],
  ton: ["net", "not", "oat"],
  tonal: ["tenet", "tonal"],
  tone: ["duet", "boot", "aunt", "bunt", "boat", "duel", "dual", "anal"],
  toner: ["jaunt", "daunt"],
  tong: [
    "duet",
    "suet",
    "snot",
    "soot",
    "boot",
    "bunt",
    "gnat",
    "goat",
    "boat",
    "duel",
    "dual",
    "goal",
  ],
  tony: ["hoot", "toot", "root", "hunt", "runt", "wont", "tool", "wool"],
  too: ["net", "not", "ant", "eat", "oat", "eel"],
  tool: ["loot", "toot", "lent", "tent", "teat", "tool", "teal"],
  toot: ["toot", "loot", "tent", "lent", "teat", "tool", "teal"],
  toothy: ["talent"],
  top: ["dot"],
  tor: ["jet", "yet", "jot", "dot"],
  torah: ["yodel", "model", "medal", "modal"],
  toss: ["gent", "sent", "seat", "seal"],
  tot: ["let", "tot", "lot", "tat"],
  total: ["total"],
  tote: ["blot"],
  totem: ["helot", "halal"],
  toughie: ["dragnet"],
  tow: ["met", "yet", "mot", "mat"],
  towel: ["jennet"],
  tower: ["jennet"],
  toy: ["wet", "hot", "tot", "rot", "hat", "tat", "rat"],
  tribe: ["beryl"],
  tsar: ["jest", "dost"],
  tsetse: ["detest"],
  tuba: ["vent"],
  tube: ["dent", "bent"],
  tuna: ["hunt"],
  tune: ["aunt", "bunt"],
  tuner: ["jaunt", "daunt"],
  u: ["n"],
  uh: ["an"],
  union: ["union", "onion"],
  unit: ["lion"],
  united: ["patron"],
  unload: ["photon"],
  unwed: ["pennon"],
  us: ["en"],
  usable: ["eleven"],
  usage: ["ashen"],
  use: ["den"],
  used: ["peen"],
  v: ["a"],
  vain: ["urea"],
  van: ["ova"],
  vat: ["tea", "lea"],
  veg: ["baa", "sea"],
  vein: ["urea"],
  veld: ["plea"],
  vent: ["tuba"],
  vet: ["tea", "lea"],
  via: ["era", "via"],
  vie: ["era", "bra"],
  vigil: ["tibia"],
  vine: ["aura"],
  vino: ["aura"],
  vital: ["tetra"],
  vow: ["yea"],
  vying: ["sorta"],
  w: ["m", "y"],
  wad: ["gem"],
  wag: ["gem", "bey", "shy", "soy", "boy"],
  wage: ["ashy"],
  wagon: ["nosey"],
  wail: ["teem", "trey", "levy", "troy"],
  wait: ["teem", "trey", "levy", "troy"],
  wale: ["atom"],
  walled: ["galley"],
  wallow: ["motley"],
  wan: ["ohm"],
  wand: ["poem"],
  wane: ["doom", "boom", "envy", "buoy"],
  wanna: ["honey", "hooey"],
  want: ["loom"],
  war: ["joy"],
  was: ["gem", "shy", "soy"],
  wash: ["ashy"],
  washy: ["washy"],
  wasp: ["deem"],
  wast: ["teem", "levy"],
  wavy: ["wavy"],
  wax: ["ohm"],
  waxy: ["room"],
  way: ["hem", "rem", "tom", "hey", "thy", "why", "toy"],
  ways: ["stem", "grey"],
  we: ["am", "em", "by"],
  weal: ["team", "loam", "teem", "them", "they"],
  wear: ["deem"],
  web: ["gem", "gay"],
  wed: ["gem", "pay", "gay"],
  wee: ["dam", "day", "bay", "bey"],
  ween: ["obey"],
  weeny: ["today", "toady", "ruddy", "toddy", "hubby", "tubby", "hobby"],
  weep: ["deem"],
  weigh: ["abeam"],
  weir: ["dram", "deem", "dray"],
  weld: ["play"],
  wen: ["nay"],
  wend: ["poem"],
  went: ["loam"],
  were: ["eddy"],
  west: ["team", "teem"],
  wet: ["tam", "lam", "lay"],
  wham: ["wham"],
  what: ["team", "loam"],
  wheal: ["today", "loamy"],
  wheat: ["today", "loamy"],
  whee: ["beam"],
  wheels: ["steamy"],
  whet: ["team"],
  whey: ["team", "ream"],
  whine: ["enemy"],
  whinny: ["hooray"],
  whiny: ["wormy"],
  whip: ["dram", "dray"],
  whir: ["dram", "dray"],
  whit: ["tram", "team", "tray", "limy"],
  who: ["ohm", "nay"],
  why: ["ham", "tam", "ram", "thy", "why", "hay", "ray", "way"],
  widow: ["mopey"],
  wienie: ["binary"],
  wig: ["gem", "dim", "dry", "bey"],
  wile: ["djinn"],
  willow: ["motley"],
  wind: ["poem", "gory"],
  wine: ["dorm", "bury", "dory"],
  wing: ["dorm", "bury", "dory", "gory"],
  wino: ["norm"],
  winy: ["worm"],
  wire: ["djinn"],
  wise: ["berm", "deem", "eery"],
  wisp: ["deem"],
  wist: ["term", "teem"],
  wit: ["try"],
  wits: ["stem", "slim"],
  witted: ["paltry", "galley"],
  woe: ["dam", "bey", "boy", "any", "day", "bay"],
  woes: ["seem", "seam"],
  wold: ["ploy", "play"],
  woman: ["noway"],
  wombat: ["leeway"],
  won: ["nay"],
  wont: ["loom", "loam", "tony"],
  woo: ["any", "nay"],
  wood: ["poem", "pony"],
  wooer: ["jenny"],
  wool: ["teem", "loom", "team", "loam", "tony"],
  wound: ["gunny"],
  wow: ["mom", "yam", "may"],
  writ: ["tidy"],
  wrong: ["goody"],
  wussy: ["teeny", "weeny"],
  x: ["x", "o"],
  xi: ["ex"],
  y: ["h", "t", "r", "w"],
  ya: ["eh", "oh", "or", "ow"],
  yahoo: ["nohow"],
  yam: ["wet", "hot", "her", "hew", "wow", "how"],
  yang: [
    "duet",
    "suet",
    "snot",
    "soot",
    "boot",
    "doer",
    "goer",
    "door",
    "boor",
    "snow",
  ],
  yap: ["dot", "dew"],
  yarn: ["odor"],
  yarrow: ["madder"],
  yaw: ["met", "yet", "mot", "mew", "yew", "mow", "yow"],
  ye: ["ah", "eh", "at", "aw"],
  yea: [
    "hah",
    "eat",
    "vat",
    "hat",
    "oat",
    "vet",
    "ear",
    "oar",
    "her",
    "haw",
    "hew",
  ],
  yeah: [
    "yeah",
    "heat",
    "meat",
    "moat",
    "meet",
    "year",
    "hear",
    "aver",
    "hoer",
  ],
  year: ["yeah", "debt", "dear", "year", "jeer", "deer", "doer"],
  yeast: ["lever"],
  yellow: ["mallet", "molter", "matter"],
  yen: ["oat", "net", "oar", "new"],
  yep: ["dew"],
  yes: ["eat", "sat", "get", "set", "ear", "gar", "saw", "sew"],
  yet: ["tat", "let", "tar", "law"],
  yew: ["mat", "met", "yet", "mar", "maw", "yaw", "mew", "yew"],
  yield: ["plait"],
  yin: ["net", "nit", "new"],
  yip: ["dew"],
  yipe: ["edit"],
  yo: ["eh", "oh", "ah", "at", "or", "ow", "aw"],
  yodel: ["taper", "leper", "lager"],
  yoga: ["odor"],
  yon: ["ooh", "net", "not", "oat", "nor", "oar", "new", "now"],
  yonder: ["jaguar"],
  yore: ["dyer", "ajar"],
  you: ["net", "not", "nor", "new", "now"],
  young: ["goner", "boner", "donor", "sonar"],
  yow: [
    "met",
    "yet",
    "mot",
    "mat",
    "mar",
    "mew",
    "yew",
    "mow",
    "yow",
    "maw",
    "yaw",
  ],
  z: ["z"],
  zeal: ["jeez"],
  "": [""],
};

export default data;
