const data = {
  a: ["e", "v", "h"],
  abed: ["page", "gage"],
  abide: ["agree"],
  abs: ["gee", "see"],
  abyss: ["serge"],
  adenoid: ["peonage"],
  adieu: ["neigh"],
  adios: ["snipe", "serge", "gorge"],
  ah: ["ye", "he", "ah"],
  aha: ["eye", "hah"],
  aid: ["pee", "gee", "pie"],
  aide: ["epee"],
  ail: ["lee", "tee", "lie", "tie"],
  aim: ["wee"],
  air: ["die"],
  alder: ["depth"],
  ale: ["ale", "ate"],
  alit: ["tile", "lite"],
  aloe: ["ante"],
  also: ["ogle"],
  am: ["we"],
  an: ["uh", "oh"],
  anew: ["mane"],
  aniline: ["aniline"],
  anon: ["none"],
  ant: ["toe"], //ant bites toe
  ante: ["aloe"],
  any: ["hue", "rue", "hoe", "toe", "roe", "huh"],
  aphid: ["grade"],
  apish: ["aside"],
  are: ["aye", "eye"],
  aria: ["hide"],
  arise: ["aside"],
  array: ["redye"],
  art: ["lye"],
  arts: ["stye"],
  as: ["eh", "sh"],
  ash: ["age", "ash"],
  ashy: ["thee", "rage", "hash", "rash"],
  aside: ["agree", "apish"],
  ass: ["gee", "see", "ssh"],
  assay: ["these"],
  ate: ["ate", "ale"],
  atop: ["dote", "dole", "doth"],
  aunt: ["tune", "tone", "lone"],
  aw: ["me"],
  away: ["heme"],
  awed: ["game"],
  ax: ["oh"],
  axe: ["axe"],
  axial: ["throe"],
  axle: ["aloe"],
  aye: ["ate", "are", "ere"],
  b: ["q", "g", "e"],
  baa: ["veg", "eve"],
  bad: ["peg", "pee", "gee"],
  bade: ["epee"],
  bail: ["tree", "jive", "live"],
  bait: ["tree", "live"],
  bald: ["glee"],
  baler: ["delve"],
  balsa: ["helve"],
  ban: ["nee"],
  barb: ["gyve"],
  bard: ["gyve"],
  basis: ["sieve"],
  basset: ["lessee"],
  bat: ["leg", "tee", "lee", "the"],
  bathos: ["goatee"],
  baths: ["salve"],
  bats: ["glee"],
  bay: ["tee", "the"],
  bayou: ["nerve"],
  beam: ["whee"],
  beast: ["levee"],
  beat: ["thee"],
  bed: ["gag", "peg", "pee", "gee"],
  below: ["melee"],
  bet: ["tag", "lag", "leg", "tee", "lee"],
  bey: ["hag", "tag", "rag", "tee"],
  bi: ["re"],
  bias: ["sere"],
  bib: ["erg", "gig", "ere", "gee"],
  bid: ["peg", "pig", "gig", "pee", "gee", "pie"],
  bide: ["epee"],
  bidet: ["tepee"],
  bier: ["dare"],
  bin: ["ore", "nee"],
  bind: ["pure", "pore", "gore"],
  bio: ["erg", "ere", "ore", "nee"],
  biped: ["padre"],
  bird: ["pyre"],
  bit: ["leg", "tee", "lee", "tie", "lie"],
  bled: ["pale", "gale", "pate", "gate"],
  blew: ["male", "mate", "mete"],
  blind: ["guile"],
  bloat: ["thole"],
  blot: ["tole", "tote"],
  blow: ["mole", "mete", "mote"],
  blower: ["demote"],
  blowsy: ["remote"],
  blue: ["ante"],
  bluster: ["detente"],
  boa: ["veg", "hog", "hoe"],
  boast: ["levee"],
  boat: ["thee"],
  bob: ["gee"],
  bod: ["peg", "pee", "gee"],
  bode: ["agog", "epee"],
  boil: ["ting", "tree", "line", "tine"],
  bold: ["glee"],
  bole: ["aloe"],
  bombed: ["peewee"],
  bond: ["gong", "pone", "gone"],
  bony: ["hung", "rung", "tong", "tune", "rune", "hone", "tone"],
  boo: ["nee", "one"],
  boob: ["gong", "gene", "gone"],
  boon: ["none"],
  boor: ["dong", "done"],
  boot: ["tong", "long", "tone", "lone"],
  booth: ["along", "atone", "alone"],
  bop: ["dog", "doe"],
  bored: ["payee"],
  bosh: ["agog"],
  boss: ["gene"],
  both: ["aloe"],
  box: ["one"],
  boxy: ["tong", "hone", "tone"],
  boy: ["hog", "tog", "tee", "hoe", "toe", "roe"],
  bra: ["eye"],
  brew: ["made"],
  brie: ["aide"],
  brim: ["wide"],
  briny: ["horde"],
  bro: ["ode", "eye"],
  broad: ["geode"],
  brood: ["geode"],
  brow: ["mode"],
  brr: ["dye"],
  bun: ["one"],
  buns: ["sung", "gong", "song", "gone"],
  bunt: ["lung", "tong", "long", "tune", "tone", "lone"],
  buoy: ["tong", "hone", "tone"],
  buss: ["gene"],
  by: ["he", "re"],
  bye: ["erg", "ate", "are", "ere"],
  d: ["p", "g"],
  dad: ["pep", "peg"],
  dais: ["seep"],
  day: ["hep", "rep"],
  days: ["step"],
  dead: ["peep"],
  deal: ["leap", "jeep"],
  dean: ["neap"],
  dear: ["jeep", "deep"],
  deb: ["gap", "gag"],
  debt: ["leap"],
  deed: ["peep"],
  deem: ["weep"],
  deep: ["deep"],
  deer: ["jeep", "deep"],
  den: ["nap", "nag"],
  dew: ["map", "mag"],
  dial: ["jeep"],
  dibs: ["seep"],
  did: ["pep", "pip", "peg", "pig", "gig"],
  die: ["erg"],
  diet: ["tarp"],
  dim: ["wig"],
  din: ["nip"],
  dip: ["dip", "dig"],
  dis: ["sip", "erg", "gig"],
  doer: ["jeep", "deep", "dang", "yang"],
  does: ["seep", "gang", "sang"],
  dole: ["atop"],
  dollop: ["dollop"],
  dona: ["hoop", "hung"],
  donor: ["young"],
  doom: ["weep"],
  door: ["jeep", "deep", "dong"],
  dose: ["agog"],
  dot: ["top", "lop", "leg", "tog", "log"],
  dote: ["atop"],
  doth: ["atop"],
  dotted: ["gallop"],
  duel: ["tang"],
  dues: ["gang", "sang"],
  duet: ["tang"],
  dye: ["erg"],
  e: ["a", "e"],
  ear: ["yea"],
  eared: ["payee"],
  eat: ["tea", "lea", "tee", "lee", "the"],
  eater: ["delve"],
  eats: ["glee"],
  ebb: ["gee"],
  ed: ["pa"],
  eel: ["lea", "tea", "lee", "tee"],
  eh: ["ya", "ha", "ye", "he"],
  either: ["dahlia"],
  elide: ["agile"],
  elite: ["elite"],
  em: ["we"],
  ensue: ["ensue"],
  eon: ["nee", "one"],
  era: ["eye"],
  ere: ["aye", "eye"],
  err: ["dye"],
  essay: ["these"],
  eta: ["eta"],
  ewer: ["dame"],
  exam: ["whoa"],
  eye: ["aha", "eta", "era", "ate", "are", "ere"],
  eyed: ["pate", "gate", "pare"],
  h: ["y", "h", "a"],
  ha: ["eh", "ha"],
  had: ["pea"],
  hah: ["hey", "yea", "aha"],
  hail: ["trey", "levy"],
  hair: ["diva"],
  hallow: ["motley"],
  ham: ["why"],
  has: ["shy", "shh", "sea"],
  hash: ["ashy"],
  hast: ["levy"],
  hat: ["thy", "tea", "lea"],
  hay: ["hey", "thy", "tea"],
  he: ["ah", "eh"],
  heal: ["they"],
  hear: ["yeah"],
  heat: ["they"],
  heir: ["dray", "yeah"],
  held: ["play", "plea"],
  hem: ["way"],
  heme: ["away"],
  hen: ["nay"],
  henna: ["honey", "hooey"],
  hep: ["day"],
  her: ["jay", "day", "yea"],
  hew: ["may"],
  hey: ["hay", "ray", "hey", "hah", "rah", "tea"],
  hi: ["eh"],
  hid: ["pry", "pea"],
  hie: ["era"],
  him: ["wry"],
  hind: ["gory"],
  hip: ["dry"],
  his: ["era", "sea"],
  hiss: ["eery", "sera"],
  hit: ["try", "tea", "lea"],
  hither: ["dahlia"],
  ho: ["eh", "oh"],
  hoary: ["hyena"],
  hobby: ["teeny"],
  hod: ["pea"],
  hoe: ["any"],
  hoer: ["deny"],
  hoist: ["teeny"],
  hold: ["ploy", "plea"],
  holder: ["deploy"],
  hollow: ["motley"],
  homey: ["tawny"],
  hon: ["ooh"],
  honer: ["jenny"],
  honey: ["henna"],
  honor: ["jenny"],
  hood: ["pony", "pooh"],
  hooey: ["teeny", "henna"],
  hoop: ["deny", "dona"],
  hoot: ["tony"],
  hot: ["toy", "tea", "lea"],
  hound: ["gunny", "gonna"],
  hubby: ["teeny"],
  hue: ["any"],
  huh: ["any"],
  humor: ["downy"],
  hunt: ["tony", "tuna"],
  hussy: ["teeny"],
  hyena: ["hoary"],
  I: ["r", "e", "i"],
  i: ["r", "e", "i"],
  iamb: ["ewer", "ewe"],
  ibis: ["seer", "erg", "gig", "ere", "gee", "see"],
  id: ["pi", "p", "g"],
  idea: ["hap", "hep", "hag", "veg"],
  ideal: ["leap", "jeep"],
  idem: ["wage", "wag"],
  ides: ["gape", "gage", "sage", "gap", "sap", "gag", "sag"],
  idiom: ["weep"],
  idle: ["alp"],
  idler: ["yelp"],
  idol: ["lope", "loge", "lop", "top", "leg", "jog", "log", "tog"],
  ilea: ["vale", "hale", "hate", "eel", "eat", "vat", "hat", "vet"],
  imbue: ["anew"],
  in: ["or", "u", "n", "o"],
  indite: ["align"],
  indoor: ["dengue"],
  inhale: ["ethane"],
  inn: ["our", "nor", "one", "nu", "on", "no"],
  inset: ["teen"],
  inter: ["jato"],
  ion: ["nor", "nee", "one", "no", "on"],
  ire: ["aye", "eye", "ad", "ed"],
  iris: ["side"],
  iron: ["node", "nod"],
  irons: ["suede", "good"],
  irony: ["hued", "toed", "hood", "rood", "tony"], //TODO irony is not here so I still need to udpate that function
  is: ["e", "g", "s"],
  isle: ["else", "ale", "ate"],
  islet: ["tater", "later", "tale", "late"],
  ism: ["wee", "we"],
  isomer: ["yawner"],
  issue: ["anger"],
  issuer: ["danger", "dense"],
  it: ["ti", "t", "l"],
  item: ["wale", "wet"],
  j: ["l", "r"],
  jab: ["gel", "eel"],
  jabber: ["dagger"],
  jaded: ["paper", "pager"],
  jail: ["jeer", "leer", "tier"],
  jamb: ["ewer"],
  jaunt: ["tuner", "toner", "loner"],
  jay: ["her"],
  jean: ["oval", "near", "over"],
  jeans: ["sneer"],
  jeep: ["deal", "dear", "deer"],
  jeer: ["deal", "dear", "year", "jeer", "deer"],
  jeez: ["zeal"],
  jello: ["otter"],
  jennet: ["tanner"],
  jenny: ["tonal", "tuner", "honer", "toner"],
  jest: ["teal", "tear", "tsar", "leer"],
  jet: ["tar"],
  jew: ["mar"],
  jewel: ["tamer", "tanner"],
  jib: ["gel", "eel", "err"],
  jihad: ["pearl"],
  jinn: ["noel"],
  jinni: ["inner"],
  jitney: ["ranter", "renter", "hauler"],
  job: ["gel", "eel"],
  jobber: ["dagger"],
  joiner: ["denier"],
  josh: ["heel"],
  jot: ["tor"],
  joust: ["tenor"],
  joy: ["her", "tor"],
  joyous: ["snorer"],
  l: ["j", "l", "t"],
  lab: ["gel", "eel", "get"],
  labia: ["eight"],
  labile: ["alight"],
  lad: ["gel", "pet", "get"],
  laid: ["peel"],
  lair: ["diet"],
  lam: ["wet"],
  land: ["poet"],
  lash: ["heel"],
  law: ["met"],
  lea: ["eel", "eat", "vat", "hat", "vet"],
  lead: ["peal", "peel", "peat", "phat"],
  lean: ["oval", "neat"],
  leap: ["deal"],
  least: ["level"],
  led: ["pal", "gal", "gel", "pat", "pet", "get"],
  lee: ["eel", "eat"],
  leer: ["deal"],
  lees: ["seal", "seat"],
  lei: ["eel", "rat", "eat"],
  lemon: ["newel"],
  lend: ["goal", "gnat", "goat", "poet"],
  lens: ["goal", "gnat", "goat", "suet"],
  lesion: ["unreal", "unreel"],
  less: ["seal", "seat"],
  lesson: ["unseal", "unseat"],
  lest: ["teal", "teat"],
  let: ["tat", "let"],
  lib: ["gel", "eel", "get"],
  libel: ["legit"],
  lid: ["gel", "pet", "get", "pit"],
  lie: ["eel", "ail", "art"],
  lied: ["peel", "pail", "part", "pert", "gait"],
  lieder: ["depart"],
  lien: ["nail"],
  lieu: ["nail"],
  limbo: ["newel"],
  limy: ["twit"],
  lined: ["panel"],
  lint: ["toil", "tort"],
  lion: ["noel", "unit"],
  lira: ["edit"],
  lire: ["edit"],
  lisle: ["alert"],
  lists: ["steel", "sleet"],
  lit: ["let", "tit", "lit"],
  lite: ["alit"],
  load: ["peel", "pent", "gent"],
  loads: ["spent"],
  loam: ["whet", "went"],
  loamy: ["tweet"],
  lob: ["gel", "eel", "get", "got"],
  loins: ["enrol"],
  lone: ["aunt"],
  loner: ["jaunt", "daunt"],
  loom: ["wool", "went", "wont"],
  loon: ["noel"],
  loop: ["dent"],
  loose: ["agent"],
  loot: ["tool", "toot", "loot", "tent", "lent"],
  lop: ["dot"],
  loss: ["gent", "sent"],
  lost: ["tent", "lent"],
  lot: ["let", "tot", "lot"],
  lots: ["stet", "slot"],
  lousy: ["tenet"],
  low: ["met", "mot"],
  lower: ["jennet"],
  lust: ["tent", "lent"],
  lye: ["art"],
  m: ["w"],
  mad: ["pew"],
  maid: ["grew"],
  man: ["new"],
  mane: ["anew"],
  map: ["dew"],
  mar: ["jew", "dew", "yew"],
  maw: ["mew"],
  may: ["hew"],
  mayday: ["regrew"],
  me: ["aw"],
  mead: ["phew"],
  meal: ["thaw", "thew"],
  meat: ["thaw", "thew"],
  men: ["new"],
  mend: ["gnaw"],
  messy: ["resew"],
  met: ["law"],
  mew: ["maw", "mew"],
  mid: ["pew"],
  mil: ["jew"],
  mine: ["anew"],
  moat: ["thew"],
  mod: ["pew"],
  moil: ["trow"],
  mold: ["plow", "glow"],
  molter: ["yellow"],
  mom: ["wow"],
  money: ["renew"],
  moo: ["new", "now"],
  mop: ["dew"],
  mosey: ["resew", "resow"],
  mossy: ["resew", "resow"],
  mot: ["tow", "low"],
  motley: ["hallow", "tallow"],
  moue: ["anew"],
  mousy: ["renew"],
  mow: ["mew", "mow"],
  n: ["u", "n", "o"],
  nail: ["lieu", "teen", "lien"],
  nap: ["den"],
  nay: ["hen", "ten", "tho", "rho"],
  neap: ["dean"],
  near: ["jean", "dean"],
  neat: ["lean", "than", "teen", "then"],
  need: ["peen"],
  nest: ["lean", "teen"],
  net: ["tau", "tan", "ten"],
  new: ["man", "men"],
  newsman: ["newsman"],
  newsroom: ["woodsman"],
  next: ["loan"],
  nib: ["gin"],
  nibs: ["seen"],
  nil: ["ten", "tin"],
  nine: ["euro"],
  nip: ["den", "din"],
  nisei: ["resin"],
  nit: ["ten", "tin"],
  no: ["nu", "en", "on", "no"],
  nod: ["gnu", "pen", "goo"],
  noel: ["teen"],
  noes: ["seen"],
  noisy: ["heron"],
  none: ["anon"],
  noon: ["neon", "noon"],
  nor: ["you", "den", "yen", "don", "yon"],
  nose: ["aeon"],
  nosh: ["aeon"],
  nosy: ["teen"],
  not: ["ten", "ton", "too"],
  notes: ["eaten", "salon"],
  now: ["men", "moo"],
  nu: ["nu", "no"],
  nub: ["gnu"],
  O: ["e", "o", "n"],
  o: ["e", "o", "n"],
  oar: ["den", "yen"],
  oasis: ["sieve", "green"], //oasis and green is cool
  oat: ["tee", "lee", "the", "tho", "ten"],
  oaten: ["oaten"],
  oats: ["glee", "glen"],
  obey: ["rage", "teen"],
  obi: ["ego"],
  obit: ["tree", "teen", "lien"],
  ode: ["ape", "age", "ago", "ego"],
  odor: ["dope", "doge"],
  oh: ["ye", "he", "yo", "ho", "an"],
  ohm: ["who", "wan"],
  oho: ["eye", "oho"],
  oil: ["lee", "tee", "lie", "tie", "ten", "tin"],
  oiled: ["patio"],
  oils: ["glee", "glen"],
  ole: ["ale", "ate"],
  om: ["we"],
  on: ["no", "on"],
  one: ["eon"],
  onion: ["union", "onion"],
  ooh: ["hoe", "yen", "hen", "yon", "hon"],
  or: ["ye", "do", "yo"],
  orb: ["eye"],
  ore: ["aye", "eye", "ado"],
  osier: ["deign"], //type of tree
  osprey: ["redden"],
  otter: ["jello"],
  ow: ["me"],
  ox: ["on"],
  oxen: ["neon"],
  oxide: ["apron"],
  oyster: ["delete"],
  p: ["d"],
  pa: ["ed"],
  padre: ["edged"],
  paid: ["pied"],
  pail: ["lied"],
  pain: ["need"],
  pair: ["deed"],
  pal: ["led"],
  pallid: ["pitted"],
  pallor: ["dotted"],
  panier: ["darned"],
  pant: ["toed"],
  paper: ["jaded"],
  pare: ["eyed"],
  parent: ["loaded"],
  parer: ["jaded"],
  pass: ["seed"],
  passel: ["jagged", "legged"],
  passer: ["jagged"],
  pat: ["led"],
  pathos: ["sealed"],
  patio: ["oiled"],
  pay: ["red"],
  payee: ["eared"],
  payer: ["dated"],
  pea: ["had"],
  peal: ["lead"],
  pear: ["dead", "deed"],
  peat: ["lead"],
  peel: ["lead"],
  peen: ["need"],
  peep: ["dead", "deed"],
  peer: ["dead", "deed"],
  pend: ["goad"],
  pent: ["toad", "load", "toed"],
  peon: ["need"],
  pep: ["dad"],
  per: ["dad"],
  persona: ["honeyed"], //this is just kind of cool
  peso: ["egad", "need"],
  pest: ["lead"],
  pet: ["tad", "lad", "led"],
  peter: ["dated"],
  pew: ["mad"],
  phat: ["lead"],
  phew: ["mead"],
  phi: ["rad"],
  photon: ["unload"],
  pi: ["ed", "id"],
  pie: ["aid"],
  pied: ["paid"],
  pier: ["yard", "deed"],
  piled: ["gelid"],
  piles: ["gelid"],
  pint: ["turd", "lord", "toed"],
  piny: ["turd", "hued", "toed"],
  pip: ["did"],
  piper: ["jaded"],
  piss: ["seed"],
  pit: ["led", "lid"],
  pithy: ["hated"],
  piton: ["noted"],
  pitted: ["pallid"],
  pixy: ["toed"],
  play: ["held"],
  plea: ["veld", "held"],
  pled: ["geld"],
  plod: ["geld", "gold"],
  plot: ["told"],
  plow: ["meld", "mold"],
  ploy: ["held", "hold", "told"],
  pod: ["pod", "god"],
  poem: ["weed", "wand", "wend"], //go in an indirect route
  poet: ["land", "tend", "lend"],
  poi: ["red", "rod", "end"],
  pol: ["led"],
  polio: ["oiled"],
  pond: ["good", "pond"],
  pony: ["hued", "toed", "hood", "rood"], //rood is crucifix
  pooh: ["heed", "hood"],
  pool: ["toed", "lend", "tend"],
  poop: ["deed"],
  poor: ["deed"],
  pore: ["eyed"],
  pose: ["aged"],
  posh: ["heed", "aged"],
  posit: ["trend"],
  post: ["tend", "lend"],
  posy: ["heed", "reed", "tend", "rend"],
  pot: ["led"],
  potion: ["united"],
  pro: ["odd"],
  psi: ["red"],
  pub: ["end"],
  pus: ["end"],
  puss: ["send"],
  q: ["b"],
  r: ["j", "d", "y"],
  rabbet: ["legged"],
  rabbit: ["legged"],
  rabid: ["greed"],
  rah: ["hey"],
  raid: ["pied", "prey", "grey"],
  rail: ["lied", "trey", "levy"],
  rain: ["need"],
  ram: ["wed", "why"],
  rani: ["envy"],
  rant: ["toed"],
  raper: ["jaded"],
  rare: ["eyed"],
  rash: ["heed", "aged", "ashy"],
  rasp: ["deed"],
  rat: ["led", "thy"],
  rater: ["dated"],
  ratio: ["oiled"],
  ration: ["united"],
  rats: ["sled"],
  ray: ["red", "hey", "thy"],
  rayon: ["noted", "nervy"],
  re: ["ad", "ed"],
  real: ["lead", "they"],
  ream: ["weed", "whey"],
  reap: ["dead", "deed"],
  rear: ["dead", "deed"],
  rebid: ["greed"],
  reboil: ["tinged"],
  red: ["pad", "gad", "pay", "gay"],
  redden: ["napped"],
  redo: ["egad"],
  reel: ["lead"],
  rein: ["need"],
  relay: ["relay"],
  rem: ["wad", "wed", "way"],
  rend: ["goad"],
  renew: ["maned"],
  rennet: ["tanned"],
  rent: ["toad", "load", "toed"],
  rep: ["dad", "day"],
  repeal: ["leaded"],
  repeat: ["leaded"],
  repel: ["jaded"],
  repent: ["loaded"],
  reside: ["agreed"],
  resow: ["mosey"],
  rest: ["lead"],
  rewed: ["gamey"],
  rhea: ["head"],
  rho: ["nay"],
  ribber: ["jagged"],
  rid: ["pry"],
  ridden: ["napped"],
  ride: ["aged"],
  rim: ["wed", "wry"],
  rime: ["awed", "awry"],
  rind: ["gory"],
  riot: ["lord", "toed"],
  rip: ["did", "dry"],
  rise: ["aged", "eery"],
  road: ["pend"],
  roads: ["speed", "spend"],
  roam: ["weed", "wend", "whey"],
  roan: ["need"],
  roar: ["deed", "deny"],
  roast: ["teeny"],
  rob: ["god", "end"],
  robber: ["jagged"],
  robe: ["aged"],
  robot: ["teeny"], //Could use this
  rod: ["pod", "god"],
  rode: ["aged"],
  roe: ["and", "end", "any"],
  roil: ["lied", "trod", "lend", "tend", "trey", "troy", "tiny"],
  rood: ["good", "pend", "pond", "pony"],
  room: ["weed", "wood", "wend"],
  roomy: ["tweed"],
  roost: ["teeny"],
  root: ["toed", "tend", "lend", "tony"],
  roots: ["steed", "stood", "stony"],
  roper: ["jaded"],
  rose: ["aged"],
  rosette: ["alleged"],
  rosy: ["heed", "reed", "tend", "rend"],
  rot: ["led", "toy"],
  round: ["gunny"],
  row: ["mod"],
  rowel: ["tanned"],
  rub: ["end"],
  ruby: ["tend", "rend"],
  rue: ["and", "end", "any"],
  rumor: ["downy"],
  runny: ["hound", "round", "tunny", "runny"],
  runt: ["tony"],
  russet: ["legend"],
  rust: ["tend", "lend"],
  rustle: ["attend"],
  s: ["e", "g", "s"],
  sad: ["pee", "gee", "peg"],
  sadist: ["teepee"],
  sahib: ["grave"],
  said: ["give"],
  sail: ["tree", "jive", "live", "lees"],
  saith: ["alive"],
  sales: ["salve", "sales"],
  salon: ["notes"],
  salsa: ["helve"],
  sand: ["goes"],
  sans: ["goes"],
  sari: ["ides"],
  sash: ["ages"],
  sassy: ["reeve"],
  sat: ["tee", "lee", "the", "leg"],
  say: ["tee", "the"],
  sea: ["hag", "veg", "has"],
  seal: ["thee", "lees"],
  sealed: ["pelves"],
  seam: ["whee"],
  seat: ["thee", "lees"],
  send: ["goes"],
  set: ["tee", "lee", "tag", "lag", "leg"],
  sew: ["mag"],
  sh: ["ye", "he", "as"],
  she: ["aye", "eye"],
  shh: ["aye", "hag", "has"],
  ship: ["drag"],
  shy: ["rye", "the", "hag", "tag", "rag", "has"],
  sibyl: ["there"],
  side: ["epee", "ages"],
  sin: ["ore", "nee"],
  sinus: ["snore"],
  sip: ["die", "dig", "dis"],
  sir: ["die", "jig", "dig", "yes", "dis"],
  sis: ["ere", "gee", "see", "erg", "gig", "sis"],
  sisal: ["there"],
  sit: ["tee", "lee", "tie", "lie", "leg"],
  six: ["ore"],
  slash: ["heels"],
  slaw: ["mete"],
  sled: ["pale", "gale", "pate", "gate"],
  slew: ["male", "mate", "mete"],
  slid: ["pile"],
  slide: ["agile"],
  slier: ["darts"],
  slim: ["wile", "wits"],
  slit: ["tile", "lite"],
  sloe: ["ante"],
  slop: ["dole", "dote"],
  slosh: ["heels"],
  slot: ["tole", "tote", "lots"],
  slow: ["mole", "mete", "mote"],
  slue: ["ante"],
  snail: ["teens"],
  sneer: ["jeans"],
  snide: ["aging"],
  snip: ["dine", "drug", "ding"],
  snipe: ["adios"],
  snit: ["true", "tine", "line", "ting", "lens"],
  snob: ["gene", "gone", "gong"],
  snood: ["genus"],
  snoot: ["teens"],
  snot: ["tone", "lone", "tong", "long", "lens"],
  snow: ["moue"],
  sob: ["gee"],
  sod: ["pee", "gee", "peg"],
  soda: ["epee"],
  soil: ["tree", "line", "tine", "ting", "lees", "lens"],
  sol: ["lee", "tee", "toe", "leg", "jog", "log", "tog"],
  sold: ["glee"],
  sole: ["aloe"],
  solid: ["piles"],
  solids: ["epilog"],
  son: ["nee", "one"],
  soon: ["none", "noes"],
  soot: ["tone", "lone", "tong", "long", "lees", "lens"],
  sooth: ["atone", "alone", "along"],
  sop: ["doe", "dog"],
  sot: ["tee", "lee", "toe", "leg", "tog", "log"],
  sox: ["one"],
  soy: ["tee", "hoe", "toe", "roe", "hog", "tog"],
  spasm: ["weeds"],
  spent: ["loads"],
  spew: ["made"],
  spiny: ["horde"],
  spit: ["tide"],
  spite: ["elide"],
  split: ["tilde"],
  spoils: ["strode"],
  spoon: ["needs"],
  spot: ["lode"],
  ssh: ["age", "yes", "ass"],
  stash: ["heels"],
  steam: ["whale"],
  stein: ["orate"],
  stem: ["wale"],
  step: ["date", "dale"],
  steroid: ["predate"],
  stet: ["late", "tale"],
  stew: ["mate", "mete", "male"],
  stile: ["elite"],
  stint: ["torte"],
  stoat: ["thole"],
  stony: ["roots"],
  stop: ["dote", "dole"],
  stow: ["mete", "mote", "mole"],
  strain: ["needle"],
  stye: ["arts"],
  suet: ["lane", "tang", "lens"],
  suit: ["tine", "line", "ting", "lens"],
  suitor: ["doting"],
  sun: ["one"],
  sway: ["heme"],
  sweat: ["theme"],
  swop: ["dome"],
  synod: ["genre"],
  system: ["waters"],
  t: ["t", "l"],
  tab: ["get", "gel", "eel"],
  tabloid: ["genteel"],
  tad: ["pet", "get", "gel"],
  tailed: ["petrel"],
  tails: ["sleet", "steel"],
  tam: ["wet"],
  tamer: ["jewel"],
  tan: ["net"],
  tanned: ["gannet"],
  tanner: ["jennet"],
  tansy: ["tenet"],
  tar: ["jet", "yet"],
  tassel: ["tassel"],
  tat: ["let"],
  tau: ["net"],
  tawny: ["tunnel", "runnel"],
  tea: ["eat", "vat", "hat", "vet", "eel"],
  teal: ["teat", "that", "teal"],
  team: ["what", "whet", "weal"],
  tear: ["deal"],
  teat: ["teat", "that", "teal"],
  tee: ["eat", "eel"],
  teem: ["weal"],
  teen: ["neat"],
  ten: ["oat", "net"],
  tend: ["gnat", "goat", "poet", "goal"],
  tenet: ["tenet"],
  tepid: ["pedal"],
  test: ["teat", "teal"],
  than: ["neat", "oval"],
  that: ["teat", "that", "teal"],
  thaw: ["meat", "meal"],
  the: ["eat"],
  them: ["weal"],
  then: ["neat"],
  thew: ["meat", "meal"],
  they: ["heat", "teat", "heal", "teal", "real"],
  thin: ["neat", "oral"],
  thine: ["aural"],
  this: ["seat", "seal"],
  tho: ["eat", "oat"],
  thou: ["neat"],
  threw: ["medal"],
  throes: ["sandal"],
  throw: ["medal", "modal"],
  thud: ["gnat"],
  thus: ["gnat"],
  thy: ["hat", "tat", "rat"],
  ti: ["it"],
  tibia: ["vigil"],
  tidal: ["legit"],
  tie: ["art", "eel", "ail"],
  tier: ["dart", "jail"],
  tile: ["alit"],
  timer: ["jewel"],
  timid: ["pewit"],
  tin: ["net", "nit", "nil", "oil"],
  tinder: ["deport"],
  tint: ["tort", "toil"],
  tiny: ["hurt", "tort", "hurl", "toil", "roil"],
  tire: ["edit"],
  tit: ["let", "tit", "lit"],
  titled: ["pallet", "pellet"],
  toad: ["pent", "gent", "peel"],
  toast: ["level"],
  today: ["repel"],
  toe: ["ant", "eel"],
  toed: ["pant", "pent", "gent", "peel"],
  toil: ["trot", "lent", "tent", "lint", "tint"],
  toilet: ["talent", "latent"],
  told: ["plot"],
  tom: ["wet"],
  ton: ["net", "not"],
  tonal: ["tenet"],
  tone: ["aunt"],
  toner: ["jaunt", "daunt"],
  tony: ["hoot", "toot", "root", "hunt", "runt", "tool"],
  too: ["net", "not", "eel"],
  tool: ["loot", "toot", "lent", "tent", "tool"],
  toot: ["toot", "loot", "tent", "lent", "tool"],
  toothy: ["talent"],
  top: ["dot"],
  tor: ["jet", "yet", "jot", "dot"],
  toss: ["gent", "sent"],
  tot: ["let", "tot", "lot"],
  tow: ["met", "mot"],
  towel: ["jennet"],
  tower: ["jennet"],
  toy: ["hot", "tot", "rot"],
  tsar: ["jest"],
  tuba: ["vent"],
  tuna: ["hunt"],
  tune: ["aunt"],
  tuner: ["jaunt", "daunt"],
  u: ["n"],
  uh: ["an"],
  union: ["union", "onion"],
  unit: ["lion"],
  united: ["patron"],
  unload: ["photon"],
  unwed: ["pennon"],
  us: ["en"],
  usable: ["eleven"],
  used: ["peen"],
  w: ["m"],
  wad: ["gem"],
  wail: ["teem"],
  wait: ["teem"],
  wan: ["ohm"],
  wand: ["poem"],
  was: ["gem"],
  wasp: ["deem"],
  wast: ["teem"],
  wax: ["ohm"],
  way: ["hem", "rem"],
  ways: ["stem"],
  we: ["am", "em"],
  weal: ["team", "teem", "them"],
  wear: ["deem"],
  web: ["gem"],
  wed: ["gem"],
  weep: ["deem"],
  weir: ["dram", "deem"],
  wend: ["poem"],
  went: ["loam"],
  west: ["team", "teem"],
  wet: ["tam", "lam"],
  wham: ["wham"],
  what: ["team"],
  whet: ["team"],
  whey: ["team", "ream"],
  whip: ["dram"],
  whir: ["dram"],
  whit: ["tram", "team"],
  who: ["ohm"],
  why: ["ham", "tam", "ram"],
  wind: ["poem"],
  wino: ["norm"],
  wisp: ["deem"],
  wist: ["term", "teem"],
  wits: ["stem", "slim"],
  woes: ["seem"],
  wont: ["loom"],
  wood: ["poem"],
  wool: ["teem", "loom"],
  wow: ["mom"],
  x: ["x", "o"],
  xi: ["ex"],
  y: ["h", "t", "r"],
  ya: ["eh"],
  yam: ["wet"],
  yaw: ["met"],
  ye: ["ah", "eh", "at"],
  yea: ["hah", "eat", "vat", "hat", "vet", "ear", "her"],
  yeah: ["yeah", "heat", "year", "hear", "aver"],
  year: ["yeah", "dear", "year", "jeer", "deer"],
  yeast: ["lever"],
  yellow: ["molter"],
  yen: ["oat", "net", "oar"],
  yes: ["eat", "sat", "get", "set", "ear", "gar"],
  yet: ["tat", "let", "tar"],
  yew: ["mat", "met", "mar"],
  yield: ["plait"],
  yin: ["net", "nit"],
  yipe: ["edit"],
  yo: ["eh", "oh", "or"],
  yodel: ["taper", "leper", "lager"],
  yon: ["ooh", "net", "not", "nor"],
  you: ["net", "not", "nor"],
  yow: ["met", "mot"],
  z: ["z"],
  zeal: ["jeez"],
  "": [""],
};

export default data;
