const data = {
  a: ["e", "v", "h"],
  abed: ["page", "gage"],
  abide: ["agree"],
  abs: ["gee", "see"],
  adenoid: ["peonage"],
  adieu: ["neigh"],
  adios: ["serge", "gorge"],
  ah: ["ye", "he", "ah"],
  aha: ["eye", "hah"],
  aid: ["pee", "gee", "pie"],
  aide: ["epee"],
  ail: ["lee", "tee", "lie", "tie"],
  aim: ["wee"],
  air: ["die"],
  alder: ["depth"],
  ale: ["ale", "ate"],
  alit: ["tile", "lite"],
  also: ["ogle"],
  am: ["we"],
  an: ["uh"],
  anew: ["mane"],
  aniline: ["aniline"],
  anon: ["none"],
  any: ["hue", "huh"],
  aphid: ["grade"],
  apish: ["aside"],
  aria: ["hide"],
  arise: ["aside"],
  as: ["eh", "sh"],
  ash: ["age", "ash"],
  ashy: ["thee", "hash"],
  aside: ["agree", "apish"],
  ass: ["gee", "see", "ssh"],
  assay: ["these"],
  ate: ["ate", "ale"],
  atop: ["dote", "dole", "doth"],
  aunt: ["tune"],
  aw: ["me"],
  away: ["heme"],
  awed: ["game"],
  ax: ["oh"],
  axe: ["axe"],
  axial: ["throe"],
  axle: ["aloe"],
  aye: ["ate"],
  b: ["q", "g", "e"],
  baa: ["veg", "eve"],
  bad: ["peg", "pee", "gee"],
  bade: ["epee"],
  bail: ["tree", "jive", "live"],
  bait: ["tree", "live"],
  bald: ["glee"],
  baler: ["delve"],
  balsa: ["helve"],
  ban: ["nee"],
  basis: ["sieve"],
  basset: ["lessee"],
  bat: ["leg", "tee", "lee", "the"],
  bathos: ["goatee"],
  baths: ["salve"],
  bats: ["glee"],
  bay: ["tee", "the"],
  beam: ["whee"],
  beast: ["levee"],
  beat: ["thee"],
  bed: ["gag", "peg", "pee", "gee"],
  below: ["melee"],
  bet: ["tag", "lag", "leg", "tee", "lee"],
  bey: ["hag", "tag", "tee"],
  bi: ["re"],
  bias: ["sere"],
  bib: ["erg", "gig", "ere", "gee"],
  bid: ["peg", "pig", "gig", "pee", "gee", "pie"],
  bide: ["epee"],
  bidet: ["tepee"],
  bier: ["dare"],
  bin: ["nee"],
  bind: ["pure"],
  bio: ["erg", "ere", "ore"],
  biped: ["padre"],
  bit: ["leg", "tee", "lee", "tie", "lie"],
  bled: ["pale", "gale", "pate", "gate"],
  blew: ["male", "mate", "mete"],
  blind: ["guile"],
  bloat: ["thole"],
  blot: ["tole", "tote"],
  blow: ["mole", "mete", "mote"],
  blower: ["demote"],
  blue: ["ante"],
  bluster: ["detente"],
  boa: ["veg", "hog", "hoe"],
  boast: ["levee"],
  boat: ["thee"],
  bob: ["gee"],
  bod: ["peg", "pee", "gee"],
  bode: ["agog", "epee"],
  boil: ["tree"],
  bold: ["glee"],
  bole: ["aloe"],
  bombed: ["peewee"],
  bop: ["dog", "doe"],
  bosh: ["agog"],
  both: ["aloe"],
  boy: ["hog", "tog", "tee", "hoe", "toe"],
  brew: ["made"],
  brie: ["aide"],
  brim: ["wide"],
  bro: ["ode"],
  broad: ["geode"],
  brood: ["geode"],
  brow: ["mode"],
  buns: ["sung"],
  bunt: ["lung", "tune"],
  buoy: ["tong", "hone", "tone"],
  buss: ["gene"],
  by: ["he"],
  bye: ["ate"],
  d: ["p", "g"],
  dad: ["pep", "peg"],
  dais: ["seep"],
  day: ["hep"],
  days: ["step"],
  dead: ["peep"],
  deal: ["leap", "jeep"],
  dean: ["neap"],
  dear: ["jeep", "deep"],
  deb: ["gap", "gag"],
  debt: ["leap"],
  deed: ["peep"],
  deem: ["weep"],
  deep: ["deep"],
  deer: ["jeep", "deep"],
  den: ["nap", "nag"],
  dew: ["map", "mag"],
  dial: ["jeep"],
  dibs: ["seep"],
  did: ["pep", "pip", "peg", "pig", "gig"],
  die: ["erg"],
  diet: ["tarp"],
  dim: ["wig"],
  din: ["nip"],
  dip: ["dip", "dig"],
  dis: ["sip", "erg", "gig"],
  doer: ["jeep", "deep"],
  does: ["seep"],
  dole: ["atop"],
  dollop: ["dollop"],
  doom: ["weep"],
  door: ["jeep", "deep"],
  dose: ["agog"],
  dot: ["top", "lop", "leg", "tog", "log"],
  dote: ["atop"],
  doth: ["atop"],
  dotted: ["gallop"],
  duel: ["tang"],
  dues: ["gang", "sang"], //USE
  duet: ["tang"],
  e: ["a", "e"],
  eat: ["tea", "lea", "tee", "lee", "the"],
  eater: ["delve"],
  eats: ["glee"],
  ebb: ["gee"],
  ed: ["pa"],
  eel: ["lea", "tea", "lee", "tee"],
  eh: ["ya", "ha", "ye", "he"],
  either: ["dahlia"],
  elide: ["agile"],
  elite: ["elite"],
  em: ["we"],
  ensue: ["ensue"],
  eon: ["nee"],
  essay: ["these"],
  eta: ["eta"],
  ewer: ["dame"],
  exam: ["whoa"],
  eye: ["aha", "eta", "ate"],
  eyed: ["pate", "gate"],
  h: ["y", "h", "a"],
  ha: ["eh", "ha"],
  had: ["pea"],
  hah: ["hey", "yea", "aha"],
  hail: ["trey", "levy"],
  hair: ["diva"],
  hallow: ["motley"],
  ham: ["why"],
  has: ["shy", "shh", "sea"],
  hash: ["ashy"],
  hast: ["levy"],
  hat: ["thy", "tea", "lea"],
  hay: ["hey", "thy", "tea"],
  he: ["ah", "eh"],
  heal: ["they"],
  heat: ["they"],
  heir: ["dray"],
  held: ["play", "plea"],
  hem: ["way"],
  heme: ["away"],
  hen: ["nay"],
  hep: ["day"],
  her: ["jay", "day"],
  hew: ["may"],
  hey: ["hay", "hey", "hah", "tea"],
  hi: ["eh"],
  hid: ["pry", "pea"],
  hie: ["era"],
  him: ["wry"],
  hip: ["dry"],
  his: ["era", "sea"],
  hiss: ["eery", "sera"],
  hit: ["try", "tea", "lea"],
  hither: ["dahlia"],
  ho: ["eh", "oh"],
  hod: ["pea"],
  hold: ["ploy", "plea"],
  holder: ["deploy"],
  hollow: ["motley"],
  hood: ["pooh"],
  hot: ["toy", "tea", "lea"],
  hubby: ["teeny"],
  hue: ["any"],
  huh: ["any"],
  humor: ["downy"],
  hunt: ["tuna"],
  hussy: ["teeny"],
  I: ["r", "e", "i"],
  i: ["r", "e", "i"],
  iamb: ["ewer"],
  ibis: ["seer"],
  id: ["pi"],
  idem: ["wage"],
  ides: ["gape", "gage", "sage"],
  idol: ["lope", "loge"],
  ilea: ["vale", "hale", "hate"],
  inhale: ["ethane"],
  inn: ["we"],
  ion: ["nor", "nee"],
  iris: ["side"],
  iron: ["node"],
  irons: ["suede"],
  isle: ["else"],
  islet: ["tater", "later"],
  ism: ["wee"],
  issue: ["anger"],
  issuer: ["danger"],
  it: ["ti"],
  item: ["wale"],
  j: ["l", "r"],
  jab: ["gel", "eel"],
  jabber: ["dagger"],
  jaded: ["paper", "pager"],
  jail: ["jeer", "leer", "tier"],
  jamb: ["ewer"],
  jaunt: ["tuner"],
  jay: ["her"],
  jean: ["near"],
  jeans: ["sneer"],
  jeep: ["deal", "dear", "deer"],
  jeer: ["deal", "dear", "jeer", "deer"],
  jeez: ["zeal"],
  jello: ["otter"],
  jennet: ["tanner"],
  jenny: ["tuner"],
  jest: ["teal", "tear", "tsar", "leer"],
  jet: ["tar"],
  jew: ["mar"],
  jewel: ["tamer", "tanner"],
  jib: ["gel", "eel", "err"],
  jihad: ["pearl"],
  jinni: ["ewer", "inner"],
  jitney: ["hauler"],
  job: ["gel", "eel"],
  jobber: ["dagger"],
  joiner: ["denier"],
  josh: ["heel"],
  jot: ["tor"],
  joust: ["tenor"],
  joy: ["her", "tor"],
  l: ["j", "l", "t"],
  lab: ["gel", "eel", "get"],
  labia: ["eight"],
  labile: ["alight"],
  lad: ["gel", "pet", "get"],
  laid: ["peel"],
  lair: ["diet"],
  lam: ["wet"],
  lash: ["heel"],
  law: ["met"],
  lea: ["eel", "eat", "vat", "hat", "vet"],
  lead: ["peal", "peel", "peat", "phat"],
  lean: ["neat"],
  leap: ["deal"],
  least: ["level"],
  led: ["pal", "gal", "gel", "pat", "pet", "get"],
  lee: ["eel", "eat"],
  leer: ["deal"],
  lees: ["seal", "seat"],
  lei: ["eel", "rat", "eat"],
  lemon: ["newel"],
  lend: ["gnat"],
  lens: ["gnat", "suet"],
  less: ["seal", "seat"],
  lest: ["teal", "teat"],
  let: ["tat", "let"],
  lib: ["gel", "eel", "get"],
  libel: ["legit"],
  lid: ["gel", "pet", "get", "pit"],
  lie: ["eel", "ail", "art"],
  lied: ["peel", "pail", "part", "pert", "gait"],
  lieder: ["depart"],
  lien: ["nail"],
  lieu: ["nail"],
  limy: ["twit"],
  lined: ["panel"],
  lion: ["noel"],
  lira: ["edit"],
  lire: ["edit"],
  lisle: ["alert"],
  lists: ["steel", "sleet"],
  lit: ["let", "tit", "lit"],
  lite: ["alit"],
  load: ["peel"],
  loam: ["whet"],
  loamy: ["tweet"],
  lob: ["gel", "eel", "get", "got"],
  loins: ["enrol"],
  loom: ["wool"],
  loon: ["noel"],
  loot: ["tool", "toot", "loot"],
  lop: ["dot"],
  lot: ["let", "tot", "lot"],
  lots: ["stet", "slot"],
  lousy: ["tenet"],
  low: ["met", "mot"],
  lower: ["jennet"],
  lust: ["tent", "lent"],
  m: ["w"],
  mad: ["pew"],
  maid: ["grew"],
  man: ["new"],
  mane: ["anew"],
  map: ["dew"],
  mar: ["jew", "dew"],
  maw: ["mew"],
  may: ["hew"],
  me: ["aw"],
  mead: ["phew"],
  meal: ["thaw", "thew"],
  meat: ["thaw", "thew"],
  men: ["new"],
  mend: ["gnaw"],
  met: ["law"],
  mew: ["maw", "mew"],
  mid: ["pew"],
  mil: ["jew"],
  mine: ["anew"],
  moat: ["thew"],
  mod: ["pew"],
  moil: ["trow"],
  mold: ["plow", "glow"],
  mom: ["wow"],
  mop: ["dew"],
  mot: ["tow", "low"],
  motley: ["hallow", "tallow"],
  moue: ["anew"],
  mow: ["mew", "mow"],
  muumuu: ["muumuu"],
  n: ["u", "n"],
  nail: ["lieu", "teen", "lien"],
  nap: ["den"],
  nay: ["hen", "ten"],
  neap: ["dean"],
  near: ["jean", "dean"],
  neat: ["lean", "than", "teen", "then"],
  need: ["peen"],
  nest: ["lean", "teen"],
  net: ["tau", "tan", "ten"],
  new: ["man", "men"],
  newsman: ["newsman"],
  newsroom: ["woodsman"],
  next: ["loan"],
  nib: ["gin"],
  nibs: ["seen"],
  nil: ["ten", "tin"],
  ninny: ["twin"],
  nip: ["den", "din"],
  nisei: ["resin"],
  nit: ["ten", "tin"],
  no: ["en", "on"],
  nod: ["pen"],
  noel: ["teen"],
  noes: ["seen"],
  noisy: ["heron"],
  none: ["anon"],
  noon: ["neon", "noon"],
  nor: ["den", "don"],
  nose: ["aeon"],
  nosh: ["aeon"],
  nosy: ["teen"],
  not: ["ten", "ton"],
  notes: ["eaten", "salon"],
  now: ["men"],
  nu: ["nu"],
  nub: ["gnu"],
  O: ["e", "o"],
  o: ["e", "o"],
  oasis: ["sieve"],
  oat: ["tee", "lee", "the", "tho"],
  oats: ["glee"],
  obi: ["ego"],
  obit: ["tree"],
  ode: ["ape", "age", "ago", "ego"],
  odor: ["dope", "doge"],
  oh: ["ye", "he", "yo", "ho"],
  ohm: ["who"],
  oho: ["eye", "oho"],
  oil: ["lee", "tee", "lie", "tie"],
  oiled: ["patio"],
  oils: ["glee"],
  ole: ["ale", "ate"],
  om: ["we"],
  on: ["no"],
  ooh: ["hoe"],
  or: ["do"],
  ore: ["ado"],
  otter: ["jello"],
  ow: ["me"],
  oyster: ["delete"],
  p: ["d"],
  pa: ["ed"],
  padre: ["edged"],
  paid: ["pied"],
  pail: ["lied"],
  pain: ["need"],
  pair: ["deed"],
  pal: ["led"],
  pallid: ["pitted"],
  pallor: ["dotted"],
  panier: ["darned"],
  paper: ["jaded"],
  parer: ["jaded"],
  pass: ["seed"],
  passel: ["jagged", "legged"], //A large group of people or things
  passer: ["jagged"],
  pat: ["led"],
  pathos: ["sealed"],
  patio: ["oiled"],
  payer: ["dated"],
  pea: ["had"],
  peal: ["lead"],
  pear: ["dead", "deed"],
  peat: ["lead"],
  peel: ["lead"],
  peen: ["need"],
  peep: ["dead", "deed"],
  peer: ["dead", "deed"],
  peon: ["need"],
  pep: ["dad"],
  per: ["dad"],
  peso: ["egad"],
  pest: ["lead"],
  pet: ["tad", "lad", "led"],
  peter: ["dated"],
  pew: ["mad"],
  phat: ["lead"],
  phew: ["mead"],
  phi: ["rad"],
  pi: ["ed", "id"],
  pie: ["aid"],
  pied: ["paid"],
  pier: ["deed"],
  piled: ["gelid"],
  piles: ["gelid"],
  pint: ["turd"],
  piny: ["turd", "hued"],
  pip: ["did"],
  piper: ["jaded"],
  piss: ["seed"],
  pit: ["led", "lid"],
  pithy: ["hated"],
  piton: ["noted"],
  pitted: ["pallid"],
  pixy: ["toed"],
  play: ["held"],
  plea: ["veld", "held"],
  pled: ["geld"],
  plod: ["geld", "gold"],
  plot: ["told"],
  plow: ["meld", "mold"],
  ploy: ["held", "hold", "told"],
  pod: ["pod", "god"],
  poem: ["weed"],
  poi: ["red", "rod"],
  pol: ["led"],
  polio: ["oiled"],
  pony: ["hued"],
  pooh: ["heed", "hood"],
  pool: ["toed"],
  poop: ["deed"],
  poor: ["deed"],
  pose: ["aged"],
  posh: ["heed", "aged"],
  posy: ["heed"],
  pot: ["led"],
  pro: ["odd"],
  psi: ["red"],
  pub: ["end"],
  pus: ["end"],
  puss: ["send"],
  q: ["b"],
  r: ["j", "d"],
  rabbet: ["legged"],
  rabbit: ["legged"],
  rabid: ["greed"],
  raid: ["pied"],
  rail: ["lied"],
  rain: ["need"],
  ram: ["wed"],
  raper: ["jaded"],
  rash: ["heed", "aged"],
  rasp: ["deed"],
  rat: ["led"],
  rater: ["dated"],
  ratio: ["oiled"],
  rats: ["sled"],
  rayon: ["noted"],
  re: ["ad", "ed"],
  real: ["lead"],
  ream: ["weed"],
  reap: ["dead", "deed"],
  rear: ["dead", "deed"],
  rebid: ["greed"],
  red: ["pad", "gad"],
  redden: ["napped"],
  redo: ["egad"],
  reel: ["lead"],
  rein: ["need"],
  rem: ["wad", "wed"],
  renew: ["maned"],
  rennet: ["tanned"],
  rep: ["dad"],
  repeal: ["leaded"],
  repeat: ["leaded"],
  repel: ["jaded"],
  reside: ["agreed"],
  rest: ["lead"],
  rhea: ["head"],
  ribber: ["jagged"],
  ridden: ["napped"],
  ride: ["aged"],
  rim: ["wed"],
  rime: ["awed"],
  riot: ["lord", "toed"],
  rip: ["did"],
  rise: ["aged"],
  roads: ["speed"],
  roam: ["weed"],
  roan: ["need"],
  roar: ["deed"],
  rob: ["god"],
  robber: ["jagged"],
  robe: ["aged"],
  rod: ["pod", "god"],
  rode: ["aged"],
  roil: ["lied", "trod"],
  rood: ["good"],
  room: ["weed", "wood"],
  roomy: ["tweed"],
  root: ["toed"],
  roots: ["steed", "stood"],
  roper: ["jaded"],
  rose: ["aged"],
  rosette: ["alleged"],
  rosy: ["heed"],
  rot: ["led"],
  row: ["mod"],
  rowel: ["tanned"],
  rub: ["end"],
  ruby: ["tend"],
  rue: ["and", "end"],
  russet: ["legend"],
  rust: ["tend", "lend"],
  rustle: ["attend"],
  s: ["e", "g", "s"],
  sad: ["pee", "gee", "peg"],
  sadist: ["teepee"],
  sahib: ["grave"],
  said: ["give"],
  sail: ["tree", "jive", "live", "lees"],
  saith: ["alive"],
  sales: ["salve", "sales"],
  salon: ["notes"],
  salsa: ["helve"],
  sari: ["ides"],
  sash: ["ages"],
  sat: ["tee", "lee", "the", "leg"],
  say: ["tee", "the"],
  sea: ["hag", "veg", "has"],
  seal: ["thee", "lees"],
  sealed: ["pelves"],
  seam: ["whee"],
  seat: ["thee", "lees"],
  set: ["tee", "lee", "tag", "lag", "leg"],
  sew: ["mag"],
  sh: ["ye", "he", "as"],
  she: ["aye", "eye"],
  shh: ["aye", "hag", "has"],
  ship: ["drag"],
  shy: ["the", "hag", "tag", "has"],
  sibyl: ["there"],
  side: ["epee", "ages"],
  sin: ["nee"],
  sip: ["die", "dig", "dis"],
  sir: ["die", "jig", "dig", "dis"],
  sis: ["ere", "gee", "see", "erg", "gig", "sis"],
  sisal: ["there"],
  sit: ["tee", "lee", "tie", "lie", "leg"],
  six: ["ore"],
  slash: ["heels"],
  slaw: ["mete"],
  sled: ["pale", "gale", "pate", "gate"],
  slew: ["male", "mate", "mete"],
  slid: ["pile"],
  slide: ["agile"],
  slier: ["darts"],
  slim: ["wile", "wits"],
  slit: ["tile", "lite"],
  slop: ["dole", "dote"],
  slosh: ["heels"],
  slot: ["tole", "tote", "lots"],
  slow: ["mole", "mete", "mote"],
  slue: ["ante"],
  snail: ["teens"],
  sneer: ["jeans"],
  snide: ["aging"],
  snip: ["dine", "drug", "ding"],
  snit: ["true", "tine", "line", "ting", "lens"],
  snob: ["gene", "gone", "gong"],
  snoot: ["teens"],
  snot: ["tone", "lone", "tong", "long", "lens"],
  snow: ["moue"],
  sob: ["gee"],
  sod: ["pee", "gee", "peg"],
  soda: ["epee"],
  soil: ["tree", "lees"],
  sol: ["lee", "tee", "toe", "leg", "jog", "log", "tog"],
  sold: ["glee"],
  sole: ["aloe"],
  solid: ["piles"],
  solids: ["epilog"],
  son: ["nee"],
  soon: ["noes"],
  soot: ["lees"],
  sop: ["doe", "dog"],
  sot: ["tee", "lee", "toe", "leg", "tog", "log"],
  soy: ["tee", "hoe", "toe", "hog", "tog"],
  spasm: ["weeds"],
  spew: ["made"],
  spit: ["tide"],
  spite: ["elide"],
  split: ["tilde"],
  spoils: ["strode"],
  spoon: ["needs"],
  spot: ["lode"],
  ssh: ["age", "yes", "ass"],
  stash: ["heels"],
  steam: ["whale"],
  stem: ["wale"],
  step: ["date", "dale"],
  steroid: ["predate"],
  stet: ["late", "tale"],
  stew: ["mate", "mete", "male"],
  stile: ["elite"],
  stoat: ["thole"],
  stop: ["dote", "dole"],
  stow: ["mete", "mote", "mole"],
  strain: ["needle"],
  suet: ["lane", "tang", "lens"],
  suit: ["tine", "line", "ting", "lens"],
  suitor: ["doting"],
  sway: ["heme"],
  sweat: ["theme"],
  swop: ["dome"],
  t: ["t", "l"],
  tab: ["get", "gel", "eel"],
  tad: ["pet", "get", "gel"],
  tailed: ["petrel"],
  tails: ["sleet", "steel"],
  tam: ["wet"],
  tamer: ["jewel"],
  tan: ["net"],
  tanned: ["gannet"],
  tanner: ["jennet", "jewel"],
  tannin: ["newel"],
  tansy: ["tenet"],
  tar: ["jet"],
  tassel: ["tassel"],
  tat: ["let"],
  tau: ["net"],
  tawny: ["tunnel"],
  tea: ["eat", "vat", "hat", "vet", "eel"],
  teal: ["teat", "that", "teal"],
  team: ["what", "whet", "weal"],
  tear: ["deal"],
  teat: ["teat", "that", "teal"],
  tee: ["eat", "eel"],
  teem: ["weal"],
  teen: ["neat"],
  ten: ["net"],
  tend: ["gnat"],
  tenet: ["tenet"],
  tepid: ["pedal"],
  test: ["teat", "teal"],
  than: ["neat"],
  that: ["teat", "that", "teal"],
  thaw: ["meat", "meal"],
  the: ["eat"],
  them: ["weal"],
  then: ["neat"],
  thew: ["meat", "meal"],
  they: ["heat", "teat", "heal", "teal"],
  thin: ["neat"],
  thine: ["aural"],
  this: ["seat", "seal"],
  tho: ["eat", "oat"],
  thou: ["neat"],
  threw: ["medal"],
  throw: ["medal", "modal"],
  thud: ["gnat"],
  thus: ["gnat"],
  thy: ["hat", "tat"],
  ti: ["it"],
  tibia: ["vigil"],
  tidal: ["legit"],
  tie: ["art", "eel", "ail"],
  tier: ["dart", "jail"],
  tile: ["alit"],
  timer: ["jewel"],
  timid: ["pewit"],
  tin: ["net", "nit", "nil"],
  tinny: ["twit"],
  tiny: ["hurt", "hurl"],
  tire: ["edit"],
  tit: ["let", "tit", "lit"],
  titled: ["pallet", "pellet"],
  toad: ["peel"],
  toast: ["level"],
  toe: ["eel"],
  toed: ["peel"],
  toil: ["trot"],
  told: ["plot"],
  tom: ["wet"],
  ton: ["net", "not"],
  tonal: ["tenet"],
  too: ["eel"],
  tool: ["loot", "toot", "tool"],
  toot: ["toot", "loot", "tool"],
  top: ["dot"],
  tor: ["jet", "jot", "dot"],
  tot: ["let", "tot", "lot"],
  tow: ["met", "mot"],
  towel: ["jennet"],
  tower: ["jennet"],
  toy: ["hot", "tot"],
  tsar: ["jest"],
  tuba: ["vent"],
  tuna: ["hunt"],
  tune: ["aunt"],
  tuner: ["jaunt", "daunt"],
  u: ["n"],
  uh: ["an"],
  us: ["en"],
  usable: ["eleven"],
  used: ["peen"],
  w: ["m"],
  wad: ["gem"],
  wail: ["teem"],
  wait: ["teem"],
  was: ["gem"],
  wasp: ["deem"],
  wast: ["teem"],
  wax: ["ohm"],
  way: ["hem"],
  ways: ["stem"],
  we: ["am", "em"],
  weal: ["team", "teem", "them"],
  wear: ["deem"],
  web: ["gem"],
  wed: ["gem"],
  weep: ["deem"],
  weir: ["dram", "deem"],
  west: ["team", "teem"],
  wet: ["tam", "lam"],
  wham: ["wham"],
  what: ["team"],
  whet: ["team"],
  whey: ["team"],
  whip: ["dram"],
  whir: ["dram"],
  whit: ["tram", "team"],
  who: ["ohm"],
  why: ["ham", "tam"],
  wisp: ["deem"],
  wist: ["term", "teem"],
  wits: ["stem", "slim"],
  woes: ["seem"],
  wood: ["poem"],
  wool: ["teem", "loom"],
  wow: ["mom"],
  x: ["x", "o"],
  xi: ["ex"],
  y: ["h", "t"],
  ya: ["eh"],
  yam: ["wet"],
  yaw: ["met"],
  ye: ["ah", "eh", "at"],
  yea: ["hah", "eat", "vat", "hat", "vet"],
  yeah: ["yeah", "heat"],
  yen: ["net"],
  yes: ["eat", "sat", "get", "set"],
  yet: ["tat", "let"],
  yew: ["mat", "met"],
  yield: ["plait"],
  yin: ["net", "nit"],
  yipe: ["edit"],
  yo: ["eh", "oh"],
  yon: ["net", "not"],
  you: ["net", "not"],
  yow: ["met", "mot"],
  z: ["z"],
  zeal: ["jeez"],
  "": [""],
};

export default data;
