#!/usr/bin/env python3
"""
build_adj_attrs.py
------------------
Build data/adj-attrs.json — the map that makes adjective potions MEANING-DRIVEN.

Inklings' adjectives brew potions. Instead of a random potion, each adjective should brew the potion
matching its meaning, arranged as WordNet "dumbbells": an ATTRIBUTE (speed/size/light) with two poles —
a self-buff pole you DRINK and an antonym pole you THROW at enemies. This script classifies dictionary
adjectives onto one of six poles and emits the compact runtime form the game needs:

  data/adj-attrs.json   { word: potionId }        potionId in {speed,slow,size,small,reveal,dark}

Runtime only needs word -> potionId (a plain map lookup, like verb-cats.json). The richer per-pole
dumbbell metadata (attribute noun, full similar-to lists) the Apothecary UI will want later
(grammar-systems.md §6/§8.2) is deferred — this file is the Step-1 self-buff-reslot form.

Classification (precision over recall — unmapped adjectives fall back to a random self-buff at runtime):
  - Each pole has a curated SEED list.
  - Expand each seed set by ONE hop over WordNet's "similar-to" (`sim`) edges, keeping only lemmas that
    are adjectives in the shipped dictionary. Seeds are never dropped; a word reachable from two DIFFERENT
    poles is ambiguous and dropped. No transitive walk (avoids sense drift like quick -> intelligent).
  - ON-ATTRIBUTE FILTER: word-level `sim` aggregates every sense, so "bright" links to intelligent/happy.
    Accept an expansion candidate only if it is on-attribute — it has no `attr` (a pure descriptive
    satellite like "twinkling"), or its `attr` intersects the pole's ATTRIBUTE anchor nouns. Off-attribute
    words carry their own unrelated `attr` (happy->happiness, intelligent->intelligence) and are dropped.

INPUTS  (already generated by build_dictionary.py — no NLTK needed here):
  data/dictionary.json         {word: {pos, def, syn}}
  data/wordnet-relations.json  {word: {sim, ant, attr, ...}}

USAGE
  python build_adj_attrs.py
"""

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "data")

# potionId -> curated seed adjectives. potionId is the in-game potion:
#   self-buff (DRINK): speed(=Swift), size(=Big), reveal(=Bright)   -- legacy ids, keep buff logic
#   antonym  (THROW):  slow,          small,      dark              -- new poles, thrown at enemies
POTIONS = {
    # --- Speed dumbbell ---
    "speed": ["fast", "quick", "rapid", "swift", "speedy", "brisk", "fleet", "nimble",
              "hasty", "snappy", "prompt", "expeditious", "agile", "spry", "breakneck", "quickened"],
    "slow":  ["slow", "sluggish", "lethargic", "leisurely", "laggard", "dilatory", "poky", "pokey",
              "torpid", "plodding", "tardy", "languid", "unhurried", "creeping"],
    # --- Size dumbbell ---
    "size":  ["big", "large", "huge", "great", "enormous", "gigantic", "massive", "immense",
              "vast", "giant", "colossal", "mammoth", "towering", "hulking", "jumbo", "sizable",
              "sizeable", "grand", "monumental"],
    "small": ["small", "little", "tiny", "miniature", "minuscule", "petite", "diminutive", "wee",
              "minute", "compact", "slight", "puny", "teeny", "dinky", "bantam", "undersized"],
    # --- Light dumbbell ---
    "reveal": ["bright", "luminous", "radiant", "brilliant", "gleaming", "shining", "glowing",
               "dazzling", "vivid", "sunny", "luminescent", "incandescent", "aglow", "lustrous",
               "resplendent", "shiny", "beaming"],
    "dark":   ["dark", "dim", "murky", "gloomy", "shadowy", "dusky", "tenebrous", "obscure",
               "dingy", "somber", "sombre", "shady", "darkened", "unlit", "lightless", "inky"],
}

# potionId -> the WordNet ATTRIBUTE nouns its dumbbell hangs from. An expansion candidate is kept only if
# it has no `attr` (a pure satellite) or its `attr` intersects this set (see ON-ATTRIBUTE FILTER above).
ATTR_NOUNS = {
    "speed":  {"speed", "swiftness", "fastness", "rate", "velocity", "pace"},
    "slow":   {"speed", "swiftness", "fastness", "rate", "velocity", "pace"},
    "size":   {"size", "bigness", "largeness", "magnitude", "dimension", "stature", "height", "bulk"},
    "small":  {"size", "bigness", "largeness", "magnitude", "dimension", "stature", "height", "bulk"},
    "reveal": {"light", "lightness", "luminosity", "brightness", "luminance", "luminousness",
               "value", "illumination"},
    "dark":   {"light", "lightness", "luminosity", "brightness", "luminance", "luminousness",
               "value", "illumination"},
}


def load(name):
    with open(os.path.join(DATA, name), encoding="utf-8") as f:
        return json.load(f)


def main():
    dictionary = load("dictionary.json")
    rels = load("wordnet-relations.json")

    def is_adj(w):
        e = dictionary.get(w)
        return bool(e) and "adjective" in (e.get("pos") or [])

    def on_attribute(word, pid):
        """A candidate is on-attribute if it has no `attr` (pure satellite) or shares one with the pole."""
        attrs = set((rels.get(word, {}) or {}).get("attr", []) or [])
        return (not attrs) or bool(attrs & ATTR_NOUNS[pid])

    # word -> potionId, and word -> set of poles that claimed it (to detect ambiguity)
    assigned = {}
    claims = {}

    def claim(word, pid):
        claims.setdefault(word, set()).add(pid)

    # 1) Seeds win outright (curated, trusted). Only keep seeds actually in the dictionary as adjectives.
    for pid, seeds in POTIONS.items():
        for s in seeds:
            if is_adj(s):
                assigned[s] = pid
                claim(s, pid)

    # 2) One hop of `sim` from each seed. Collect candidates per pole first, then resolve conflicts.
    expand = {}  # word -> set of poles reached via expansion
    for pid, seeds in POTIONS.items():
        for s in seeds:
            for nb in (rels.get(s, {}) or {}).get("sim", []) or []:
                if nb in assigned:            # already a seed -> keep seed's pole
                    continue
                if not is_adj(nb):
                    continue
                if not on_attribute(nb, pid):  # sense drift (bright->happy/intelligent) -> reject
                    continue
                expand.setdefault(nb, set()).add(pid)

    added = 0
    for word, poles in expand.items():
        if len(poles) == 1:                   # unambiguous -> assign
            assigned[word] = next(iter(poles))
            added += 1
        # ambiguous (reachable from >1 pole) -> drop; runtime falls back to random self-buff

    out = dict(sorted(assigned.items()))
    with open(os.path.join(DATA, "adj-attrs.json"), "w", encoding="utf-8") as f:
        json.dump(out, f, ensure_ascii=False, separators=(",", ":"), sort_keys=True)

    # Report
    counts = {}
    for pid in out.values():
        counts[pid] = counts.get(pid, 0) + 1
    total_adj = sum(1 for w in dictionary if is_adj(w))
    print(f"adj-attrs.json: {len(out)} adjectives mapped "
          f"({100*len(out)/max(1,total_adj):.1f}% of {total_adj} dictionary adjectives)")
    for pid in ("speed", "slow", "size", "small", "reveal", "dark"):
        print(f"  {pid:6s}: {counts.get(pid,0)}")
    print(f"  (+{added} added via 1-hop similar-to; ambiguous drops excluded)")


if __name__ == "__main__":
    main()
