const data = {
  o: ["e", "o"],
  oases: ["seseo"],
  oasis: ["seseo", "siseo"],
  oat: ["leo"],
  oath: ["ateo"],
  obey: ["hogo"],
  obi: ["ego", "reo"],
  obit: ["lego", "treo"],
  oblate: ["aleteo"],
  ode: ["epo", "ego"],
  odor: ["jopo", "dogo", "jopé"],
  oh: ["ye", "he", "yo"],
  oil: ["leo", "lío", "tío"],
  oiled: [
    "potro",
    "gáleo",
    "poleo",
    "pateo",
    "goteo",
    "palio",
    "galio",
    "polio",
    "patio",
  ],
  old: ["ple"],
  ole: [
    "aje",
    "eje",
    "ale",
    "ele",
    "ole",
    "ate",
    "ajo",
    "ojo",
    "oto",
    "olé",
    "ajó",
  ],
  on: ["ne", "no", "ño"],
  one: ["ene", "eñe", "ano", "año"],
  oodles: ["golpeo"],
  ooze: ["ázoe"],
  opal: ["ledo"],
  open: ["nado", "nodo"],
  opener: ["donado", "dañado"],
  operate: ["alejado"],
  opiate: ["olvido"],
  opus: ["ende"],
  or: ["je", "de", "jo", "do"],
  oral: ["tejo", "ledo"],
  orate: ["ateje", "alejo"],
  orb: ["eje"],
  ore: ["aje", "eje", "ajo", "ojo", "ajó"],
  oriel: ["tarde", "lardo", "tardo", "lerdo", "tordo", "laido", "leído"],
  osier: ["jorge", "dorso"],
  otiose: ["aserto"],
  otter: ["dalle", "dello"],
  oust: ["lene", "leñe", "leño"],
  ow: ["me"],
  owe: ["eme", "amo"],
  owlet: ["telmo", "tolmo"],
  owner: ["jaume"],
  oxen: ["nexo"],
  oyster: ["deleto"],
};

export default data;
