const data = {
  h: ["y", "h"],
  ha: ["eh", "ea", "ha"],
  habit: ["lieva"],
  had: ["pea", "gea"],
  hail: ["leva"],
  hair: ["drea", "diva"],
  haired: ["pedrea"],
  hale: ["ajea", "alea"],
  hap: ["dey", "dea"],
  hare: ["ajea"],
  has: ["gea", "eva"],
  hast: ["leva"],
  hat: ["ley", "tea"],
  hate: ["alea"],
  hated: ["galea", "gálea", "pelea", "polea"],
  hater: ["jalea"],
  hath: ["alea"],
  haw: ["mea"],
  hay: ["tea"],
  he: ["ay", "ah", "eh", "oh", "ea", "oa"],
  heir: ["diay", "drea"],
  hen: ["nea"],
  hep: ["dey", "doy", "dea"],
  her: ["dey", "doy", "jea", "dea"],
  here: ["ajea"],
  hew: ["mea", "moa"],
  hey: ["hoy", "tea", "toa"],
  hi: ["rh", "eh", "ea"],
  hiatus: ["entera"],
  hid: ["pea", "gea", "pía"],
  hide: ["apea"],
  hie: ["ara", "era", "ora"],
  hind: ["gura", "guía"],
  hint: ["tura"],
  hinter: ["datura"],
  hip: ["dey", "dea", "día"],
  hire: ["adra", "ajea"],
  his: ["era", "gea"],
  hiss: ["sera"],
  hist: ["lera"],
  hit: ["ley", "tea", "lía"],
  ho: ["eh", "oh", "ea", "oa"],
  hob: ["gea"],
  hod: ["pea", "gea", "poa"],
  hole: ["ajea", "alea"],
  holey: ["tajea", "tálea"],
  hon: ["nea"],
  hone: ["anea", "enea", "anoa"],
  hop: ["dey", "doy", "dea"],
  hot: ["ley", "tea", "toa", "loa"],
  hotel: ["jalea", "tálea"],
  how: ["mea", "moa"],
  hubris: ["sedeña"],
  hue: ["ana", "ona", "aña"],
  hued: ["pana", "gana", "pena", "peña"],
  huh: ["ana", "aña"],
  hunt: ["tuna", "luna"],
  hush: ["asna"],
  hushed: ["gehena"],
};

export default data;
