const data = {
  s: ["e", "g", "s"],
  sable: ["aleve"],
  sahib: ["grave"],
  said: ["gres"],
  sail: ["leve", "tres"],
  saith: ["aleve"],
  sales: ["salve", "galés", "goles"],
  salon: ["neles"],
  sand: ["pues"],
  sap: ["des"],
  sat: ["les"],
  satin: ["neles"],
  saw: ["mes"],
  sea: ["vos"],
  send: ["pues"],
  senor: ["jonás"],
  sent: ["lúes"],
  set: ["tas", "las", "les", "tos", "los"],
  sew: ["mas", "más", "mes"],
  sewer: ["jamás", "demás"],
  sh: ["ye", "he", "as"],
  shah: ["yeyé"],
  shale: ["aleas"],
  she: ["ahé"],
  shed: ["payé"],
  shh: ["ahé"],
  shit: ["tras"],
  shy: ["tas"],
  side: ["agre"],
  sided: ["popés"],
  sidle: ["alpes"],
  silo: ["otre"],
  sine: ["anís"],
  sinew: ["maure", "manes", "menés", "monís"],
  sip: ["des"],
  sir: ["des"],
  sire: ["odre"],
  siren: ["nadie"],
  sis: ["ere", "erg", "ses", "gis"],
  sisal: ["tesis"],
  sissy: ["tesis"],
  sit: ["les", "lis"],
  site: ["otre"],
  sixth: ["aloes"],
  slap: ["deje", "dele"],
  slat: ["tele", "tete"],
  slate: ["ateje"],
  slaw: ["melé"],
  slay: ["tele", "tete"],
  sled: ["paje", "gaje", "peje", "pate", "pote", "palé", "paté"],
  slew: ["maje", "moje", "mole", "mate", "mote", "melé"],
  slid: ["peje", "pije", "pite"],
  slip: ["deje", "dije", "dele"],
  slit: ["tele", "tile", "tete", "lite"],
  slop: ["deje", "dele", "dote"],
  slosh: ["agote"],
  slot: ["tele", "tole", "tete", "tote", "lote"],
  sloth: ["ateje", "atole"],
  slow: ["moje", "mole", "mote", "melé"],
  slue: ["ante", "ente"],
  slush: ["yente"],
  snit: ["true", "lene", "leñe"],
  snob: ["gong"],
  snot: ["lene", "leñe"],
  snow: ["mene"],
  so: ["os"],
  sod: ["pos"],
  soil: ["tres"],
  sol: ["les", "los", "tos"],
  sole: ["áloe"],
  son: ["nos", "noé"],
  sooth: ["aloes"],
  sop: ["des", "dos"],
  sot: ["les", "tos", "los"],
  sow: ["mes"],
  soy: ["tos"],
  spewer: ["demodé"],
  spiel: ["tarde"],
  split: ["tilde"],
  stale: ["ajete", "ojete"],
  star: ["dele"],
  stare: ["ajete", "ojete"],
  starer: ["dedeté"],
  stat: ["tete", "tele"],
  stay: ["tete", "tele"],
  step: ["dote", "dele"],
  stet: ["tate", "tete", "tote", "lote", "tele", "tole"],
  stew: ["mate", "mote", "mole", "melé"],
  stile: ["ajete", "ojete", "élite"],
  stilted: ["pallete", "gallete", "gollete"],
  stint: ["lurte"],
  stir: ["dele"],
  stole: ["ajete", "ojete", "ajote", "ejote", "elote", "olote", "atole"],
  stolid: [
    "pelete",
    "pijote",
    "pelote",
    "pilote",
    "pitote",
    "pelele",
    "pítele",
  ],
  stoned: ["gonete", "pañete", "gañote"],
  stop: ["dote", "dele"],
  store: ["ajete", "ojete", "ajote", "ejote"],
  stow: ["mote", "mole", "melé"],
  stub: ["ente"],
  stubble: ["algente"],
  sub: ["ene", "eñe"],
  sue: ["ene", "eñe", "ong"],
  suet: ["lene", "leñe"],
  suit: ["lene", "leñe"],
  swan: ["neme"],
  swat: ["leme"],
  sweat: ["teame"],
  sweet: ["teame"],
  swine: ["anime"],
  swipe: ["ademe"],
  swore: ["ademe"],
  synod: ["gente"],
};

export default data;
