const data = {
  j: ["l", "r"],
  jab: ["gel"],
  jaded: ["papel", "popel", "pagel"],
  jail: ["leer"],
  janitor: ["detener"],
  jar: ["dél", "del"],
  jato: ["éter", "oler"],
  jaunt: ["lunel", "túnel"],
  jawed: ["gomel", "gomer"],
  jay: ["her", "ter"],
  jean: ["uval"],
  jeans: ["eneal"],
  jeep: ["deal"],
  jeer: ["deal", "joel"],
  jell: ["llar"],
  jello: ["ollar"],
  jenny: ["tunal", "túnel", "tunar"],
  jest: ["leal", "leer"],
  jester: ["datear", "jetear", "jalear"],
  jet: ["tal", "tol", "lar", "ter"],
  jew: ["mal", "mol", "mar", "mor"],
  jewel: [
    "tamal",
    "jemal",
    "jamar",
    "temar",
    "tomar",
    "lamer",
    "jemer",
    "temer",
    "temor",
  ],
  jeweled: ["palomar"],
  jib: ["gel", "gil"],
  jibe: ["ágil"],
  jinn: ["unir", "uñir"],
  jinni: ["ruñir"],
  job: ["gel", "gol"],
  join: ["niel"],
  joiner: ["daniel"],
  jot: ["tol", "ter"],
  joust: ["tener", "tenor"],
  jouster: ["detener"],
  joy: ["tol", "her", "ter"],
};

export default data;
