const data = {
  e: ["e", "o"],
  ear: ["jea", "dea"],
  eared: ["pajea", "godeo"],
  earth: ["aldea"],
  ease: ["aseo", "óseo"],
  easel: ["tegeo", "leseo"],
  east: ["leva", "leve"],
  eat: ["tea", "leo"],
  eater: ["jalea", "jateo", "dateo", "jaleo"],
  ebb: ["gea", "ego", "geo"],
  ebony: ["huego"],
  ed: ["pe", "ge"],
  edit: ["tipa", "lipa", "lega", "liga", "tepe", "lepe", "tipo", "lego"],
  eel: ["jea", "tea", "loa", "toa", "tao", "leo"],
  eerie: ["árdea"],
  eh: ["ya", "ha", "ye", "he", "yo"],
  eider: ["depre", "dogre", "jopeo"],
  elan: ["neja", "nejo", "neto"],
  eland: ["gueto"],
  elate: ["aleja", "aleta", "ateje", "alejo", "alelo", "aleto", "eleto"],
  elated: [
    "pelela",
    "pateta",
    "paleta",
    "goleta",
    "pelele",
    "pelete",
    "gotelé",
    "paletó",
    "paleto",
  ],
  elite: [
    "aleja",
    "atila",
    "aleta",
    "ateje",
    "élite",
    "alejo",
    "alijo",
    "alelo",
    "etilo",
    "aleto",
    "eleto",
  ],
  ell: ["lle"],
  elope: ["adela"],
  else: ["aeta", "asta", "osta", "este", "oste"],
  en: ["na", "ña", "ne", "no", "ño"],
  end: ["gua", "púa"],
  enjoy: ["terna", "torna", "terne", "terno", "horno", "torno"],
  eon: ["nea", "noé", "neo"],
  epee: ["aeda", "aedo"],
  era: ["eje"],
  ere: ["aja", "oda", "ajá", "aje", "eje", "ajó", "ajo", "ojo"],
  erode: ["epoda", "apodo", "ápodo", "epodo"],
  erst: ["teja", "leja", "teda", "tejo", "ledo"],
  essay: ["tegeo"],
  estate: ["aleteo"],
  ester: ["jalea", "delga", "jateo", "dateo", "jaleo", "dalgo"],
  eta: ["eta", "ele"],
  ewe: ["ama", "anna", "eme", "amo"],
  ewer: ["jama", "dama", "doma", "jeme", "demo", "domo"],
  ex: ["oa"],
  eye: ["eta", "ate", "ahé", "ahó", "oto"],
  eyed: [
    "pata",
    "gata",
    "geta",
    "pota",
    "gota",
    "pate",
    "pote",
    "paté",
    "pato",
    "gato",
    "peto",
    "poto",
  ],
  eyelet: ["teleta", "talete", "tolete", "lejote"],
  eyelid: [
    "pileta",
    "pijota",
    "pelota",
    "petate",
    "pelete",
    "pijote",
    "pelote",
    "pilote",
    "pitote",
    "peloto",
    "piloto",
  ],
};

export default data;
