const data = {
  a: ["e", "v", "h"],
  ad: ["pe", "ge", "ph"],
  adieu: ["naipe"],
  ah: ["ye", "he", "ah"],
  aid: ["pre", "pie"],
  aide: ["agre"],
  ail: ["lev"],
  ajar: ["dele"],
  alas: ["seje", "sete"],
  alb: ["eje", "ele"],
  ale: ["aje", "eje", "ale", "ele", "ate"],
  alit: ["tele", "tile", "tete", "lite"],
  all: ["lle"],
  alleluia: ["ventalle"],
  alley: ["talle"],
  allow: ["molle"],
  also: ["este", "oste"],
  alter: ["dalle"],
  alto: ["elle"],
  an: ["ne", "uh"],
  anal: ["lene"],
  anew: ["mene"],
  annoy: ["tenue"],
  anon: ["nene"],
  are: ["aje", "eje"],
  area: ["vade"],
  arena: ["huaje"],
  aria: ["vide"],
  arid: ["peje", "pije"],
  as: ["ge", "se", "eh"],
  aside: ["apese"],
  ass: ["ese"],
  at: ["te", "le"],
  ate: ["ate", "ale", "ele"],
  atop: ["dote", "dele"],
  attend: ["guelte"],
  aw: ["me"],
  aware: ["ademe"],
  awe: ["eme"],
  ax: ["oh"],
  aye: ["ate"],
  b: ["q", "g", "e"],
  bah: ["ave"],
  bail: ["leve"],
  bait: ["leve"],
  ban: ["uve"],
  basil: ["lieve"],
  basin: ["nieve"],
  bast: ["leve"],
  baste: ["aleve"],
  baths: ["salve"],
  bed: ["gag"],
  bi: ["re"],
  bib: ["erg", "ere"],
  bid: ["pre", "pie"],
  bide: ["agre"],
  billed: ["peltre"],
  bio: ["erg", "ere"],
  biped: ["padre"],
  blare: ["ajete"],
  bled: ["paje", "gaje", "peje", "pate"],
  bleed: ["peaje"],
  blend: ["guaje", "guate"],
  blew: ["maje", "mate"],
  blip: ["deje", "dije", "dele"],
  blister: ["deleite"],
  bloated: ["galeote"],
  blot: ["tele", "tole", "tete", "tote", "lote"],
  blow: ["moje", "mole", "mote"],
  blower: ["jamete"],
  blue: ["ante", "ente"],
  bluenose: ["asonante"],
  blues: ["gante", "gente"],
  bluet: ["lente"],
  bluish: ["agente"],
  blush: ["yente"],
  bluster: ["detente"],
  bra: ["eje"],
  brad: ["peje"],
  bread: ["peaje"],
  bred: ["paje", "gaje", "peje"],
  breed: ["peaje"],
  brew: ["maje"],
  bro: ["eje"],
  broil: ["troje"],
  broth: ["ateje"],
  brow: ["moje"],
  bruit: ["linde"],
  bub: ["ene"],
  bus: ["ene"],
  buss: ["sene"],
  bust: ["lene"],
  by: ["he", "te"],
  bye: ["ate"],
  d: ["p", "g"],
  deb: ["gap", "gag"],
  die: ["erg"],
  dis: ["erg"],
  dot: ["top"],
  dowse: ["esmog"],
  duo: ["ong"],
  e: ["e"],
  ear: ["jea", "dea"],
  eared: ["pajea"],
  earth: ["aldea"],
  east: ["leva", "leve"],
  eat: ["tea"],
  eater: ["jalea"],
  ebb: ["gea"],
  ed: ["pe", "ge"],
  edit: ["tipa", "lipa", "lega", "liga", "tepe", "lepe"],
  eel: ["jea", "tea"],
  eh: ["ya", "ha", "ye", "he"],
  eider: ["depre"],
  elan: ["neja"],
  elate: ["aleja", "aleta", "ateje"],
  elated: ["pelela", "pateta", "paleta", "pelele", "pelete"],
  elite: ["aleja", "atila", "aleta", "ateje"],
  ell: ["lle"],
  elope: ["adela"],
  else: ["aeta", "asta", "este"],
  en: ["na", "ne"],
  end: ["gua"],
  enjoy: ["terna", "torna", "terne"],
  eon: ["nea"],
  epee: ["aeda"],
  era: ["eje"],
  ere: ["aja", "aje", "eje"],
  erode: ["epoda"],
  erst: ["teja", "leja", "teda"],
  ester: ["jalea", "delga"],
  eta: ["eta", "ele"],
  ewe: ["ama", "anna", "eme"],
  ewer: ["jama", "dama", "jeme"],
  ex: ["oa"],
  eye: ["eta", "ate"],
  eyed: ["pata", "gata", "geta", "pate"],
  eyelet: ["teleta", "talete"],
  eyelid: ["pileta", "petate", "pelete"],
  h: ["y", "h"],
  ha: ["eh", "ea", "ha"],
  habit: ["lieva"],
  had: ["pea", "gea"],
  hail: ["leva"],
  hair: ["drea", "diva"],
  haired: ["pedrea"],
  hale: ["ajea", "alea"],
  hap: ["dey", "dea"],
  hare: ["ajea"],
  has: ["gea", "eva"],
  hast: ["leva"],
  hat: ["ley", "tea"],
  hate: ["alea"],
  hated: ["galea", "pelea"],
  hater: ["jalea"],
  hath: ["alea"],
  haw: ["mea"],
  hay: ["tea"],
  he: ["ay", "ah", "eh", "ea"],
  heir: ["diay", "drea"],
  hen: ["nea"],
  hep: ["dey", "dea"],
  her: ["dey", "jea", "dea"],
  here: ["ajea"],
  hew: ["mea"],
  hey: ["tea"],
  hi: ["rh", "eh", "ea"],
  hiatus: ["entera"],
  hid: ["pea", "gea"],
  hide: ["apea"],
  hie: ["ara", "era"],
  hind: ["gura"],
  hint: ["tura"],
  hinter: ["datura"],
  hip: ["dey", "dea"],
  hire: ["adra", "ajea"],
  his: ["era", "gea"],
  hiss: ["sera"],
  hist: ["lera"],
  hit: ["ley", "tea"],
  ho: ["eh", "oh", "ea", "oa"],
  hob: ["gea"],
  hod: ["pea", "gea", "poa"],
  hole: ["ajea", "alea"],
  holey: ["tajea"],
  hon: ["nea"],
  hone: ["anea", "enea", "anoa"],
  hop: ["dey", "doy", "dea"],
  hot: ["ley", "tea", "toa", "loa"],
  hotel: ["jalea"],
  how: ["mea", "moa"],
  hue: ["ana"],
  hued: ["pana", "gana", "pena"],
  huh: ["ana"],
  hunt: ["tuna", "luna"],
  hush: ["asna"],
  hushed: ["gehena"],
  i: ["r", "e", "i"],
  ibis: ["seer"],
  id: ["pe", "ge", "pi"],
  ides: ["sepe"],
  idiot: ["torpe"], //clumsy
  idol: ["lepe", "tepe", "tope"],
  ilea: ["vale", "hale", "vate"],
  ill: ["lle"],
  in: ["ne", "ni"],
  indite: ["aligui"],
  inset: ["legui"],
  irate: ["ateje"],
  ire: ["aje", "eje"],
  iris: ["seje", "sede"],
  is: ["ge", "se", "si"],
  islet: ["tejer"],
  it: ["te", "le", "ti"],
  its: ["ele"],
  j: ["l", "r"],
  jab: ["gel"],
  jaded: ["papel", "pagel"],
  jail: ["leer"],
  janitor: ["detener"],
  jar: ["del"],
  jato: ["oler"], //jet assisted take-off
  jaunt: ["lunel"], //short excursion for pleasure
  jay: ["her", "ter"],
  jean: ["uval"],
  jeans: ["eneal"],
  jeep: ["deal"],
  jeer: ["deal"], //deal doesn't seem to be a spanish word
  jell: ["llar"],
  jello: ["ollar"],
  jenny: ["tunal", "tunar"],
  jest: ["leal", "leer"],
  jester: ["datear", "jetear", "jalear"], //jetear to show off,jalear to cheer
  jet: ["tal", "lar", "ter"],
  jew: ["mal", "mar"],
  jewel: ["tamal", "jemal", "jamar", "temar", "lamer", "jemer", "temer"],
  jib: ["gel", "gil"],
  jinn: ["unir"],
  job: ["gel", "gol"],
  join: ["niel"],
  joiner: ["daniel"],
  jot: ["tol", "ter"],
  joust: ["tener", "tenor"],
  jouster: ["detener"],
  joy: ["tol", "her", "ter"],
  l: ["j", "l", "t"],
  la: ["el", "et"],
  lab: ["gel"],
  lad: ["gel"],
  laid: ["piel"],
  lain: ["niel"],
  lap: ["del"],
  lea: ["val"],
  lead: ["peal"],
  lean: ["uval"],
  leap: ["deal"],
  led: ["pal", "gal", "gel"],
  leer: ["deal"],
  leper: ["dedal"],
  lest: ["leal"],
  let: ["tal"],
  lib: ["gel", "gil"],
  lid: ["gel", "gil"],
  lined: ["panel"],
  lines: ["senil"],
  lip: ["dij", "del"],
  lira: ["edil"],
  lire: ["edil"],
  lo: ["el", "et"],
  lob: ["gel", "gol"],
  lobed: ["pagel"],
  loin: ["niel"],
  lop: ["del"],
  lot: ["tol"],
  loth: ["atol"],
  low: ["mol"],
  m: ["w"],
  n: ["u", "n"],
  nab: ["gen"],
  nail: ["tren"],
  nay: ["ten"],
  net: ["tau", "tan", "ten", "len"],
  new: ["man"],
  nib: ["gen", "gin"],
  nil: ["len", "ten"],
  nip: ["diu", "din"],
  nit: ["ten", "len"],
  no: ["en"],
  nod: ["gen", "pon"],
  nor: ["don"],
  not: ["ten", "len", "ton"],
  o: ["e", "o"],
  oases: ["seseo"],
  oasis: ["seseo", "siseo"],
  oat: ["leo"],
  oath: ["ateo"],
  obi: ["ego", "reo"],
  obit: ["lego", "treo"],
  oblate: ["aleteo"],
  ode: ["epo", "ego"],
  odor: ["jopo", "dogo"],
  oh: ["ye", "he", "yo"],
  oil: ["leo"],
  oiled: ["pateo", "palio", "galio", "patio"],
  old: ["ple"],
  ole: ["aje", "eje", "eje", "ele", "ate", "ajo"], //eje = axis, ajo = garlic
  on: ["ne", "no"],
  one: ["ene", "ano"],
  opal: ["ledo"],
  open: ["nado"],
  operate: ["alejado"],
  opus: ["ende"],
  or: ["je", "de", "jo", "do"],
  oral: ["tejo", "ledo"],
  orate: ["ateje", "alejo"],
  orb: ["eje"],
  ore: ["aje", "eje", "ajo"],
  oriel: ["tarde", "lardo", "tardo", "lerdo", "laido"],
  otiose: ["aserto"], //serving no practical purpose
  otter: ["dalle", "dello"],
  oust: ["lene"], //soft smooth mil gentle
  ow: ["me"],
  owe: ["eme", "amo"],
  owlet: ["telmo"],
  owner: ["jaume"],
  oxen: ["nexo"],
  oyster: ["deleto"],
  p: ["d"],
  pal: ["led"],
  pap: ["dvd"],
  par: ["dvd"],
  pat: ["led"],
  perinea: ["vanidad"],
  pet: ["led"],
  phi: ["rad"],
  pis: ["sed"],
  pit: ["led", "lid"],
  pithy: ["taled"],
  poi: ["red"],
  pol: ["led"],
  pot: ["led"],
  psi: ["red"],
  q: ["b"],
  r: ["j", "d"],
  rap: ["dvd"],
  rat: ["led"],
  re: ["aj", "ad"],
  repaid: ["piedad"],
  riot: ["lord"],
  rip: ["dij"],
  roil: ["troj"],
  rot: ["led"],
  s: ["e", "g", "s"],
  sable: ["aleve"],
  sahib: ["grave"],
  said: ["gres"],
  sail: ["leve", "tres"],
  saith: ["aleve"],
  sales: ["salve"],
  salon: ["neles"],
  sand: ["pues"],
  sap: ["des"],
  sat: ["les"],
  satin: ["neles"],
  saw: ["mes"],
  send: ["pues"],
  set: ["tas", "las", "les"],
  sew: ["mas", "mes"],
  sh: ["ye", "he", "as"],
  shale: ["aleas"],
  shit: ["tras"],
  shy: ["tas"],
  side: ["agre"],
  sidle: ["alpes"],
  silo: ["otre"],
  sinew: ["maure", "manes"],
  sip: ["des"],
  sir: ["des"],
  siren: ["nadie"],
  sis: ["ere", "erg", "ses", "gis"],
  sisal: ["tesis"],
  sissy: ["tesis"],
  sit: ["les", "lis"],
  sixth: ["aloes"],
  slap: ["deje", "dele"],
  slat: ["tele", "tete"],
  slate: ["ateje"],
  slay: ["tele", "tete"],
  sled: ["paje", "gaje", "peje", "pate"],
  slew: ["maje", "mate"],
  slid: ["peje", "pije", "pite"],
  slip: ["deje", "dije", "dele"],
  slit: ["tele", "tile", "tete", "lite"],
  slop: ["deje", "dele", "dote"],
  slosh: ["agote"],
  slot: ["tele", "tole", "tete", "tote", "lote"],
  sloth: ["ateje", "atole"],
  slow: ["moje", "mole", "mote"],
  slue: ["ante", "ente"],
  slush: ["yente"],
  snit: ["true", "lene"],
  snob: ["gong"],
  snot: ["lene"],
  snow: ["mene"],
  so: ["os"],
  sod: ["pos"],
  soil: ["tres"],
  sol: ["les", "los", "tos"],
  son: ["nos"],
  sooth: ["aloes"],
  sop: ["des", "dos"],
  sot: ["les", "tos", "los"],
  sow: ["mes"],
  soy: ["tos"],
  spiel: ["tarde"],
  split: ["tilde"],
  stale: ["ajete"],
  star: ["dele"],
  stare: ["ajete"],
  stat: ["tete", "tele"],
  stay: ["tete", "tele"],
  step: ["dele"],
  stet: ["tate", "tete", "tele"],
  stew: ["mate"],
  stile: ["ajete"],
  stilted: ["pallete", "gallete"],
  stint: ["lurte"],
  stir: ["dele"],
  stole: ["ajete", "ajote", "ejote", "elote", "atole"],
  stolid: ["pelete", "pijote", "pelote", "pilote", "pitote", "pelele"],
  stop: ["dote", "dele"], //dowry
  store: ["ajete", "ajote", "ejote"],
  stow: ["mote", "mole"],
  stub: ["ente"],
  stubble: ["algente"],
  sub: ["ene"],
  sue: ["ene"],
  suet: ["lene"],
  suit: ["lene"],
  swan: ["neme"],
  swat: ["leme"], //not a word
  sweat: ["teame"],
  sweet: ["teame"],
  swine: ["anime"],
  swipe: ["ademe"],
  swore: ["ademe"],
  synod: ["gente"],
  t: ["t", "l"],
  tab: ["gel"],
  tad: ["gel"],
  tailed: ["petrel"],
  tap: ["del"],
  tar: ["jet", "del"],
  tarsi: ["redel"],
  taunt: ["lunel"],
  taxi: ["roel"],
  tea: ["val"],
  teal: ["leal"],
  tear: ["deal"],
  teat: ["leal"],
  teens: ["eneal"],
  tense: ["asnal"],
  tepid: ["pedal"],
  test: ["leal"],
  than: ["uval"],
  thane: ["eneal"],
  that: ["leal"],
  thin: ["nial"],
  thine: ["eneal"],
  this: ["eral"],
  threw: ["majal"],
  throw: ["modal"], //modal verbs
  thrust: ["tendal"],//rooflike cover
  thy: ["tal"],
  ti: ["et", "el"],
  tip: ["del"],
  tire: ["edil"],
  tired: ["pajel", "pajil"],
  to: ["et", "el"],
  toil: ["trol"],
  tole: ["atol"],
  tool: ["joel"],
  top: ["del"],
  tor: ["jet", "del"],
  torsi: ["redel", "redol"],
  tot: ["tol"],
  tote: ["atol"],
  tow: ["mol"],
  toy: ["tol"],
  tut: ["tnt"],
  u: ["n"],
  unit: ["trun"],
  us: ["en"],
  w: ["m"],
  wale: ["ejem"],
  ware: ["ejem"],
  wax: ["ohm"],
  we: ["am"],
  were: ["ejem"],
  who: ["ohm"],
  wild: ["plim"],
  wile: ["ejem", "alim"],
  wire: ["ejem"],
  with: ["alim"],
  wore: ["ejem"],
  x: ["x", "o"],
  xi: ["ex", "ro"],
  y: ["h", "t"],
  ya: ["eh", "et"],
  ye: ["ah", "eh", "et"],
  yes: ["sah", "set"],
  yo: ["eh", "oh", "et"],
  z: ["z"],
  zed: ["paz", "pez"],
  zit: ["tez"],
};

export default data;
