const data = {
  b: ["q", "g", "e"],
  bah: ["ave"],
  bail: ["leve"],
  bait: ["leve"],
  ban: ["uve"],
  basil: ["lieve"],
  basin: ["nieve"],
  bast: ["leve"],
  baste: ["aleve"],
  baths: ["salve"],
  bed: ["gag"],
  bi: ["re"],
  bib: ["erg", "ere"],
  bid: ["pre", "pie"],
  bide: ["agre"],
  bile: ["otre"],
  billed: ["peltre"],
  bio: ["erg", "ere"],
  biped: ["padre", "podre"],
  bite: ["otre"],
  blare: ["ajete", "ojete"],
  bled: ["paje", "gaje", "peje", "pate", "pote"],
  bleed: ["peaje"],
  blend: ["guaje", "guate"],
  blew: ["maje", "moje", "mole", "mate", "mote"],
  blip: ["deje", "dije", "dele"],
  blister: ["deleite"],
  bloated: ["galeote"],
  blot: ["tele", "tole", "tete", "tote", "lote"],
  blow: ["moje", "mole", "mote"],
  blower: ["jamete"],
  blue: ["ante", "ente"],
  bluenose: ["asonante"],
  blues: ["gante", "gente"],
  bluet: ["lente"],
  bluish: ["agente"],
  blush: ["yente"],
  bluster: ["detente"],
  bole: ["áloe"],
  bra: ["eje"],
  brad: ["peje"],
  bread: ["peaje"],
  bred: ["paje", "gaje", "peje"],
  breed: ["peaje"],
  brew: ["maje", "moje"],
  bro: ["eje"],
  broil: ["troje"],
  broth: ["ateje"],
  brow: ["moje"],
  bruit: ["linde"],
  bub: ["ene", "eñe"],
  bus: ["ene", "eñe"],
  buss: ["sene"],
  bust: ["lene", "leñe"],
  by: ["he", "te"],
  bye: ["ate"],
};

export default data;
