const data = {
  a: ["e", "v", "h"],
  ad: ["pe", "ge", "ph"],
  adieu: ["naipe"],
  ah: ["ye", "he", "ah"],
  aid: ["pre", "pie"],
  aide: ["agre"],
  ail: ["lev"],
  ajar: ["dele"],
  alas: ["seje", "sete"],
  alb: ["eje", "ele"],
  ale: ["olé", "aje", "eje", "ale", "ele", "ole", "ate"],
  alien: ["norte"],
  alit: ["tele", "tile", "tete", "lite"],
  all: ["lle"],
  alleluia: ["ventalle"],
  alley: ["talle"],
  allow: ["molle"],
  also: ["este", "oste"],
  alter: ["dalle"],
  alto: ["elle"],
  an: ["ne", "uh"],
  anal: ["lene", "leñe"],
  anent: ["lueñe"],
  anew: ["mene"],
  annoy: ["tenue"],
  anon: ["nene"],
  ant: ["lúe"],
  are: ["aje", "eje"],
  area: ["vade"],
  arena: ["huaje"],
  aria: ["vide"],
  arid: ["peje", "pije"],
  as: ["ge", "se", "eh"],
  aside: ["apese"],
  ass: ["ese"],
  at: ["té", "te", "le"],
  ate: ["olé", "ate", "ale", "ele", "ole"],
  atop: ["dote", "dele"],
  attend: ["guelte"],
  aw: ["me"],
  aware: ["ademe"],
  awe: ["eme"],
  ax: ["oh"],
  axe: ["oxe"],
  axle: ["áloe"],
  aye: ["ahé", "ate"],
};

export default data;
