const data = {
  l: ["j", "l", "t"],
  la: ["él", "el", "et"],
  lab: ["gel"],
  lad: ["gel"],
  laid: ["piel"],
  lain: ["niel"],
  lap: ["dél", "del"],
  laser: ["dosel"],
  lea: ["val"],
  lead: ["peal"],
  lean: ["uval"],
  leap: ["deal"],
  led: ["pal", "gal", "gel", "gol"],
  leer: ["deal", "joel"],
  lei: ["rol"],
  leper: ["dedal"],
  lest: ["leal"],
  let: ["tal", "tol"],
  lib: ["gel", "gil"],
  lid: ["gel", "gil"],
  lie: ["oíl"],
  line: ["añil"],
  lined: ["panel", "pañil", "gañil"],
  linens: ["guañil"],
  lines: ["senil", "gañil"],
  lip: ["dij", "del", "dél"],
  lira: ["edil"],
  lire: ["edil"],
  liter: ["dátil"],
  lo: ["el", "él", "et"],
  lob: ["gel", "gol"],
  lobed: ["pagel"],
  loin: ["niel"],
  lop: ["del", "dél"],
  loser: ["dosel"],
  lot: ["tol"],
  loth: ["atol"],
  low: ["mol"],
};

export default data;
