const data = {
  a: ["o"],
  b: ["b"],
  baa: ["boo"],
  be: ["bi"],
  boa: ["bio"],
  bob: ["bib"],
  bub: ["bob"],
  bum: ["boy"],
  d: ["l"],
  dab: ["lob"],
  deb: ["lib"],
  does: ["lice"],
  dog: ["lie"],
  dub: ["lob"],
  e: ["c", "i"],
  g: ["e"],
  good: ["evil"],
  h: ["i"],
  hem: ["icy"],
  I: ["h"],
  i: ["h"],
  is: ["he"],
  ism: ["hey"],
  j: ["j"],
  jab: ["job"],
  jam: ["joy"],
  job: ["jib"],
  m: ["y", "u", "v"],
  ma: ["yo"],
  mead: ["viol"],
  mi: ["uh"],
  mu: ["yo"],
  mum: ["you"],
  O: ["i", "v"],
  o: ["i", "v"],
  odd: ["ill"],
  s: ["e"],
  u: ["o"],
  "": [""],
};

export default data;
