const data = {
  a: ["o", "i"],
  ad: ["id"],
  add: ["old", "odd", "oil", "ill"],
  an: ["om"],
  b: ["b", "i"],
  baa: ["boo", "bio"],
  bad: ["bod", "bid"],
  be: ["bi"],
  bed: ["bid"],
  beg: ["ice"],
  boa: ["bio"],
  bob: ["bib"],
  bod: ["bid"],
  bub: ["bob"],
  bud: ["bod"],
  buff: ["boss"],
  bum: ["boy"],
  d: ["l", "d", "i"],
  dab: ["lob", "lib"],
  dad: ["lid", "did"],
  dang: ["lime", "dome", "dime"],
  deb: ["lib"],
  def: ["dis"],
  den: ["dim"],
  does: ["lice", "dice"],
  dog: ["lie", "die"],
  domed: ["livid"],
  don: ["dim"],
  dona: ["limo"],
  dong: ["lime", "dime"],
  dub: ["lob"],
  duds: ["lode", "dole"],
  due: ["doc"],
  duff: ["loss"],
  dug: ["doe"],
  dung: ["dome"],
  e: ["c", "i"],
  ed: ["id"],
  f: ["s"],
  fa: ["so"],
  fad: ["sol", "sod"],
  fang: ["some"],
  fee: ["sic"],
  fig: ["she"],
  foe: ["sic"],
  g: ["e"],
  goad: ["evil"],
  good: ["evil"],
  h: ["i"],
  hem: ["icy"],
  I: ["h"],
  i: ["h"],
  id: ["hi"],
  ion: ["him"],
  is: ["he"],
  ism: ["hey"],
  j: ["j"],
  jab: ["job", "jib"],
  jam: ["joy"],
  job: ["jib"],
  m: ["y", "u", "v"],
  ma: ["yo"],
  mag: ["vie"],
  man: ["vim"],
  mead: ["viol"],
  men: ["vim"],
  mi: ["uh"],
  mu: ["yo"],
  mum: ["you"],
  n: ["m"],
  nab: ["mob"],
  no: ["mi"],
  nod: ["mil", "mid"],
  node: ["midi"],
  noes: ["mice"],
  nub: ["mob"],
  nun: ["mom"],
  O: ["i", "v"],
  o: ["i", "v"],
  odd: ["ill"],
  odds: ["idle", "vile"],
  of: ["is"],
  s: ["e"],
  u: ["o"],
  "": [""],
};

export default data;
