const data = {
  a: ["u", "a"],
  abs: ["awn"],
  ace: ["ant"],
  ache: ["unit"],
  acne: ["unit"],
  act: ["ant", "any"],
  actuator: ["anteater"],
  adze: ["aunt"],
  afar: ["afar"],
  affray: ["affray"],
  afoot: ["afoot"],
  aft: ["aft"],
  ammo: ["abbe"],
  an: ["us", "as"],
  anion: ["ashes"],
  aorta: ["aorta"],
  arc: ["urn"],
  are: ["urn", "arm", "art"],
  armor: ["arbor"],
  array: ["array"],
  arroyo: ["arroyo"],
  art: ["art"],
  arty: ["arty"],
  as: ["an"],
  ascot: ["annoy"],
  at: ["at"],
  attar: ["attar"],
  attune: ["attest"],
  ax: ["ax"],
  axon: ["axes"],
  b: ["w"],
  bait: ["want"],
  ban: ["was"],
  bane: ["wast", "wain", "wait"],
  bar: ["war"],
  bare: ["warn", "warm", "wart"],
  baron: ["wares"],
  base: ["want"],
  bast: ["want"],
  bat: ["way"],
  bate: ["watt"],
  bay: ["way"],
  bio: ["who"],
  bit: ["why"],
  boar: ["wear"],
  bob: ["wow"],
  bone: ["west"],
  boo: ["woo", "woe", "wee"],
  boon: ["woes"],
  boost: ["weeny"],
  boozy: ["weeny"],
  bore: ["worn", "worm", "wort"],
  borne: ["worst"],
  bow: ["woe", "wee"],
  brunt: ["wrest"],
  bum: ["web"],
  bunt: ["west"],
  bus: ["wen"],
  bust: ["went"],
  but: ["wet"],
  c: ["n"],
  cam: ["nub", "nab"],
  cart: ["nary"],
  cat: ["nut", "nay"],
  catty: ["nutty", "natty"],
  cay: ["nay"],
  chest: ["ninny"],
  chew: ["nine", "nite"],
  coat: ["neat"],
  cob: ["now", "new"],
  coco: ["none"],
  code: ["noun"],
  cone: ["nest"],
  cony: ["nosy"],
  coo: ["nee"],
  coon: ["noes"],
  core: ["norm"],
  cot: ["not", "net"],
  cow: ["nee"],
  cub: ["new"],
  cube: ["newt"],
  cue: ["net"],
  cunt: ["nest"],
  cut: ["net"],
  d: ["u"],
  demur: ["umber"],
  dent: ["unit"],
  dimwit: ["unbent"],
  dine: ["unit"],
  dint: ["unit"],
  e: ["n", "m", "t"],
  ear: ["mar", "tar"],
  earthen: ["martini"],
  east: ["many"],
  easy: ["many"],
  eat: ["nut", "nay", "mat", "may", "tut", "tat"],
  eaten: ["tutti"],
  ed: ["nu", "mu"],
  edict: ["tunny"],
  eh: ["mi", "ti"],
  eject: ["tunny"],
  en: ["mi", "ti"],
  erode: ["trout"],
  euro: ["mere"],
  ewe: ["net", "men", "met", "ten"],
  f: ["f"],
  fa: ["fa"],
  facet: ["funny", "fanny"],
  fade: ["faun"],
  fanny: ["fuzzy", "fussy"],
  far: ["fur", "far"],
  fare: ["farm", "fart"],
  faro: ["faro", "fare"],
  fart: ["fury", "fart"],
  fat: ["fat", "fay"],
  fatty: ["fatty"],
  fax: ["fax"],
  fay: ["fay"],
  fob: ["few"],
  foe: ["fen"],
  font: ["fest"],
  foot: ["foot", "feet"],
  for: ["for"],
  foray: ["foray"],
  fore: ["form", "fort", "fern"],
  fort: ["fort"],
  forty: ["forty"],
  fox: ["fox"],
  foxtrot: ["foxtrot"],
  foxy: ["foxy"],
  frat: ["frat", "fray"],
  fray: ["fray"],
  fro: ["fro"],
  front: ["frost"],
  frost: ["front"],
  froze: ["front"],
  fry: ["fry"],
  fun: ["fez"],
  furry: ["ferry"],
  h: ["i", "z"],
  hast: ["zany"],
  hazy: ["zany"],
  he: ["in", "it"],
  hen: ["its"],
  hi: ["in"],
  hie: ["inn"],
  his: ["inn"],
  hoe: ["ion"],
  hone: ["zest"],
  honey: ["zesty"],
  hunt: ["zest"],
  hut: ["icy"],
  I: ["h", "n"],
  i: ["h", "n"],
  id: ["nu"],
  idem: ["numb"],
  in: ["hi"],
  inn: ["his"],
  inset: ["ninny"],
  into: ["nite"],
  j: ["u"],
  m: ["b"],
  mace: ["bunt"],
  main: ["buns"],
  man: ["bus"],
  mane: ["bust", "bast", "bait"],
  many: ["busy"],
  mar: ["bur", "bar"],
  mare: ["burn", "barn"],
  mart: ["bury"],
  mast: ["bunt"],
  mat: ["but", "buy", "bat", "bay"],
  mate: ["butt"],
  matt: ["butt"],
  may: ["buy", "bay"],
  mayor: ["buyer"],
  maze: ["bunt"],
  moat: ["bout", "boat", "beat"],
  mob: ["bow"],
  mode: ["bout"],
  mom: ["bob"],
  mono: ["bozo"],
  moo: ["boo", "bee"],
  moor: ["boor", "beer"],
  moot: ["boot", "beet"],
  more: ["born", "berm"],
  most: ["bony", "bent"],
  mot: ["boy", "bet", "bey"],
  moue: ["been", "beet"],
  mow: ["bee"],
  mu: ["be"],
  muse: ["bent"],
  must: ["bent"],
  my: ["by"],
  n: ["z", "s", "i"],
  nab: ["saw"],
  nanny: ["sassy"],
  nay: ["say"],
  near: ["star"],
  neat: ["smut", "stat", "stay"],
  nee: ["inn"],
  net: ["sty"],
  newt: ["stet"],
  nine: ["shin", "shim", "shit", "snit"],
  ninety: ["shitty"],
  nit: ["shy"],
  nitwit: ["intent"],
  no: ["so"],
  noisy: ["sonny"],
  none: ["zest"],
  nose: ["sent"],
  nosey: ["sonny"],
  not: ["sot", "soy", "set"],
  now: ["see"],
  nub: ["sew"],
  nude: ["scum"],
  nut: ["set", "icy"],
  O: ["o", "e"],
  o: ["o", "e"],
  oaf: ["oaf"],
  oar: ["our", "oar", "ear"],
  oat: ["out", "oat", "eat"],
  obi: ["own"],
  ocean: ["ennui"],
  ode: ["out"],
  of: ["of"],
  off: ["off"],
  oft: ["oft"],
  or: ["or"],
  orator: ["orator"],
  oratory: ["oratory"],
  ox: ["ox", "ex"],
  r: ["r"],
  race: ["runt", "rant"],
  raft: ["raft"],
  rain: ["runs", "rani"],
  ram: ["rub"],
  rani: ["rush", "ruin", "rash", "rain"],
  rant: ["rust"],
  rash: ["rani"],
  rat: ["rut", "rat", "ray"],
  ratty: ["rutty", "ratty"],
  raw: ["rue"],
  ray: ["ray"],
  raze: ["runt", "rant"],
  rhino: ["rinse"],
  roar: ["roar", "rear"],
  rob: ["row"],
  rode: ["rout"],
  rodeo: ["route"],
  roe: ["rot", "rem"],
  roman: ["rebus"],
  roof: ["roof", "reef"],
  root: ["root"],
  rose: ["rent"],
  rot: ["rot"],
  rotary: ["rotary"],
  rotatory: ["rotatory"],
  rotor: ["rotor"],
  row: ["roe"],
  rue: ["rem"],
  rune: ["rest", "rein"],
  runs: ["rein"],
  runt: ["rest"],
  ruse: ["rent"],
  rust: ["rent"],
  s: ["n"],
  sac: ["nun"],
  sassy: ["nanny"],
  sat: ["nut", "nay"],
  say: ["nay"],
  she: ["nit"],
  sheet: ["ninny"],
  shew: ["nine", "nite"],
  so: ["no"],
  soar: ["near"],
  sob: ["now", "new"],
  sonny: ["noisy"],
  soon: ["noes"],
  sore: ["norm"],
  sot: ["not", "net"],
  sow: ["nee"],
  sown: ["noes"],
  sub: ["new"],
  sue: ["net"],
  swat: ["neat"],
  t: ["t", "y"],
  tab: ["yaw"],
  tacit: ["tunny"],
  taco: ["tune"],
  tad: ["tau"],
  taffy: ["taffy"],
  taint: ["tansy"],
  tam: ["tub", "tab"],
  tar: ["tar"],
  tare: ["turn", "tarn", "tart", "yurt", "yarn"],
  tarmac: ["turban"],
  taro: ["taro", "tare"],
  tarot: ["tarot"],
  tarry: ["tarry"],
  tart: ["tart", "yurt"],
  tartar: ["tartar"],
  tat: ["tut", "tat"],
  tattoo: ["tattoo"],
  taunt: ["tacit"],
  taut: ["tact"],
  tax: ["tux", "tax"],
  the: ["tin", "tit", "yin"],
  thee: ["tint"],
  thew: ["tine", "time"],
  they: ["tiny"],
  tho: ["tie"],
  thru: ["tire"],
  tine: ["thin"],
  tit: ["thy"],
  to: ["to", "yo", "ye"],
  toe: ["ton", "tom", "tot", "ten", "yon", "yen", "yet"],
  toffy: ["toffy"],
  ton: ["yes"],
  tone: ["test"],
  too: ["too", "toe", "tee"],
  toot: ["toot"],
  tor: ["tor"],
  tore: ["torn", "tort", "tern", "term"],
  tort: ["tort"],
  tot: ["tot", "toy", "yet"],
  tow: ["toe", "tee"],
  toy: ["toy"],
  tray: ["tray"],
  trot: ["trot", "troy", "trey"],
  trow: ["tree"],
  troy: ["troy", "trey"],
  try: ["try"],
  tub: ["yew"],
  tun: ["yes"],
  tune: ["test"],
  tut: ["yet"],
  twit: ["tent"],
  two: ["tee"],
  tyro: ["tyro"],
  u: ["c", "e"],
  unto: ["cite"],
  us: ["en"],
  w: ["e"],
  wane: ["east"],
  want: ["east", "easy"],
  war: ["ear"],
  ware: ["earn"],
  we: ["en", "em"],
  wed: ["emu"],
  went: ["emit"],
  woe: ["eon"],
  wort: ["eery"],
  x: ["x"],
  y: ["y"],
  ya: ["ya"],
  yo: ["yo", "ye"],
  yon: ["yes"],
  z: ["n"],
  zone: ["nest"],
  zoo: ["nee"],
  "": [""],
};

export default data;
