//BenumB

//m   B
//E   m
//D   u
//i   n
//u   e
//m   B
const data = {
  a: ["u", "j", "a"],
  ad: ["nu"],
  area: ["aura"],
  arm: ["era"],
  as: ["nu"],
  at: ["ya"],
  b: ["m"],
  baa: ["jam"],
  ban: ["sum"],
  bar: ["rum", "ram"],
  baron: ["serum"],
  bat: ["yum", "tam", "yam"],
  bay: ["yum", "yam"],
  be: ["um"],
  been: ["swum"],
  benumb: ["medium"],
  bet: ["yum"],
  bey: ["yum"],
  bio: ["ohm"],
  bob: ["mom"],
  bonsai: ["hansom"],
  boon: ["zoom", "seem"],
  boor: ["room"],
  boot: ["teem"],
  both: ["item"],
  bra: ["arm"],
  brae: ["warm"],
  brow: ["berm"],
  c: ["u"],
  cat: ["tau"],
  cot: ["you"],
  coy: ["you"],
  d: ["n"],
  dab: ["man"],
  dad: ["nun"],
  dame: ["wean"],
  dean: ["sawn"],
  den: ["sun"],
  dew: ["bun"],
  din: ["inn"],
  do: ["on", "en"],
  doe: ["won", "wen"],
  dome: ["ween"],
  don: ["son", "ion"],
  dot: ["ton", "yon", "ten", "yen"],
  dram: ["earn"],
  drat: ["turn", "tarn", "yarn"],
  draw: ["burn", "barn"],
  dray: ["yarn"],
  drew: ["burn"],
  drowse: ["unborn"],
  e: ["u", "w"],
  ear: ["raw"],
  eat: ["tau", "yaw"],
  ed: ["nu"],
  emit: ["thew"],
  emu: ["dew"],
  eon: ["sow", "sew"],
  h: ["i", "z"],
  hi: ["hi"],
  I: ["h", "n"],
  i: ["h", "n"],
  iamb: ["mean"],
  in: ["sh", "in"],
  inn: ["ssh", "sin"],
  ion: ["son", "ion"],
  ionic: ["union"],
  ire: ["urn"],
  its: ["nth"],
  m: ["e"],
  man: ["sue"],
  mar: ["rue"],
  mart: ["true"],
  me: ["we"],
  men: ["sue"],
  mi: ["he"],
  mind: ["nine"],
  mine: ["wine"],
  mini: ["nine"],
  mint: ["tine"],
  mod: ["nee"],
  mot: ["toe", "tee"],
  mow: ["bee"],
  my: ["ye"],
  n: ["z", "s", "i"],
  neat: ["yaws"],
  new: ["bus"],
  not: ["yes"],
  noun: ["ides"],
  nth: ["its"],
  O: ["o", "e"],
  o: ["o", "e"],
  oar: ["rue"],
  omit: ["thee"],
  on: ["so"],
  one: ["use"],
  onion: ["sense"],
  ooh: ["zoo"],
  or: ["re"],
  ow: ["be"],
  r: ["r"],
  radon: ["sonar"],
  ram: ["ear"],
  rant: ["tzar", "tsar"],
  rat: ["tar"],
  raw: ["bur", "bar"],
  rod: ["nor"],
  rodeo: ["owner"],
  rosin: ["inner"],
  rot: ["tor"],
  rotor: ["rotor"],
  rouse: ["under"], //USE
  s: ["n"],
  sad: ["nun"],
  same: ["wean"],
  saran: ["saran"],
  sat: ["tun", "tan"],
  saw: ["bun", "ban"],
  sea: ["awn"],
  seat: ["yawn"],
  semi: ["hewn"],
  set: ["tun"],
  sew: ["bun"],
  sh: ["in"],
  she: ["win"],
  shin: ["shin"],
  shit: ["thin"],
  shy: ["yin"],
  sin: ["inn"],
  snit: ["thin"],
  so: ["on", "en"],
  sob: ["men"],
  soda: ["anon"],
  some: ["ween"],
  son: ["son", "ion"],
  sonic: ["union"],
  soon: ["soon", "seen"],
  soot: ["teen"],
  sore: ["wren"],
  sot: ["ton", "yon", "ten", "yen"],
  soy: ["yon", "yen"],
  ssh: ["inn"],
  t: ["t", "y"],
  tab: ["mat", "may"],
  tad: ["nut", "nay"],
  tam: ["eat"],
  tan: ["sat", "say"],
  tar: ["rut", "rat", "ray"],
  tart: ["tray"],
  tat: ["tut", "tat"],
  tau: ["day"],
  tea: ["jut"],
  teat: ["taut"],
  than: ["suit"],
  thaw: ["bait"],
  the: ["wit"],
  then: ["suit"],
  thin: ["shit", "snit"],
  throb: ["merit"],
  tie: ["why"],
  tier: ["runt"],
  time: ["went"],
  tin: ["shy"],
  tine: ["winy"],
  tint: ["tint", "tiny"],
  tit: ["thy"],
  toe: ["wet"],
  tomb: ["meet"],
  ton: ["sot", "set", "soy"],
  toot: ["toot"],
  tor: ["rot"],
  tort: ["trot", "troy", "trey"],
  tot: ["tot", "yet", "toy"],
  tow: ["bet", "boy", "bey"],
  toy: ["yet"],
  tray: ["yurt"],
  trey: ["yurt"],
  trot: ["tort"],
  tsar: ["runt", "rant"],
  tumor: ["reedy"],
  tzar: ["runt", "rant"],
  u: ["d"],
  uh: ["id"],
  um: ["ed"],
  umbra: ["armed"],
  w: ["b"],
  wad: ["nub", "nab"],
  wain: ["snub"],
  wan: ["sub"],
  war: ["rub"],
  was: ["nub", "nab"],
  wed: ["nub"],
  wen: ["sub"],
  wet: ["tub"],
  woe: ["web"],
  won: ["sob"],
  wow: ["bob"],
  x: ["x"],
  y: ["y"],
  yaw: ["buy", "bay"],
  yew: ["buy"],
  yin: ["shy"],
  yon: ["soy"],
  yow: ["boy", "bey"],
  z: ["n"],
  zed: ["nun"],
  zoo: ["eon"],
  "": [""],
};

export default data;
