//                   B
//                   a
//                   r
//                   B
//                   e
//M  u  r  m e r     r

const data = {
  a: ["u", "j", "a"],
  act: ["jut"],
  ad: ["an"],
  admit: ["anent"],
  an: ["us", "as"],
  anion: ["ashes"],
  aorta: ["aorta"],
  arbor: ["armor"],
  arm: ["are"],
  array: ["array"],
  arroyo: ["arroyo"],
  art: ["art"],
  arty: ["arty"],
  as: ["an"],
  at: ["at"],
  attar: ["attar"],
  awn: ["abs"],
  ax: ["ax"],
  axon: ["axes"],
  b: ["m"],
  bad: ["man"],
  bait: ["many"],
  band: ["main"],
  bar: ["mar"],
  barber: ["murmur"],
  bast: ["many"],
  bat: ["mat", "may"],
  bay: ["may"],
  be: ["mu"],
  bent: ["must"],
  bettor: ["mutter"],
  board: ["mourn"],
  boast: ["mount", "meant"],
  boat: ["moat", "meat"],
  bob: ["mom"],
  bod: ["men"],
  bode: ["menu"],
  boo: ["moo"],
  boor: ["moor"],
  boot: ["moot", "meet"],
  boron: ["mores"],
  bow: ["mob"],
  bozo: ["mono"],
  by: ["my"],
  c: ["u"],
  d: ["n"],
  dad: ["nun"],
  daddy: ["nanny"],
  daisy: ["nanny"],
  dart: ["nary"],
  day: ["nay"],
  dew: ["nub"],
  do: ["no"],
  doctor: ["neuter"],
  dodo: ["none"],
  doe: ["now", "new"],
  does: ["noun"],
  dot: ["not", "net"],
  e: ["u", "w"],
  ear: ["war"],
  east: ["want"],
  eat: ["way"],
  em: ["we"],
  emit: ["went"],
  emu: ["wed"],
  en: ["us"],
  end: ["win"],
  h: ["i", "z"],
  hast: ["zany"],
  hazy: ["zany"],
  hi: ["in"],
  hid: ["inn"],
  his: ["inn"],
  hod: ["ion"],
  I: ["h", "n"],
  i: ["h", "n"],
  in: ["hi"],
  inn: ["his"],
  intent: ["nitwit"],
  into: ["nite"],
  m: ["e"],
  many: ["easy"],
  mar: ["ear"],
  mat: ["eat"],
  mi: ["eh", "en"],
  mod: ["eon"],
  mu: ["ed"],
  n: ["z", "s", "i"],
  nab: ["sum"],
  nanny: ["sassy"],
  nay: ["say"],
  neat: ["swat", "sway"],
  new: ["sub"],
  nit: ["shy"],
  no: ["so"],
  nod: ["son", "ion"],
  noes: ["sown", "sewn"],
  noisy: ["sonny"],
  norm: ["sore", "sere"],
  not: ["sot", "soy", "set"],
  now: ["sob"],
  nu: ["id"],
  numb: ["idem"],
  O: ["o", "e"],
  o: ["o", "e"],
  oar: ["our", "oar", "ear"],
  oat: ["out", "oat", "eat"],
  or: ["or"],
  orator: ["orator"],
  oratory: ["oratory"],
  own: ["obi"],
  ox: ["ox", "ex"],
  r: ["r"],
  rad: ["run", "ran"],
  rain: ["runs", "rani"],
  ram: ["rue"],
  randy: ["rainy"],
  rani: ["rush", "ruin", "rash", "rain"],
  rant: ["rust"],
  rash: ["rani"],
  rat: ["rut", "rat", "ray"],
  ratty: ["rutty", "ratty"],
  raw: ["rub"],
  ray: ["ray"],
  red: ["run"],
  redo: ["rune"],
  rein: ["runs"],
  rem: ["rue"],
  rend: ["ruin"],
  rent: ["rust"],
  rest: ["runt"],
  rhino: ["rinse"],
  road: ["roan"],
  roam: ["roue"],
  roar: ["roar", "rear"],
  rob: ["rem"],
  roe: ["row"],
  root: ["root"],
  rot: ["rot"],
  rotary: ["rotary"],
  rotatory: ["rotatory"],
  rotor: ["rotor"],
  row: ["rob"],
  s: ["n"],
  sad: ["nun"],
  sassy: ["nanny"],
  sat: ["nut", "nay"],
  saw: ["nub", "nab"],
  say: ["nay"],
  scum: ["nude"],
  set: ["nut"],
  sew: ["nub"],
  shim: ["nine"],
  so: ["no"],
  soar: ["near"],
  sonny: ["noisy"],
  soon: ["noes"],
  sot: ["not", "net"],
  t: ["t", "y"],
  tab: ["tam", "yum", "yam"],
  tabby: ["tummy", "yummy"],
  tacit: ["taunt"],
  tact: ["taut"],
  tad: ["tun", "tan"],
  taint: ["tansy"],
  tar: ["tar"],
  taro: ["taro", "tare"],
  tarot: ["tarot"],
  tarry: ["tarry"],
  tart: ["tart", "yurt"],
  tartar: ["tartar"],
  tat: ["tut", "tat"],
  tattoo: ["tattoo"],
  tau: ["tad"],
  tax: ["tux", "tax"],
  tend: ["twin"],
  tent: ["twit"],
  tho: ["tie"],
  time: ["thew"],
  tire: ["thru"],
  tit: ["thy"],
  to: ["to", "yo", "ye"],
  toe: ["tow", "you", "yow", "yew"],
  toed: ["town"],
  tom: ["toe", "tee"],
  tomb: ["teem"],
  ton: ["yes"],
  too: ["too", "toe", "tee"],
  toot: ["toot"],
  tor: ["tor"],
  tort: ["tort"],
  tot: ["tot", "toy", "yet"],
  toy: ["toy"],
  tram: ["true"],
  transom: ["trainee"],
  tray: ["tray"],
  trot: ["trot", "troy", "trey"],
  troy: ["troy", "trey"],
  try: ["try"],
  tyro: ["tyro"],
  u: ["d"],
  umber: ["demur"],
  unbent: ["dimwit"],
  undo: ["dine"],
  unit: ["dint"],
  w: ["b"],
  wad: ["bun", "ban"],
  wain: ["buns"],
  waist: ["bunny"],
  wait: ["bunt"],
  wan: ["bus"],
  want: ["bust", "busy", "bast", "bait"],
  war: ["bur", "bar"],
  ward: ["burn", "barn"],
  warm: ["bare"],
  wart: ["bury"],
  wary: ["bury"],
  was: ["bun", "ban"],
  wast: ["bunt"],
  watt: ["butt"],
  way: ["buy", "bay"],
  web: ["bum"],
  wed: ["bun"],
  wen: ["bus"],
  went: ["bust", "busy"],
  west: ["bunt"],
  wet: ["but", "buy"],
  who: ["bio"],
  woe: ["bow"],
  wont: ["best"],
  woo: ["boo", "bee"],
  wood: ["boon", "been"],
  word: ["born"],
  worm: ["bore"],
  worry: ["berry"],
  wow: ["bob"],
  wrest: ["brunt"],
  x: ["x"],
  y: ["y"],
  ya: ["ya"],
  yard: ["yarn"],
  yo: ["yo", "ye"],
  yon: ["yes"],
  z: ["n"],
  zed: ["nun"],
  zoo: ["nee"],
  "": [""],
};

export default data;
