//t r A I n

//c
//H
//A
//r
//t
const data = {
  a: ["u", "a"],
  aeon: ["iota", "zeta"],
  aide: ["tuna"],
  arm: ["bra"],
  armed: ["umbra"],
  as: ["nu"],
  at: ["ya"],
  atom: ["beta"],
  aura: ["urea", "area"],
  awe: ["tea"],
  awn: ["sea"],
  b: ["w"],
  bait: ["thaw"],
  ban: ["saw"],
  bar: ["raw"],
  bat: ["yaw"],
  bay: ["yaw"],
  bob: ["wow"],
  bore: ["trow"],
  boy: ["yow", "yew"],
  bun: ["sew"],
  bus: ["new"],
  but: ["yew"],
  buy: ["yew"],
  c: ["n"],
  cab: ["wan"],
  cam: ["bun", "ban"],
  can: ["sun"],
  car: ["run", "ran"],
  cat: ["tun", "tan"],
  char: ["ruin", "rain"],
  charm: ["bruin", "brain"],
  chart: ["train"],
  chin: ["shin"],
  chit: ["thin"],
  cob: ["won", "wen"],
  coca: ["anon"],
  con: ["son", "ion"],
  cone: ["mien"],
  coo: ["eon"],
  coon: ["soon", "seen"],
  coot: ["teen"],
  corn: ["iron"],
  cot: ["ton", "yon", "ten", "yen"],
  cow: ["eon"],
  coy: ["yon", "yen"],
  crab: ["warn"],
  cram: ["burn", "barn"],
  craw: ["earn"],
  crotch: ["intern"],
  crutch: ["intern"],
  cub: ["wen"],
  cue: ["men", "ten"],
  curb: ["wren"],
  cut: ["ten", "yen"],
  d: ["u"],
  dew: ["emu"],
  dot: ["you"],
  e: ["n", "m", "t"],
  ear: ["run", "ran", "rum", "ram", "rut", "rat"],
  eat: ["tun", "tan", "yum", "tam", "yam", "tut", "tat"],
  ed: ["um"],
  eh: ["in", "it"],
  en: ["in", "it"],
  enamor: ["robust"],
  ennui: ["heist"],
  eon: ["son", "ion", "sot", "set"],
  era: ["urn", "arm", "art"],
  ewe: ["men", "ten", "net", "met"],
  f: ["f"],
  for: ["ref"],
  four: ["reef"],
  frat: ["turf"],
  fur: ["ref"],
  h: ["i", "z"],
  hansom: ["bonsai"],
  he: ["mi", "ti"],
  hear: ["rani"],
  hewn: ["semi"],
  hi: ["hi"],
  I: ["h", "n"],
  i: ["h", "n"],
  id: ["uh"],
  in: ["sh", "in"],
  inn: ["ssh", "sin"],
  ion: ["son", "ion"],
  its: ["nth"],
  j: ["u"],
  jew: ["emu"],
  jot: ["you"],
  joy: ["you"],
  m: ["b"],
  main: ["snub"],
  man: ["sub"],
  mar: ["rub"],
  mat: ["tub", "tab"],
  mean: ["iamb"],
  medium: ["benumb"],
  mob: ["web"],
  mom: ["bob"],
  n: ["z", "s", "i"],
  nab: ["was"],
  near: ["runs", "rats", "rani"],
  neon: ["semi"],
  newt: ["yeti"],
  nine: ["mini"],
  not: ["yes"],
  nth: ["its"],
  nut: ["yes"],
  O: ["o", "e"],
  o: ["o", "e"],
  oar: ["rue"],
  odor: ["roue"],
  ohm: ["bio"],
  om: ["be"],
  on: ["so"],
  one: ["tie"],
  onion: ["sense"],
  ooh: ["zoo"],
  or: ["re"],
  out: ["tee"],
  ouzo: ["once"],
  owe: ["nee", "tee"],
  own: ["see"],
  r: ["r"],
  ram: ["bur", "bar"],
  rant: ["tzar", "tsar"],
  rat: ["tar"],
  raw: ["ear"],
  robot: ["tower"],
  roe: ["nor", "tor"],
  roman: ["saber"],
  room: ["boor", "beer"],
  rosin: ["inner"],
  rot: ["tor"],
  rotor: ["rotor"],
  rune: ["tier"],
  runt: ["tier"],
  s: ["n"],
  sac: ["nun"],
  saran: ["saran"],
  sat: ["tun", "tan"],
  sh: ["in"],
  share: ["train"],
  she: ["tin"],
  shin: ["shin"],
  shit: ["thin"],
  shy: ["yin"],
  sin: ["inn"],
  snare: ["train"],
  snit: ["thin"],
  so: ["on", "en"],
  sob: ["won", "wen"],
  son: ["son", "ion"],
  soon: ["soon", "seen"],
  soot: ["teen"],
  sot: ["ton", "yon", "ten", "yen"],
  sow: ["eon"],
  sown: ["seen"],
  soy: ["yon", "yen"],
  ssh: ["inn"],
  sub: ["wen"],
  sue: ["men", "ten"],
  suit: ["then"],
  swum: ["been"],
  t: ["t", "y"],
  tab: ["way"],
  tam: ["but", "bat", "buy", "bay"],
  tan: ["sat", "say"],
  tar: ["rut", "rat", "ray"],
  tare: ["tray"],
  tart: ["tray"],
  tat: ["tut", "tat"],
  tau: ["cut", "cat", "eat", "cay"],
  taut: ["teat"],
  tea: ["ant", "any"],
  team: ["bunt", "butt"],
  tear: ["runt", "rant"],
  teens: ["ninny"],
  ten: ["sty"],
  tenon: ["zesty"],
  tent: ["tint", "tiny"],
  than: ["suit"],
  thatch: ["intuit"],
  the: ["nit", "tit"],
  then: ["snit"],
  thew: ["emit"],
  thin: ["shit", "snit"],
  thou: ["cozy"],
  throe: ["merit"],
  tie: ["thy"],
  tin: ["shy"],
  tine: ["mint", "tint", "tiny"],
  tint: ["tint", "tiny"],
  tit: ["thy"],
  toe: ["not", "mot", "tot", "net", "met", "toy"],
  tom: ["bet", "boy", "bey"],
  ton: ["sot", "set", "soy"],
  toot: ["toot"],
  tor: ["rot"],
  tore: ["trot", "troy", "trey"],
  tort: ["trot", "troy", "trey"],
  tot: ["tot", "yet", "toy"],
  toy: ["yet"],
  tram: ["bury"],
  tray: ["yurt"],
  trot: ["tort"],
  trow: ["eery"],
  tsar: ["runt", "rant"],
  tub: ["wet"],
  tun: ["set", "icy"],
  turf: ["fret"],
  tut: ["yet"],
  twit: ["they"],
  tzar: ["runt", "rant"],
  u: ["c", "e"],
  um: ["be"],
  uncut: ["tense"],
  union: ["sonic", "ionic", "sense"],
  urn: ["ire"],
  w: ["e"],
  wan: ["sue"],
  war: ["rue"],
  ware: ["true"],
  warm: ["brae"],
  wart: ["true"],
  we: ["me"],
  wean: ["sane", "same", "sate"],
  wear: ["rune", "rate"],
  went: ["tine", "time"],
  wide: ["tune"],
  win: ["she"],
  wine: ["nine", "mine", "tine"],
  wit: ["the"],
  withe: ["tithe"],
  woe: ["toe", "nee", "tee"],
  won: ["see"],
  wore: ["tree"],
  wort: ["tree"],
  x: ["x"],
  y: ["y"],
  yam: ["buy", "bay"],
  ye: ["my"],
  yea: ["any"],
  yeah: ["zany"],
  yen: ["sty"],
  yin: ["shy"],
  yon: ["soy"],
  yore: ["troy", "trey"],
  you: ["coy"],
  yum: ["bey"],
  yurt: ["trey"],
  z: ["n"],
  zone: ["mien"],
  zoned: ["union"],
  zoo: ["eon"],
  zoom: ["boon", "been"],
  "": [""],
};

export default data;
