const data = {
  a: ["a", "n", "u"],
  abs: ["awn"],
  ace: ["ant"],
  ache: ["unit"],
  act: ["ant"],
  ad: ["nu"],
  adz: ["nun"],
  adze: ["aunt"],
  ago: ["ago"],
  agog: ["agog"],
  ahem: ["nite"],
  ail: ["ant"],
  air: ["ant"],
  ajar: ["aunt"],
  aloe: ["atom"],
  an: ["as", "us"],
  ant: ["act"],
  arm: ["ate"],
  as: ["an"],
  at: ["at"],
  ate: ["aft"],
  awn: ["abs"],
  ax: ["ax"],
  b: ["w"],
  baa: ["wan"],
  bag: ["wag"],
  bail: ["want"],
  bait: ["want"],
  bale: ["watt"],
  ball: ["watt"],
  ban: ["was"],
  bane: ["wast"],
  bare: ["watt"],
  base: ["want"],
  bast: ["want"],
  bate: ["watt", "waft"],
  bay: ["way"],
  bio: ["who"],
  boa: ["won"],
  boar: ["wont"],
  boat: ["wont"],
  bob: ["wow"],
  boil: ["wont"],
  boo: ["woo"],
  boot: ["woof"],
  c: ["n"],
  car: ["nut"],
  carry: ["natty", "nutty"],
  cat: ["nut"],
  catty: ["natty", "nutty"],
  caw: ["nab", "nub"],
  cay: ["nay"],
  chili: ["ninth"],
  cob: ["now"],
  coda: ["noun"],
  coital: ["nonfat"],
  cony: ["nosy"],
  corm: ["note"],
  costar: ["nonfat"],
  cot: ["not"],
  d: ["u"],
  e: ["m", "t"],
  ear: ["mat", "tat", "tut"],
  earl: ["matt", "mutt"],
  earth: ["tutti"], //USE tutti is all instruments or voices together MUSIC book
  easy: ["many"],
  eat: ["mat", "tat", "tut"],
  ed: ["mu"],
  eh: ["mi", "ti"],
  em: ["me"],
  email: ["meant"],
  emir: ["tent"],
  emit: ["tent"],
  g: ["g"],
  gad: ["gnu"],
  gag: ["gag"],
  gaga: ["gaga"],
  gal: ["gut"],
  gar: ["gut"],
  gas: ["gun"],
  gassy: ["gunny"],
  gay: ["gay", "guy"],
  go: ["go"],
  goal: ["goat", "gout"],
  goat: ["goat", "gout"],
  gobs: ["gown"],
  godly: ["gouty"],
  goo: ["goo"],
  got: ["got"],
  gotta: ["gotta"],
  gown: ["gobs"],
  h: ["i", "l", "z"],
  ha: ["in", "la"],
  hag: ["lag", "lug"],
  halo: ["into"],
  harem: ["latte"],
  harm: ["late", "lute"],
  has: ["inn"],
  haw: ["lab"],
  hay: ["lay"],
  hazy: ["zany"],
  he: ["it"],
  heme: ["item"],
  hen: ["its"],
  hi: ["in"],
  his: ["inn"],
  ho: ["lo"],
  hob: ["low"],
  hoe: ["lot"],
  hog: ["log"],
  hone: ["lost"],
  hoot: ["loot"],
  hora: ["iota"],
  horn: ["lots"],
  hot: ["lot"],
  hotly: ["lofty"],
  how: ["lob"],
  I: ["h", "n"],
  i: ["h", "n"],
  id: ["nu"],
  j: ["u"],
  jato: ["unto"],
  l: ["t"],
  lac: ["tan", "tun"],
  lad: ["tau"],
  lade: ["taut"],
  lag: ["tag", "tug"],
  lane: ["tact"],
  lard: ["tutu"],
  late: ["tuft"],
  law: ["tab", "tub"],
  lax: ["tax", "tux"],
  liar: ["that"],
  limb: ["thew"],
  lime: ["them"],
  limy: ["they"],
  lo: ["to"],
  loam: ["tone"],
  lob: ["tow"],
  lode: ["tout"],
  log: ["tog"],
  loot: ["toot"],
  lot: ["tot"],
  m: ["e"],
  ma: ["en"],
  mane: ["east"],
  many: ["easy"],
  mar: ["eat"],
  mat: ["eat"],
  me: ["em"],
  mi: ["eh", "en"],
  mu: ["ed"],
  n: ["s", "z", "c"],
  nab: ["saw", "caw"],
  nag: ["sag"],
  nail: ["cant", "cunt"],
  name: ["suet"],
  nanny: ["sassy"],
  natty: ["catty"],
  nay: ["say", "cay"],
  near: ["smut", "stat"],
  nearly: ["smutty"],
  neat: ["smut", "stat"],
  neatly: ["smutty"],
  no: ["so"],
  nodal: ["count"],
  noisy: ["sonny"],
  none: ["cost"],
  nor: ["sot", "cot"],
  norm: ["cote"],
  nosy: ["cony"],
  not: ["sot", "cot"],
  note: ["soft"],
  now: ["sob", "cob"],
  O: ["o"],
  o: ["o"],
  oar: ["oat", "out"],
  oat: ["oat", "oaf", "out"],
  obi: ["own"],
  ode: ["out"],
  ohm: ["ole"],
  ox: ["ox"],
  q: ["q"],
  r: ["t"],
  rad: ["tau"],
  radar: ["taunt"],
  rag: ["tag", "tug"],
  rainy: ["tansy"],
  rani: ["tush"],
  rant: ["tact"],
  rat: ["tat", "tut"],
  rate: ["tuft"],
  ratty: ["taffy"],
  raw: ["tab", "tub"],
  rim: ["the"],
  rime: ["them"],
  roam: ["tone"],
  roar: ["tout"],
  rob: ["tow"],
  rode: ["tout"],
  roe: ["tom", "tot"],
  root: ["toot"],
  rosy: ["tony"],
  rot: ["tot"],
  s: ["n"],
  sac: ["nun"],
  sag: ["nag"],
  sally: ["natty", "nutty"],
  salty: ["natty", "nutty"],
  sassy: ["nanny"],
  sat: ["nut"],
  saw: ["nab", "nub"],
  say: ["nay"],
  sham: ["nine"],
  she: ["nit"],
  shh: ["nil"],
  shim: ["nine"],
  so: ["no"],
  sob: ["now"],
  soda: ["noun"],
  sol: ["not"],
  sot: ["not"],
  t: ["t", "f"],
  tad: ["tau"],
  tag: ["tag", "tug", "fag"],
  tally: ["fatty"],
  tar: ["tat", "tut", "fat"],
  tarn: ["futz"],
  tarry: ["fatty"],
  tat: ["tat", "tut", "fat"],
  tattoo: ["tattoo"],
  tau: ["tad", "fad"],
  tax: ["tax", "tux", "fax"],
  that: ["tint", "fiat", "flat"],
  thaw: ["flab", "flub"],
  the: ["tit", "fit"],
  them: ["time"],
  thy: ["fly"],
  time: ["them"],
  to: ["to"],
  toast: ["fount"],
  toe: ["tom", "tot"],
  tog: ["tog", "fog"],
  toga: ["toga"],
  toil: ["font"],
  tom: ["toe", "foe"],
  too: ["too"],
  tool: ["toot", "foot"],
  toot: ["toot", "foot"],
  tor: ["tot"],
  torah: ["total"],
  tot: ["tot"],
  tow: ["fob"],
  toy: ["toy"],
  u: ["d"],
  w: ["b"],
  wag: ["bag", "bug"],
  wail: ["bunt"],
  wain: ["buns"],
  wait: ["bunt"],
  wale: ["butt"],
  wall: ["butt"],
  wan: ["bus"],
  wane: ["bast", "bust"],
  wanly: ["busty"],
  want: ["bast", "bust"],
  war: ["bat", "but"],
  ware: ["butt"],
  warm: ["bate"],
  warn: ["bats"],
  wart: ["butt"],
  warty: ["batty"],
  was: ["ban", "bun"],
  wast: ["bunt"],
  watt: ["butt", "buff"],
  way: ["bay", "buy"],
  wham: ["blue"],
  who: ["bio"],
  woo: ["boo"],
  wool: ["boot"],
  wooly: ["booty"],
  wow: ["bob"],
  x: ["x"],
  y: ["y"],
  ya: ["ya"],
  yo: ["yo"],
  yoga: ["yoga"],
  z: ["n"],
  "": [""],
};

export default data;
