const data = {
  a: ["r"],
  add: ["ado"],
  advert: ["adverb"],
  aft: ["apt"],
  aid: ["rid"],
  aide: ["ride"],
  aim: ["rim"],
  ale: ["ace", "alb"],
  alp: ["asp"],
  alter: ["aster"],
  aunt: ["runt"],
  aunty: ["runty"],
  aural: ["rural"],
  awake: ["aware"],
  away: ["awry"],
  axe: ["are"],
  aye: ["rye"],
  baa: ["bra", "bar"],
  bake: ["bare"],
  bale: ["base"],
  balk: ["back", "bask"],
  bar: ["brr"],
  bare: ["barb"],
  barter: ["barber"],
  basil: ["basic", "basis"],
  bate: ["babe"],
  beak: ["bear"],
  beaker: ["bearer"],
  beam: ["berm"],
  beef: ["beep"],
  belt: ["best"],
  bid: ["bio"],
  big: ["bio"],
  bilker: ["bicker"],
  bit: ["bib"],
  blah: ["blab"],
  bleak: ["blear"],
  blot: ["blob"],
  blurt: ["blurb"],
  bod: ["boo"],
  bog: ["boo"],
  book: ["boor"],
  bookish: ["boorish"],
  boot: ["boob"],
  booty: ["booby"],
  boxer: ["borer"],
  boxing: ["boring"],
  bra: ["brr"],
  bulk: ["buck"],
  bushy: ["busby"],
  busty: ["busby"],
  but: ["bub"],
  buy: ["bum"],
  cafe: ["cape"],
  cake: ["care"],
  calk: ["cask"],
  carton: ["carbon"],
  casing: ["casino"],
  cat: ["cab"],
  cause: ["cruse"],
  cay: ["cry", "cam"],
  chary: ["charm"],
  cheat: ["chert"],
  cheek: ["cheer"],
  cheekily: ["cheerily"],
  cheekiness: ["cheeriness"],
  cheeky: ["cheery"],
  choke: ["chore"],
  civil: ["civic"],
  clay: ["clam"],
  clime: ["climb"],
  clue: ["club"],
  cod: ["coo"],
  codex: ["coder"],
  cog: ["coo"],
  coke: ["core"],
  cola: ["coca"],
  colt: ["cost"],
  come: ["comb"],
  comfort: ["comport"],
  cornea: ["corner"],
  cot: ["cob"],
  cue: ["cub"],
  cure: ["curb"],
  curt: ["curb"],
  curtly: ["curtsy"],
  cut: ["cub"],
  cute: ["cube"],
  cutely: ["cutesy"],
  cuticle: ["cubicle"],
  d: ["o"],
  daily: ["drily", "daisy"],
  dale: ["dace"],
  daub: ["drub"],
  day: ["dry", "dam"],
  decay: ["decry"],
  defend: ["depend"],
  defendant: ["dependant"],
  delay: ["decay"],
  detect: ["deject"],
  detection: ["dejection"],
  dike: ["dire"],
  dole: ["dose"],
  dolt: ["dost"],
  dory: ["dorm"],
  doze: ["ooze"],
  drat: ["drab"],
  dray: ["dram"],
  dud: ["duo"],
  due: ["dub"],
  duel: ["dues"],
  dug: ["duo"],
  duh: ["dub"],
  dunce: ["ounce"],
  dust: ["oust"],
  duster: ["ouster"],
  e: ["b"],
  ear: ["bar", "err"],
  earn: ["barn"],
  earring: ["barring"],
  ease: ["base"],
  easement: ["basement"],
  east: ["bast", "erst"],
  eat: ["bat"],
  eats: ["bats"],
  egg: ["ego"],
  eight: ["bight"],
  eke: ["ere"],
  eland: ["bland"],
  elect: ["eject"],
  election: ["ejection"],
  elector: ["ejector"],
  ellipse: ["eclipse"],
  elliptic: ["ecliptic"],
  era: ["bra", "err"],
  err: ["brr"],
  evaluate: ["evacuate"],
  evaluation: ["evacuation"],
  exalt: ["exact"],
  exogenous: ["erogenous"],
  exotic: ["erotic"],
  exotically: ["erotically"],
  exoticism: ["eroticism"],
  eye: ["bye"],
  f: ["p"],
  fa: ["pa"],
  face: ["pace"],
  fact: ["pact"],
  fad: ["pad"],
  fail: ["pail"],
  fain: ["pain"],
  faint: ["paint"],
  fair: ["pair"],
  fake: ["fare"],
  fall: ["pall"],
  fan: ["pan"],
  fang: ["pang"],
  far: ["par"],
  fare: ["pare"],
  fart: ["part"],
  fast: ["past"],
  fat: ["pat"],
  fate: ["pate"],
  fatty: ["patty"],
  fawn: ["pawn"],
  fax: ["far"],
  fay: ["pay", "fry"],
  fear: ["pear"],
  feat: ["peat"],
  fee: ["pee"],
  feel: ["peel"],
  feeler: ["peeler"],
  feeling: ["peeling"],
  feelings: ["peelings"],
  felt: ["pelt", "fest"],
  fen: ["pen"],
  fence: ["pence"],
  fend: ["pend"],
  fest: ["pest"],
  fester: ["pester"],
  fetal: ["petal"],
  few: ["pew"],
  fickle: ["pickle"],
  fiddle: ["piddle"],
  fie: ["pie", "fib"],
  fierce: ["pierce"],
  fig: ["pig"],
  figment: ["pigment"],
  file: ["pile"],
  filing: ["piling"],
  fill: ["pill"],
  fin: ["pin"],
  finch: ["pinch"],
  fine: ["pine"],
  fink: ["pink"],
  fit: ["pit", "fib"],
  fitted: ["pitted"],
  fix: ["pix", "fir"],
  fixer: ["firer"],
  flake: ["flare"],
  flan: ["plan"],
  flank: ["plank"],
  flash: ["plash"],
  flat: ["plat", "flab"],
  flatter: ["platter"],
  flay: ["play"],
  flea: ["plea"],
  fled: ["pled"],
  flight: ["plight"],
  flop: ["plop"],
  flow: ["plow"],
  flue: ["flub"],
  flume: ["plume"],
  flunk: ["plunk"],
  flush: ["plush"],
  fly: ["ply"],
  foam: ["form"],
  foe: ["fob"],
  folio: ["polio"],
  fond: ["pond"],
  fool: ["pool"],
  fop: ["pop"],
  fore: ["pore"],
  fork: ["pork"],
  fort: ["port"],
  foster: ["poster"],
  found: ["pound"],
  four: ["pour"],
  fox: ["pox", "for"],
  frank: ["prank"],
  fray: ["pray"],
  fro: ["pro"],
  from: ["prom"],
  fry: ["pry"],
  fuck: ["puck"],
  fucker: ["pucker"],
  fuddle: ["puddle"],
  full: ["pull"],
  fullback: ["pullback"],
  fuller: ["puller"],
  fun: ["pun"],
  funk: ["punk"],
  furl: ["purl"],
  fuss: ["puss"],
  fussy: ["pussy"],
  g: ["o"],
  gain: ["grin"],
  gait: ["grit"],
  gal: ["gas"],
  gar: ["oar"],
  gaunt: ["grunt"],
  gilt: ["gist"],
  god: ["goo"],
  goes: ["gobs"],
  goof: ["goop"],
  got: ["gob"],
  grange: ["orange"],
  grate: ["orate"],
  gray: ["gram"],
  guile: ["guise"],
  gulf: ["gulp"],
  gust: ["oust"],
  gut: ["out"],
  guy: ["gum"],
  h: ["b"],
  hack: ["back"],
  hacker: ["backer"],
  hacking: ["backing"],
  had: ["bad"],
  hag: ["bag"],
  hah: ["bah"],
  hail: ["bail"],
  hake: ["bake", "hare"],
  hale: ["bale"],
  hall: ["ball"],
  halt: ["hast"],
  hand: ["band"],
  handstand: ["bandstand"],
  handy: ["bandy"],
  hang: ["bang"],
  hank: ["bank"],
  hanker: ["banker"],
  hard: ["bard"],
  hardtack: ["hardback"],
  hare: ["bare"],
  hark: ["bark"],
  harrier: ["barrier"],
  harrow: ["barrow"],
  hash: ["bash"],
  hast: ["bast"],
  haste: ["baste"],
  hat: ["bat"],
  hatch: ["batch"],
  hate: ["bate"],
  hated: ["bated"],
  hath: ["bath"],
  hatter: ["batter"],
  hay: ["bay", "ham"],
  he: ["be"],
  head: ["bead", "herd"],
  header: ["herder"],
  heading: ["beading"],
  headsman: ["herdsman"],
  heady: ["beady"],
  hear: ["bear"],
  heard: ["beard"],
  hearer: ["bearer"],
  hearing: ["bearing", "herring"],
  heat: ["beat"],
  heater: ["beater"],
  heating: ["beating"],
  heaver: ["beaver"],
  heck: ["beck"],
  hell: ["bell"],
  herd: ["hero"],
  here: ["herb"],
  hex: ["her"],
  hey: ["bey", "hem"],
  hi: ["bi"],
  hid: ["bid"],
  hidden: ["bidden"],
  hide: ["bide"],
  hike: ["bike", "hire"],
  hiker: ["biker"],
  hill: ["bill"],
  hilly: ["billy"],
  hilt: ["hist"], //Call for silence
  hind: ["bind"],
  hinder: ["binder"],
  hinge: ["binge"],
  hit: ["bit"],
  hitch: ["bitch"],
  hitter: ["bitter"],
  hoard: ["board"],
  hoarder: ["boarder"],
  hoarding: ["boarding"],
  hob: ["bob"],
  hobble: ["bobble"],
  hock: ["bock"],
  hod: ["bod"],
  hoe: ["hob"],
  hog: ["bog"],
  hold: ["bold"],
  hole: ["bole", "hose"],
  holster: ["bolster"],
  hone: ["bone"],
  honer: ["boner"],
  hoof: ["hoop"],
  hook: ["book"],
  hookworm: ["bookworm"],
  hoot: ["boot"],
  hop: ["bop"],
  horn: ["born"],
  hot: ["hob"],
  hound: ["bound"],
  how: ["bow"],
  howl: ["bowl"],
  howler: ["bowler"],
  howling: ["bowling"],
  hub: ["bub"],
  hue: ["hub"],
  huff: ["buff"],
  hug: ["bug"],
  huh: ["hub"],
  hulk: ["bulk", "husk"],
  hull: ["bull"],
  hum: ["bum"],
  humble: ["bumble"],
  humbler: ["bumbler"],
  humbling: ["bumbling"],
  hummer: ["bummer"],
  hump: ["bump"],
  hunch: ["bunch"],
  hung: ["bung"],
  hunk: ["bunk"],
  hunker: ["bunker"],
  hunt: ["bunt"],
  hunting: ["bunting"],
  hurl: ["burl"],
  hush: ["bush"],
  hushed: ["bushed"],
  hustle: ["bustle"],
  hut: ["but", "hub"],
  hutch: ["butch"],
  ikon: ["iron"],
  inlet: ["inset"],
  jay: ["jam"],
  jot: ["job"],
  k: ["r"],
  kaiser: ["raiser"],
  keel: ["reel"],
  ketch: ["retch"],
  kick: ["rick"],
  kid: ["rid"],
  kill: ["rill"],
  kind: ["rind"],
  king: ["ring"],
  kink: ["rink"],
  kipper: ["ripper"],
  kite: ["rite"],
  knot: ["knob"],
  kook: ["rook"],
  l: ["c", "s", "j"],
  lab: ["cab", "jab"],
  lac: ["sac"],
  lack: ["sack", "jack"],
  lacking: ["sacking"],
  lad: ["cad", "sad"],
  lade: ["jade"],
  lag: ["sag", "jag"],
  laid: ["said"],
  lake: ["cake", "sake"],
  lam: ["cam", "jam"],
  lamb: ["jamb"],
  lame: ["came", "same", "lamb"],
  lameness: ["sameness"],
  lamp: ["camp"],
  lancer: ["cancer"],
  land: ["sand"],
  lane: ["cane", "sane"],
  lank: ["sank"],
  lap: ["cap", "sap"],
  lard: ["card"],
  larder: ["carder"],
  large: ["sarge"],
  largo: ["cargo"],
  lash: ["cash", "sash"],
  lass: ["sass"],
  last: ["cast"],
  lasting: ["casting"],
  latch: ["catch"],
  late: ["sate"],
  later: ["cater"],
  latex: ["later"],
  lava: ["java"],
  lavage: ["savage"], //washing out body cavity
  lave: ["cave", "save"], //wash
  law: ["caw", "saw", "jaw"],
  lawbreaker: ["jawbreaker"], //USE
  lawn: ["sawn"],
  lawyer: ["sawyer"], //saws logs
  lax: ["sax"],
  lay: ["cay", "say", "jay", "lam"],
  layman: ["cayman"],
  lea: ["sea"],
  leaf: ["leap"],
  lean: ["jean"],
  lease: ["cease"],
  ledge: ["sedge"], //plants
  lee: ["see"], //sheltered ledge
  leek: ["seek", "leer"],
  leer: ["seer", "jeer"],
  lend: ["send"],
  lender: ["sender"], //You be a lender, and I'll be a sender!
  lent: ["cent", "sent"],
  lest: ["jest"],
  let: ["set", "jet"],
  letter: ["setter"],
  letup: ["setup"],
  lever: ["sever"],
  lib: ["jib"],
  lick: ["sick"],
  lie: ["lib"],
  liege: ["siege"],
  lift: ["sift"],
  lifter: ["sifter"],
  light: ["sight"],
  lighting: ["sighting"],
  lightly: ["sightly"],
  like: ["lire"],
  lilt: ["silt", "jilt", "list"],
  lilting: ["listing"],
  lime: ["limb"],
  limply: ["simply"],
  line: ["sine"],
  linger: ["singer"],
  link: ["sink"],
  lip: ["sip"],
  lire: ["sire"],
  lit: ["sit", "lib"],
  lite: ["cite", "site"],
  literal: ["liberal"],
  literally: ["liberally"], //I will literally
  literalness: ["liberalness"],
  literate: ["liberate"],
  litter: ["sitter"],
  litterbug: ["jitterbug"], //Don't be a litterbug, be a jitterbug
  live: ["jive"],
  lo: ["so"],
  load: ["lord"],
  loan: ["lorn"],
  lob: ["cob", "sob", "job"],
  lobber: ["jobber"],
  lock: ["cock", "sock", "jock"],
  locket: ["socket"],
  loco: ["coco"],
  lode: ["code"],
  lodger: ["codger"],
  loft: ["soft"],
  lofty: ["softy"],
  log: ["cog", "jog"],
  logger: ["jogger"],
  logging: ["jogging"], //loggers to joggers
  loin: ["coin", "join"],
  lone: ["cone"],
  long: ["song"],
  look: ["cook"],
  looker: ["cooker"],
  lookout: ["cookout"],
  loon: ["coon", "soon"],
  loop: ["coop"],
  loot: ["coot", "soot"],
  lop: ["cop", "sop"],
  lope: ["cope"],
  lord: ["cord"],
  lore: ["core", "sore"],
  lorn: ["corn"],
  lost: ["cost"],
  lot: ["cot", "sot", "jot", "lob"],
  louse: ["souse"],
  love: ["cove"],
  lover: ["cover"],
  low: ["cow", "sow"],
  lowboy: ["cowboy"],
  lower: ["cower", "sower"],
  lowly: ["jowly"], //Roundabout should use lowly
  lox: ["sox"],
  lube: ["cube"],
  luck: ["suck"],
  luff: ["cuff"],
  lug: ["jug"],
  lull: ["cull"],
  lumber: ["cumber"],
  lump: ["sump", "jump"],
  lumpiness: ["jumpiness"],
  lumpy: ["jumpy"],
  lung: ["sung"],
  lupine: ["supine"],
  lure: ["cure", "sure"],
  lust: ["just"],
  lute: ["cute", "jute", "lube"],
  lynch: ["synch"],
  make: ["mare"],
  male: ["mace"],
  malt: ["mast"],
  malted: ["masted"],
  max: ["mar"],
  meager: ["merger"],
  melon: ["meson"], //subatomic particle
  mewl: ["mews"],
  mike: ["mire"],
  mile: ["mice"],
  miler: ["miser"], //person or horse trained to run a mile
  milt: ["mist"],
  moan: ["morn"],
  mod: ["moo"],
  molt: ["most"],
  morals: ["morass"], //a complicated or confused situation. Morals have become a morass
  morel: ["mores"], //fungus
  mot: ["mob"],
  motile: ["mobile"],
  motility: ["mobility"],
  move: ["moue"],
  mule: ["muse"],
  newly: ["newsy"],
  nit: ["nib"],
  noel: ["noes"],
  normally: ["normalcy"],
  nut: ["nub"],
  oak: ["oar"],
  oft: ["opt"],
  ore: ["orb"],
  outlast: ["outcast"],
  outlet: ["outset"],
  overdue: ["overdub"],
  overload: ["overlord"],
  overlook: ["overcook"],
  overtook: ["overbook"],
  ox: ["or"],
  paint: ["print"],
  painter: ["printer"],
  painting: ["printing"],
  pale: ["pace"],
  paltry: ["pastry"], //Roundabout could use paltry
  pay: ["pry"],
  pea: ["per"],
  peach: ["perch"],
  peak: ["perk", "pear"],
  peat: ["pert"],
  peek: ["peer"],
  pelt: ["pest"],
  phantasy: ["phantasm"],
  pilot: ["picot"],
  plume: ["plumb"],
  poach: ["porch"],
  poke: ["pore"],
  pole: ["pose"],
  poof: ["poop"],
  prof: ["prop"],
  profane: ["propane"],
  profound: ["propound"],
  protect: ["project"],
  protection: ["projection"],
  protectionist: ["projectionist"],
  protector: ["projector"],
  puke: ["pure"],
  pule: ["puce"],
  put: ["pub"],
  raft: ["rapt"],
  ragtag: ["ragbag"],
  rake: ["rare"],
  ray: ["ram"],
  realtor: ["reactor"],
  ref: ["rep"],
  refine: ["repine"],
  refutable: ["reputable"],
  refutation: ["reputation"],
  refute: ["repute"],
  relent: ["recent", "resent"],
  repaint: ["reprint"],
  revile: ["revise"],
  reviler: ["reviser"],
  rife: ["ripe"],
  rile: ["rice", "rise"],
  roe: ["rob"],
  role: ["rose"],
  rot: ["rob"],
  rote: ["robe"],
  rove: ["roue"],
  rue: ["rub"],
  rule: ["ruse"],
  rut: ["rub"],
  scarf: ["scarp"],
  scat: ["scab"],
  seek: ["seer"],
  servile: ["service"],
  shake: ["share"],
  shaker: ["sharer"],
  shay: ["sham"],
  shirk: ["shirr"],
  shoat: ["short"],
  shod: ["shoo"],
  silk: ["sick"],
  silken: ["sicken"],
  six: ["sir"],
  slab: ["scab"],
  slam: ["scam"],
  slant: ["scant"],
  slat: ["scat", "slab"],
  slay: ["slam"],
  sloe: ["slob"],
  sloop: ["scoop"],
  slope: ["scope"],
  slot: ["slob"],
  slow: ["scow"],
  slum: ["scum"],
  slummy: ["scummy"],
  slurry: ["scurry"],
  snake: ["snare"],
  snot: ["snob"],
  soak: ["soar"],
  soaking: ["soaring"],
  sold: ["solo"],
  sot: ["sob"],
  spake: ["spare"],
  spay: ["spry"],
  speak: ["spear"],
  spike: ["spire"],
  spiky: ["spiry"],
  spoke: ["spore"],
  spook: ["spoor"],
  squat: ["squab"],
  stake: ["stare"],
  stalk: ["stack"],
  stalked: ["stacked"],
  stat: ["stab"],
  stoke: ["store"],
  story: ["storm"],
  strife: ["stripe"],
  sublet: ["subset"],
  sue: ["sub"],
  sulk: ["suck"],
  swat: ["swab"],
  sway: ["swam"],
  t: ["j", "b"],
  tab: ["jab"],
  tack: ["jack", "back"],
  tacker: ["backer"],
  tad: ["bad"],
  tag: ["jag", "bag"],
  tail: ["jail", "bail"],
  tailor: ["jailor"],
  take: ["bake", "tare"],
  taker: ["baker"],
  tale: ["bale"],
  talk: ["balk", "tack", "task"],
  talker: ["tacker"],
  talky: ["balky", "tacky"],
  tall: ["ball", "talc"],
  tam: ["jam"],
  tan: ["ban"],
  tang: ["bang"],
  tangle: ["jangle", "bangle"],
  tank: ["bank"],
  tanker: ["banker"],
  tanner: ["banner"],
  tape: ["jape"],
  tar: ["jar", "bar"],
  tare: ["bare"],
  tarn: ["barn"],
  task: ["bask"],
  taste: ["baste"],
  taster: ["baster"],
  tat: ["bat", "tab"],
  tatter: ["batter"],
  tattered: ["battered"],
  tatting: ["batting"],
  tattle: ["battle"],
  tattler: ["battler"],
  taunt: ["jaunt"],
  tax: ["tar"],
  teach: ["beach"],
  teak: ["beak", "tear"],
  team: ["beam", "term"],
  tear: ["bear"],
  teary: ["terry"],
  tease: ["terse"],
  teat: ["beat"],
  tee: ["bee"],
  teen: ["been"],
  tell: ["jell", "bell"],
  tend: ["bend"],
  tender: ["bender"],
  tent: ["bent"],
  term: ["berm"],
  terry: ["berry"],
  test: ["jest", "best"], //Surely you jest, for you cannot best me
  tester: ["jester"],
  they: ["them"],
  thole: ["those"],
  throe: ["throb"],
  ti: ["bi"],
  ticker: ["bicker"],
  tide: ["bide"],
  tier: ["bier"],
  tight: ["bight"],
  tike: ["bike", "tire"],
  til: ["'tis"],
  tile: ["bile"],
  till: ["bill"],
  tillable: ["billable"],
  tilt: ["jilt"],
  tin: ["bin"],
  tinder: ["binder"],
  tinge: ["binge"],
  tingle: ["jingle"],
  tingly: ["jingly"],
  tit: ["bit"],
  titter: ["bitter"],
  toast: ["boast"],
  toaster: ["boaster"],
  tog: ["jog", "bog", "too"],
  toggle: ["joggle", "boggle"],
  toil: ["boil"],
  toiler: ["boiler"],
  toke: ["joke", "tore"],
  told: ["bold"],
  tole: ["bole"],
  toll: ["boll"],
  tomb: ["bomb"],
  tome: ["tomb"],
  tone: ["bone"],
  toneless: ["boneless"],
  toner: ["boner"],
  tong: ["bong"],
  tony: ["bony"],
  too: ["boo"],
  took: ["book"],
  toot: ["boot"],
  tooth: ["booth"],
  top: ["bop"],
  tore: ["bore"],
  torn: ["born"],
  toss: ["boss"],
  tot: ["jot"],
  totter: ["jotter"],
  tough: ["bough"],
  tourney: ["journey"],
  tout: ["bout"],
  tow: ["bow"],
  towel: ["bowel"],
  tower: ["bower"],
  towline: ["bowline"],
  toy: ["joy", "boy", "tom"],
  trace: ["brace"],
  tracer: ["bracer"],
  tracing: ["bracing"],
  tract: ["bract"],
  train: ["brain"],
  trash: ["brash"],
  trawl: ["brawl"],
  trawler: ["brawler"],
  tray: ["bray", "tram"],
  tread: ["bread"],
  tribe: ["bribe"],
  trick: ["brick"],
  trier: ["brier"],
  trifle: ["triple"],
  trig: ["brig", "trio"],
  trim: ["brim"],
  trite: ["tribe"],
  troth: ["broth"], //archaic truth
  trow: ["brow"],
  tub: ["bub"],
  tuck: ["buck"],
  tug: ["jug", "bug"],
  tumble: ["jumble", "bumble"],
  tumbler: ["bumbler"],
  tumbling: ["bumbling"],
  tun: ["bun"],
  tunny: ["bunny"], //tuna
  turn: ["burn"],
  turner: ["burner"],
  turning: ["burning"],
  turnout: ["burnout"],
  tush: ["bush"],
  tut: ["jut", "but", "tub"],
  unmarked: ["unmarred"],
  v: ["u"],
  vale: ["vase"],
  valve: ["value"],
  valved: ["valued"],
  valveless: ["valueless"],
  vile: ["vice", "vise"],
  voile: ["voice"],
  waist: ["wrist"],
  waistband: ["wristband"],
  wait: ["writ"],
  waiter: ["writer"],
  waiting: ["writing"],
  wake: ["ware"],
  wary: ["warm"],
  wax: ["war"],
  waxiness: ["wariness"],
  waxy: ["wary"],
  way: ["wry"],
  weak: ["wear"],
  wee: ["web"],
  weft: ["wept"],
  welt: ["west"],
  wet: ["web"],
  whole: ["whose"],
  wife: ["wipe"],
  wile: ["wise"],
  wilt: ["wist"],
  wind: ["wino"],
  wing: ["wino"],
  woke: ["wore"],
  x: ["r"],
  y: ["m"],
  ya: ["ma"],
  yap: ["map"],
  yarrow: ["marrow"],
  yaw: ["maw"],
  yawl: ["yaws"],
  ye: ["me"],
  yellow: ["mellow"],
  yellowness: ["mellowness"],
  yen: ["men"],
  yet: ["met"],
  yew: ["mew"],
  yodel: ["model"],
  yodeler: ["modeler"],
  yoke: ["yore"],
  yore: ["more"],
  youth: ["mouth"],
  youthful: ["mouthful"],
  yow: ["mow"],
  yuck: ["muck"],
  yucky: ["mucky"],
  yule: ["mule"],
  yum: ["mum"],
  yummy: ["mummy"],
};

export default data;
