const data = {
  acidify: ["acidity"],
  age: ["ace"],
  ail: ["all"],
  ale: ["ate"],
  all: ["ail"],
  alone: ["atone"],
  alp: ["alb"],
  altar: ["attar"],
  altitude: ["attitude"],
  am: ["aw"],
  ample: ["amble"],
  any: ["and"],
  arson: ["argon"],
  ate: ["ale"],
  atone: ["alone"],
  attar: ["altar"],
  attitude: ["altitude"], //CHange you altitude
  auger: ["anger"],
  bail: ["ball", "bait"],
  bait: ["bail"],
  bale: ["bate"],
  ball: ["bail"],
  barf: ["barb"],
  bate: ["bale"],
  baud: ["band"],
  bay: ["bad"],
  beau: ["bean"],
  beef: ["beet"],
  belie: ["belle"],
  bell: ["belt"],
  belle: ["belie"],
  belt: ["bell"],
  berry: ["beery"],
  beset: ["beget"],
  besot: ["begot"],
  best: ["beat"],
  bey: ["bed"],
  bile: ["bite"],
  bite: ["bile"],
  blase: ["blaze"],
  blowsy: ["blowzy"],
  blur: ["blue"],
  blurt: ["bluet"],
  boil: ["boll"],
  boll: ["boil", "bolt"],
  bolt: ["boll"],
  bony: ["bond"],
  bop: ["bob"],
  boy: ["bod"],
  brad: ["bead"],
  bran: ["bean"],
  brat: ["beat"],
  bray: ["brad"],
  bring: ["being"],
  buns: ["bung"],
  bursar: ["bursae"],
  bus: ["bug"],
  butler: ["butter"],
  butter: ["butler"],
  buy: ["bud"],
  caliper: ["caliber"],
  cam: ["caw"],
  camper: ["camber"],
  canary: ["canard"],
  cap: ["cab"],
  carpel: ["carpet"],
  carpet: ["carpel"],
  case: ["cage"],
  casually: ["casualty"],
  casualty: ["casually"],
  cay: ["cad"],
  certainly: ["certainty"],
  certainty: ["certainly"],
  change: ["chance"],
  charily: ["charity"],
  charity: ["charily"],
  chary: ["chard"], //reluctant to do something
  cherry: ["cheery"],
  chest: ["cheat"],
  chili: ["chill"],
  chill: ["chili"],
  chores: ["chorea"],
  clam: ["claw"],
  clarify: ["clarity"],
  clay: ["clad"],
  cloy: ["clod"],
  coal: ["coat"],
  coat: ["coal"],
  cochlear: ["cochleae"],
  coffer: ["coffee"],
  comer: ["cower"],
  comp: ["comb"],
  confuse: ["contuse"], //bruise
  confusion: ["contusion"],
  congeal: ["conceal"],
  congealment: ["concealment"],
  converse: ["converge"],
  cool: ["coot"],
  coolie: ["cootie"],
  coot: ["cool"],
  cootie: ["coolie"],
  cop: ["cob"],
  copra: ["cobra"], //coconut kernels
  cord: ["coed"],
  cost: ["coat"],
  cosy: ["cozy"],
  couch: ["conch"], //USE
  cough: ["couch"],
  coy: ["cod"],
  cram: ["craw"],
  crap: ["crab"],
  crosier: ["crozier"],
  cruel: ["cruet"],
  cruelly: ["cruelty"],
  cruelty: ["cruelly"],
  cruet: ["cruel"],
  crumple: ["crumble"], //USE
  cull: ["cult"],
  cult: ["cull"],
  cup: ["cub"],
  cur: ["cue"],
  curl: ["curt"],
  curt: ["curl"],
  cutler: ["cutter"],
  cutter: ["cutler"],
  daily: ["dally"],
  dale: ["date"],
  dally: ["daily"],
  damn: ["dawn"],
  danger: ["dancer"],
  date: ["dale"],
  day: ["dad"],
  def: ["deb"],
  defect: ["detect"],
  defection: ["detection"],
  defective: ["detective"], //USE
  defector: ["detector"],
  defer: ["deter"],
  deferment: ["determent"],
  deft: ["debt"],
  degree: ["decree"],
  deify: ["deity"],
  delectable: ["detectable"],
  deli: ["dell"],
  dell: ["deli"],
  detectable: ["delectable"], //USE
  dignify: ["dignity"],
  dirt: ["diet"],
  dis: ["dig"],
  disloyally: ["disloyalty"],
  disloyalty: ["disloyally"],
  ditsy: ["ditzy"],
  diverse: ["diverge"],
  diversify: ["diversity"],
  dog: ["doc"], //USE
  doily: ["dolly"],
  dole: ["dote"],
  doll: ["dolt"],
  dolly: ["doily"],
  dolt: ["doll"],
  dose: ["doze", "doge"],
  dote: ["dole"],
  drafter: ["draftee"], //USE
  dram: ["draw"],
  dress: ["dregs"],
  ducal: ["ducat"],
  ducat: ["ducal"],
  duel: ["duet"], //USE let's have a duet
  duet: ["duel"],
  duly: ["duty"],
  dump: ["dumb"],
  duty: ["duly"],
  dwell: ["dwelt"],
  dwelt: ["dwell"],
  eider: ["elder"], //type of duck
  eject: ["elect"], // Eject them
  ejection: ["election"],
  ejector: ["elector"],
  elder: ["eider"],
  elude: ["etude"],
  employer: ["employee"], //opposites
  empower: ["embower"], //surround of shelter with plants, could use with EM leaf scene
  entirely: ["entirety"],
  entirety: ["entirely"],
  err: ["ere"],
  ester: ["eater"],
  etude: ["elude"],
  exorcise: ["exorcize"],
  f: ["t", "b", "z"],
  fable: ["table"],
  fact: ["tact"],
  fad: ["tad", "bad"],
  fade: ["bade"],
  fag: ["tag", "bag"],
  fail: ["tail", "bail", "fall"],
  faint: ["taint"],
  fake: ["take", "bake"],
  faker: ["taker", "baker"],
  fall: ["tall", "ball", "fail"],
  fallow: ["tallow"], //period characterized by inaction
  falls: ["balls"],
  falsify: ["falsity"],
  fame: ["tame"],
  fan: ["tan", "ban"],
  fang: ["tang", "bang"],
  far: ["tar", "bar"],
  fare: ["tare", "bare"],
  faro: ["taro"],
  farrier: ["barrier"],
  farrow: ["barrow"],
  fart: ["tart"],
  fast: ["bast"],
  fat: ["tat", "bat"],
  fate: ["bate"],
  fated: ["bated"],
  father: ["bather"], //Kind of funny
  fatten: ["batten"], //Could be funny
  fatty: ["batty"],
  fax: ["tax"],
  fay: ["bay", "fad"],
  fear: ["tear", "bear"],
  fearful: ["tearful"],
  fearfully: ["tearfully"],
  feast: ["beast"],
  feat: ["teat", "beat"],
  fed: ["bed", "zed"],
  fee: ["tee", "bee"],
  feel: ["feet"],
  feet: ["beet", "feel"],
  fell: ["tell", "bell", "felt"],
  fellow: ["bellow"],
  felt: ["belt", "fell"],
  fen: ["ten"],
  fend: ["tend", "bend"],
  fender: ["tender", "bender"],
  fern: ["tern"],
  ferry: ["terry", "berry"], //Take the berry
  fest: ["test", "best", "zest", "feat"],
  fester: ["tester"],
  feta: ["beta", "zeta"],
  fetter: ["better"],
  feud: ["fend"],
  fey: ["bey", "fed"],
  fiat: ["flat"],
  fib: ["bib"],
  fibular: ["fibulae"],
  fickle: ["tickle"],
  fie: ["tie"],
  fifer: ["fiber"],
  fig: ["big"],
  fight: ["tight", "bight"],
  filch: ["zilch"],
  file: ["tile", "bile"],
  filer: ["tiler"],
  filing: ["tiling"],
  fill: ["till", "bill"],
  filler: ["tiller", "filter"],
  fillet: ["billet"],
  filling: ["billing"],
  filly: ["billy", "fitly"],
  filter: ["fitter", "filler"],
  fin: ["tin", "bin"],
  find: ["bind"],
  finder: ["tinder", "binder"],
  finding: ["binding"],
  fine: ["tine"],
  finger: ["zinger"],
  finny: ["tinny"],
  fir: ["fie"],
  fire: ["tire"],
  firth: ["birth"],
  fist: ["fiat"],
  fit: ["tit", "bit", "zit"],
  fitly: ["filly"],
  fitter: ["titter", "bitter", "filter"],
  fizzy: ["tizzy"],
  flab: ["blab"],
  flack: ["black"],
  flame: ["blame"],
  flank: ["blank"],
  flap: ["flab"],
  flare: ["blare"],
  flat: ["fiat"],
  flatfish: ["flattish"],
  fled: ["bled"],
  flew: ["blew"],
  flight: ["blight"],
  flip: ["blip"],
  float: ["bloat"],
  flock: ["block"],
  flood: ["blood"],
  flow: ["blow"],
  flower: ["blower"],
  flown: ["blown"],
  flue: ["blue"],
  fluff: ["bluff"],
  flurry: ["blurry"],
  flush: ["blush"],
  fluster: ["bluster"],
  fob: ["bob"],
  foe: ["toe"],
  fog: ["tog", "bog"],
  fogey: ["bogey"],
  foggy: ["boggy"],
  fogy: ["bogy"],
  foil: ["toil", "boil"],
  fold: ["told", "bold"],
  fond: ["bond"],
  fool: ["tool", "foot"],
  foot: ["toot", "boot", "fool"],
  footfall: ["football"],
  footless: ["bootless"],
  fop: ["top", "bop", "fob"],
  for: ["tor", "foe"],
  fore: ["tore", "bore"],
  forge: ["force"],
  formal: ["format"],
  format: ["formal"],
  fort: ["tort"],
  forte: ["torte"], //pastry
  fought: ["bought"], //USE
  found: ["bound"],
  founder: ["bounder"],
  four: ["tour"],
  fowl: ["bowl"],
  fox: ["box"],
  foxy: ["boxy"],
  fraction: ["traction"],
  frail: ["trail"],
  frailly: ["frailty"],
  frailty: ["frailly"],
  franchiser: ["franchisee"], //opposite
  frat: ["brat", "feat"],
  fray: ["tray", "bray"],
  freak: ["break"],
  freakout: ["breakout"],
  free: ["tree"],
  freeze: ["breeze"], //funny visual
  fret: ["feet"],
  friar: ["briar"],
  fridge: ["bridge"],
  fried: ["tried"],
  fright: ["bright"],
  frighten: ["brighten"], //funny visual
  frill: ["trill"],
  frisk: ["brisk"],
  fro: ["bro"],
  froth: ["troth", "broth"],
  frown: ["brown"],
  fruit: ["bruit"], //spread a rumor
  frump: ["trump"],
  fry: ["try", "fey"],
  fuck: ["tuck", "buck"],
  fucker: ["tucker"],
  fudge: ["budge"],
  full: ["bull"],
  fully: ["bully"],
  fumble: ["tumble", "bumble"],
  fumbler: ["tumbler", "bumbler"],
  fun: ["tun", "bun"],
  funk: ["bunk"],
  funnel: ["tunnel"],
  funny: ["tunny", "bunny"],
  fur: ["bur"],
  furl: ["burl", "fuel"],
  furnish: ["burnish"], //polish
  furnished: ["burnished"],
  furrow: ["burrow"],
  fury: ["bury"],
  fuse: ["fuze"],
  fuss: ["buss"],
  fusty: ["busty"],
  fuzz: ["buzz"],
  g: ["c", "q"],
  gab: ["cab"],
  gabby: ["cabby"],
  gable: ["cable"], //wall that encloses roof
  gad: ["cad"],
  gage: ["cage"],
  gale: ["gate"],
  gall: ["call"],
  galling: ["calling"],
  game: ["came"],
  gap: ["cap", "gab"],
  gape: ["cape"],
  gar: ["car"],
  garter: ["carter"],
  gas: ["gag"],
  gash: ["cash"],
  gasket: ["casket"],
  gate: ["gale"],
  gave: ["cave"],
  gay: ["cay", "gad"],
  gel: ["get"],
  gent: ["cent"],
  get: ["gel"],
  gill: ["gilt"],
  gilt: ["gill"],
  girl: ["girt"],
  girt: ["girl"],
  gismo: ["gizmo"],
  glad: ["clad"],
  glamor: ["clamor"],
  glamorous: ["clamorous"], //noisy
  glass: ["class"],
  glassiness: ["classiness"],
  glassy: ["classy"],
  glean: ["clean"],
  gleaner: ["cleaner"],
  glop: ["clop", "glob"],
  glove: ["clove"],
  glue: ["clue"],
  goal: ["coal", "goat"],
  goat: ["coat", "goal"],
  gob: ["cob"],
  gobble: ["cobble"],
  gobbler: ["cobbler"],
  god: ["cod"],
  gold: ["cold"],
  gone: ["cone"],
  goo: ["coo"],
  gook: ["cook"],
  goon: ["coon"],
  goop: ["coop"],
  gore: ["core"],
  gorse: ["gorge"],
  got: ["cot"],
  grab: ["crab"],
  grabber: ["crabber"],
  grabby: ["crabby"],
  grackle: ["crackle"], //bird
  graft: ["craft"],
  gram: ["cram"],
  granny: ["cranny"],
  granter: ["grantee"], //opposite
  grape: ["crape"],
  grass: ["crass"],
  grate: ["crate"],
  grater: ["crater"],
  grave: ["crave"],
  graven: ["craven"],
  gray: ["grad"],
  graze: ["craze"],
  grease: ["crease"],
  greed: ["creed"],
  grew: ["crew"],
  grime: ["crime"],
  gross: ["cross"],
  grossly: ["crossly"],
  grossness: ["crossness"],
  grouch: ["crouch"],
  group: ["croup"],
  grow: ["crow"],
  grown: ["crown"],
  gruel: ["cruel"],
  grumble: ["crumble"], //Could have like a visual here of him crumbling something up while grumbling
  guest: ["quest"],
  guff: ["cuff"],
  guilt: ["quilt"],
  gull: ["cull"],
  gum: ["cum"],
  gushy: ["cushy"],
  gut: ["cut"],
  gutter: ["cutter"],
  hail: ["hall"],
  hale: ["hate"],
  half: ["halt"],
  hall: ["hail", "halt"],
  halt: ["hall"],
  halter: ["hatter"],
  ham: ["haw"],
  has: ["hag"],
  hate: ["hale"],
  hatter: ["halter"],
  hay: ["had"],
  heal: ["heat"],
  healer: ["heater"],
  heat: ["heal"],
  heater: ["healer"],
  hem: ["hew"],
  herd: ["heed"],
  hill: ["hilt"],
  hilt: ["hill"],
  hoary: ["hoard"],
  holly: ["hotly"],
  holy: ["hold"],
  honorer: ["honoree"], //USE
  hoof: ["hoot"],
  hookey: ["hooked"],
  hop: ["hob"],
  hotly: ["holly"],
  humidify: ["humidity"],
  hurl: ["hurt"],
  hurt: ["hurl"],
  I: ["l"],
  i: ["l"],
  iamb: ["lamb"],
  identify: ["identity"],
  ides: ["idea"],
  if: ["it"],
  indemnify: ["indemnity"],
  infer: ["inter"],
  inferior: ["interior"], //USE
  infernal: ["internal"],
  infernally: ["internally"],
  info: ["into"],
  ingest: ["incest"],
  intensify: ["intensity"],
  interviewer: ["interviewee"], //USE
  j: ["l"],
  jab: ["lab"],
  jack: ["lack"],
  jade: ["lade"],
  jag: ["lag"],
  jam: ["lam", "jaw"],
  jamb: ["lamb"],
  java: ["lava"],
  jaw: ["law"],
  jawbreaker: ["lawbreaker"], //funny visual
  jay: ["lay"],
  jean: ["lean"],
  jeer: ["leer"],
  jest: ["lest"],
  jet: ["let"],
  jib: ["lib"],
  jilt: ["lilt"],
  jitterbug: ["litterbug"],
  jive: ["live"],
  job: ["lob"],
  jobber: ["lobber"],
  jock: ["lock"],
  jog: ["log"],
  jogger: ["logger"],
  jogging: ["logging"],
  join: ["loin"],
  jollily: ["jollity"],
  jollity: ["jollily"],
  jolter: ["jotter"],
  jot: ["lot"],
  jotter: ["jolter"],
  jowly: ["lowly"],
  jug: ["lug"],
  jump: ["lump"],
  jumpiness: ["lumpiness"],
  jumpy: ["lumpy"],
  just: ["lust"],
  jute: ["lute"],
  kill: ["kilt"],
  killer: ["kilter"],
  kilt: ["kill"],
  kilter: ["killer"],
  knell: ["knelt"],
  knelt: ["knell"],
  l: ["i", "t"],
  lab: ["tab"],
  lack: ["tack"],
  lactic: ["tactic"],
  lad: ["tad"],
  lag: ["tag", "lac"],
  lake: ["take"],
  lam: ["tam", "law"],
  lamb: ["iamb"],
  lame: ["tame"],
  lamely: ["tamely"],
  lameness: ["tameness"],
  laminar: ["laminae"],
  lamp: ["tamp", "lamb"],
  lank: ["tank"],
  lap: ["tap", "lab"],
  lapel: ["label"],
  lappet: ["tappet"],
  lardy: ["tardy"],
  laser: ["lager"],
  lasting: ["tasting"],
  later: ["tater"],
  latter: ["tatter"],
  laud: ["land"],
  lax: ["tax"],
  lay: ["lad"],
  lea: ["tea"],
  leach: ["teach"],
  leak: ["teak"],
  lease: ["tease"],
  leaser: ["teaser"],
  lech: ["tech"],
  lee: ["tee"],
  lend: ["tend"],
  lender: ["tender"],
  lent: ["tent"],
  lesion: ["legion"],
  lesser: ["leaser", "lessee"],
  lest: ["test"],
  lever: ["levee"],
  lick: ["tick"],
  licking: ["ticking"],
  lie: ["tie"],
  lieu: ["lien"],
  life: ["lite"],
  lifer: ["liter"],
  lifter: ["litter"],
  light: ["tight"],
  lighten: ["tighten"],
  lightener: ["tightener"],
  lightly: ["tightly"],
  lightness: ["tightness"],
  lights: ["tights"],
  like: ["tike"],
  lilt: ["tilt"],
  limber: ["timber"],
  lime: ["time"],
  limp: ["limb"],
  line: ["tine"],
  lint: ["tint"],
  lip: ["tip", "lib"],
  lire: ["tire"],
  lit: ["tit"],
  lithe: ["tithe"],
  litter: ["titter"],
  little: ["tittle"],
  lo: ["to"],
  load: ["toad"],
  locale: ["locate"],
  locate: ["locale"],
  log: ["tog"],
  logo: ["loco"],
  loll: ["toll"],
  lone: ["tone"],
  loner: ["toner"],
  long: ["tong"],
  look: ["took"],
  loot: ["toot"],
  looter: ["tooter"],
  lop: ["top", "lob"],
  lope: ["lobe"],
  lore: ["tore"],
  lorn: ["torn"],
  lose: ["loge"],
  loss: ["toss"],
  lot: ["tot"],
  lout: ["tout"],
  low: ["tow"],
  lower: ["tower"],
  loyally: ["loyalty"],
  loyalty: ["loyally"],
  lube: ["tube"],
  luck: ["tuck"],
  lug: ["tug"],
  lush: ["tush"],
  lying: ["tying"],
  m: ["w"],
  mad: ["wad"],
  madding: ["wadding"],
  made: ["wade"],
  mag: ["wag"],
  mail: ["wail", "mall"],
  mailer: ["wailer"],
  mailing: ["wailing"],
  main: ["wain"],
  make: ["wake"],
  making: ["waking"],
  male: ["wale", "mate"],
  mall: ["wall", "mail", "malt"],
  mallet: ["wallet"],
  mallow: ["wallow"],
  malt: ["matt", "mall"],
  malted: ["matted"],
  man: ["wan"],
  mane: ["wane"],
  mangle: ["wangle"],
  manly: ["wanly"],
  manna: ["wanna"],
  manse: ["mange"],
  mar: ["war"],
  marble: ["warble"],
  mare: ["ware"],
  marl: ["mart"],
  marlin: ["martin"],
  mart: ["wart", "marl"],
  martin: ["marlin"],
  mash: ["wash"],
  masher: ["washer"],
  mast: ["wast"],
  masted: ["wasted"],
  master: ["waster"],
  match: ["watch"],
  matchmaker: ["watchmaker"],
  matchmaking: ["watchmaking"],
  mate: ["male"],
  matins: ["mating"],
  matt: ["watt", "malt"],
  matted: ["malted"],
  max: ["wax"],
  may: ["way", "mad"],
  me: ["we"],
  meal: ["weal", "meat"],
  mealiness: ["meatiness"],
  mealy: ["meaty"],
  mean: ["wean"],
  meat: ["meal"],
  meatiness: ["mealiness"],
  meaty: ["mealy"],
  meed: ["weed"],
  meek: ["week"],
  meekly: ["weekly"],
  meld: ["weld"],
  melt: ["welt"],
  men: ["wen"],
  menage: ["menace"],
  mend: ["wend"],
  mere: ["were"],
  merger: ["mercer"],
  mess: ["mesa"],
  met: ["wet"],
  might: ["wight"],
  mild: ["wild"],
  mildly: ["wildly"],
  mildness: ["wildness"],
  mile: ["wile", "mite"],
  miler: ["miter"],
  mill: ["will", "milt"],
  milling: ["willing"],
  milt: ["wilt", "mitt", "mill"],
  mince: ["wince"],
  mind: ["wind"],
  minded: ["winded"],
  mindless: ["windless"],
  mine: ["wine"],
  mink: ["wink"], //Mr. murmerer winks at him and todbot releases a mink on him haha. Where could i put it though
  minnow: ["winnow"],
  minter: ["winter"],
  mire: ["wire"],
  miry: ["wiry"],
  misspell: ["misspelt"],
  misspelt: ["misspell"],
  mist: ["wist"],
  mite: ["mile"],
  miter: ["miler"],
  mitt: ["milt"],
  moil: ["moll"],
  mold: ["wold"],
  mole: ["mote"],
  moll: ["moil", "molt"],
  molt: ["moll"],
  mom: ["mow"],
  monk: ["wonk"],
  moo: ["woo"],
  mood: ["wood"],
  moodiness: ["woodiness"],
  moody: ["woody"],
  mop: ["mob"],
  mopey: ["moped"],
  more: ["wore"],
  morn: ["worn"],
  mortgager: ["mortgagee"],
  most: ["moat"],
  mote: ["mole"],
  motel: ["motet"],
  motet: ["motel"],
  mound: ["wound"],
  mouth: ["month"],
  move: ["wove"],
  mow: ["wow"],
  mule: ["mute"],
  muss: ["wuss"],
  mussy: ["wussy"],
  mute: ["mule"],
  naively: ["naivety"],
  naivety: ["naively"],
  nap: ["nab"],
  nebular: ["nebulae"],
  nerd: ["need"],
  nerdy: ["needy"],
  nest: ["neat"],
  nicely: ["nicety"],
  nicety: ["nicely"],
  nil: ["nit"],
  nip: ["nib"],
  nit: ["nil"],
  nosey: ["nosed"],
  nullify: ["nullity"],
  oaf: ["oat"],
  off: ["oft"],
  om: ["ow"],
  outfox: ["outbox"],
  outrage: ["outrace"],
  overflown: ["overblown"],
  overfly: ["overtly"],
  overlook: ["overtook"],
  overtook: ["overlook"],
  p: ["b"],
  pack: ["back"],
  packer: ["backer"],
  packing: ["backing"],
  pad: ["bad"],
  page: ["pace"],
  pager: ["pacer"],
  pail: ["bail", "pall"],
  pal: ["pat"],
  pale: ["bale", "pate"],
  pall: ["ball", "pail"],
  pallet: ["ballet"],
  palm: ["balm"],
  palmy: ["balmy"],
  palsy: ["patsy"],
  pan: ["ban"],
  pane: ["bane"],
  pang: ["bang"],
  par: ["bar"],
  pare: ["bare"],
  parish: ["pariah"],
  park: ["bark"],
  parley: ["barley"],
  pass: ["bass"],
  past: ["bast"],
  paste: ["baste"],
  pat: ["bat", "pal"],
  patch: ["batch"],
  pate: ["bate", "pale"],
  path: ["bath"],
  pathetic: ["bathetic"],
  pathos: ["bathos"],
  patsy: ["palsy"],
  patter: ["batter"],
  patty: ["batty"],
  pawl: ["bawl"],
  pay: ["bay", "pad"],
  payer: ["payee"],
  peach: ["beach"],
  peak: ["beak"],
  peaked: ["beaked"],
  peal: ["peat"],
  pear: ["bear"],
  peat: ["beat", "peal"],
  peck: ["beck"],
  pee: ["bee"],
  peen: ["been"],
  peep: ["beep"],
  peeper: ["beeper"],
  peer: ["beer"],
  peg: ["beg"],
  pelf: ["pelt"],
  pelt: ["belt"],
  pend: ["bend"],
  pent: ["bent"],
  per: ["pee"],
  perk: ["peek"],
  perm: ["berm"],
  personally: ["personalty"],
  personalty: ["personally"],
  pest: ["best", "peat"],
  pet: ["bet"],
  pi: ["bi"],
  picker: ["bicker"],
  pied: ["pled"],
  pier: ["bier"],
  pig: ["big", "pic"],
  piggish: ["biggish"],
  pike: ["bike"],
  piker: ["biker"],
  pile: ["bile"],
  pill: ["bill"],
  pillion: ["billion"],
  pillow: ["billow"],
  pin: ["bin"],
  pinnacle: ["binnacle"],
  pis: ["pig"],
  pit: ["bit"],
  pitch: ["bitch"],
  plague: ["plaque"],
  plank: ["blank"],
  plaster: ["blaster"],
  pleat: ["bleat"],
  pled: ["bled", "pied"],
  plight: ["blight"],
  plot: ["blot"],
  plotter: ["blotter"],
  plow: ["blow"],
  ploy: ["plod"],
  plump: ["plumb"],
  plunder: ["blunder"],
  plunderer: ["blunderer"],
  plus: ["plug"],
  plush: ["blush"],
  pock: ["bock"],
  pod: ["bod"],
  poi: ["pol"],
  pol: ["poi", "pot"],
  pole: ["bole"],
  poll: ["boll"],
  pond: ["bond"],
  pone: ["bone"],
  pony: ["bony", "pond"],
  poodle: ["boodle"],
  poor: ["boor"],
  pop: ["bop"],
  pore: ["bore"],
  porn: ["born"],
  port: ["poet"],
  posh: ["bosh"],
  pot: ["pol"],
  pother: ["bother"],
  pounce: ["bounce"],
  pound: ["bound"],
  pout: ["bout"],
  power: ["bower"],
  powwow: ["bowwow"],
  pox: ["box"],
  praise: ["braise"],
  prawn: ["brawn"],
  pray: ["bray"],
  preach: ["breach"],
  prep: ["peep"],
  prick: ["brick"],
  pride: ["bride"],
  prier: ["brier"],
  prig: ["brig"],
  prim: ["brim"],
  pro: ["bro"],
  prom: ["prow"],
  properly: ["property"],
  property: ["properly"],
  prow: ["brow"],
  psst: ["past"],
  pub: ["bub"],
  puck: ["buck"],
  pudding: ["budding"],
  puff: ["buff"],
  puffer: ["buffer"],
  pug: ["bug"],
  pull: ["bull"],
  pullet: ["bullet"],
  pump: ["bump"],
  pumper: ["bumper"],
  pumpkin: ["bumpkin"],
  pun: ["bun"],
  punch: ["bunch"],
  punchy: ["bunchy"],
  punk: ["bunk"],
  punt: ["bunt"],
  pup: ["pub"],
  purger: ["burger"],
  purify: ["purity"],
  purl: ["burl"],
  purr: ["burr", "pure"],
  purse: ["purge"],
  purser: ["purger"],
  pus: ["bus", "pug"],
  push: ["bush"],
  pushiness: ["bushiness"],
  pushing: ["bushing"],
  pushy: ["bushy"],
  puss: ["buss"],
  put: ["but"],
  putt: ["butt"],
  putter: ["butter", "puttee"],
  q: ["d"],
  qualify: ["quality"],
  quality: ["duality"],
  quantify: ["quantity"],
  quay: ["quad"],
  quill: ["quilt"],
  quilt: ["quill"],
  quilter: ["quitter"],
  quirt: ["quiet"],
  quitter: ["quilter"],
  r: ["e"],
  rafter: ["ratter"],
  rage: ["race"],
  raging: ["racing"],
  rags: ["raga"],
  ram: ["raw"],
  rapid: ["rabid"],
  rapidly: ["rabidly"],
  rapidness: ["rabidness"],
  rat: ["eat"],
  rater: ["eater"],
  rats: ["eats"],
  rave: ["eave"],
  ray: ["rad"],
  rayon: ["radon"],
  really: ["realty"],
  realty: ["really"],
  refold: ["retold"],
  refract: ["retract"],
  refraction: ["retraction"],
  refrain: ["retrain"],
  refuse: ["refuge"],
  regent: ["recent"],
  remind: ["rewind"],
  repeal: ["repeat"],
  repeat: ["repeal"],
  repel: ["rebel"],
  resale: ["regale"],
  resent: ["regent"],
  resister: ["register"],
  rider: ["eider"],
  rife: ["rite"],
  riff: ["rift"],
  right: ["eight"],
  rile: ["rite"],
  rip: ["rib"],
  rite: ["rile"],
  roil: ["roll"],
  role: ["rote"],
  roll: ["roil"],
  roof: ["root"],
  roofed: ["rooted"],
  roofer: ["rooter"],
  roofless: ["rootless"],
  rope: ["robe"],
  rote: ["role"],
  rouse: ["rouge"],
  royally: ["royalty"],
  royalty: ["royally"],
  rumple: ["rumble"],
  runs: ["rung"],
  rye: ["eye"],
  s: ["z", "a", "g"],
  sable: ["gable"],
  sad: ["gad"],
  safe: ["sate"],
  safely: ["safety"],
  safety: ["safely"],
  sag: ["gag", "sac"],
  saga: ["gaga"],
  sage: ["gage"],
  sale: ["gale", "sate"],
  sally: ["salty"],
  salty: ["sally"],
  same: ["game"],
  sameness: ["gameness"],
  sanctify: ["sanctity"],
  sander: ["gander"],
  sang: ["gang"],
  sans: ["sang"],
  sap: ["zap", "gap"],
  sash: ["gash"],
  sassy: ["gassy"],
  sate: ["gate", "sale"],
  save: ["gave"],
  say: ["gay", "sad"],
  scaly: ["scald"],
  scapular: ["scapulae"],
  scorn: ["acorn"],
  seal: ["zeal", "seat"],
  sear: ["gear"],
  seat: ["seal"],
  secretarial: ["secretariat"],
  secretariat: ["secretarial"],
  see: ["gee"],
  seek: ["geek"],
  sender: ["gender"],
  sent: ["gent"],
  sentry: ["gentry"],
  serial: ["aerial"],
  serially: ["aerially"],
  set: ["get"],
  setter: ["settee"],
  setup: ["getup"],
  sh: ["ah"],
  shall: ["shalt"],
  shalt: ["shall"],
  shay: ["shad"],
  shifty: ["shitty"],
  shirr: ["shier", "shire"],
  shoal: ["shoat"],
  shoat: ["shoal"],
  sickie: ["sickle"],
  sickle: ["sickie"],
  side: ["aide"],
  sift: ["gift"],
  sifter: ["sitter"],
  sill: ["gill", "silt"],
  silly: ["silty"],
  silt: ["gilt", "sill"],
  silty: ["silly"],
  sin: ["gin"],
  sing: ["zing"],
  singe: ["since"],
  singer: ["zinger", "ginger"],
  sip: ["zip"],
  sipper: ["zipper"],
  sir: ["air"],
  sit: ["zit"],
  skin: ["akin"],
  slab: ["stab"],
  slack: ["alack", "stack"],
  slacks: ["stacks"],
  slag: ["stag"],
  slain: ["stain"],
  slake: ["stake"],
  slam: ["slaw"],
  slammer: ["stammer"],
  slander: ["stander"],
  slap: ["slab"],
  slash: ["stash"],
  slat: ["stat"],
  slate: ["state"],
  slave: ["stave"],
  slay: ["stay"],
  sleep: ["steep"],
  slew: ["stew"],
  slick: ["stick"],
  slicker: ["sticker"],
  slide: ["glide"],
  slider: ["glider"],
  slight: ["alight"],
  sling: ["sting"],
  slink: ["stink"],
  slinky: ["stinky"],
  slit: ["alit"],
  slob: ["glob"],
  sloe: ["aloe"],
  sloop: ["stoop"],
  slop: ["glop", "stop", "slob"],
  sloppy: ["gloppy"],
  slough: ["slouch"],
  slow: ["glow", "stow"],
  slue: ["glue"],
  slum: ["alum", "glum"],
  slump: ["stump"],
  slung: ["stung"],
  slunk: ["stunk"],
  slur: ["slue"],
  slut: ["glut"],
  sly: ["sty"],
  smash: ["swash"],
  smear: ["swear"],
  smell: ["swell", "smelt"],
  smelt: ["smell"],
  smelter: ["swelter"],
  smile: ["smite"],
  smite: ["smile"],
  snarl: ["gnarl"],
  sniffer: ["snifter"],
  snowfall: ["snowball"],
  so: ["go"],
  sob: ["gob"],
  sod: ["god"],
  sol: ["sot"],
  sold: ["gold"],
  solidify: ["solidity"],
  song: ["gong"],
  soon: ["goon"],
  sop: ["sob"],
  sore: ["gore"],
  sorta: ["aorta"],
  sot: ["got", "sol"],
  sown: ["gown"],
  soy: ["sod"],
  space: ["apace"],
  spacey: ["spaced"],
  specially: ["specialty"],
  specialty: ["specially"],
  spell: ["spelt"],
  spelt: ["spell"],
  spill: ["spilt"],
  spilt: ["spill"],
  ssh: ["ash"],
  stab: ["slab"],
  stack: ["slack"],
  stacks: ["slacks"],
  stag: ["slag"],
  stain: ["slain"],
  stake: ["slake"],
  stale: ["state"],
  stammer: ["slammer"],
  stander: ["slander", "standee"],
  staple: ["stable"],
  stash: ["slash"],
  stat: ["slat"],
  state: ["slate", "stale"],
  stave: ["slave"],
  stay: ["slay"],
  steep: ["sleep"],
  stem: ["stew"],
  stew: ["slew"],
  stick: ["slick"],
  sticker: ["slicker"],
  still: ["stilt"],
  stilt: ["atilt", "still"],
  sting: ["sling"],
  stink: ["slink"],
  stinky: ["slinky"],
  stone: ["atone"],
  stoop: ["sloop"],
  stop: ["atop", "slop"],
  stow: ["slow"],
  strep: ["steep"],
  stria: ["atria"],
  strive: ["striae"],
  stump: ["slump"],
  stung: ["slung"],
  stunk: ["slunk"],
  sty: ["sly"],
  submerse: ["submerge"],
  suction: ["auction"],
  suit: ["snit"],
  sully: ["gully"],
  sum: ["gum"],
  sun: ["gun"],
  sunk: ["gunk"],
  sunny: ["gunny"],
  sup: ["sub"],
  surely: ["surety"],
  surety: ["surely"],
  suspicious: ["auspicious"],
  suspiciously: ["auspiciously"],
  swap: ["swab"],
  sward: ["award"],
  swash: ["awash"],
  sway: ["away"],
  t: ["l"],
  tab: ["lab"],
  tack: ["lack"],
  tactic: ["lactic"],
  tad: ["lad"],
  tag: ["lag"],
  tail: ["tall"],
  take: ["lake"],
  tali: ["tall"],
  tall: ["tail", "tali"],
  tam: ["lam"],
  tame: ["lame"],
  tamely: ["lamely"],
  tameness: ["lameness"],
  tamp: ["lamp"],
  tank: ["lank"],
  tansy: ["tangy"],
  tap: ["lap", "tab"],
  tappet: ["lappet"],
  tardy: ["lardy"],
  tasting: ["lasting"],
  tater: ["later"],
  tatter: ["latter"],
  tau: ["tan"],
  tax: ["lax"],
  tea: ["lea"],
  teach: ["leach"],
  teak: ["leak"],
  teal: ["teat"],
  tease: ["lease"],
  teaser: ["leaser"],
  teat: ["teal"],
  tech: ["lech"],
  tee: ["lee"],
  tend: ["lend"],
  tender: ["lender"],
  tent: ["lent"],
  term: ["teem"],
  tern: ["teen"],
  test: ["lest", "teat"],
  them: ["thew"],
  thump: ["thumb"],
  thus: ["thug"],
  tick: ["lick"],
  ticking: ["licking"],
  tie: ["lie"],
  tight: ["light"],
  tighten: ["lighten"],
  tightener: ["lightener"],
  tightly: ["lightly"],
  tightness: ["lightness"],
  tights: ["lights"],
  tike: ["like"],
  till: ["tilt"],
  tilt: ["lilt", "till"],
  timber: ["limber"],
  time: ["lime"],
  tine: ["line"],
  tint: ["lint"],
  tip: ["lip"],
  tire: ["lire"],
  tit: ["lit"],
  tithe: ["lithe"],
  titter: ["litter"],
  tittle: ["little"],
  to: ["lo"],
  toad: ["load"],
  tog: ["log"],
  togs: ["toga"],
  toil: ["toll"],
  tole: ["tote"],
  toll: ["loll", "toil"],
  tom: ["tow"],
  tone: ["lone"],
  toner: ["loner"],
  tong: ["long"],
  took: ["look"],
  tool: ["toot"],
  toot: ["loot", "tool"],
  tooter: ["looter"],
  top: ["lop"],
  tor: ["toe"],
  tore: ["lore"],
  torn: ["lorn"],
  toss: ["loss", "togs"],
  tot: ["lot"],
  tote: ["tole"],
  tough: ["touch"],
  tout: ["lout"],
  tow: ["low"],
  tower: ["lower"],
  trail: ["trait"],
  trainer: ["trainee"],
  trait: ["trail"],
  tram: ["team"],
  tripe: ["tribe"],
  troy: ["trod"],
  tsar: ["tzar"],
  tsarina: ["tzarina"],
  tube: ["lube"],
  tuck: ["luck"],
  tug: ["lug"],
  tush: ["lush"],
  tying: ["lying"],
  u: ["n"],
  ulnar: ["ulnae"],
  uncertainly: ["uncertainty"],
  uncertainty: ["uncertainly"],
  unfold: ["untold"],
  unfounded: ["unbounded"],
  unhealed: ["unheated"],
  unheated: ["unhealed"],
  unify: ["unity"],
  unseal: ["unseat"],
  unseat: ["unseal"],
  uvular: ["uvulae"],
  v: ["a"],
  verify: ["verity"],
  verily: ["verity"],
  verity: ["verily"],
  verse: ["verge"],
  vim: ["aim"],
  visor: ["vizor", "vigor"],
  vole: ["vote"],
  vote: ["vole"],
  wafer: ["water"],
  waft: ["watt"],
  waif: ["wait"],
  wail: ["wall", "wait"],
  wailer: ["waiter"],
  wailing: ["waiting"],
  wait: ["wail"],
  waiter: ["wailer"],
  waiting: ["wailing"],
  wall: ["wail"],
  wary: ["ward"],
  was: ["wag"],
  way: ["wad"],
  well: ["welt"],
  welt: ["well"],
  welter: ["wetter"],
  wetter: ["welter"],
  wheal: ["wheat"],
  wheat: ["wheal"],
  while: ["white"],
  white: ["while"],
  whooper: ["whoopee"],
  will: ["wilt"],
  wilt: ["will"],
  wily: ["wild"],
  winy: ["wind"],
  wren: ["ween"],
  wright: ["weight"],
  y: ["d"],
  yam: ["dam", "yaw"],
  yang: ["dang"],
  yank: ["dank"],
  yarn: ["darn"],
  yawn: ["dawn"],
  year: ["dear"],
  yearly: ["dearly"],
  yell: ["dell"],
  yen: ["den"],
  yes: ["yea"],
  yew: ["dew"],
  yin: ["din"],
  yip: ["dip"],
  yo: ["do"],
  yon: ["don"],
  you: ["yon"],
  your: ["dour"],
  yuck: ["duck"],
  yucky: ["ducky"],
  yummy: ["dummy"],
  z: ["f"],
  zed: ["fed"],
  zest: ["fest"],
  zeta: ["feta"],
  zilch: ["filch"],
  zing: ["zinc"],
  zinger: ["finger"],
  zit: ["fit"],
};

export default data;
