const data = {
  "ah": "ha",
  "am": "ma",
  "b": "d",
  "bah": "had",
  "bat": "tad",
  "bi": "id",
  "bib": "did",
  "blot": "told",
  "blow": "wold",
  "boom": "mood",
  "bub": "dud",
  "bum": "mud",
  "d": "b",
  "did": "bib",
  "dud": "bub",
  "duh": "hub",
  "ha": "ah",
  "had": "bah",
  "ho": "oh",
  "hub": "duh",
  "id": "bi",
  "it": "ti",
  "loot": "tool",
  "ma": "am",
  "mat": "tam",
  "may": "yam",
  "mood": "boom",
  "mot": "tom",
  "mu": "um",
  "mud": "bum",
  "oh": "ho",
  "p": "q",
  "q": "p",
  "tad": "bat",
  "tam": "mat",
  "ti": "it",
  "told": "blot",
  "tom": "mot",
  "tool": "loot",
  "um": "mu",
  "way": "yaw",
  "wold": "blow",
  "yam": "may",
  "yaw": "way"
};

export default data;