const data = {
  a: ["a"],
  abaci: ["abaci"],
  aback: ["aback"],
  abalone: ["abalone"],
  abandon: ["abandon"],
  abandoned: ["abandoned"],
  abbe: ["abbe"],
  abed: ["abed"],
  abidance: ["abidance"],
  abide: ["abide"],
  abiding: ["abiding"],
  able: ["able"],
  abode: ["abode"],
  acacia: ["acacia"],
  accede: ["accede"],
  accolade: ["accolade"],
  ace: ["ace"],
  ache: ["ache"],
  achene: ["achene"],
  achoo: ["achoo"],
  acid: ["acid"],
  acidic: ["acidic"],
  acne: ["acne"],
  ad: ["ad"],
  adage: ["adage"],
  adagio: ["adagio"],
  add: ["add"],
  addable: ["addable"],
  addend: ["addend"],
  addenda: ["addenda"],
  addle: ["addle"],
  adenine: ["adenine"],
  adenoid: ["adenoid"],
  adenoidal: ["adenoidal"],
  ado: ["ado"],
  adobe: ["adobe"],
  aeon: ["aeon"],
  again: ["again"],
  age: ["age", "ago", "ace"],
  aged: ["aged"],
  agenda: ["agenda"],
  ages: ["agog"],
  agile: ["agile"],
  aging: ["aging"],
  ago: ["ago", "age", "ace"],
  agog: ["agog"],
  ague: ["acne"],
  ah: ["ah"],
  aha: ["aha"],
  ahead: ["ahead"],
  aid: ["aid"],
  aide: ["aide"],
  ail: ["ail", "all"],
  ailing: ["ailing"],
  air: ["ale"],
  akin: ["akin"],
  alack: ["alack"],
  alb: ["alb"],
  albino: ["albino"],
  alcohol: ["alcohol"],
  alcoholic: ["alcoholic"],
  ale: ["ale", "ate"],
  alga: ["alga"],
  algae: ["algae"],
  algal: ["algal"],
  alibi: ["alibi"],
  alien: ["alien"],
  alienable: ["alienable"],
  align: ["align"],
  alike: ["alike"],
  alkali: ["alkali"],
  alkaline: ["alkaline"],
  alkaloid: ["alkaloid"],
  all: ["all", "ail"],
  allege: ["allege"],
  alleged: ["alleged"],
  allegiance: ["allegiance"],
  allele: ["allele"],
  alliance: ["alliance"],
  allied: ["allied"],
  aloe: ["aloe"],
  aloha: ["aloha"],
  alone: ["alone", "atone"],
  along: ["along"],
  alp: ["alb"],
  alpine: ["albino"],
  am: ["aw"],
  an: ["an"],
  anaconda: ["anaconda"],
  anal: ["anal"],
  analog: ["analog"],
  analogical: ["analogical"],
  and: ["and"],
  angel: ["angel"],
  angelic: ["angelic"],
  angelica: ["angelica"],
  angelical: ["angelical"],
  angina: ["angina"],
  angle: ["angle"],
  angling: ["angling"],
  aniline: ["aniline"],
  anion: ["anion"],
  anionic: ["anionic"],
  ankh: ["ankh"],
  ankle: ["ankle"],
  anklebone: ["anklebone"],
  anneal: ["anneal"],
  annelid: ["annelid"],
  annex: ["annex"],
  anode: ["anode"],
  anon: ["anon"],
  any: ["and"],
  ate: ["ale"],
  atomize: ["alewife"],
  atone: ["alone"],
  ax: ["ax"],
  axe: ["axe"],
  axial: ["axial"],
  axle: ["axle"],
  axon: ["axon"],
  aye: ["ado"],
  b: ["b"],
  baa: ["baa"],
  babble: ["babble"],
  babe: ["babe"],
  babel: ["babel"],
  baboon: ["baboon"],
  bacchanal: ["bacchanal"],
  bacchanalia: ["bacchanalia"],
  bacchanalian: ["bacchanalian"],
  bacilli: ["bacilli"],
  back: ["back"],
  backache: ["backache"],
  backbone: ["backbone"],
  backhand: ["backhand"],
  backhanded: ["backhanded"],
  backhoe: ["backhoe"],
  backing: ["backing"],
  backlog: ["backlog"],
  bacon: ["bacon"],
  bad: ["bad"],
  bade: ["bade"],
  badge: ["badge"],
  badinage: ["badinage"],
  baffle: ["battle", "babble"],
  bag: ["bag"],
  bagel: ["bagel"],
  baggage: ["baggage"],
  baggie: ["baggie"],
  bah: ["bah"],
  bail: ["bail", "bait", "ball"],
  bailable: ["bailable"],
  bait: ["bail", "ball"],
  bake: ["bake"],
  balalaika: ["balalaika"],
  balance: ["balance"],
  balanced: ["balanced"], //USE just clever. Might be able to be horizontal too
  bald: ["bald"],
  balding: ["balding"],
  bale: ["bale", "bate"],
  baleen: ["baleen"],
  balk: ["balk"],
  ball: ["ball", "bail", "bait"],
  ballad: ["ballad"],
  ballcock: ["ballcock"],
  balloon: ["balloon"],
  ballsy: ["ballad"],
  ban: ["ban"],
  banal: ["banal"],
  banana: ["banana"],
  band: ["band"],
  bandage: ["bandage"],
  bandana: ["bandana"],
  bandanna: ["bandanna"],
  bandbox: ["bandbox"],
  bane: ["bane"],
  bang: ["bang"],
  bangle: ["bangle"],
  bank: ["bank"],
  bankable: ["bankable"],
  bankbook: ["bankbook"],
  banking: ["banking"],
  baobab: ["baobab"],
  bate: ["bale"],
  baud: ["band"],
  bay: ["bad"],
  be: ["be"],
  beach: ["beach"],
  beachhead: ["beachhead"],
  beacon: ["beacon"],
  bead: ["bead"],
  beading: ["beading"],
  beadle: ["beadle"],
  beagle: ["beagle"],
  beak: ["beak"],
  beaked: ["beaked"],
  bean: ["bean"],
  beanbag: ["beanbag"],
  beanie: ["beanie"],
  beau: ["bean"],
  beck: ["beck", "bock"],
  beckon: ["beckon"],
  bed: ["bed", "bod"],
  bedding: ["bedding"],
  bedeck: ["bedeck"],
  bee: ["bee", "boo"],
  beech: ["beech"],
  beef: ["beet", "boot", "boob"],
  beeline: ["beeline"],
  been: ["been", "boon"],
  beep: ["boob"],
  beg: ["beg", "bog"],
  began: ["began"],
  begin: ["begin"],
  beginning: ["beginning"],
  begone: ["begone"],
  begonia: ["begonia"],
  behead: ["behead"],
  beheld: ["beheld", "behold"],
  behind: ["behind"],
  behindhand: ["behindhand"],
  behold: ["behold", "beheld"],
  beholden: ["beholden"],
  beige: ["beige"],
  being: ["being"],
  belch: ["belch", "botch"],
  belfry: ["belted"],
  belie: ["belie", "belle"],
  bell: ["bell", "belt", "boll", "bolt", "boil"],
  belladonna: ["belladonna"],
  belle: ["belle", "belie"],
  belong: ["belong"],
  belt: ["bell", "boll", "boil"],
  bench: ["bench"],
  bend: ["bend", "bond"],
  bendable: ["bendable"],
  benign: ["benign"],
  beset: ["bezel"],
  besot: ["bezel"],
  beta: ["bola"],
  bevy: ["bead"],
  bey: ["bed", "bod"],
  bi: ["bi"],
  bib: ["bib"],
  bible: ["bible"],
  biblical: ["biblical"],
  bid: ["bid"],
  biddable: ["biddable"],
  bidden: ["bidden"],
  bidding: ["bidding"],
  bide: ["bide"],
  biennial: ["biennial"],
  big: ["big"],
  biggie: ["biggie"],
  bike: ["bike"],
  bikini: ["bikini"],
  bilabial: ["bilabial"],
  bile: ["bile", "bite"],
  bilge: ["bilge"],
  bilk: ["bilk"],
  bill: ["bill"],
  billable: ["billable"],
  billed: ["billed"],
  billing: ["billing"],
  billion: ["billion"],
  bin: ["bin"],
  bind: ["bind"],
  binding: ["binding"],
  binge: ["binge", "bingo"],
  bingo: ["bingo", "binge"],
  binnacle: ["binnacle"],
  bio: ["bio"],
  biological: ["biological"],
  bionic: ["bionic"],
  bird: ["bled"],
  bite: ["bile"],
  blab: ["blab"],
  black: ["black"],
  blackball: ["blackball"],
  blacken: ["blacken"],
  blackhead: ["blackhead"],
  blacking: ["blacking"],
  blade: ["blade"],
  bladed: ["bladed"],
  blah: ["blah"],
  blanch: ["blanch"],
  bland: ["bland"],
  blank: ["blank"],
  blase: ["blaze"],
  bleach: ["bleach"],
  bleak: ["bleak"],
  bled: ["bled"],
  bleed: ["bleed", "blood"],
  bleeding: ["bleeding"],
  blench: ["blench"],
  blend: ["blend", "blond"],
  blind: ["blind"],
  blinding: ["blinding"],
  blini: ["blini"],
  blink: ["blink"],
  blob: ["blob"],
  bloc: ["bloc"],
  block: ["block"],
  blockade: ["blockade"],
  blockage: ["blockage"],
  blockhead: ["blockhead"],
  blond: ["blond", "blend"],
  blonde: ["blonde"],
  blood: ["blood", "bleed"],
  blooded: ["blooded"],
  bloodline: ["bloodline"],
  boa: ["boa"],
  bob: ["bob"],
  bobbin: ["bobbin"],
  bobble: ["bobble"],
  bobolink: ["bobolink"],
  boccie: ["boccie"],
  bock: ["bock", "beck"],
  bod: ["bod", "bed"],
  bode: ["bode"],
  bodega: ["bodega"],
  bodice: ["bodice"],
  bodied: ["bodied"],
  bodkin: ["bodkin"],
  bog: ["bog", "beg"],
  boggle: ["boggle", "boccie"],
  bogie: ["bogie"],
  boil: ["boil", "boll", "bolt", "bell", "belt"],
  boiling: ["boiling"],
  bola: ["bola", "beta"],
  bold: ["bold"],
  bole: ["bole"],
  boll: ["boll", "bolt", "boil", "bell", "belt"],
  bollix: ["bollix"],
  bologna: ["bologna"],
  bolt: ["boll", "boil", "bell"],
  bolus: ["being"],
  bonbon: ["bonbon"],
  bond: ["bond", "bend"],
  bondage: ["bondage"],
  bonding: ["bonding"],
  bone: ["bone"],
  bonehead: ["bonehead"],
  boneheaded: ["boneheaded"],
  bong: ["bong"],
  bongo: ["bongo"],
  bony: ["bond", "bend"],
  boo: ["boo", "bee"],
  boob: ["boob"],
  booboo: ["booboo"],
  boodle: ["boodle"],
  boogie: ["boogie"],
  book: ["book"],
  bookbinding: ["bookbinding"],
  bookend: ["bookend"],
  bookie: ["bookie"],
  booking: ["booking"],
  boon: ["boon", "been"],
  boondoggle: ["boondoggle"],
  bop: ["bob"],
  born: ["been"],
  botch: ["belch"],
  bottom: ["bellow"],
  bough: ["bench"],
  box: ["box"],
  boxing: ["boxing"],
  boxlike: ["boxlike"],
  boy: ["bod", "bed"],
  brad: ["bead"],
  bran: ["bean"],
  bray: ["bead"],
  bring: ["being"],
  bro: ["bee"],
  brr: ["bee"],
  c: ["c"],
  cab: ["cab"],
  cabal: ["cabal"],
  cabala: ["cabala"],
  cabana: ["cabana"],
  cabbage: ["cabbage"],
  cabbie: ["cabbie"],
  cabin: ["cabin"],
  cable: ["cable"],
  cabochon: ["cabochon"],
  caboodle: ["caboodle"],
  cacao: ["cacao"],
  cache: ["cache"],
  cackle: ["cackle"],
  cad: ["cad"],
  caddie: ["caddie"],
  cadence: ["cadence"],
  cadenced: ["cadenced"],
  cadge: ["cadge"],
  cage: ["cage"],
  cake: ["cake"],
  calcine: ["calcine"],
  calico: ["calico"],
  calk: ["calk"],
  call: ["call"],
  calla: ["calla"],
  callback: ["callback"],
  calling: ["calling"],
  cam: ["caw"],
  can: ["can"],
  canal: ["canal"],
  cancan: ["cancan"],
  cancel: ["cancel"],
  candid: ["candid"],
  candied: ["candied"],
  candle: ["candle"],
  cane: ["cane"],
  caner: ["canoe"],
  canine: ["canine"],
  canned: ["canned"],
  cannelloni: ["cannelloni"],
  cannibal: ["cannibal"],
  cannon: ["cannon"],
  cannonade: ["cannonade"],
  cannonball: ["cannonball"],
  canoe: ["canoe"],
  canola: ["canola"],
  canon: ["canon"],
  canonical: ["canonical"],
  canst: ["canal"],
  cap: ["cab"],
  case: ["cage"],
  cay: ["cad"],
  ceca: ["ceca", "coca"],
  cecal: ["cecal"],
  cede: ["cede", "code"],
  cedilla: ["cedilla"],
  ceiling: ["ceiling"],
  celandine: ["celandine"],
  cell: ["cell", "colt", "coil"],
  celled: ["celled"],
  cello: ["cello"],
  chain: ["chain"],
  chalice: ["chalice"],
  chalk: ["chalk"],
  challenge: ["challenge"],
  challenged: ["challenged"],
  challenging: ["challenging"],
  chance: ["chance"],
  chancel: ["chancel"],
  change: ["change", "chance"],
  changeable: ["changeable"],
  changeling: ["changeling"],
  channel: ["channel"],
  check: ["check", "chock"],
  checkbook: ["checkbook"],
  checked: ["checked"],
  cheek: ["cheek"],
  cheekbone: ["cheekbone"],
  chenille: ["chenille"],
  chi: ["chi"],
  chic: ["chic"],
  chichi: ["chichi"],
  chick: ["chick"],
  chickadee: ["chickadee"],
  chicken: ["chicken"],
  chicle: ["chicle"],
  chid: ["chid"],
  chidden: ["chidden"],
  chide: ["chide"],
  chignon: ["chignon"],
  chilblain: ["chilblain"],
  child: ["child"],
  childhood: ["childhood"],
  childlike: ["childlike"],
  chile: ["chile"],
  chili: ["chili", "chill"],
  chill: ["chill", "chili"],
  chilling: ["chilling"],
  chin: ["chin"],
  china: ["china"],
  chinchilla: ["chinchilla"],
  chine: ["chine", "chino"],
  chink: ["chink"],
  chino: ["chino", "chine"],
  chitlins: ["chilling"],
  chock: ["chock", "check"],
  chockablock: ["chockablock"],
  chocoholic: ["chocoholic"],
  choice: ["choice"],
  choke: ["choke"],
  ciao: ["ciao"],
  cicada: ["cicada"],
  cilia: ["cilia"],
  cinch: ["cinch"],
  cinchona: ["cinchona"],
  clack: ["clack"],
  clad: ["clad"],
  cladding: ["cladding"],
  clam: ["claw"],
  clan: ["clan"],
  clang: ["clang"],
  clank: ["clank"],
  clay: ["clad"],
  clean: ["clean"],
  cleanable: ["cleanable"],
  cleaning: ["cleaning"],
  clef: ["clot"],
  clench: ["clench"],
  cliche: ["cliche"],
  cliched: ["cliched"],
  click: ["click"],
  clinch: ["clinch"],
  cling: ["cling"],
  clinic: ["clinic"],
  clinical: ["clinical"],
  clinician: ["clinician"],
  clink: ["clink"],
  cloaca: ["cloaca"],
  cloacae: ["cloacae"],
  cloak: ["cloak"],
  cloche: ["cloche"],
  clock: ["clock"],
  clod: ["clod"],
  clog: ["clog"],
  clogged: ["clogged"],
  clonal: ["clonal"],
  clone: ["clone"],
  clonk: ["clonk"],
  cloy: ["clod"],
  coach: ["coach"],
  coal: ["coal", "coat"],
  coat: ["coal"],
  coax: ["coax"],
  coaxial: ["coaxial"],
  cob: ["cob"],
  cobble: ["cobble"],
  cobbled: ["cobbled"],
  coca: ["coca", "ceca"],
  cocaine: ["cocaine"],
  cocci: ["cocci"],
  cochineal: ["cochineal"],
  cochlea: ["cochlea"],
  cochleae: ["cochleae"],
  cochlear: ["cochleae"],
  cock: ["cock"],
  cockade: ["cockade"],
  cockle: ["cockle"],
  coco: ["coco"],
  cocoa: ["cocoa"],
  cocoon: ["cocoon"],
  cod: ["cod"],
  coda: ["coda"],
  coddle: ["coddle"],
  code: ["code", "cede"],
  coded: ["coded"],
  codeine: ["codeine"],
  codex: ["codex"],
  codicil: ["codicil"],
  coed: ["coed"],
  cog: ["cog"],
  cognac: ["cognac"],
  coho: ["coho"],
  coif: ["colt"],
  coil: ["coil", "colt", "cell"],
  coin: ["coin"],
  coinage: ["coinage"],
  coincide: ["coincide"],
  coincidence: ["coincidence"],
  coke: ["coke"],
  cola: ["cola"],
  cold: ["cold"],
  coldblooded: ["coldblooded"],
  colic: ["colic"],
  collage: ["collage", "cottage"],
  colleen: ["colleen"],
  college: ["college"],
  collegian: ["collegian"],
  collide: ["collide"],
  collie: ["collie"],
  colloid: ["colloid"],
  colloidal: ["colloidal"],
  cologne: ["cologne"],
  colon: ["colon"],
  colonel: ["colonel"],
  colonial: ["colonial"],
  colonist: ["colonial"],
  colonnade: ["colonnade"],
  colonnaded: ["colonnaded"],
  colt: ["coil", "cell"],
  con: ["con"],
  conceal: ["conceal"],
  concealable: ["concealable"],
  concede: ["concede"],
  conch: ["conch"],
  condign: ["condign"],
  condo: ["condo"],
  condole: ["condole"],
  condolence: ["condolence"],
  condone: ["condone"],
  cone: ["cone"],
  confluence: ["continence"],
  conga: ["conga"],
  congeal: ["congeal", "conceal"],
  congenial: ["congenial"],
  congest: ["congeal", "conceal"],
  conic: ["conic"],
  conical: ["conical"],
  conk: ["conk"],
  coo: ["coo"],
  cook: ["cook"],
  cookbook: ["cookbook"],
  cooked: ["cooked"],
  cookie: ["cookie"],
  cooking: ["cooking"],
  cool: ["cool", "coot"],
  coolie: ["coolie", "cootie"],
  coon: ["coon"],
  coot: ["cool"],
  cootie: ["coolie"],
  cop: ["cob"],
  cord: ["coed"],
  cost: ["coal"],
  cottage: ["collage"],
  couch: ["conch"],
  cough: ["conch"],
  coy: ["cod"],
  d: ["d"],
  dab: ["dab"],
  dabble: ["dabble"],
  dace: ["dace"],
  dacha: ["dacha"],
  dad: ["dad"],
  dado: ["dado"],
  dahlia: ["dahlia"],
  dale: ["dale", "date"],
  dalliance: ["dalliance"],
  damn: ["dawn"],
  dance: ["dance"],
  dancing: ["dancing"],
  dandelion: ["dandelion"],
  dandle: ["dandle"],
  dang: ["dang"],
  dangle: ["dangle"],
  dank: ["dank"],
  dapple: ["dabble"],
  date: ["dale"],
  day: ["dad"],
  deacon: ["deacon"],
  dead: ["dead"],
  deaden: ["deaden"], //USE
  deadline: ["deadline"],
  deadlock: ["deadlock"],
  deal: ["deal"],
  dealing: ["dealing"],
  dean: ["dean"],
  deb: ["deb"],
  debacle: ["debacle"],
  decade: ["decade"],
  decadence: ["decadence"],
  decagon: ["decagon"],
  decal: ["decal"],
  decennial: ["decennial"],
  decibel: ["decibel"],
  decidable: ["decidable"],
  decide: ["decide"],
  decided: ["decided"],
  deck: ["deck", "dock"],
  deckhand: ["deckhand"],
  decline: ["decline"],
  decode: ["decode"],
  deed: ["deed"],
  def: ["deb", "dot"],
  deice: ["deice"],
  deign: ["deign"],
  deli: ["deli", "dell", "doll"],
  dell: ["dell", "deli", "doll", "dolt"],
  den: ["den", "don"],
  deniable: ["deniable"],
  denial: ["denial"],
  devil: ["dealt"],
  diabetic: ["diabolic"],
  diabolic: ["diabolic", "diabetic"],
  diabolical: ["diabolical"],
  diagonal: ["diagonal"],
  dial: ["dial"],
  dialog: ["dialog"],
  dibble: ["dibble"],
  dice: ["dice"],
  dick: ["dick"],
  did: ["did"],
  diddle: ["diddle"],
  dido: ["dido"],
  die: ["die"],
  dig: ["dig"],
  dike: ["dike"],
  diligence: ["diligence"],
  dill: ["dill"],
  din: ["din"],
  dine: ["dine"],
  ding: ["ding"],
  dingdong: ["dingdong"],
  dingle: ["dingle"],
  dingo: ["dingo"],
  diode: ["diode"],
  dioxide: ["dioxide"],
  dioxin: ["dioxin"],
  dis: ["dig"],
  dixieland: ["dixieland"],
  do: ["do"],
  doable: ["doable"],
  dobbin: ["dobbin"],
  doc: ["doc"],
  docile: ["docile"],
  dock: ["dock", "deck"],
  dodge: ["dodge"],
  dodo: ["dodo"],
  doe: ["doe"],
  doff: ["debt"],
  dog: ["dog", "doc"],
  doge: ["doge"],
  dogged: ["dogged"],
  doggie: ["doggie"],
  doggone: ["doggone"],
  dogie: ["dogie"],
  dogleg: ["dogleg"],
  doing: ["doing"],
  dole: ["dole", "dote"],
  doll: ["doll", "dolt", "dell", "deli"],
  dolt: ["doll", "dell"],
  don: ["don", "den"],
  dona: ["dona"],
  done: ["done"],
  dong: ["dong"],
  dongle: ["dongle"],
  doodad: ["doodad"],
  doodle: ["doodle"],
  dory: ["deed"],
  dose: ["doze", "doge"],
  dost: ["deal"],
  dote: ["dole"],
  dour: ["done"],
  dragon: ["deacon"],
  drat: ["deal"],
  dray: ["dead"],
  e: ["e", "o"],
  each: ["each"],
  eagle: ["eagle"],
  ebb: ["ebb"],
  echelon: ["echelon"],
  echo: ["echo"],
  echoic: ["echoic"],
  ecocide: ["ecocide"],
  ecological: ["ecological"],
  ed: ["ed"],
  edge: ["edge"],
  edged: ["edged"],
  edging: ["edging"],
  edible: ["edible"],
  eek: ["eek"],
  eel: ["eel"],
  egad: ["egad"],
  egg: ["egg"],
  egghead: ["egghead"],
  eggnog: ["eggnog"],
  ego: ["ego"],
  eh: ["eh", "oh"],
  eke: ["eke"],
  elan: ["elan"],
  eland: ["eland"],
  elegance: ["elegance"],
  elegiac: ["elegiac"],
  elide: ["elide"],
  eligible: ["eligible"],
  elk: ["elk"],
  ell: ["ell", "oil"],
  elodea: ["elodea"],
  em: ["ow"],
  emu: ["own"],
  en: ["en", "on"],
  enable: ["enable"],
  enabling: ["enabling"],
  enchain: ["enchain"],
  enchilada: ["enchilada"],
  encode: ["encode"],
  end: ["end"],
  ending: ["ending"],
  engage: ["engage"],
  engaged: ["engaged"],
  engaging: ["engaging"],
  engine: ["engine"],
  enhance: ["enhance"],
  ennoble: ["ennoble"],
  eolian: ["eolian"],
  eon: ["eon"],
  epee: ["oboe"],
  ex: ["ex", "ox"],
  exceed: ["exceed"],
  exceeding: ["exceeding"],
  excel: ["excel"],
  excellence: ["excellence"],
  exchange: ["exchange"],
  exchangeable: ["exchangeable"],
  exec: ["exec"],
  exhale: ["exhale"],
  exile: ["exile"],
  exiled: ["exiled"],
  eye: ["ode"],
  f: ["t", "b", "z"],
  fable: ["table"],
  face: ["taco"],
  fad: ["tad", "bad"],
  fade: ["bade"],
  fag: ["tag", "bag"],
  fagot: ["bagel"],
  fail: ["tail", "tall", "tali", "bail", "bait", "ball"],
  fair: ["tale", "bale"],
  fake: ["take", "bake"],
  fall: ["tall", "tali", "tail", "ball", "bail", "bait"],
  fallen: ["batten"],
  false: ["baize"],
  fan: ["tan", "ban"],
  fang: ["tang", "bang"],
  fate: ["tale", "bale"],
  fax: ["tax"],
  fay: ["tad", "bad"],
  feat: ["teal", "zeal"],
  fed: ["bed", "bod", "zed"],
  fee: ["tee", "toe", "too", "bee", "boo", "zoo"],
  feed: ["toed"],
  feel: ["tool", "toot", "beet", "boot"],
  feeler: ["bootee"],
  feet: ["tool"],
  fell: ["tell", "toll", "toil", "bell", "belt", "boll", "bolt", "boil"],
  felt: ["tell", "toll", "toil", "bell", "boll", "boil"],
  fen: ["ten", "ton"],
  fend: ["tend", "bend", "bond"],
  fennel: ["bonnet"],
  fern: ["teen", "been"],
  fest: ["teal", "zeal"],
  feta: ["bola"],
  fetch: ["belch"],
  fete: ["tole", "bole"],
  feud: ["tend", "bend", "bond"],
  fey: ["bed", "bod", "zed"],
  fib: ["bib"],
  fickle: ["tickle"],
  fie: ["tie", "bio"],
  fief: ["blot", "blob"],
  fiend: ["blend", "blond"],
  fiery: ["bleed"],
  fife: ["bite"],
  fig: ["tic", "big"],
  filch: ["bitch", "zilch"],
  file: ["tile", "bile", "bite"],
  filing: ["tiling", "biting"],
  fill: ["till", "tilt", "bill"],
  filling: ["billing"],
  fin: ["tin", "bin"],
  find: ["bind"],
  finding: ["binding"],
  fine: ["tine"],
  fiord: ["bleed"],
  fir: ["tie"],
  firm: ["blew"],
  fish: ["blah"],
  fitted: ["billed"],
  fitting: ["billing"],
  fizz: ["tiff"],
  fjord: ["bleed"],
  flab: ["blab"],
  flack: ["black"],
  flank: ["blank"],
  flap: ["blab"],
  fleck: ["block"],
  fled: ["bled"],
  flit: ["till", "bill"],
  flock: ["block"],
  flog: ["bloc"],
  flood: ["blood", "bleed"],
  flop: ["blob"],
  flu: ["tin", "bin"],
  flue: ["tine"],
  fly: ["bid"],
  foal: ["teal", "teat", "boat", "beat", "zeal"],
  fob: ["bob"],
  foe: ["toe", "too", "tee", "boo", "bee", "zoo"],
  fog: ["tog", "bog", "beg"],
  foil: ["toil", "toll", "tell", "boil", "boll", "bolt", "bell", "belt"],
  fold: ["told", "bold"],
  folio: ["belie", "belle"],
  fond: ["tend", "bond", "bend"],
  food: ["toed"],
  foodie: ["boodle"],
  fool: ["tool", "toot", "boot", "beet"],
  foot: ["tool"],
  fop: ["bob"],
  for: ["toe", "tee", "bee"],
  ford: ["toed"],
  foul: ["tent", "bent"],
  four: ["tone", "bone", "zone"],
  fox: ["box"],
  frat: ["teal", "zeal"],
  fray: ["bead"],
  fro: ["tee", "bee"],
  fry: ["bed", "zed"],
  g: ["g", "c", "q"],
  gab: ["gab", "cab"],
  gabble: ["gabble", "cabbie"],
  gable: ["gable", "cable"],
  gabled: ["gabled"],
  gad: ["gad", "cad"],
  gag: ["gag"],
  gaga: ["gaga"],
  gage: ["gage", "cage"],
  gaggle: ["gaggle"],
  gain: ["gain"],
  gait: ["gall", "call"],
  gal: ["gal", "cat"],
  gala: ["gala"],
  gale: ["gale", "gate"],
  galena: ["galena"],
  gall: ["gall", "gait", "call"],
  galleon: ["galleon"],
  galling: ["galling", "calling"],
  gallon: ["gallon", "cation"],
  gang: ["gang"],
  gangland: ["gangland"],
  ganglia: ["ganglia"],
  gangling: ["gangling"],
  ganglion: ["ganglion"],
  ganglionic: ["ganglionic"],
  gap: ["gab", "cab"],
  gas: ["gag"],
  gate: ["gale"],
  gay: ["gad", "cad"],
  gaze: ["cafe"],
  gecko: ["gecko"],
  gee: ["gee", "goo", "coo"],
  geek: ["geek", "gook", "cook"],
  gel: ["gel", "get", "got", "cot"],
  geld: ["geld", "gold", "cold"],
  gelding: ["gelding"],
  gelid: ["gelid"],
  gem: ["cow"],
  gene: ["gene", "gone", "cone"],
  genealogical: ["genealogical"],
  genial: ["genial"],
  genie: ["genie"],
  genii: ["genii"],
  genocidal: ["genocidal"],
  genocide: ["genocide"],
  genus: ["gonna"],
  geode: ["geode"],
  geologic: ["geologic"],
  geological: ["geological"],
  get: ["gel"],
  gibbon: ["gibbon"],
  gibe: ["gibe"],
  gig: ["gig"],
  giggle: ["giggle"],
  gigolo: ["gigolo"],
  gild: ["gild"],
  gilding: ["gilding", "gliding"],
  gill: ["gill", "gilt"],
  gilt: ["gill"],
  gin: ["gin"],
  gingko: ["gingko"],
  ginkgo: ["ginkgo"],
  give: ["ciao"],
  glace: ["glace"],
  glacial: ["glacial"],
  glad: ["glad", "clad"],
  gladden: ["gladden"],
  glade: ["glade"],
  gladiola: ["gladiola"],
  gladioli: ["gladioli"],
  glance: ["glance"],
  glancing: ["glancing"],
  gland: ["gland"],
  glans: ["clang"],
  glean: ["glean", "clean"],
  glee: ["glee"],
  glen: ["glen"],
  glib: ["glib"],
  glide: ["glide"],
  gliding: ["gliding", "gilding"],
  glob: ["glob"],
  global: ["global"],
  globe: ["globe"],
  glop: ["glob"],
  go: ["go"],
  goad: ["goad"],
  goal: ["goal", "goat", "coal", "coat"],
  goalie: ["goalie"],
  goat: ["goal", "coal"],
  gob: ["gob", "cob"],
  gobble: ["gobble", "cobble"],
  gobbledegook: ["gobbledegook"],
  goblin: ["goblin"],
  god: ["god", "cod"],
  godchild: ["godchild"],
  godhead: ["godhead"],
  godhood: ["godhood"],
  godlike: ["godlike"],
  goggle: ["goggle"],
  going: ["going"],
  gold: ["gold", "geld", "cold"],
  golden: ["golden"],
  golf: ["colt"],
  golly: ["gelid"],
  gonad: ["gonad"],
  gonadal: ["gonadal"],
  gondola: ["gondola"],
  gone: ["gone", "gene", "cone"],
  gong: ["gong"],
  gonna: ["gonna"],
  goo: ["goo", "gee", "coo"],
  good: ["good", "coed"],
  goodie: ["goodie"],
  goof: ["coot"],
  gook: ["gook", "geek", "cook"],
  goon: ["goon", "coon"],
  gory: ["coed"],
  gosling: ["coating"],
  got: ["gel"],
  grid: ["geld"],
  grit: ["cell"],
  h: ["h"],
  ha: ["ha"],
  hacienda: ["hacienda"],
  hack: ["hack"],
  hacking: ["hacking"],
  hackle: ["hackle"],
  had: ["had"],
  haddock: ["haddock"],
  hag: ["hag"],
  haggle: ["haggle"],
  hah: ["hah"],
  hail: ["hail", "hall", "halt"],
  hair: ["hale"],
  hajj: ["hall"],
  hake: ["hake"],
  halal: ["halal"],
  hale: ["hale", "halo", "hate"],
  half: ["halt"],
  hall: ["hall", "halt", "hail"],
  halloo: ["halloo"],
  halo: ["halo", "hale", "hate"],
  halogen: ["halogen"],
  halt: ["hall", "hail"],
  ham: ["haw"],
  hand: ["hand"],
  handbag: ["handbag"],
  handball: ["handball"],
  handbill: ["handbill"],
  handbook: ["handbook"],
  handed: ["handed"],
  handhold: ["handhold"],
  handle: ["handle"],
  handled: ["handled"],
  hang: ["hang"],
  hangdog: ["hangdog"],
  hanging: ["hanging"],
  hangnail: ["hangnail"],
  hank: ["hank"],
  hankie: ["hankie"],
  has: ["hag"],
  hassle: ["haggle"],
  hate: ["hale", "halo"],
  hay: ["had"],
  he: ["he", "ho"],
  head: ["head"],
  headache: ["headache"],
  headband: ["headband"],
  headed: ["headed"],
  heading: ["heading"],
  headland: ["headland"],
  headline: ["headline"],
  headlock: ["headlock"],
  headlong: ["headlong"],
  heal: ["heal", "heat"],
  heat: ["heal"],
  heck: ["heck", "hock"],
  heckle: ["heckle"],
  heckling: ["heckling"],
  hedge: ["hedge"],
  hedgehog: ["hedgehog"],
  heed: ["heed", "hood"],
  heel: ["heel", "hoot"],
  heir: ["hole"],
  held: ["held", "hold"],
  helical: ["helical", "hellcat"],
  helix: ["helix"],
  hell: ["hell"],
  hellcat: ["helical"],
  hellhole: ["hellhole"],
  hellion: ["hellion"],
  hello: ["hello"],
  helot: ["hotel"],
  hem: ["hew", "how"],
  hen: ["hen", "hon"],
  hence: ["hence"],
  henna: ["henna"],
  hep: ["hob"],
  her: ["hoe"],
  herd: ["heed"],
  hex: ["hex"],
  hexagon: ["hexagon"],
  hexagonal: ["hexagonal"],
  hey: ["hod"],
  hi: ["hi"],
  hibachi: ["hibachi"],
  hick: ["hick"],
  hid: ["hid"],
  hidden: ["hidden"],
  hide: ["hide"],
  hiding: ["hiding"],
  hie: ["hie"],
  high: ["high"],
  highball: ["highball"],
  highhanded: ["highhanded"],
  highland: ["highland"],
  hike: ["hike"],
  hiking: ["hiking"],
  hill: ["hill", "hilt"],
  hillock: ["hillock"],
  hilt: ["hill"],
  hind: ["hind"],
  hinge: ["hinge"],
  hinged: ["hinged"],
  ho: ["ho", "he"],
  hoagie: ["hoagie"],
  hoax: ["hoax"],
  hob: ["hob"],
  hobble: ["hobble"],
  hobgoblin: ["hobgoblin"],
  hobnail: ["hobnail"],
  hobnailed: ["hobnailed"],
  hobnob: ["hobnob"],
  hobo: ["hobo"],
  hock: ["hock", "heck"],
  hod: ["hod"],
  hoe: ["hoe"],
  hoecake: ["hoecake"],
  hog: ["hog"],
  hogan: ["hogan"],
  hogback: ["hogback"],
  hoke: ["hoke"],
  hold: ["hold", "held"],
  holding: ["holding"],
  hole: ["hole"],
  holy: ["hold", "held"],
  hon: ["hon", "hen"],
  honcho: ["honcho"],
  hone: ["hone"],
  honk: ["honk"],
  hooch: ["hooch"],
  hood: ["hood", "heed"],
  hooded: ["hooded"],
  hoodoo: ["hoodoo"],
  hoof: ["hoot"],
  hook: ["hook"],
  hookah: ["hookah"],
  hooked: ["hooked"],
  hookey: ["hooked"],
  hooligan: ["hooligan"],
  hoot: ["heel"],
  hop: ["hob"],
  hope: ["hobo"],
  host: ["heal"],
  hotel: ["helot"],
  hour: ["hone"],
  I: ["i", "l"],
  i: ["i", "l"],
  ibex: ["ibex"],
  ice: ["ice"],
  icebox: ["icebox"],
  iced: ["iced"],
  icicle: ["icicle"],
  icing: ["icing"],
  icon: ["icon"],
  iconic: ["iconic"],
  id: ["id"],
  idea: ["idea"],
  ideal: ["ideal"],
  ideological: ["ideological"],
  ides: ["idea"],
  idle: ["idle"],
  idol: ["idol"],
  if: ["it"],
  igloo: ["igloo"],
  ignoble: ["ignoble"],
  ikon: ["ikon"],
  ilea: ["ilea"],
  ilk: ["ilk"],
  ill: ["ill", "lit"],
  illegal: ["illegal"],
  illegible: ["illegible"], //USE
  illogical: ["illogical"],
  in: ["in"],
  inalienable: ["inalienable"],
  inane: ["inane"],
  inch: ["inch"],
  incidence: ["incidence"],
  incline: ["incline"],
  inclined: ["inclined"],
  indeed: ["indeed"],
  indelible: ["indelible"],
  index: ["index"],
  indigence: ["indigence"],
  indigo: ["indigo"],
  indolence: ["indolence"],
  inedible: ["inedible"],
  inelegance: ["inelegance"],
  ineligible: ["ineligible"],
  info: ["into"],
  inglenook: ["inglenook"],
  inhale: ["inhale"],
  ink: ["ink"],
  inkling: ["inkling"],
  inlaid: ["inlaid"],
  inland: ["inland"],
  inn: ["inn"],
  inning: ["inning"],
  innocence: ["innocence"],
  iodide: ["iodide"],
  iodine: ["iodine"],
  ion: ["ion"],
  ionic: ["ionic"],
  ire: ["lee"],
  is: ["la"],
  isle: ["late"],
  ism: ["law"],
  ivy: ["lad"],
  j: ["l"],
  jab: ["lab"],
  jabot: ["label"],
  jack: ["lack"],
  jade: ["lade"],
  jag: ["lag", "lac"],
  jam: ["law"],
  jay: ["lad"],
  jean: ["lean", "loan"],
  jell: ["loll"],
  jello: ["lotto"],
  jerk: ["leek"],
  jib: ["lib"],
  job: ["lob"],
  jock: ["lock"],
  jog: ["log", "leg"],
  jogging: ["logging", "legging"],
  join: ["loin"],
  jolt: ["loll"],
  joy: ["led"],
  k: ["k"],
  kabob: ["kabob"],
  kale: ["kale"],
  kaolin: ["kaolin"],
  kebab: ["kebab"],
  kebob: ["kebob"],
  keel: ["keel"],
  keen: ["keen"],
  keg: ["keg"],
  ken: ["ken"],
  kennel: ["kennel"],
  keno: ["keno"],
  khaki: ["khaki"],
  khan: ["khan"],
  kibble: ["kibble"],
  kick: ["kick"],
  kickback: ["kickback"],
  kickball: ["kickball"],
  kid: ["kid"],
  kiddie: ["kiddie"],
  kiddo: ["kiddo"],
  kill: ["kill", "kilt"],
  killing: ["killing"],
  kiln: ["kiln"],
  kilo: ["kilo", "kite"],
  kilt: ["kill"],
  kin: ["kin"],
  kind: ["kind"],
  kinda: ["kinda"],
  kindle: ["kindle"],
  kindling: ["kindling"],
  kine: ["kine"],
  king: ["king"],
  kink: ["kink"],
  kite: ["kilo"],
  knack: ["knack"],
  knead: ["knead"],
  knee: ["knee"],
  kneel: ["kneel"],
  knell: ["knell", "knelt", "knoll"],
  knelt: ["knell", "knoll"],
  knickknack: ["knickknack"], //USE
  knob: ["knob"],
  knock: ["knock"],
  knoll: ["knoll", "knell", "knelt"],
  koala: ["koala"],
  kola: ["kola"],
  kook: ["kook"],
  l: ["l", "i", "t"],
  la: ["la"],
  lab: ["lab", "tab"],
  label: ["label"],
  labia: ["labia", "tabla"],
  labial: ["labial"],
  labile: ["labile"],
  lac: ["lac"],
  lace: ["lace", "taco"],
  lack: ["lack", "tack"],
  lacking: ["lacking"],
  laconic: ["laconic"],
  lad: ["lad", "tad"],
  lade: ["lade"],
  laden: ["laden"],
  lading: ["lading"],
  ladle: ["ladle"],
  lag: ["lag", "lac", "tag"],
  lagoon: ["lagoon"],
  laid: ["laid"],
  lain: ["lain"],
  lair: ["tale"],
  lake: ["lake", "take"],
  lam: ["law"],
  lanai: ["lanai"],
  lance: ["lance"],
  land: ["land"],
  landed: ["landed"],
  landholding: ["landholding"],
  landing: ["landing"],
  landlocked: ["landlocked"],
  lane: ["lane"],
  lank: ["lank", "tank"],
  lanolin: ["lanolin"],
  lap: ["lab", "tab"],
  lapel: ["label"],
  late: ["tale"],
  laud: ["land"],
  lax: ["lax", "tax"],
  lay: ["lad", "tad"],
  lea: ["lea", "tea"],
  leach: ["leach", "teach"],
  lead: ["lead", "load", "toad"],
  leaded: ["leaded", "loaded"],
  leaden: ["leaden"],
  leading: ["leading", "loading"],
  leaf: ["teat"],
  leak: ["leak", "teak"],
  leakage: ["leakage"],
  lean: ["lean", "loan"],
  leaning: ["leaning"],
  lech: ["lech", "tech"],
  led: ["led"],
  ledge: ["ledge", "lodge"],
  lee: ["lee", "tee", "toe", "too"],
  leech: ["leech"],
  leek: ["leek", "look", "took"],
  leg: ["leg", "log", "tog"],
  legal: ["legal", "local"],
  legate: ["locale"],
  legato: ["locale"],
  legend: ["legend"],
  legged: ["legged"],
  legging: ["legging", "logging"],
  legible: ["legible"],
  legion: ["legion"],
  lei: ["lei"],
  lend: ["lend", "tend"],
  lenience: ["lenience"],
  lens: ["long", "tong"],
  leonine: ["leonine"],
  lesion: ["legion"],
  less: ["toga"],
  lest: ["teal"],
  levy: ["lead", "load", "toad"],
  lexica: ["lexica"],
  lexical: ["lexical"],
  lexicon: ["lexicon"],
  liable: ["liable"],
  lib: ["lib"],
  libel: ["libel"],
  libidinal: ["libidinal"],
  libido: ["libido"],
  lice: ["lice"],
  lichee: ["lichee"],
  lichen: ["lichen"],
  lick: ["lick", "tick"],
  licking: ["licking", "ticking"],
  lid: ["lid"],
  lidded: ["lidded"],
  lie: ["lie", "tie"],
  lied: ["lied"],
  liege: ["liege"],
  lien: ["lien", "lion"],
  lieu: ["lien", "lion"],
  life: ["lite"],
  likable: ["likable"],
  like: ["like", "tike"],
  likeable: ["likeable"],
  likelihood: ["likelihood"],
  liken: ["liken"],
  liking: ["liking"],
  lilac: ["lilac"],
  lilt: ["till"],
  linage: ["linage"],
  linden: ["linden"],
  line: ["line", "tine"],
  lineage: ["lineage"],
  lineal: ["lineal"],
  lined: ["lined"],
  linen: ["linen"],
  lingo: ["lingo", "tinge"],
  lining: ["lining"],
  link: ["link"],
  linkage: ["linkage"],
  lion: ["lion", "lien"],
  lip: ["lib"],
  lira: ["ilea"],
  lit: ["ill"],
  lite: ["tile"],
  llano: ["llano"],
  lo: ["lo", "to"],
  load: ["load", "lead", "toad"],
  loaded: ["loaded", "leaded"],
  loading: ["loading", "leading"],
  loaf: ["teat"],
  loan: ["loan", "lean"],
  lob: ["lob"],
  lobe: ["lobe"],
  lobed: ["lobed"],
  local: ["local"],
  locale: ["locale", "locate"],
  locate: ["locale"],
  loci: ["loci"],
  lock: ["lock"],
  loco: ["loco"],
  lode: ["lode"],
  lodge: ["lodge", "ledge"],
  lodging: ["lodging"],
  log: ["log", "leg", "tog"],
  logbook: ["logbook"],
  loge: ["loge", "logo", "loco"],
  loggia: ["loggia"],
  logging: ["logging", "legging"],
  logic: ["logic"],
  logical: ["logical"],
  logician: ["logician"],
  logo: ["logo", "loge", "loco"],
  loin: ["loin"],
  loll: ["loll", "toll", "toil", "tell"],
  lone: ["lone", "tone"],
  long: ["long", "tong"],
  longhand: ["longhand"],
  longing: ["longing"],
  look: ["look", "leek", "took"],
  lookalike: ["lookalike"],
  loon: ["loon", "teen"],
  loot: ["tool"],
  lop: ["lob"],
  lope: ["lobe"],
  lord: ["toed"],
  lorn: ["teen"],
  lose: ["loge", "logo"],
  loss: ["toga"],
  lost: ["teal"],
  loud: ["lend", "tend"],
  lox: ["lox"],
  m: ["w"],
  mad: ["wad"],
  madding: ["wadding"],
  made: ["wade"],
  mag: ["wag"],
  mail: ["wail", "wait", "wall"],
  mailed: ["walled"],
  mailing: ["wailing", "waiting"],
  main: ["wain"],
  make: ["wake"],
  making: ["waking"],
  male: ["wale"],
  mall: ["wall", "wail", "wait", "watt"],
  malt: ["wall", "wail"],
  malted: ["walled"],
  man: ["wan"],
  mane: ["wane"],
  mangle: ["wangle"],
  manna: ["wanna"],
  many: ["wand"],
  mason: ["wagon"],
  mate: ["wale"],
  matt: ["wall"],
  matted: ["walled"],
  maul: ["want"],
  max: ["wax"],
  may: ["wad"],
  mayo: ["wade"],
  me: ["we"],
  meal: ["weal"],
  mean: ["wean"],
  meat: ["weal"],
  meed: ["weed", "wood"],
  meek: ["week"],
  meet: ["wool"],
  meld: ["weld", "wold"],
  melt: ["well"],
  men: ["wen", "won"],
  mend: ["wend"],
  mickey: ["wicked"],
  miffed: ["witted"],
  mil: ["wit"],
  milch: ["witch"],
  mild: ["wild"],
  mile: ["wile"],
  mill: ["will", "wilt"],
  milling: ["willing", "witting"],
  milt: ["will"],
  mince: ["wince"],
  mind: ["wind"],
  minded: ["winded"],
  mine: ["wine", "wino"],
  mink: ["wink"],
  mite: ["wile"],
  mitt: ["will"],
  moan: ["wean"],
  moat: ["weal"],
  mob: ["web"],
  mod: ["wed"],
  moil: ["well", "welt"],
  mold: ["wold", "weld"],
  moll: ["well", "welt"],
  molt: ["well"],
  mom: ["wow"],
  monk: ["wonk"],
  moo: ["woo", "woe", "wee"],
  mood: ["wood", "weed"],
  moon: ["ween"],
  moot: ["wool"],
  mop: ["web"],
  morn: ["ween"],
  most: ["weal"],
  n: ["n"],
  nab: ["nab"],
  nabob: ["nabob"],
  nacelle: ["nacelle"],
  nacho: ["nacho"],
  nag: ["nag"],
  nagging: ["nagging"],
  naiad: ["naiad"],
  nail: ["nail"],
  naked: ["naked"],
  nap: ["nab"],
  neck: ["neck"],
  necked: ["necked"],
  necking: ["necking"],
  necklace: ["necklace"],
  neckline: ["neckline"],
  nee: ["nee"],
  need: ["need"],
  needle: ["needle", "noodle"],
  negligee: ["negligee"],
  negligence: ["negligence"],
  negligible: ["negligible"],
  neigh: ["neigh"],
  neon: ["neon", "noon"],
  nerd: ["need"],
  niacin: ["niacin"],
  nib: ["nib"],
  nibble: ["nibble"],
  nice: ["nice"],
  niche: ["niche"],
  nick: ["nick"],
  nickel: ["nickel"],
  nickelodeon: ["nickelodeon"],
  niece: ["niece"],
  niggle: ["niggle"],
  niggling: ["niggling"],
  nigh: ["nigh"],
  nil: ["nil", "nit"],
  nine: ["nine"],
  nip: ["nib"],
  nipple: ["nibble"],
  nit: ["nil"],
  nix: ["nix"],
  no: ["no"],
  noble: ["noble"],
  nod: ["nod"],
  nodal: ["nodal"],
  node: ["node"],
  noel: ["noel"],
  noggin: ["noggin"],
  nonacid: ["nonacid"],
  nonage: ["nonage"],
  nonalcoholic: ["nonalcoholic"],
  nonaligned: ["nonaligned"],
  nonbinding: ["nonbinding"],
  nonce: ["nonce"],
  nonchalance: ["nonchalance"],
  nonclinical: ["nonclinical"],
  none: ["none"],
  nonexchangeable: ["nonexchangeable"],
  nonlegal: ["nonlegal"],
  noodle: ["noodle", "needle"],
  nook: ["nook"],
  noon: ["noon", "neon"],
  nor: ["nee"],
  O: ["o", "e"],
  o: ["o", "e"],
  oaf: ["oat", "eat"],
  oak: ["oak"],
  oaken: ["oaken"],
  obedience: ["obedience"],
  obi: ["obi"],
  oblige: ["oblige"],
  obliging: ["obliging"],
  oblong: ["oblong"],
  oboe: ["oboe"],
  ocean: ["ocean"],
  oceangoing: ["oceangoing"],
  oceanic: ["oceanic"],
  odd: ["odd"],
  oddball: ["oddball"],
  ode: ["ode"],
  off: ["ebb"],
  ogle: ["ogle"],
  oh: ["oh", "eh"],
  oho: ["oho"],
  oil: ["oil", "ell"],
  oiled: ["oiled"],
  oink: ["oink"],
  old: ["old"],
  olden: ["olden"],
  oldie: ["oldie"],
  ole: ["ole"],
  oleo: ["oleo"],
  om: ["ow"],
  on: ["on", "en"],
  once: ["once"],
  oncogene: ["oncogene"],
  one: ["one"],
  ongoing: ["ongoing"],
  onion: ["onion"],
  online: ["online"],
  onlooking: ["onlooking"],
  ooh: ["ooh"],
  our: ["one"],
  ox: ["ox", "ex"],
  oxblood: ["oxblood"],
  oxen: ["oxen"],
  oxide: ["oxide"],
  p: ["b"],
  pack: ["back"],
  packing: ["backing"],
  pad: ["bad"],
  paid: ["bald"],
  pail: ["bail", "bait", "ball"],
  pair: ["bale"],
  pal: ["bat"],
  pale: ["bale", "bate"],
  pall: ["ball", "bail", "bait"],
  pan: ["ban"],
  pane: ["bane"],
  pang: ["bang"],
  passage: ["baggage"],
  pate: ["bale"],
  patron: ["baleen"],
  pay: ["bad"],
  pea: ["boa"],
  peach: ["beach"],
  peak: ["beak"],
  peaked: ["beaked"],
  peal: ["beat", "boat"],
  pebble: ["bobble"],
  peck: ["beck", "bock"],
  pee: ["bee", "boo"],
  peek: ["book"],
  peel: ["beet", "boot"],
  peeler: ["bootee"],
  peen: ["been", "boon"],
  peep: ["boob"],
  peg: ["beg", "bog"],
  pelf: ["belt", "bolt"],
  pelt: ["bell", "boll", "boil"],
  pend: ["bend", "bond"],
  pending: ["bonding"],
  penile: ["bonito"],
  peon: ["been", "boon"],
  pep: ["bob"],
  per: ["bee"],
  perch: ["beech"],
  peso: ["bozo"],
  petaled: ["belated"],
  pi: ["bi"],
  pie: ["bio"],
  pied: ["bled"],
  pig: ["big"],
  pike: ["bike"],
  pile: ["bile", "bite"],
  piling: ["biting"],
  pill: ["bill"],
  pillion: ["billion"],
  pin: ["bin"],
  pinnacle: ["binnacle"],
  piny: ["bind"],
  pip: ["bib"],
  pis: ["biz", "big"],
  pitiable: ["billable"],
  pitted: ["billed"],
  plank: ["blank"],
  pled: ["bled"],
  plod: ["bled"],
  plop: ["blob"],
  plough: ["blench"],
  ploy: ["bled"],
  ply: ["bid"],
  poach: ["beach"],
  pock: ["bock", "beck"],
  pod: ["bod", "bed"],
  poise: ["beige"],
  pol: ["bet"],
  pole: ["bole"],
  polio: ["belie", "belle"],
  poll: ["boll", "bolt", "boil", "bell", "belt"],
  polling: ["boiling"],
  polo: ["bole"],
  pond: ["bond", "bend"],
  pone: ["bone"],
  pony: ["bond", "bend"],
  pooch: ["beech"],
  poodle: ["boodle"],
  poof: ["boot", "boob", "beet"],
  pool: ["boot", "beet"],
  poop: ["boob"],
  pop: ["bob"],
  porch: ["beech"],
  porn: ["been"],
  pose: ["bozo"],
  poseur: ["begone"],
  posy: ["bead"],
  pouch: ["bench"],
  pour: ["bone"],
  pox: ["box"],
  pray: ["bead"],
  pro: ["bee"],
  prof: ["beet"],
  pry: ["bed"],
  q: ["d"],
  r: ["e"],
  rot: ["eel"],
  s: ["z", "a", "g"],
  sable: ["gable"],
  sad: ["gad"],
  safe: ["gate", "gaze"],
  sag: ["gag"],
  saga: ["gaga"],
  sage: ["gage"],
  sago: ["gage"],
  sail: ["gait", "gall"],
  sailing: ["galling"],
  sale: ["gale", "gate"],
  salt: ["gall"],
  sang: ["gang"],
  sans: ["gang"],
  sap: ["gab"],
  sass: ["gaga"],
  sat: ["gal"],
  sate: ["gale"],
  say: ["gad"],
  seal: ["zeal", "goal", "goat"],
  sealer: ["goatee"],
  seat: ["zeal", "goal"],
  see: ["zoo", "gee", "goo"],
  seed: ["good"],
  seek: ["geek", "gook"],
  seen: ["aeon", "goon"],
  senna: ["gonna"],
  set: ["gel"],
  sh: ["ah"],
  side: ["aide"],
  sill: ["alit", "gill", "gilt"],
  silo: ["alto"],
  silt: ["gill"],
  sin: ["gin"],
  sing: ["zing", "zinc"],
  sip: ["alb"],
  sir: ["ale"],
  sire: ["glee"],
  sis: ["gig"],
  sisal: ["algal"],
  sit: ["ail", "all"],
  skin: ["akin"],
  slack: ["alack"],
  slay: ["glad"],
  slid: ["gild"],
  slide: ["glide"],
  slip: ["glib"],
  slit: ["gill"],
  slob: ["glob"],
  sloe: ["aloe", "glee"],
  slop: ["glob"],
  slope: ["globe"],
  slug: ["zing", "zinc"],
  sly: ["aid"],
  small: ["await"],
  smoke: ["awoke"],
  so: ["go"],
  sob: ["gob"],
  sod: ["zed", "god"],
  sofa: ["zeta"],
  sol: ["got", "gel", "get"],
  sold: ["gold", "geld"],
  solid: ["gelid"],
  song: ["gong"],
  soon: ["aeon", "goon"],
  sop: ["gob"],
  sot: ["gel"],
  soul: ["gent"],
  sour: ["zone", "gone", "gene"],
  soy: ["zed", "god"],
  sped: ["abed"],
  spry: ["abed"],
  stack: ["alack"],
  stage: ["glace"],
  stance: ["glance"],
  stand: ["gland"],
  stay: ["glad"],
  steal: ["gloat"],
  stem: ["glow"],
  steno: ["alone"],
  step: ["glob"],
  stiff: ["glitz"],
  stone: ["alone"],
  stop: ["glob"],
  suede: ["anode"],
  t: ["l"],
  tab: ["lab"],
  tabla: ["labia"],
  tack: ["lack"],
  taco: ["lace"],
  tad: ["lad"],
  tag: ["lag", "lac"],
  take: ["lake"],
  tale: ["late"],
  tam: ["law"],
  tango: ["lance"],
  tank: ["lank"],
  tap: ["lab"],
  tax: ["lax"],
  tea: ["lea"],
  teach: ["leach"],
  teak: ["leak"],
  tech: ["lech"],
  tee: ["lee"],
  teen: ["loon"],
  tell: ["loll"],
  tend: ["lend"],
  tick: ["lick"],
  ticking: ["licking"],
  tie: ["lie"],
  tike: ["like"],
  tile: ["lite"],
  till: ["lilt"],
  tine: ["line"],
  tinge: ["lingo"],
  tip: ["lib"],
  to: ["lo"],
  toad: ["load", "lead"],
  toe: ["lee"],
  tog: ["log", "leg"],
  toil: ["loll"],
  toll: ["loll"],
  tom: ["low"],
  tone: ["lone"],
  tong: ["long"],
  tony: ["lend"],
  too: ["lee"],
  took: ["look", "leek"],
  tool: ["loot"],
  top: ["lob"],
  tor: ["lee"],
  torch: ["leech"],
  tour: ["lone"],
  toy: ["led"],
  trading: ["leading"],
  tray: ["lead"],
  trek: ["leek"],
  try: ["led"],
  u: ["n"],
  v: ["a"],
  vie: ["ale"],
  vile: ["alto"],
  villus: ["ailing"],
  visa: ["alga"],
  x: ["x"],
  xenon: ["xenon"],
  xi: ["xi"],
  y: ["d"],
  yang: ["dang"],
  yank: ["dank"],
  yap: ["dab"],
  ye: ["do"],
  yell: ["dell", "deli", "doll", "dolt"],
  yen: ["den", "don"],
  yep: ["deb"],
  yes: ["dog"],
  yeti: ["deli", "dell", "doll"],
  yin: ["din"],
  yo: ["do"],
  yon: ["don", "den"],
  you: ["don", "den"],
  your: ["done"],
  z: ["f"],
  zeal: ["feat", "foal"],
  zed: ["fed"],
  zest: ["foal"],
  zilch: ["filch"],
  zip: ["fib"],
  zoo: ["foe", "fee"],
  "": [""],
};

export default data;
