const data = {
  a: ["a"],
  abed: ["coda", "soda"],
  ad: ["ha"],
  ah: ["ha"],
  aha: ["aha"],
  ale: ["sea", "lea"],
  all: ["lea"],
  am: ["ma"],
  amazed: ["hosanna"],
  b: ["d", "e"],
  babe: ["lead"],
  babel: ["bead"],
  bad: ["cad", "clad", "had", "sad", "gad"],
  bade: ["scad", "shad"],
  bah: ["had"],
  bake: ["stifle"],
  bald: ["clad", "glad", "head"],
  bale: ["lead"],
  ball: ["lead"],
  balm: ["mead"],
  bat: ["tad"],
  bead: ["case", "hale", "sale", "gale"],
  beam: ["male"],
  beat: ["tale"],
  bed: ["cod", "clod", "hod", "sod", "god", "hoe"],
  bee: ["sod", "old", "ole"],
  beef: ["told", "tole"],
  beet: ["told", "tole"],
  befit: ["title"],
  belie: ["libel"],
  bell: ["else"],
  best: ["tale"],
  bet: ["toe"],
  bi: ["id"],
  bib: ["did", "die"],
  bible: ["oldie"],
  bid: ["hid", "hie"],
  bile: ["slid"],
  billed: ["collie"],
  bit: ["tie"],
  blab: ["dale"],
  blade: ["scald", "scale", "shale"],
  blah: ["hale"],
  bled: [
    "cold",
    "hold",
    "sold",
    "gold",
    "coed",
    "sled",
    "hole",
    "sole",
    "glee",
  ],
  bleed: ["closed"],
  blew: ["wold"],
  blitz: ["stile"],
  blob: ["dole"],
  blot: ["told", "toed", "tole"],
  blow: ["wold"],
  boa: ["floe"],
  bob: ["clod", "doe"],
  bod: ["cod", "clod", "hod", "sod", "god", "hoe"],
  bode: ["shod", "shoe"],
  bola: ["aloe"],
  bold: ["clod", "sloe"],
  bole: ["sloe"],
  boom: ["mood"],
  bow: ["woe"],
  bub: ["dud", "duel", "due", "clue"],
  bud: ["cud", "cue", "clue", "hue", "sue"],
  bum: ["mud"],
  burl: ["hue"],
  by: ["ye"],
  bye: ["lye"],
  byte: ["stye"],
  clad: ["cab", "gab", "cad", "clad", "had", "sad", "gad"],
  clam: ["mad"],
  claw: ["wad"],
  clod: ["cob", "hob", "sob", "gob", "cod", "clod", "hod", "sod", "god"],
  club: ["dub", "club", "dud"],
  clue: ["sub"],
  d: ["c", "h", "s", "g"],
  dad: ["sac", "hah", "has", "gas", "hag", "sag", "gag"],
  dale: ["slag"],
  dam: ["mag"],
  date: ["stag"],
  dead: ["cash", "clash", "hash", "sash", "gash", "class", "sass"],
  deaf: ["talc"],
  deal: ["lash", "lass"],
  deb: ["doc", "dog", "clog"],
  deed: ["gosh", "clog", "slog"],
  deem: ["mosh", "moss"],
  def: ["tog"],
  deist: ["tails"], //someone who believes in a god
  dell: ["less"],
  diadem: ["mosaic"],
  did: ["sic", "his", "sis", "gig"],
  die: ["sic", "sis"],
  diesel: ["basic", "basis"],
  do: ["oh"],
  doe: ["ooh", "log"],
  dole: ["slog"],
  dome: ["smog"],
  dot: ["tog"],
  dub: ["duh", "dug"],
  dud: ["huh", "hug"],
  due: ["lug"],
  duel: ["bus", "bug"],
  duh: ["huh", "hug"],
  e: ["o", "s", "l"],
  earl: ["has"],
  eave: ["oval"],
  ebb: ["dell", "eel"],
  ed: ["ho", "so", "go"],
  eek: ["till"],
  eel: ["ell"],
  eh: ["ho"],
  elate: ["stab", "stall"],
  eldest: ["tassel"],
  elide: ["shill"],
  elite: ["still"],
  elk: ["till"],
  ell: ["ell", "eel"],
  else: ["lab"],
  elude: ["scull"],
  ewe: ["owl"],
  eyelid: ["sibyl"],
  f: ["z", "t"],
  fa: ["at"],
  fad: ["cat", "hat", "sat"],
  fade: ["scat", "shat"],
  fat: ["tat"],
  fate: ["stat"],
  fed: ["cot", "clot", "hot", "sot", "got"],
  fee: ["sot", "lot"],
  feed: ["coot", "hoot", "soot", "clot", "slot", "cost", "host", "colt"],
  feel: ["loot", "lost"],
  feet: ["toot"],
  fell: ["lest"],
  felt: ["test"],
  feud: ["gust", "cult"],
  fez: ["sot"],
  fie: ["sit", "lit"],
  file: ["slit"],
  fit: ["tit"],
  fled: ["colt"],
  flit: ["tilt"],
  flub: ["duet"],
  flue: ["suet"],
  fly: ["ya", "yet"],
  fob: ["dot", "clot"],
  foe: ["sot", "lot"],
  fold: ["clot", "slot"],
  food: ["coot", "hoot", "soot"],
  fool: ["loot"],
  foot: ["toot"],
  fuel: ["but", "lout"],
  fume: ["smut"],
  furl: ["hut"],
  h: ["h"],
  ha: ["ah"],
  had: ["hah"],
  hah: ["hah"],
  ham: ["marl"],
  he: ["oh", "sh"],
  head: ["cash", "clash", "hash", "sash", "gash"],
  heal: ["lash"],
  heed: ["gosh"],
  helm: ["mesh"],
  hid: ["girl"],
  ho: ["oh"],
  hoe: ["ooh"],
  hub: ["duh"],
  huh: ["huh", "hurl"],
  hurl: ["huh", "hurl"],
  I: ["i"],
  i: ["i"],
  id: ["hi"],
  idol: ["loci"],
  if: ["ti"],
  ill: ["lei"],
  inn: ["mi"],
  it: ["ti"],
  j: ["t"],
  jab: ["eat"],
  jade: ["scat", "shat"],
  jam: ["mat"],
  jeez: ["soot", "slot"],
  jell: ["lest"],
  jet: ["tot"],
  job: ["dot", "clot"],
  jot: ["tot"],
  just: ["taut"],
  jut: ["tut"],
  k: ["ti"],
  l: ["l", "e"],
  lad: ["gal"],
  ladle: ["legal"],
  lake: ["stifle"], //could maybe use
  lave: ["oval"],
  lea: ["all", "floe", "ale"],
  lead: ["call", "hall", "gall", "case", "hale", "sale", "gale"],
  leaf: ["tall", "tale"],
  led: ["sol", "hoe"],
  lee: ["sol", "ole"],
  lees: ["aloe"],
  lei: ["ill"],
  lest: ["tall", "tale"],
  let: ["toe"],
  lib: ["die"],
  libel: ["belie"],
  lid: ["hie"],
  lie: ["oil", "lie"],
  lied: ["coil", "soil"],
  lief: ["toil"],
  list: ["tail"],
  lit: ["tie"],
  livid: ["civil"],
  lob: ["doe"],
  lode: ["shoe"],
  loot: ["tool"],
  lot: ["toe"],
  low: ["woe"],
  lush: ["haul"],
  lye: ["lye"],
  m: ["m"],
  ma: ["am"],
  mad: ["cam", "clam", "ham"],
  made: ["scam", "sham"],
  male: ["slam", "seam"],
  malt: ["team"],
  marl: ["ham"],
  mat: ["tam"],
  may: ["yam"],
  me: ["om"],
  mead: ["calm"],
  meld: ["helm"],
  met: ["tom"],
  mi: ["inn"],
  mid: ["him"],
  mild: ["slim"],
  mile: ["slim"],
  mom: ["mom"],
  mot: ["tom"],
  mu: ["um"],
  mud: ["cum", "hum", "sum", "gum"],
  mule: ["slum"],
  mum: ["mum"],
  O: ["o"],
  o: ["o"],
  ode: ["oho"],
  of: ["to"],
  oh: ["ho"],
  oho: ["oho"],
  oleo: ["oleo"],
  s: ["z", "a"],
  seal: ["seal"],
  see: ["sol"],
  seed: ["cola", "shoo"],
  seek: ["still"],
  sell: ["sell"],
  sh: ["ha", "sh"],
  shad: ["shah"],
  shah: ["shah"],
  she: ["ssh"],
  sheaf: ["stash"],
  shh: ["shh"],
  slab: ["seal"],
  sled: ["cola", "shoe"],
  sleet: ["stool", "stole"],
  sloe: ["sloe"],
  slue: ["soul", "slue"],
  sly: ["yea"],
  small: ["llama"],
  so: ["so"],
  soda: ["sago"],
  sole: ["solo"],
  solo: ["solo"],
  stab: ["data", "seat"],
  stat: ["stat"],
  stead: ["shalt"],
  steed: ["scoot", "shoot"],
  stood: ["scoot", "shoot"],
  stud: ["shut"],
  t: ["t"],
  tab: ["eat"],
  tad: ["cat", "hat", "sat"],
  tale: ["slat", "seat"],
  tam: ["mat"],
  tat: ["tat"],
  teal: ["last", "east"],
  team: ["mast", "malt"],
  tee: ["sot", "lot"],
  teem: ["moot", "most", "molt"],
  tell: ["lest"],
  ti: ["it"],
  tide: ["shit"],
  tie: ["sit", "lit"],
  tile: ["slit"],
  time: ["omit"],
  tit: ["tit"],
  toe: ["sot", "lot"],
  toed: ["coot", "hoot", "soot", "clot", "slot"],
  told: ["clot", "slot"],
  tole: ["slot"],
  tom: ["mot"],
  tool: ["loot"],
  toot: ["toot"],
  tot: ["tot"],
  tut: ["tut"],
  u: ["u"],
  um: ["mu"],
  v: ["v"],
  w: ["w"],
  wad: ["caw", "claw", "haw", "saw"],
  wale: ["slaw"],
  way: ["yaw"],
  we: ["ow"],
  wed: ["cow", "how", "sow"],
  wee: ["sow", "low"],
  weed: ["slow", "glow"],
  weeds: ["aglow"],
  weld: ["slow", "glow"],
  wet: ["tow"],
  woe: ["sow", "low"],
  wold: ["slow", "glow"],
  world: ["chow", "show"],
  wow: ["wow"],
  x: ["x"],
  y: ["y"],
  ya: ["fly"],
  yam: ["may"],
  yaw: ["way"],
  yaws: ["away"],
  yet: ["toy"],
  z: ["s"],
  zeal: ["lass"],
  "": [""],
};

export default data;
